# -*- coding: utf-8 -*-
"""Sesión 2: Exploración de Casos Prácticos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rHXeA1hZBo6oNlGiEvEiaxw6G5a6zvDM

# Sesión 2: Exploración de Casos Prácticos

### ¿Qué hace que un problema sea "resoluble con datos"?

El trabajo de un científico de datos no es aplicar matemáticas a ciegas; su verdadero rol es convertir problemas caóticos del mundo real en problemas estructurados de datos. Un problema se vuelve "resoluble" cuando dejamos de hacer preguntas vagas y comenzamos a hacer preguntas específicas, medibles y basadas en información.

Para que un problema se pueda resolver con datos, necesitamos dos cosas fundamentales:
1. **Un objetivo claro:** Saber exactamente qué queremos predecir, clasificar o descubrir.
2. **Materia prima:** Información histórica (registros, textos, imágenes) de la cual la computadora pueda aprender.

### La diferencia en las preguntas: El Caso de la Cafetería

Imagina que eres el dueño de una cafetería y quieres aumentar tus ganancias.

* **Pregunta vaga (El enfoque tradicional):** *"¿Cómo mejoro mi negocio?"* Esta pregunta es demasiado amplia. No nos dice qué medir, ni dónde buscar, ni cómo sabremos si tuvimos éxito.
* **Pregunta basada en datos (El enfoque del Data Scientist):** *"¿Qué características (edad, ocupación, clima exterior) tienen los clientes que compran más café los viernes por la tarde?"* Esta segunda pregunta es excelente porque nos conecta directamente con lo que vimos en la Sesión 1. Al formularla así, ya sabemos qué buscar en nuestra tabla de datos: nuestra columna **Objetivo (Target)** será "Cantidad de café comprado", y nuestras **Pistas (Features)** serán las columnas de "Edad", "Ocupación" y "Clima".

---

### Los 3 Niveles de Preguntas en la Ciencia de Datos

Para estructurar nuestra mente, los científicos de datos dividimos nuestras preguntas en tres niveles, de menor a mayor complejidad. Siguiendo con la cafetería:

1. **Análisis Descriptivo (¿Qué pasó?):** Miramos hacia el pasado para entender la realidad.
 * *Ejemplo:* ¿Cuántos cafés vendimos el mes pasado los días que llovió?
2. **Análisis Predictivo (¿Qué pasará?):** Usamos los patrones del pasado para adivinar el futuro (¡Aquí es donde brilla el Machine Learning!).
 * *Ejemplo:* Si el pronóstico dice que mañana lloverá, ¿cuántos cafés es altamente probable que vendamos?
3. **Análisis Prescriptivo (¿Qué deberíamos hacer?):** Dejamos que los datos nos recomienden la mejor decisión estratégica.
 * *Ejemplo:* Basado en la predicción de ventas de mañana, ¿cuántos baristas extra debo contratar para no hacer esperar a los clientes, sin desperdiciar dinero en sueldos innecesarios?

---

### De la vida real a los datos: 4 Ejemplos Cotidianos

Para entender cómo traducir la complejidad del mundo a preguntas de datos, veamos cómo distintas disciplinas ya lo están haciendo:

**1. El Caso de la Salud (Medicina y Biología)**
* **El problema complejo:** "¿Cómo evitamos que las personas se enfermen?"
* **La traducción a datos:** "Utilizando historiales clínicos electrónicos, ¿cuál es la probabilidad de que un paciente con ciertos niveles de glucosa y antecedentes familiares desarrolle diabetes en los próximos 5 años?".
* **El impacto:** Los médicos dejan de reaccionar a la enfermedad y comienzan a realizar intervenciones preventivas y personalizadas.

**2. El Caso de la Economía (Sociología y Finanzas)**
* **El problema complejo:** "¿Cómo evitamos que nos roben dinero en el banco?"
* **La traducción a datos:** "Analizando las transacciones en tiempo real, ¿qué patrones inusuales (ej. múltiples compras en 5 minutos desde distintas ubicaciones) indican que una tarjeta de crédito está siendo usada de forma fraudulenta?".
* **El impacto:** Las instituciones financieras bloquean fraudes en milisegundos antes de que el cliente pierda su dinero.

**3. El Caso de las Políticas Públicas (Ciencias Sociales y Urbanismo)**
* **El problema complejo:** "¿Cómo reducimos la criminalidad en la ciudad?"
* **La traducción a datos:** "Analizando el histórico de incidentes, la iluminación de las calles y la densidad de población, ¿en qué cuadrantes de la ciudad y en qué horarios existe una probabilidad mayor al 80% de que ocurra un robo?"
* **El impacto:** Los gobiernos dejan de patrullar a ciegas y envían recursos de seguridad exactamente donde y cuando más se necesitan.

**4. El Caso de la Logística (Ingeniería y Transporte)**
* **El problema complejo:** "¿Cómo entregamos los paquetes más rápido?"
* **La traducción a datos:** "Considerando el historial del tráfico, el clima actual y la distancia entre puntos, ¿cuál es la ruta óptima que minimiza el consumo de combustible y el tiempo para cada camión?".
* **El impacto:** Empresas globales ahorran millones y reducen su huella de carbono al evitar el tráfico.

---

### Ejercicio: El Traductor de Preguntas (Gimnasio Mental)

*(💡 **Tip técnico:** Haz doble clic sobre esta celda de texto para escribir tus respuestas abajo).*

A continuación, verás 3 "Preguntas de Jefe" (preguntas muy vagas y amplias). Tu misión es reescribirlas como si fueras un Científico de Datos e identificar cuál sería tu columna Objetivo (Target) y cuáles serían tus Pistas (Features).

> **Ejemplo de prueba (Biología):**
> * **Pregunta de Jefe:** *"¿Cómo salvamos a los osos polares?"*
> * **Tu traducción a datos:** *"¿Qué relación existe entre la disminución del hielo marino, la temperatura anual y la tasa de natalidad de los osos en la bahía de Hudson durante los últimos 20 años para predecir la población del próximo año?"*
> * **Objetivo (Target):** Tasa de natalidad / Población del próximo año.
> * **Pistas (Features):** Grosor del hielo, temperatura, año, ubicación.

**¡Ahora es tu turno!**

**1. Caso Educación:**
* **Pregunta de Jefe:** "¿Cómo hacemos para que los alumnos no reprueben?"
* **Tu traducción a datos:**
 * **Objetivo (Target):**
 * **Pistas (Features):**

**2. Caso Marketing:**
* **Pregunta de Jefe:** "¿Cómo hacemos que nuestro nuevo producto sea un éxito?"
* **Tu traducción a datos:**
 * **Objetivo (Target):**
 * **Pistas (Features):**

**3. Caso Ecología:**
* **Pregunta de Jefe:** "¿Cómo limpiamos los océanos de plástico?"
* **Tu traducción a datos:**
 * **Objetivo (Target):**
 * **Pistas (Features):**

---

### 5to Ejemplo: El Caso México (Datos Abiertos del Gobierno)

México es uno de los países de Latinoamérica con más datos abiertos disponibles para el público. El gobierno federal publica bases de datos reales que tú puedes descargar y analizar hoy mismo:

**5. El Caso de la Salud Pública en México (IMSS / ISSSTE)**
* **El problema complejo:** "¿Cómo reducimos las muertes por enfermedades crónicas en México?"
* **La traducción a datos:** "Usando el Registro Nacional de Derechohabientes del IMSS, ¿qué combinación de factores (edad, estado, índice de marginación del municipio, acceso a servicios) predice mejor si un paciente con diabetes desarrollará complicaciones renales en los próximos 2 años?"
* **El impacto:** El IMSS podría priorizar recursos de prevención exactamente donde y para quienes más los necesitan.
* **Fuente de datos real:** [datos.gob.mx](https://datos.gob.mx) tiene más de 40,000 conjuntos de datos públicos y gratuitos.

---

### 🔍 El 4to Nivel Oculto: Análisis Diagnóstico

Aunque en clase mencionamos 3 niveles, los científicos de datos profesionales trabajan con **4 niveles**. El que falta es el que más se usa en el día a día empresarial:

| Nivel | Pregunta clave | Ejemplo en la cafetería |
|---|---|---|
| **1. Descriptivo** | ¿Qué pasó? | Vendimos 30% menos café en marzo |
| **2. Diagnóstico** | ¿Por qué pasó? | Porque llovió menos y bajó la temperatura |
| **3. Predictivo** | ¿Qué pasará? | El próximo martes venderemos ~120 cafés |
| **4. Prescriptivo** | ¿Qué debemos hacer? | Contratar 1 barista extra el martes a las 8 AM |

> 💡 El **Análisis Diagnóstico** es el más poderoso para detectar la *causa raíz* de un problema. Por eso, antes de predecir el futuro, siempre debemos entender bien el pasado.

---

# Parte 2: Llevando la lógica a Python (Variables y Comentarios)

Ahora que ya sabemos cómo estructurar mentalmente un problema, vamos a llevar esa lógica a nuestro cuaderno de Google Colab utilizando Python. Para empezar a programar hoy, solo necesitamos entender dos conceptos fundamentales: los comentarios y las variables.

### ¿Qué es un comentario?
Cuando escribimos código, a veces necesitamos dejarnos notas a nosotros mismos o a nuestro equipo para recordar qué hace esa parte del programa. En Python, cualquier línea que empiece con el símbolo de almohadilla (`#`) es un **comentario**. La computadora ignora los comentarios por completo, así que puedes escribir lo que quieras ahí en lenguaje humano.

### ¿Qué es una variable?
Imagina que una variable es como una "caja" de cartón a la que le pones una etiqueta con un marcador. Adentro de esa caja puedes guardar información (como números o texto) para usarla más tarde. En Python, creamos la caja (le damos un nombre) y usamos el signo de igual (`=`) para meterle algo adentro.

#### Las "Reglas de Oro" para etiquetar tus cajas
Cuando le pones nombre a tus variables (etiquetas), Python es un poco estricto. Para evitar errores en la pantalla, sigue estas tres reglas:
1. **Cero espacios:** Nunca uses espacios. Si quieres separar palabras, usa un guion bajo (a esto se le llama *snake_case*). Escribe `problema_negocio`, nunca `problema negocio`.
2. **Cero acentos y sin la letra 'ñ':** La programación se inventó en inglés. Escribe `ano_nacimiento`, no `año_nacimiento`.
3. **No empieces con números:** Puedes usar números al final (`cliente_1`), pero nunca al principio (`1_cliente`).

#### ¿Texto o Números? (El contenido de la caja)
A la computadora hay que decirle qué tipo de información le estamos dando:
* **Si es Texto:** Siempre, siempre, siempre debe ir entre comillas. Ejemplo: `nombre = "Ana"`
* **Si es un Número:** Nunca lleva comillas (para que Python sepa que puede hacer matemáticas con él). Ejemplo: `edad = 20`

---

### Traduciendo un problema a código

Vamos a escribir un programa muy sencillo que guarde en la memoria de la computadora nuestro problema de negocio y nuestra pregunta de datos del hospital.

### 📦 Los 4 Tipos de Datos Básicos en Python

Antes de escribir código, aquí tienes la guía rápida de los tipos de "caja" que existen en Python. Esto es lo que más usarás en todo el diplomado:

| Tipo | Nombre técnico | Ejemplo | ¿Lleva comillas? |
|---|---|---|---|
| Número entero | `int` (integer) | `edad = 25` | ❌ No |
| Número decimal | `float` | `temperatura = 36.6` | ❌ No |
| Texto | `str` (string) | `nombre = "Ana"` | ✅ Sí |
| Verdadero/Falso | `bool` (boolean) | `sobrevivio = True` | ❌ No |

> **¿Por qué importa esto en ciencia de datos?**  
> Porque cuando cargues una tabla (dataset), Python necesita saber el tipo de cada columna para saber si puede sumar, promediar o comparar sus valores. Una columna `str` no se puede multiplicar; una columna `int` no se puede ordenar alfabéticamente. ¡Verificar los tipos es uno de los primeros pasos en la limpieza de datos!
"""

# 1. Definimos el problema complejo (El enfoque tradicional)
problema_negocio = "Quiero que mi hospital sea más eficiente."

# 2. Lo traducimos a una pregunta de datos (El enfoque del Data Scientist)
pregunta_datos = "¿Qué características tienen los pacientes que cancelan sus citas los lunes?"

# 3. Mostramos la información en pantalla
print("Problema original:")
print(problema_negocio)

print("Traducción para Ciencia de Datos:")
print(pregunta_datos)

"""#### Diseccionando el código línea por línea

¿Qué pasó exactamente cuando presionaste el botón de "Play"? Vamos a revisarlo a detalle:

* `# 1. Definimos el problema...`: Esta línea es para ti. Al tener el símbolo `#`, Python la ignoró. Es una excelente práctica comentar tu código para que no te pierdas.
* `problema_negocio = "..."`: Aquí creamos nuestra primera "caja" y le pusimos la etiqueta *problema_negocio*. El signo `=` le dice a Python: "toma el texto que está a la derecha y guárdalo en la caja de la izquierda".
* `pregunta_datos = "..."`: Creamos una segunda caja llamada *pregunta_datos* y guardamos en ella nuestra pregunta específica. ¡Ahora la computadora recuerda ambos textos por nosotros!
* `print(problema_negocio)`: Como no usamos comillas aquí, Python sabe que no queremos que imprima literalmente la palabra "problema_negocio". En su lugar, va a buscar la caja que tiene ese nombre, la abre, e imprime lo que hay adentro.

---

### ⚠️ Un concepto vital: La Memoria de Colab

Antes de pasar al ejercicio, debes saber un secreto de Google Colab: **las celdas comparten memoria**.

Si tú creas la variable `pregunta_datos` en la celda de arriba y le das "Play", esa caja se queda guardada en el cerebro de la computadora. Si luego bajas a una celda nueva y escribes `print(pregunta_datos)`, Python se acordará perfectamente de lo que tenía adentro.
*(Nota: Si cierras tu navegador y vuelves mañana, la memoria se borra y tendrás que volver a darle "Play" a tus celdas desde arriba hacia abajo).*

---

### Ejercicio: Creando tu Gafete Virtual

Es momento de ensuciarte las manos. En la celda de código vacía que está debajo de este texto, vas a crear tu primer gafete virtual utilizando variables.

**Tu Tarea:**

1. Crea un comentario en la primera línea que diga: `# Mi Gafete de Científico de Datos`.
2. Crea una variable llamada `mi_nombre` y guarda tu nombre en ella (¡recuerda usar comillas porque es texto!).
3. Crea una variable llamada `mi_carrera` y guarda la carrera que estudias (texto).
4. Crea una variable llamada `mi_edad` y guarda tu edad (¡sin comillas, porque es un número!).
5. En las siguientes líneas, usa la función `print()` para imprimir cada una de tus tres variables.
6. ¡Dale "Play" a la celda y comprueba que no haya errores!

*(Ejemplo de cómo debe verse tu código antes de ejecutarlo)*:

"""

# Mi Gafete de Científico de Datos
mi_nombre = "Pilares"
mi_carrera = "Ingeniería"
mi_edad = 25

print(mi_nombre)
print(mi_carrera)
print(mi_edad)

"""---

### ✨ BONUS: f-strings — La Forma Profesional de Imprimir

El `print()` con comas funciona, pero los profesionales de Python usan una técnica más elegante llamada **f-string** (cadena formateada). La idea es muy simple: pones una `f` antes de las comillas y usas `{}` para insertar variables directamente dentro del texto.

**Comparando los dos estilos:**

```python
# Estilo básico (comas)
print("Hola, soy", mi_nombre, "y tengo", mi_edad, "años")

# Estilo profesional (f-string) — mismo resultado, más limpio
print(f"Hola, soy {mi_nombre} y tengo {mi_edad} años")
```

Los f-strings son especialmente poderosos porque también permiten hacer cálculos dentro de las llaves:
```python
print(f"En 10 años tendré {mi_edad + 10} años")
```

Ejecuta la celda de abajo para ver la diferencia en acción:

"""

# ============================================================
# F-STRINGS: La forma profesional de combinar texto y variables
# ============================================================

# Usamos las variables del gafete que ya creamos
mi_nombre = "Pilares"   # Cambia estos valores por los tuyos
mi_carrera = "Ingeniería"
mi_edad = 25

# Estilo básico (comas) — funciona pero es menos legible
print("--- Estilo básico con comas ---")
print("Hola, soy", mi_nombre, "y estudio", mi_carrera)

# Estilo f-string — más profesional y legible
print("\n--- Estilo f-string (profesional) ---")
print(f"Hola, soy {mi_nombre} y estudio {mi_carrera}")
print(f"Tengo {mi_edad} años, y en 5 años tendré {mi_edad + 5}")

# Aplicación en ciencia de datos
print("\n--- Aplicación en Ciencia de Datos ---")
dataset = "Titanic"
num_filas = 891
num_columnas = 12
print(f"El dataset '{dataset}' tiene {num_filas} filas y {num_columnas} columnas.")
print(f"En total son {num_filas * num_columnas:,} celdas de información.")

"""---

# Parte 3: Ejemplos Paso a Paso con Datasets Famosos

Para que un modelo de ciencia de datos pueda responder a nuestras preguntas, necesitamos alimentarlo con ejemplos del pasado. A estas colecciones de información les llamamos **datasets** (conjuntos de datos).

Vamos a analizar dos de los datasets de prueba más famosos del mundo, desglosando cómo traducen un problema real a una tabla de datos:

**1. El Dataset de Cáncer de Mama (Salud y Biología)**

* **El problema real:** El personal médico necesita una segunda opinión rápida y precisa para diagnosticar si un tumor de mama es peligroso o inofensivo.
* **La pregunta de datos:** ¿Podemos predecir si un tumor es "maligno" o "benigno" basándonos en las medidas microscópicas del tejido?
* **¿Qué representan las filas?** Cada fila representa el análisis de un tumor individual (un paciente distinto).
* **Columnas clave:**
  * **Las Pistas (Features):** Medidas numéricas exactas, como el "radio_medio" (tamaño), la "textura" o la "simetría" del tumor.
  * **El Objetivo (Target):** Una columna final crucial llamada "diagnostico" que nos dice la respuesta médica real (Maligno o Benigno).

**2. El Dataset de Viviendas (Economía, Ciencias Sociales e Ingeniería)**

* **El problema real:** Las agencias inmobiliarias, compradores y gobiernos urbanos necesitan saber cuál es el precio justo de una propiedad en el mercado.
* **La pregunta de datos:** ¿Cuál será el valor medio de una casa en un vecindario específico considerando las características de su entorno?
* **¿Qué representan las filas?** Cada fila es un vecindario distinto o una propiedad individual.
* **Columnas clave:**
  * **Las Pistas (Features):** Tasa de criminalidad de la zona, proximidad a los ríos, cantidad de habitaciones o niveles de contaminación del aire.
  * **El Objetivo (Target):** El valor de la casa en dólares.

---

### Llevando los datos a Python: Las Listas

En la parte anterior aprendimos a usar variables para guardar un solo dato (como meter una sola etiqueta en una caja). Pero, ¿qué pasa si queremos guardar los nombres de TODAS las columnas de nuestro dataset de cáncer? No vamos a crear 30 cajas distintas; sería un caos. Mejor usamos una **lista**.

Una lista en Python es exactamente como una lista de compras de supermercado. Nos permite guardar múltiples elementos, ordenados, dentro de una sola gran "caja".

Vamos a crear una lista en Google Colab con algunas columnas del dataset de cáncer:

"""

# Guardamos los nombres de las columnas en una lista
columnas_cancer = ["radio_medio", "textura_media", "perimetro", "es_maligno"]

# Imprimimos nuestra lista completa
print("Las columnas que analizaremos hoy son:")
print(columnas_cancer)

"""#### ¿Qué está pasando aquí?

Vamos a desglosarlo línea por línea:

* `columnas_cancer =`: Como ya sabes, creamos una variable y le ponemos un nombre sin espacios.
* `[ ]` **(Los corchetes):** ¡Esta es la novedad! En Python, los corchetes le dicen a la computadora: *"Prepárate, porque voy a meter varios elementos aquí adentro, no solo uno"*. Todo lo que esté entre los corchetes forma parte de tu lista.
* `"radio_medio", "textura_media"...`: Estos son los elementos de nuestra lista. Son textos, por eso van entre comillas. Para separar un elemento del siguiente, simplemente usamos una coma (`,`). ¡Igual que al escribir en papel!

#### El Secreto Informático: Contando desde Cero

Las listas son increíbles porque mantienen el orden rigurosamente. Pero aquí hay una trampa de la programación que te hará sentir como un verdadero informático: **Las computadoras empiezan a contar desde el número cero, no desde el uno.**

Si queremos que Python nos muestre solo el *primer* elemento de nuestra lista (`radio_medio`), tenemos que pedirle el elemento en la posición `0`. Observa cómo se hace:

"""

# Imprimimos solo el primer elemento de la lista (posición 0)
print("La primera pista de nuestro dataset es:")
print(columnas_cancer[0])

# Imprimimos el segundo elemento (posición 1)
print("La segunda pista es:")
print(columnas_cancer[1])

"""*(💡 Si corres este código, notarás que usamos el nombre de la lista, seguido de unos corchetes pegaditos con el número de posición adentro: `[0]`).*

---

### ⚡ Más Poderes de las Listas: len, append y slicing

Las listas tienen superpoderes que usarás constantemente cuando trabajes con datos reales. Aquí los 3 más importantes para esta etapa:

| Operación | Qué hace | Ejemplo |
|---|---|---|
| `len(lista)` | Cuenta cuántos elementos tiene | `len(columnas_cancer)` → `4` |
| `lista.append("nuevo")` | Agrega un elemento al final | `columnas_cancer.append("simetria")` |
| `lista[inicio:fin]` | Extrae una porción (slicing) | `columnas_cancer[0:2]` → primeros 2 |
| `"elemento" in lista` | Pregunta si algo está en la lista | `"textura_media" in columnas_cancer` → `True` |

Ejecuta la celda de abajo para verlos en acción:

"""

# ============================================================
# SUPERPODERES DE LAS LISTAS
# ============================================================

columnas_cancer = ["radio_medio", "textura_media", "perimetro", "es_maligno"]

# 1. len() — ¿Cuántas columnas tenemos?
print(f"Número de columnas en el dataset: {len(columnas_cancer)}")

# 2. append() — Agregamos una columna nueva al análisis
columnas_cancer.append("simetria_media")
print(f"Después de agregar 'simetria_media': {columnas_cancer}")

# 3. Slicing [inicio:fin] — Extrae solo las pistas (todo menos el objetivo)
solo_pistas = columnas_cancer[0:4]   # posiciones 0,1,2,3 (no incluye el 4)
objetivo    = columnas_cancer[-1]    # -1 siempre es el ÚLTIMO elemento
print(f"\nMis pistas (Features): {solo_pistas}")
print(f"Mi objetivo (Target):   {objetivo}")

# 4. 'in' — ¿Está la textura en mi lista de análisis?
buscar = "textura_media"
if buscar in columnas_cancer:
    print(f"\n✅ La columna '{buscar}' SÍ está en mi análisis")
else:
    print(f"\n❌ La columna '{buscar}' NO está en mi análisis")

"""---

### Ejercicio: El Inventario de Datos

¡Es tu turno de armar una lista! Vamos a volver al caso clínico de la Sesión 1, donde queríamos predecir qué pacientes iban a faltar a su cita médica.

**Tu Tarea en la siguiente celda de código:**

1. Crea una variable llamada `pistas_clinica` y asígnale una lista usando corchetes `[ ]`.
2. Adentro de la lista, escribe 3 características (en texto, usando comillas) que tú usarías para predecir si alguien faltará. Ejemplo: `"distancia_hospital"`, `"edad"`, `"clima"`. No olvides separarlas con comas.
3. En la siguiente línea, usa `print(pistas_clinica)` para ver toda tu lista en pantalla.
4. En la última línea, usa el truco informático para imprimir **únicamente el primer elemento** de tu lista. (Recuerda que Python empieza a contar desde el cero).
5. ¡Presiona "Play"!

*(Ejemplo de cómo debe verse tu código antes de ejecutarlo)*:

"""

# Mi primera lista en Python
pistas_clinica = ["distancia", "tipo_enfermedad", "dia_semana"]

print("Todas mis pistas son:")
print(pistas_clinica)

print("Mi pista principal es:")
print(pistas_clinica[0])

"""---

### 🔬 Cargando el Dataset Real de Cáncer de Mama

Hasta ahora creamos listas a mano. ¡Pero en ciencia de datos real nunca escribimos los datos a mano! Los cargamos directamente desde librerías. El dataset de cáncer de mama viene incluido en **scikit-learn**, la librería de Machine Learning más famosa de Python.

Ejecuta las dos celdas de abajo para ver el dataset real, con sus 569 pacientes y 30 características médicas reales:

"""

# ============================================================
# CARGANDO EL DATASET REAL DE CÁNCER DE MAMA
# ============================================================

import pandas as pd
from sklearn.datasets import load_breast_cancer

# Cargamos el dataset desde scikit-learn
datos_cancer = load_breast_cancer()

# Lo convertimos a un DataFrame de pandas (tabla legible)
df_cancer = pd.DataFrame(datos_cancer.data, columns=datos_cancer.feature_names)
df_cancer['diagnostico'] = datos_cancer.target  # 0=Maligno, 1=Benigno

print(f"📊 El dataset tiene {df_cancer.shape[0]} pacientes y {df_cancer.shape[1]} columnas")
print(f"\n🔍 Las primeras 5 columnas (pistas / features):")
print(datos_cancer.feature_names[:5].tolist())
print(f"\n🎯 La columna objetivo (target): 'diagnostico'")
print(f"   0 = Maligno  |  1 = Benigno")
print(f"\n👇 Vista de las primeras 3 filas (solo 5 columnas para que quepa):")
df_cancer.iloc[:3, [0,1,2,3,-1]]

# ¿Cuántos tumores son malignos vs benignos?
conteo = df_cancer['diagnostico'].value_counts()
print("Distribución del Objetivo (Target):")
print(f"  Malignos  (0): {conteo[0]} pacientes")
print(f"  Benignos  (1): {conteo[1]} pacientes")
print(f"\n  Porcentaje maligno: {conteo[0]/len(df_cancer)*100:.1f}%")
print(f"  Porcentaje benigno: {conteo[1]/len(df_cancer)*100:.1f}%")

print("\n📈 Estadísticas de las primeras 3 características:")
df_cancer.iloc[:, 0:3].describe().round(2)

"""---

# Parte 4: Reto Práctico: Aplica lo Aprendido

Para terminar nuestra segunda sesión, pondremos a prueba tu nueva mentalidad de científico de datos y tus habilidades recién adquiridas en Python.

### 1. Reto Analítico: El caso de la Universidad

**El Escenario:** Imagina que trabajas para esta universidad y se presenta un problema grave: un porcentaje alto de estudiantes están abandonando sus estudios (deserción escolar) durante el primer año. La rectoría te pide ayuda para solucionar esto utilizando datos.

Pensando como un Científico de Datos, responde a las siguientes preguntas:

*(💡 **Tip técnico:** Haz doble clic aquí mismo para poder escribir tus respuestas).*

* **El problema general:** *(Ej. "Quiero reducir la deserción escolar").*
* **Tu pregunta basada en datos:** *(Recuerda hacerla específica y medible. Ej. "¿Qué características tienen los alumnos que abandonan la escuela en los primeros 6 meses?").*
* **Tus "Pistas" (Features):** Si pudieras pedirle al área de sistemas una base de datos histórica de los alumnos, ¿qué 3 columnas pedirías porque crees que influyen en que un alumno abandone? *(Ej. Promedio de la preparatoria, Tiempo de traslado a la universidad, etc.)*.

**Escribe tus respuestas aquí:**

* **Problema general:**
* **Pregunta de datos:**
* **Mis 3 pistas clave:**

---

### 2. Reto de Código: Tu Primer Análisis en Python

¡Ahora vamos a llevar tus pistas a la computadora!
Haz clic en el botón **"+ Código"** que aparece al pasar el ratón justo debajo de este texto para crear una nueva celda gris. En esa celda, deberás escribir un pequeño programa siguiendo estas instrucciones:

1. Escribe al menos un **comentario** usando el símbolo `#` explicando qué hace tu código (recuerda que la computadora ignora los comentarios, son notas para ti).
2. Crea una variable llamada `mi_nombre` y asígnale tu nombre (entre comillas).
3. Crea una variable llamada `mi_carrera` y asígnale tu área de estudio.
4. Crea una **lista** llamada `pistas_desercion` usando corchetes `[ ]`. Adentro, guarda (en texto, separadas por comas) las 3 pistas que definiste en el reto anterior.
5. Usa la función `print()` para mostrar en pantalla quién eres, cuál es tu lista completa de pistas, y finalmente, imprime solo tu pista principal (usando el índice `[0]`).

*(💡 **Truco de Python:** Puedes usar f-strings para combinar texto y variables de forma profesional: `print(f"Mi nombre es {mi_nombre}`).*

**Ejemplo de cómo debería verse tu código:**

"""

# Este programa define mi perfil y mis pistas para investigar la deserción
mi_nombre = "Ana"
mi_carrera = "Psicología"

# Guardo mis 3 pistas en una lista
pistas_desercion = ["calificaciones_prepa", "horas_trabajo", "distancia_universidad"]

# Imprimo mis resultados usando f-strings (forma profesional)
print(f"Hola, soy {mi_nombre} y estudio {mi_carrera}")
print("Para predecir si un alumno abandonará, investigaré estas pistas:")
print(pistas_desercion)
print(f"Mi pista más importante es: {pistas_desercion[0]}")
print(f"Total de pistas a analizar: {len(pistas_desercion)}")