# -*- coding: utf-8 -*-
"""Sesión 12: Exploración Inicial de Datos (Práctica)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AmY8zO6QZ__7r5SGsHmKSvf8WYT4w8qQ

# Sesión 12: Exploración Inicial de Datos (Práctica)


### La Auditoría de Datos: El Inspector de Calidad
Imagina que eres un Inspector de Calidad en una gran fábrica o un Auditor Médico que debe revisar miles de expedientes clínicos. Tu trabajo en este momento no es arreglar el problema; tu primer objetivo es saber **exactamente cuántos expedientes están incompletos** y en dónde están escondidos los errores.

En la ciencia de datos hacemos exactamente lo mismo: antes de limpiar o corregir, primero **auditamos** para conocer la magnitud del problema. Hoy iremos de cacería buscando a nuestro archienemigo principal: el valor nulo (`None`).

---

### Manual vs. Programático: El fin de las búsquedas visuales

Hasta hoy, si querías encontrar un error probablemente abrías Excel y buscabas visualmente celdas vacías. A esto le llamamos **Identificación Manual**. Funciona bien si tienes 20 registros, pero es humanamente imposible con 2 millones de ciudadanos.

Aquí es donde la programación brilla. Hoy daremos el salto a la **Identificación Programática**. Usaremos lo que ya saben sobre listas y condicionales (`if/else`) para enseñarle a Python a escanear bases de datos gigantescas en una fracción de segundo.

Para encender nuestro radar, utilizaremos la palabra **`in`** (que significa "dentro de"). Ejecuta esta celda para ver tu primer escáner en acción:
"""

# Una base de datos simulada de un hospital (con un paciente que no registró su edad)
edades_pacientes = [45, 32, 28, 50, None, 41, 33]

# Nuestro primer radar automático usando 'if' y la palabra 'in'
if None in edades_pacientes:
    print("🚨 ¡ALERTA DE AUDITORÍA! Se han detectado valores nulos (None) en el sistema.")
else:
    print("✅ Base de datos limpia. No hay valores nulos.")

"""### ¿Qué acaba de pasar?

En lugar de revisar número por número con nuestros ojos, le preguntamos a Python: *"Oye, ¿existe el valor `None` **dentro de** (`in`) la lista de pacientes?"*.

Python escaneó toda la lista a la velocidad de la luz y, gracias a nuestro bloque `if`, hizo sonar la alarma. ¡Acabas de automatizar tu primera auditoría de calidad!

---

## 🆕 Tres formas de buscar `None` en Python: ¿cuál usar?

En esta sesión usaremos tres expresiones diferentes para trabajar con `None`. Antes de continuar, conoce la diferencia para no confundirte:

| Expresión | ¿Qué pregunta? | ¿Cuándo usarla? |
|---|---|---|
| `None in lista` | ¿Existe al menos un `None` en toda la lista? | Para **detectar** si hay nulos (radar de existencia) |
| `elemento is None` | ¿Este elemento específico es `None`? | Dentro de un `for`, para **localizar** la posición exacta |
| `elemento == None` | Equivalente a `is None` pero menos preciso | Evitar — `is None` es la forma recomendada en Python |

> 💡 **Regla práctica:** Usa `None in lista` para el primer chequeo rápido. Usa `is None` dentro de un `for` cuando necesitas saber exactamente *cuál* elemento es nulo. Nunca uses `== None`.

---

### Ejercicio 1.1: El Auditor Financiero (Calentamiento)

Imagina que eres el auditor de una tienda y te entregan la lista de ingresos diarios de la semana. Tienes la sospecha de que un día el sistema falló y no registró ventas.

**Tu tarea:**

1. En la celda de abajo, tienes la lista `ingresos_semana`.
2. Escribe una condición `if` usando la palabra `in` para verificar si existe un `None` dentro de la lista.
3. Si existe, usa `print()` para mostrar un mensaje de alerta.
4. Escribe un `else` y usa `print()` para mostrar un mensaje de éxito en caso de que la lista esté limpia.
"""

ingresos_semana = [1500, 2200, 1800, None, 2500, 3000, 1900]

# Escribe aquí tu código para el Ejercicio 1.1:

"""---

## Parte 2: De la Teoría a la Práctica (Cazando Valores Nulos)

En el ejercicio de calentamiento, le preguntamos a Python si *existía* algún error. Ahora vamos a construir un radar avanzado para detectar **dónde** están esos datos faltantes.

Imagina que recibes una lista con los salarios mensuales de varios sujetos de estudio, pero la recolección estuvo llena de errores.

### El Radar de Nulos y el Escaneo Automatizado

Usaremos un bucle `for` combinado con un condicional `if` para que Python recorra la base de datos por nosotros. Ejecuta este código:

"""

# Nuestra base de datos con valores faltantes (None)
salarios = [15000, 18500, None, 22000, None, 17400, 19000]

# Encendemos el escáner: revisamos elemento por elemento
for posicion, salario in enumerate(salarios):
    if salario is None:
        print(f"🚨 ¡Alerta! Dato faltante encontrado en la posición: {posicion}")

# Resumen al final
total_nulos = sum(1 for s in salarios if s is None)
print(f"\n📊 Total de nulos encontrados: {total_nulos} de {len(salarios)} registros")

"""### Explicación Paso a Paso

¿Qué sucedió internamente en fracciones de segundo?

1. **El recorrido incansable:** La función `enumerate()` nos permite recorrer la lista obteniendo automáticamente dos cosas en cada parada: la **posición** exacta (0, 1, 2...) y el **valor** del salario que contiene.
2. **La lupa de inspección:** En cada paso, la instrucción `if salario is None:` actúa como un inspector que pregunta de forma estricta: *"¿Esta celda está vacía?"*.
3. **La alerta:** Si el dato es un número válido, Python avanza en silencio. Si descubre un `None`, ejecuta la alerta e imprime la posición exacta.

Acabas de reemplazar el trabajo manual. En lugar de forzar tus ojos haciendo *scroll* interminable en una hoja de Excel gigante, programaste un asistente virtual capaz de revisar millones de registros sin fatigarse.

---

## 🆕 ¿Por qué usamos `is None` y no `== None`?

La sesión anterior mencionamos que `is None` es la forma correcta. Aquí está la razón técnica con un ejemplo ejecutable. Este es el tipo de conocimiento que separa a un programador principiante de uno profesional:
"""

# Demostración: 'is' vs '==' con None

dato_vacio = None
numero = 0
texto_vacio = ""

print("Probando con None real:")
print(f"  dato_vacio is None  → {dato_vacio is None}")    # ✅ Correcto
print(f"  dato_vacio == None  → {dato_vacio == None}")    # También True, pero evitar

print()
print("El peligro de == : puede dar 'True' en objetos personalizados que lo redefinan.")
print("'is None' siempre es 100% confiable porque verifica identidad en memoria, no igualdad.")

print()
print("Casos que NO son None (¡trampas comunes!):")
print(f"  0 is None       → {0 is None}   ← el cero NO es nulo")
print(f"  '' is None      → {'' is None}  ← string vacío NO es nulo")
print(f"  False is None   → {False is None}  ← False NO es nulo")
print()
print("⚠️  Cada uno de estos 'datos vacíos' requiere una estrategia diferente.")

"""---

### Ejercicio 2.1: El Auditor de Sensores (Contador de Nulos)

Saber en qué posición están los errores es útil, pero a veces los directivos solo quieren saber el **total** de errores para decidir si la base de datos sirve o se desecha. Vamos a crear un contador.

Imagina que estás auditando un sensor de temperatura de una máquina industrial. El sensor falló en algunos momentos del día y registró valores nulos.

**Tu tarea:**

1. Abajo tienes la lista `temperaturas` y una variable `total_nulos` que empieza en 0.
2. Crea un bucle `for` (puedes usar `for temp in temperaturas:`).
3. Dentro del bucle, usa un `if` para revisar si la temperatura `is None`.
4. Si lo es, súmale 1 a tu contador (`total_nulos = total_nulos + 1`).
5. Fuera del bucle (quitando la indentación), imprime el gran total de fallas.
6. **🔥 RETO EXTRA:** Calcula el **% de fallas** (`total_nulos / len(temperaturas) * 100`) y muéstralo con `round()` a 1 decimal.

"""

temperaturas = [36.5, 37.2, None, 36.8, None, None, 37.1]
total_nulos = 0

# Escribe aquí tu código para el Ejercicio 2.1:

"""---

## Parte 3: Exploración con Datos (Detectando Duplicados)

### El Problema del Doble Registro

Imagina que estás administrando los ingresos de un hospital. Si un paciente con una enfermedad rara es registrado dos veces por un error del sistema, tus estadísticas indicarán que hay un brote epidémico cuando en realidad no lo hay. Si una factura se registra dos veces, la empresa perderá dinero pagando el doble.

Contar a la misma persona o evento más de una vez es uno de los errores más peligrosos en el análisis de datos porque altera por completo la realidad.

### Código para Duplicados: Nuestro Escáner de Memoria

Para evitar esto, le enseñaremos a Python a tener "memoria". Crearemos una lista de control vacía y revisaremos a los pacientes uno por uno. Si el paciente ya está en nuestra lista, encenderemos una alarma; si no, lo guardaremos ahí de forma segura.

Ejecuta este código:

"""

# Nuestra base de datos con errores intencionales (los IDs 101 y 102 se repiten)
ids_pacientes = [101, 102, 103, 101, 104, 105, 102]

# Nuestra lista de control (inicia vacía)
lista_segura = []
duplicados_encontrados = 0

# Encendemos el escáner
for paciente in ids_pacientes:
    if paciente in lista_segura:
        print(f"🚨 ¡Duplicado detectado! El ID {paciente} ya fue registrado.")
        duplicados_encontrados += 1
    else:
        lista_segura.append(paciente)

print("─" * 40)
print(f"Duplicados encontrados : {duplicados_encontrados}")
print(f"Base de datos limpia   : {lista_segura}")

"""### Lógica Computacional: El poder del operador `in`

¿Cómo supo la computadora qué números estaban repetidos sin que tú tuvieras que decírselo? El secreto está en la instrucción **`in`**.

Cuando escribimos `if paciente in lista_segura:`, le hacemos a Python una pregunta directa: *"Oye, revisa la lista. ¿Este paciente ya se encuentra adentro?"*.

1. La primera vez que el escáner lee el `101`, la `lista_segura` está vacía. Como la respuesta es Falsa, pasa a `else` y lo guarda con `append()`.
2. La segunda vez que el escáner se topa con un `101`, vuelve a preguntar. Esta vez la respuesta es Verdadera, por lo que se activa la alarma y **no se vuelve a guardar**.

¡Acabas de automatizar un proceso de auditoría que a un humano le tomaría días realizar en un Excel de miles de filas!

---

## 🆕 Forma más eficiente: `set()` para detectar duplicados

El escáner con lista de control que acabas de aprender es perfecto para entender la lógica. Pero existe una forma más rápida y eficiente para datasets grandes usando **`set()`** (conjunto). Los conjuntos no permiten elementos repetidos por definición, así que Python los elimina automáticamente:
"""

# El mismo problema, dos soluciones
ids_pacientes = [101, 102, 103, 101, 104, 105, 102]

# MÉTODO LISTA (el que aprendiste — muestra cuáles son los duplicados)
lista_segura = []
for pid in ids_pacientes:
    if pid not in lista_segura:
        lista_segura.append(pid)

# MÉTODO SET (más rápido — elimina automáticamente los repetidos)
ids_unicos_set = list(set(ids_pacientes))
ids_unicos_set.sort()  # ordenamos para ver mejor

print(f"Original           : {ids_pacientes}  ({len(ids_pacientes)} registros)")
print(f"Con lista (método 1): {lista_segura}  ({len(lista_segura)} únicos)")
print(f"Con set   (método 2): {ids_unicos_set}  ({len(ids_unicos_set)} únicos)")
print()
print(f"Duplicados eliminados: {len(ids_pacientes) - len(ids_unicos_set)}")
print()
print("¿Cuándo usar cada uno?")
print("  Método lista → cuando necesitas REPORTAR cuáles son los duplicados")
print("  Método set   → cuando solo necesitas la lista limpia, sin importar cuáles eran")

"""---

### Ejercicio 3.1: El Gestor de Boletines (Marketing)

El departamento de Marketing te entregó una lista de correos de clientes que se suscribieron hoy. Tu tarea es enviarles un boletín de bienvenida, pero la página web falló y algunos clientes se registraron dos veces. ¡Si les envías el correo doble, pensarán que es *spam*!

**Tu tarea:**

1. Abajo tienes la lista `correos` y tu lista vacía `correos_unicos`.
2. Crea un bucle `for` para recorrer la lista de `correos`.
3. Usa un `if` con `in` para revisar si el correo ya está en `correos_unicos`.
4. Si ya está, imprime un mensaje de alerta de duplicado.
5. Usa `else` para guardarlo con `.append()` si es la primera vez.
6. Al final, imprime tu lista de `correos_unicos`.
7. **🔥 RETO EXTRA:** Agrega un contador de duplicados e imprímelo al final.

"""

correos = ["ana@mail.com", "luis@mail.com", "ana@mail.com", "carlos@mail.com"]
correos_unicos = []

# Escribe aquí tu código para el Ejercicio 3.1:

"""---

## 🆕 Combinar ambos radares: Una función de auditoría reutilizable

Antes del Reto final, observa cómo podemos combinar el radar de nulos y el de duplicados en una **función** que puedes reutilizar con cualquier lista de diccionarios. Este patrón es el que usarás constantemente en tu carrera como Científico de Datos:

"""

def auditar_lista(lista_datos, campo_id, campo_verificar):
    """
    Audita una lista de diccionarios buscando nulos y duplicados.
    campo_id       : nombre de la llave que identifica únicamente cada registro
    campo_verificar: nombre de la llave que podría tener valores None
    """
    ids_vistos = []
    nulos      = 0
    duplicados = 0

    for registro in lista_datos:
        # Radar de nulos
        if registro[campo_verificar] is None:
            print(f"🚫 Nulo encontrado en: {registro['nombre']} → campo '{campo_verificar}'")
            nulos += 1

        # Radar de duplicados
        pid = registro[campo_id]
        if pid in ids_vistos:
            print(f"🔁 Duplicado encontrado: {campo_id}={pid} ({registro['nombre']})")
            duplicados += 1
        else:
            ids_vistos.append(pid)

    print("─" * 50)
    print(f"📊 RESUMEN: {len(lista_datos)} registros → {nulos} nulo(s), {duplicados} duplicado(s)")

# Probamos con datos de ejemplo
prueba = [
    {"nombre": "Ana",    "id": 1, "resultado": "Normal"},
    {"nombre": "Luis",   "id": 2, "resultado": None},
    {"nombre": "Carlos", "id": 3, "resultado": "Alto"},
    {"nombre": "Pedro",  "id": 2, "resultado": "Bajo"},   # duplicado de id=2
]

auditar_lista(prueba, campo_id="id", campo_verificar="resultado")

"""---

## Parte 4: Reto Práctico (El Escáner Definitivo)

Llegó el momento de la verdad. Vamos a fusionar nuestros dos radares (el de nulos y el de duplicados) para crear un único sistema de auditoría capaz de escanear bases de datos complejas.

**Tus instrucciones paso a paso:**

1. **El Bucle:** Crea un bucle `for` que recorra cada elemento (`paciente`) dentro de la lista `pacientes`.
2. **Radar de Nulos:** Dentro del bucle, usa un `if` para revisar si `paciente["resultado_estudio"] is None`. Si es así, imprime una alerta que incluya el `nombre` del paciente.
3. **Radar de Duplicados:** Debajo (aún dentro del bucle), agrega otro bloque `if/else` para revisar si el `id` del paciente ya existe en `ids_seguros`. Si ya está ahí, imprime una alerta. Si no, agrégalo con `.append()`.
4. **🔥 RETO EXTRA:** Al final del bucle, imprime un resumen con `f-strings`: cuántos nulos y cuántos duplicados se encontraron en total.

"""

# Nuestra base de datos de pacientes (¡Tiene trampas!)
pacientes = [
    {"nombre": "Ana",    "id": 101, "resultado_estudio": "Normal"},
    {"nombre": "Luis",   "id": 102, "resultado_estudio": "Alto"},
    {"nombre": "Carmen", "id": 103, "resultado_estudio": None},   # ¡Dato faltante!
    {"nombre": "Jorge",  "id": 104, "resultado_estudio": "Bajo"},
    {"nombre": "Pedro",  "id": 102, "resultado_estudio": "Normal"} # ¡ID Duplicado!
]

# Lista de control para nuestra memoria de duplicados
ids_seguros = []

# ¡Enciende tu escáner definitivo debajo de esta línea!

"""---

### 🧠 Diagnóstico de la Auditoría

Haz doble clic en esta celda y responde brevemente a tu hallazgo:

> *Imagina que le entregas los resultados de este escáner al director médico. ¿Qué problemas operativos graves le estarías evitando al haber detectado a Carmen (sin resultado) y a Pedro (con ID duplicado)?*

**(Escribe tu respuesta aquí):**

*

**Pregunta adicional:** Según la **tabla de estrategias de S11**, ¿qué harías con el registro de Carmen — eliminarías la fila o intentarías rellenar el dato faltante? Justifica tu decisión.

*

---

## 🆕 Puente al Módulo 2: Lo que Python puro no puede hacer solo

¡Excelente trabajo! Has dominado el Módulo 1 completo. Ahora sabes detectar nulos y duplicados con Python puro usando `for`, `if` e `in`.

Pero existe una pregunta natural: ¿y si el dataset tiene **100 columnas y 500,000 filas**? Escribir un `for` manual para cada columna sería agotador.

En el **Módulo 2** aprenderás a usar **Pandas** 🐼, la biblioteca que hace todo esto en 2 líneas. Ejecuta esta celda para ver lo que te espera — aún no necesitas entenderlo todo, solo observa la diferencia:
"""

# Anticipo del Módulo 2 — Pandas en acción
# (Esta celda puede tardar unos segundos la primera vez)
import pandas as pd

datos = {
    "nombre":            ["Ana",    "Luis",  "Carmen", "Jorge", "Pedro"],
    "id":                [101,       102,     103,      104,     102  ],
    "resultado_estudio": ["Normal", "Alto",   None,    "Bajo",  "Normal"]
}
df = pd.DataFrame(datos)

print("📋 DataFrame original (5 filas):")
print(df)

# Diagnóstico en 1 línea
print(f"\n🚫 Nulos por columna:\n{df.isnull().sum()}")
print(f"\n🔁 Filas con ID duplicado: {df.duplicated(subset='id').sum()}")
print("   (Pedro tiene id=102, igual que Luis → es el duplicado)")

# Limpieza en 2 líneas
df_limpio = df.dropna()                          # Elimina a Carmen
df_limpio = df_limpio.drop_duplicates(subset='id')  # Elimina a Pedro

print(f"\n✅ DataFrame limpio (quedan 3 filas: Ana, Luis, Jorge):")
print(df_limpio)
print(f"\nAntes  : {len(df)} registros")
print(f"Después: {len(df_limpio)} registros limpios")