# -*- coding: utf-8 -*-
"""Sesión 5: Fundamentos de Python desde Cero

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G2uBx_Butw4mZqS5F4RJbklL0fMAjrzv

# Sesión 5: Fundamentos de Python desde Cero

### La Sintaxis: El idioma de la máquina
Aprender Python es exactamente igual que aprender un nuevo idioma humano, como el francés o el inglés. Para que las personas te entiendan, debes respetar ciertas reglas gramaticales y de ortografía. En programación, a este conjunto de reglas lo llamamos **Sintaxis**.

La sintaxis dicta cómo debemos escribir nuestras instrucciones para que la máquina las comprenda. Hay una diferencia importante: si en español escribes "ola" en lugar de "hola", una persona aún podrá deducir lo que quisiste decir por el contexto. Las computadoras, en cambio, son extremadamente literales. Si olvidamos un símbolo o escribimos mal una palabra, la máquina se detendrá y nos mostrará una alerta llamada `SyntaxError` (Error de Sintaxis).

Es fundamental perderle el miedo a esta pantalla de error desde hoy; no significa que descompusiste la computadora, es simplemente la máquina diciéndote: *"Perdón, no entendí tu gramática, ¿puedes repetirlo?"*.

---

### Variables: Las cajas de mudanza
Para poder analizar información, primero necesitamos guardarla en la memoria de la computadora. Para eso utilizamos las **Variables**.

Imagina que una variable es como una caja de mudanza. Cuando te mudas, metes objetos en una caja y le pegas una etiqueta por fuera con un marcador (por ejemplo, "Libros" o "Ropa") para saber qué contiene sin tener que abrirla. En Python funciona igual: la etiqueta escrita con el marcador es el nombre de la variable, y lo que metemos adentro es nuestro dato.

**Repaso rápido: Reglas para nombrar tus cajas**
Para que la computadora lea bien tus etiquetas, recuerda usar la convención `snake_case` (minúsculas y guiones bajos) y evitar caracteres especiales:
* ✅ **Correcto:** `edad_paciente`, `total_ventas`, `anio_2026`.
* ❌ **Incorrecto:** `edad paciente` (tiene un espacio), `1er_lugar` (empieza con número).

---

### Tipos de Datos: Clasificando el contenido

En una mudanza real, no guardarías copas de cristal en la misma caja que unas pesas de metal; clasificas el contenido por su naturaleza. En la ciencia de datos hacemos lo mismo. Dependiendo de la información, la guardamos en cuatro diferentes tipos de cajas (Tipos de Datos):

1. **Texto (*Strings* o Cadenas):** Sirven para guardar palabras, letras, nombres, diagnósticos o categorías.
   * *Ejemplos:* "Paciente A", "Ciudad de México", "Ingeniería Civil".
2. **Números Enteros (*Integers*):** Son números completos, sin punto decimal. Se usan para contar unidades indivisibles.
   * *Ejemplos:* 25 (años de edad), 100 (habitaciones de hospital).
3. **Números Decimales (*Floats*):** Son números que sí utilizan punto decimal, necesarios cuando requerimos alta precisión.
   * *Ejemplos:* 36.5 (grados de temperatura), 150.99 (costo de un producto).
4. **Lógicos (*Booleans* o Booleanos):** Son cajas muy pequeñas que solo aceptan respuestas binarias absolutas (Sí o No). Se usan muchísimo para hacer clasificaciones. Solo admiten dos palabras en inglés: `True` (Verdadero) o `False` (Falso).

---

### ⚠️ La Regla de Oro Visual: ¿Comillas o no comillas?
Para que Python entienda qué tipo de caja estás usando sin confundirse, debes seguir una regla estricta al escribir tu código:

* El **Texto (*Strings*) SIEMPRE va entre comillas** (pueden ser simples `' '` o dobles `" "`): `"Ingeniería"`
* Los **Números (*Integers/Floats*) y los *Booleanos*** **NUNCA llevan comillas**: `25`, `True`

*(💡 **Nota:** Si por error escribes `"25"` entre comillas, Python pensará que son los dibujos de un dos y un cinco (texto), no un valor matemático, y marcará error si intentas sumarlo o restarlo).*

---

### Ejercicio 1: El Gimnasio Mental (Clasificador de Cajas)

Antes de teclear, vamos a entrenar tu intuición de científico de datos. Lee los siguientes 4 ejemplos de datos de la vida real e identifica mentalmente qué Tipo de Dato (`String`, `Integer`, `Float` o `Boolean`) es el adecuado para guardar esa información.

*(Las respuestas están al final, ¡pero no hagas trampa!)*

1. El peso exacto en gramos de una muestra biológica en el laboratorio (Ej. 14.5).
2. El nombre de la facultad del estudiante (Ej. "Ciencias Sociales").
3. El número total de camas disponibles en el área de urgencias (Ej. 42).
4. ¿El alumno tiene derecho a beca este semestre? (Ej. Sí/No).

> **Respuestas del Ejercicio 1:**
> *1. Float (Decimal) | 2. String (Texto) | 3. Integer (Entero) | 4. Boolean (True/False)*

---

## Parte 2: De la Teoría a la Práctica: Creando "Cajas"

Ahora que entendemos cómo Python clasifica la información en su "cabeza", vamos a crear nuestras primeras variables.

Para crear una variable, simplemente inventamos un nombre (la etiqueta de nuestra caja, recordando usar minúsculas y guiones bajos `_`) y usamos el signo de igual (`=`) para guardar el dato adentro.

*(💡 **Tip informático:** En programación, el signo `=` no significa "igual matemático", significa **"asignar"**. Le estamos diciendo a la computadora: "Toma el dato que está a la derecha y guárdalo en la caja de la izquierda").*
"""

# ============================================================
# ESCÁNER DE TIPOS — Variables del Paciente
# NOTA: Definimos las variables aquí para que esta celda sea
#       ejecutable de forma independiente en cualquier orden.
# ============================================================

nombre_paciente = "Ana"
edad = 28
estatura = 1.65
alta_medica = True

# ── Escáner de tipos ───────────────────────────────────────
print(f"  nombre_paciente = {nombre_paciente!r}  →  {type(nombre_paciente)}")
print(f"  edad            = {edad}               →  {type(edad)}")
print(f"  estatura        = {estatura}            →  {type(estatura)}")
print(f"  alta_medica     = {alta_medica}         →  {type(alta_medica)}")

"""### La Regla Visual en Acción

Si observas el código que acabamos de ejecutar, notarás la "Regla de Oro" que vimos en la teoría: el texto tiene comillas y los números/lógicos no.

**¿Qué pasaría si rompes la regla y le pones comillas a un número, como `"28"`?**
La computadora dejará de verlo como un valor matemático y lo tratará como un simple texto. Si intentaras hacer la operación `"28" + 1`, Python entraría en pánico y te daría un error, porque es el equivalente a pedirle que sume la palabra "Manzana" más el número 1. ¡No tiene sentido matemático!

---

### Descubriendo el tipo de dato: La función `type()`

A veces, cuando descargamos bases de datos inmensas de internet, no sabemos qué tipo de datos vienen adentro de cada columna. Afortunadamente, Python tiene una herramienta integrada llamada `type()` (tipo, en inglés) que actúa como un **escáner de rayos X** para decirnos qué hay exactamente dentro de nuestra "caja".

Vamos a combinar nuestro nuevo escáner `type()` con la función `print()` que ya dominas para poder ver el resultado en pantalla:

"""

# Escaneando el tipo de dato de nuestras variables
print(type(nombre_paciente))
print(type(edad))
print(type(estatura))
print(type(alta_medica))

"""**¿Qué significan estas extrañas palabras en tu pantalla?**
Al ejecutar la celda anterior, el escáner analizó cada caja y nos devolvió su diagnóstico:

* `<class 'str'>`: Detectó las comillas en "Ana" y nos dice que es un *String* (Cadena de texto).
* `<class 'int'>`: Detectó el 28 sin decimales y nos avisa que es un *Integer* (Entero).
* `<class 'float'>`: Detectó el 1.65 y nos dice que es un *Float* (Decimal).
* `<class 'bool'>`: Detectó la palabra reservada `True` y nos confirma que es un *Boolean* (Booleano o Lógico).

---

### Ejercicio 2: Tú eres el dato (El Escáner en Acción)

¡Es tu turno de programar! Vamos a comprobar que la computadora puede escanear tu propia información.

**Tu Tarea:**

1. Crea una celda de **Código** nueva debajo de este texto (recuerda tu atajo `Ctrl` + `M`, luego `B`).
2. Crea cuatro variables sobre ti mismo (inventa los nombres de las etiquetas, respetando las reglas de escritura).
* Una con tu nombre (Texto).
* Una con tu edad (Entero).
* Una con tu estatura aproximada (Decimal).
* Una que responda si te gusta el café (Booleano: `True` o `False`).

3. En la misma celda, usa `print(type( ))` para escanear y mostrar en pantalla el tipo de dato de cada una de tus cuatro cajas.
4. Ejecuta la celda (`Shift` + `Enter`) y verifica que los cuatro resultados sean correctos (`str`, `int`, `float`, `bool`).

---

"""

# Escribe aquí tu código para el Ejercicio 2:
# Crea tus 4 variables y usa print(type()) en cada una

"""---

### 🆕 La Forma Profesional de Mostrar Variables: f-strings

Hasta ahora hemos usado `print()` así: `print("El nombre es:", nombre_paciente)`. Esto funciona, pero tiene un problema: si quieres combinar texto y variables en una frase larga, el código se vuelve complicado y difícil de leer.

Los profesionales de datos usan una técnica llamada **f-string** (cadena de formato), que te permite insertar variables directamente dentro de un texto de forma limpia. La regla es muy sencilla:

1. Pon una `f` justo **antes** de las comillas iniciales: `f"..."`
2. Coloca el nombre de tu variable entre llaves `{}` dentro del texto

```python
# Forma antigua (concatenación):
print("Paciente: " + nombre_paciente + ", Edad: " + str(edad))

# Forma profesional (f-string) → mucho más legible:
print(f"Paciente: {nombre_paciente}, Edad: {edad}")
```

> 💡 **Ventaja extra:** Con f-strings, los números se insertan **directamente** sin necesidad de convertirlos a texto con `str()`. Python lo hace automáticamente.

"""

# ============================================================
# F-STRINGS EN ACCIÓN: Usando las variables del paciente
# ============================================================

# Forma antigua con comas (funciona, pero es menos elegante)
print("--- Forma antigua ---")
print("Paciente:", nombre_paciente, "| Edad:", edad, "| Estatura:", estatura)

# Forma profesional con f-string (usaremos esto el resto del diplomado)
print("\n--- Forma profesional (f-string) ---")
print(f"Paciente: {nombre_paciente}")
print(f"Edad: {edad} años")
print(f"Estatura: {estatura} m")
print(f"Alta médica: {alta_medica}")

# BONUS: Los f-strings también hacen cálculos dentro de las llaves
print("\n--- BONUS: Cálculo directo dentro del f-string ---")
print(f"En 10 años, {nombre_paciente} tendrá {edad + 10} años.")

"""---

## Parte 3: Operaciones Matemáticas: Haciendo cálculos con nuestras cajas

Ahora que ya tenemos nuestra información clasificada y guardada en variables, ¡es hora de hacer que la computadora trabaje por nosotros! En programación, hacer cálculos no es más que aplicar la misma lógica matemática que aprendiste en la escuela, pero utilizando los símbolos correctos en tu teclado.

### Los Símbolos Matemáticos (Operadores Aritméticos)

| Símbolo | Operación | Ejemplo | Resultado |
|---|---|---|---|
| `+` | Suma | `10 + 3` | `13` |
| `-` | Resta | `10 - 3` | `7` |
| `*` | Multiplicación | `10 * 3` | `30` |
| `/` | División | `10 / 3` | `3.333...` |
| `//` | División entera | `10 // 3` | `3` (sin decimales) |
| `%` | Módulo (residuo) | `10 % 3` | `1` (lo que sobra) |
| `**` | Potencia | `2 ** 8` | `256` |

### Ejemplo Paso a Paso: Calculando el Índice de Masa Corporal (IMC)

Vamos a aplicar esto a un caso real. Imagina que necesitas calcular el IMC de un paciente. La fórmula médica tradicional nos dice que dividamos el peso entre la estatura elevada al cuadrado.

Veamos cómo se traduce esta lógica a código de Python:

"""

# 1. Creamos las cajas (variables) con los datos iniciales del paciente
peso = 70.5
estatura = 1.75

# 2. Hacemos el cálculo y lo guardamos en una NUEVA caja llamada "imc"
# Nota: Usamos ** 2 para indicarle a Python que eleve la estatura al cuadrado
imc = peso / (estatura ** 2)

# 3. Mostramos el resultado usando f-string (la forma profesional)
print(f"El Índice de Masa Corporal del paciente es: {imc:.2f}")
# El :.2f dentro de las llaves significa: muestra solo 2 decimales

"""### ¿Cuál es la lógica "oculta" detrás de esto?

Es fundamental entender cómo lee Python la línea de nuestro cálculo (`imc = peso / (estatura ** 2)`):

1. **Primero resuelve el lado derecho:** Python es muy obediente. Va a buscar los valores escondidos dentro de las cajas `peso` y `estatura`, saca los números (70.5 y 1.75) y realiza la operación matemática respetando los paréntesis, exactamente igual que una calculadora científica tradicional.
2. **Luego guarda el resultado:** Una vez que obtiene el valor final del cálculo, toma ese número y lo "guarda" en la nueva caja que pusimos al lado izquierdo del signo de igual (nuestra variable `imc`).
3. **La impresión con f-string:** Usamos `{imc:.2f}` para que el resultado se muestre con exactamente 2 decimales, como lo haría un reporte médico profesional.

---

### Ejercicio 3: El Analista Demográfico (Calculando Porcentajes)

¡Es tu turno de hacer que la máquina trabaje! Vamos a salir del hospital y entrar al área de las ciencias sociales.

Imagina que estás analizando una encuesta realizada a **500** estudiantes de tu universidad. Descubres que **85** de ellos sufren de estrés extremo durante los exámenes. Quieres saber qué porcentaje exacto representa ese grupo.

*(💡 **Tip matemático:** Para sacar un porcentaje, divides la parte entre el total y lo multiplicas por 100).*

**Tu Tarea:**

1. En la celda de código de abajo, crea una variable llamada `total_estudiantes` y asígnale el valor `500`.
2. Crea otra variable llamada `estudiantes_estresados` y asígnale el valor `85`.
3. Crea una tercera variable llamada `porcentaje_estres`. Haz que sea igual al cálculo matemático utilizando tus dos primeras variables y multiplicando por 100.
4. Usa un `print()` con **f-string** para mostrar en pantalla una frase como: `"El porcentaje de alumnos con estrés es: XX%"` con tu resultado.
5. ¡Ejecuta tu celda (`Shift` + `Enter`)!

"""

# Escribe aquí tu código para el Ejercicio 3:
# Tip: usa f"{porcentaje_estres:.1f}%" para mostrar 1 decimal y el símbolo %

"""###PEMDAS en Python para Ciencia de Datos###

**PEMDAS (en español PAPOMUDAS)** define el orden en que Python evalúa las operaciones matemáticas:

| Letra | Operación                           | Operador Python |
| ----- | ----------------------------------- | --------------- |
| P     | Paréntesis                          | ( )             |
| E     | Exponentes (Potencias)              | **              |
| M     | Multiplicación                      | *               |
| D     | División / División entera / Módulo | /, //, %        |
| A     | Adición (Suma)                      | +               |
| S     | Sustracción (Resta)                 | -               |
"""

# ============================================================
# 🎓 CLASE: PEMDAS en Python para Ciencia de Datos
# ============================================================

print("=" * 50)
print("  PEMDAS - Orden de Operaciones en Python")
print("=" * 50)

# --------------------------------------------------
# 1️⃣ P - PARÉNTESIS (máxima prioridad)
# --------------------------------------------------
print("\n📌 1. PARÉNTESIS")
sin_parentesis = 2 + 3 * 4
con_parentesis = (2 + 3) * 4
print(f"  2 + 3 * 4       = {sin_parentesis}")  # 14
print(f"  (2 + 3) * 4     = {con_parentesis}")  # 20
print("  ⚠️  Los paréntesis cambian el resultado!")

# --------------------------------------------------
# 2️⃣ E - EXPONENTES (Potencias)
# --------------------------------------------------
print("\n📌 2. EXPONENTES  (operador **)")
cuadrado  = 3 ** 2
cubo      = 2 ** 3
raiz      = 16 ** 0.5        # Raíz cuadrada = exponente 0.5
print(f"  3 ** 2  = {cuadrado}")   # 9
print(f"  2 ** 3  = {cubo}")       # 8
print(f"  16** 0.5 = {raiz}")      # 4.0  ← útil en estadística

# --------------------------------------------------
# 3️⃣ M - MULTIPLICACIÓN
# --------------------------------------------------
print("\n📌 3. MULTIPLICACIÓN")
resultado = 6 * 7
print(f"  6 * 7 = {resultado}")    # 42

# --------------------------------------------------
# 4️⃣ D - DIVISIÓN (3 tipos en Python)
# --------------------------------------------------
print("\n📌 4. DIVISIÓN")
div_real   = 10 / 3     # División real (float)
div_entera = 10 // 3    # División entera (floor)
modulo     = 10 % 3     # Residuo (módulo)
print(f"  10 / 3  = {div_real:.4f}  ← División real")
print(f"  10 // 3 = {div_entera}      ← División entera")
print(f"  10 % 3  = {modulo}          ← Módulo (residuo)")

# --------------------------------------------------
# 5️⃣ A y S - SUMA y RESTA (menor prioridad)
# --------------------------------------------------
print("\n📌 5. SUMA y RESTA")
suma  = 100 + 25
resta = 100 - 25
print(f"  100 + 25 = {suma}")
print(f"  100 - 25 = {resta}")

# ==================================================
# 🔬 APLICACIÓN EN CIENCIA DE DATOS
# ==================================================
print("\n" + "=" * 50)
print("  🔬 PEMDAS Aplicado en Ciencia de Datos")
print("=" * 50)

datos = [4, 8, 15, 16, 23, 42]
n     = len(datos)

# --- Media (promedio) ---
# Fórmula: mean = suma / n
media = sum(datos) / n
print(f"\n📊 Media aritmética:")
print(f"  sum(datos) / n = {sum(datos)} / {n} = {media:.2f}")

# --- Varianza ---
# Fórmula: varianza = Σ(xi - media)² / n
# PEMDAS importa: primero la resta dentro del paréntesis,
# luego el exponente, luego la suma, finalmente la división
varianza = sum((x - media) ** 2 for x in datos) / n
print(f"\n📊 Varianza:")
print(f"  Σ(xi - media)² / n = {varianza:.2f}")
print(f"  Orden PEMDAS: (resta) → ** → sum() → /")

# --- Desviación estándar ---
desv_std = varianza ** 0.5
print(f"\n📊 Desviación estándar:")
print(f"  varianza ** 0.5 = {desv_std:.2f}")

# --- Normalización Min-Max ---
# Fórmula: (x - min) / (max - min)
# PEMDAS: paréntesis primero, luego división
minimo  = min(datos)
maximo  = max(datos)
print(f"\n📊 Normalización Min-Max  (resultado entre 0 y 1):")
for x in datos:
    norm = (x - minimo) / (maximo - minimo)
    print(f"  ({x} - {minimo}) / ({maximo} - {minimo}) = {norm:.3f}")

# ==================================================
# ⚠️  ERRORES COMUNES
# ==================================================
print("\n" + "=" * 50)
print("  ⚠️  ERRORES COMUNES (¡Cuidado!)")
print("=" * 50)

# Error clásico: calcular promedio sin paréntesis
a, b, c = 10, 20, 30
malo  = a + b + c / 3    # ❌ Solo divide c entre 3
bueno = (a + b + c) / 3  # ✅ Divide la suma entre 3
print(f"\n  ❌ a + b + c / 3     = {malo}")
print(f"  ✅ (a + b + c) / 3   = {bueno}")
print("  → SIEMPRE usa paréntesis en fórmulas estadísticas")

# ==================================================
# 🧩 EJERCICIO RÁPIDO
# ==================================================
print("\n" + "=" * 50)
print("  🧩 EJERCICIO — Evalúa mentalmente:")
print("=" * 50)
expresiones = [
    "2 + 3 ** 2",
    "(2 + 3) ** 2",
    "10 - 4 / 2 + 1",
    "10 - 4 / (2 + 1)",
]
for expr in expresiones:
    print(f"  {expr:25s} = {eval(expr)}")

"""---

### 🔍 Operadores de Comparación: Haciendo preguntas a los datos

Los operadores matemáticos calculan valores. Los **operadores de comparación** hacen algo diferente: le hacemos una **pregunta** a Python y él nos responde con un `True` (Sí, es verdad) o un `False` (No, es falso).

Estos son el puente entre las variables y el control de flujo (`if/else`) que aprenderás en la Sesión 7. **Sin comparadores, no hay decisiones automáticas.**

| Símbolo | Significado | Ejemplo | Resultado |
|---|---|---|---|
| `==` | ¿Es **igual** a? | `28 == 28` | `True` |
| `!=` | ¿Es **diferente** a? | `28 != 30` | `True` |
| `>` | ¿Es **mayor** que? | `30 > 28` | `True` |
| `<` | ¿Es **menor** que? | `28 < 30` | `True` |
| `>=` | ¿Es **mayor o igual** que? | `28 >= 28` | `True` |
| `<=` | ¿Es **menor o igual** que? | `25 <= 28` | `True` |

> ⚠️ **Error clásico:** No confundas `=` (asignar/guardar) con `==` (comparar/preguntar). `edad = 28` guarda el número. `edad == 28` pregunta: *¿la edad guardada es 28?*

"""

# ============================================================
# OPERADORES DE COMPARACIÓN EN ACCIÓN
# ============================================================

# Datos de un paciente
edad_paciente = 28
temperatura   = 38.5
diagnostico   = "diabetes"

print("--- Preguntas sobre el paciente ---")

# ¿Es mayor de edad?
print(f"¿Es mayor de edad? (edad >= 18): {edad_paciente >= 18}")

# ¿Tiene fiebre?
print(f"¿Tiene fiebre? (temperatura > 37.5): {temperatura > 37.5}")

# ¿Tiene exactamente 30 años?
print(f"¿Tiene exactamente 30 años? (edad == 30): {edad_paciente == 30}")

# ¿El diagnóstico es Diabetes?
print(f"¿Diagnóstico es Diabetes? (diagnostico == 'Diabetes'): {diagnostico == 'Diabetes'}")

print("\n💡 Python responde True o False — igual que los booleanos que vimos antes.")
print("   En la Sesión 7 usarás estas preguntas dentro de if/else para tomar decisiones.")

"""---

## Parte 4: Reto Práctico: Tu Calculadora Personal

Para cerrar con broche de oro esta quinta sesión, vas a escribir tu primer programa funcional completamente solo. Tu misión será crear una "Calculadora Personal" que determine tu edad usando las reglas de sintaxis y las operaciones matemáticas que aprendimos hoy.

Sigue estos pasos cuidadosamente en una celda de código:

1. **El año actual:** Crea una variable llamada `anio_actual` y asígnale el valor numérico de este año (sin comillas porque es un número entero).
2. **Tu nacimiento:** Crea una segunda variable llamada `anio_nacimiento` y asígnale el año exacto en que naciste.
3. **El cálculo:** Crea una tercera variable llamada `mi_edad`. Haz que sea igual a la resta del año actual menos tu año de nacimiento (usando el símbolo `-`).
4. **El gran final:** Utiliza la instrucción `print()` con **f-string** para mostrar en pantalla tu resultado.

"""

# Escribe tu programa aquí abajo paso a paso:
# 1. Año actual
anio_actual = 2026

# 2. Año de nacimiento (cambia el número por el tuyo)
anio_nacimiento = 1998

# 3. Cálculo de edad
mi_edad = anio_actual - anio_nacimiento

# 4. Mostrar en pantalla usando f-string
print(f"Mi edad calculada por Python es: {mi_edad} años.")

# ============================================================
# 🎁 BONUS: Calculadora INTERACTIVA con input()
# ============================================================
# input() es una función especial que PAUSA el programa y espera
# a que el usuario escriba algo desde el teclado.
# Cuando ejecutes esta celda, aparecerá un campo de texto — ¡escribe tu año!

anio_actual = 2026

# input() siempre devuelve TEXTO (str), así que debemos convertirlo a int
texto_ingresado = input("¿En qué año naciste? Escribe el año y presiona Enter: ")
anio_nacimiento = int(texto_ingresado)   # <-- casting str → int

mi_edad = anio_actual - anio_nacimiento

print(f"\n🎂 ¡Hola! Tienes aproximadamente {mi_edad} años.")
print("   (¿Notas que el programa calculó TU año sin que lo escribieras en el código?)")

"""---

### 🧠 Pregunta Teórica para Reflexionar

Justo debajo de este texto, agrega una nueva celda de **Texto** y responde brevemente a esta pregunta basándote en la regla de oro que aprendimos hoy:

> *Si por accidente declaramos nuestra variable de edad usando comillas (ejemplo: `edad = "25"`), ¿por qué Python nos daría un error si intentamos sumarle 5 años más en el futuro?*

*(Pista: piensa en qué tipo de dato devuelve `input()` y por qué tuvimos que usar `int()` en el ejercicio BONUS.)*

---

"""