# -*- coding: utf-8 -*-
"""Sesión 3: Entorno de Trabajo y Herramientas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/121Q3HuWOBKU8pe-QUzxc7gjGXwRD-9MS

# Sesión 3: Entorno de Trabajo y Herramientas

### El Taller del Científico de Datos
Para entender cómo trabajaremos, imagina que la ciencia de datos es como la alta cocina. Para preparar un platillo extraordinario no basta con tener buenos ingredientes (tus datos); necesitas un espacio adecuado y los utensilios correctos. Así se conforma nuestro taller:

* **El Entorno de Trabajo (Google Colab):** Es nuestra cocina profesional. Es el lugar físico (alojado en la nube) donde entramos a trabajar. Tiene las mesas listas, la energía conectada y todo preparado para que nosotros solo nos preocupemos por crear, sin instalar nada en nuestra computadora.
* **El Lenguaje Base (Python):** Son tus habilidades y técnicas culinarias básicas. Es el idioma y la lógica fundamental que usamos para darle instrucciones precisas a la cocina.
* **Las Librerías (Herramientas Especializadas):** Son tus electrodomésticos avanzados. Si necesitas picar mil cebollas, no lo haces a mano usando solo tu técnica básica; enciendes un procesador de alimentos. En la ciencia de datos, estas herramientas son colecciones de código que expertos de todo el mundo ya inventaron para ahorrarnos trabajo:
  * **NumPy:** Es nuestra báscula y calculadora industrial. Sirve para realizar operaciones matemáticas complejas con listas gigantes de números a una velocidad increíble.
  * **Pandas:** Es nuestro organizador maestro. Nos permite acomodar, limpiar y manipular datos como si tuviéramos una hoja de cálculo hipervitaminada.
  * **Matplotlib:** Es nuestro kit de emplatado. Transforma nuestros cálculos fríos en gráficos y visualizaciones atractivas para que cualquier persona (desde un paciente hasta la dirección de una empresa) pueda entender nuestros descubrimientos de un vistazo.

---

### Enchufando los electrodomésticos: El comando `import`

En Python, por cuestiones de orden y para no saturar la memoria, nuestros electrodomésticos avanzados (las librerías) vienen guardados en sus cajas por defecto. Antes de poder usar Pandas o NumPy, tenemos que "sacarlos de la caja y enchufarlos" a nuestra área de trabajo.

Para hacer esto, utilizamos una orden directa llamada `import`.

Además, como en la ciencia de datos escribimos código todo el día, nos encantan los atajos. Por eso, al importar una herramienta, solemos ponerle un "apodo" corto usando la palabra `as` (que significa "como" en inglés).

Mira este ejemplo:
```python
import pandas as pd
```
"""

import pandas as pd

"""Con esta simple línea le estamos diciendo a la computadora: *"Por favor, trae la librería Pandas a mi área de trabajo, y de ahora en adelante, cada vez que la necesite, la llamaré simplemente `pd` para no escribir tanto"*.

---

### ¿Por qué Python?

Quizá te preguntes: con tantos lenguajes de programación que existen, ¿por qué la ciencia de datos eligió a Python como su estándar mundial?

La razón principal es que Python fue diseñado para ser amigable. Su forma de escribirse es muy limpia y se parece muchísimo a leer en inglés. Esto es un alivio gigantesco para quienes venimos de áreas que no son la informática, ya que en lugar de pelear por entender símbolos complicados en la pantalla, puedes enfocar toda tu energía mental en resolver el problema real de tu disciplina.

Además, Python es gratuito y posee una comunidad solidaria enorme. Si alguna vez te atascas en un problema, es casi seguro que alguien más ya lo resolvió y dejó la respuesta disponible para ti en algún foro de internet.

---

### Ejercicio 1: Equipando tu Cocina

¡Vamos a preparar nuestro espacio! Es tu turno de encender los electrodomésticos que usaremos en esta clase.

**Tu Tarea:**

1. Haz clic en el botón **"+ Código"** que aparece al pasar el ratón debajo de este texto para crear una celda nueva.
2. Escribe un comentario (usando `#`) que diga: `# Importando mis herramientas de trabajo`
3. En la siguiente línea, escribe el código para importar la librería Pandas y ponle el apodo `pd`.
4. En la línea de abajo, importa la librería NumPy y ponle el apodo `np`.
5. ¡Presiona el botón de "Play"!

*(Ejemplo de cómo debe verse tu código antes de ejecutarlo):*

"""

# Importando mis herramientas de trabajo
import pandas as pd
import numpy as np

"""*(💡 **Nota:** Al presionar Play, notarás que no aparece ningún mensaje especial en la pantalla, solo una pequeña palomita verde al lado del botón. ¡Eso es excelente! Significa que las herramientas se han enchufado correctamente en la memoria de Colab y están listas para usarse).*

---

### 🗺️ El Mapa del Ecosistema: ¿Cuándo usar cada herramienta?

Python tiene decenas de librerías. Para no perderte, aquí tienes un mapa de las que usaremos en todo el diplomado y para qué sirve cada una:

| Librería | Apodo | Para qué sirve | Analogía |
|---|---|---|---|
| **NumPy** | `np` | Operaciones matemáticas con grandes arreglos de números | Calculadora científica industrial |
| **Pandas** | `pd` | Leer, limpiar y manipular tablas de datos | Excel con superpoderes |
| **Matplotlib** | `plt` | Crear gráficas básicas (líneas, barras, dispersión) | Papel cuadriculado + regla |
| **Seaborn** | `sns` | Crear gráficas estadísticas elegantes con menos código | Diseñador de infografías |
| **Scikit-learn** | `sklearn` | Construir modelos de Machine Learning | El robot que aprende a predecir |

> 💡 **¿Python vs Excel vs R?** Excel es excelente para hasta ~100,000 filas. Python no tiene límite de filas, puede automatizarse, y puede hacer Machine Learning. R es muy potente en estadística, pero Python tiene más comunidad y más aplicaciones fuera de la estadística pura. Para ciencia de datos aplicada, **Python es la mejor inversión de tiempo**.

"""

# ============================================================
# IMPORTANDO EL TOOLKIT COMPLETO DEL CIENTÍFICO DE DATOS
# ============================================================

import pandas as pd          # Tablas de datos
import numpy as np            # Matemáticas avanzadas
import matplotlib.pyplot as plt  # Gráficas
import seaborn as sns         # Gráficas estadísticas elegantes

# Verificamos que todo se importó correctamente mostrando las versiones
print("✅ Herramientas cargadas correctamente:")
print(f"   NumPy     versión: {np.__version__}")
print(f"   Pandas    versión: {pd.__version__}")
print(f"   Matplotlib versión: {plt.matplotlib.__version__}")
print(f"   Seaborn   versión: {sns.__version__}")
print("\n🚀 ¡Tu laboratorio de datos está listo!")

"""---

# Parte 2: De la Teoría a la Práctica: Trabajando en la Nube

Antes de empezar a utilizar nuestras herramientas (`pandas` y `numpy`), es vital entender exactamente dónde vamos a trabajar. Durante todo este curso, nuestro laboratorio principal será **Google Colab** (o Colaboratory), una plataforma que vive completamente en la "Nube".

### ¿Qué es la "Nube" y qué es Google Colab?

Imagina cómo veíamos películas hace 15 años: tenías que ir a la tienda, comprar un DVD físico, instalar un reproductor en tu casa y asegurarte de que los cables funcionaran bien. Hoy, simplemente abres Netflix o YouTube en tu navegador web y ves el video al instante; todo el trabajo pesado de almacenamiento y procesamiento ocurre en servidores gigantes en otro lado del mundo.

El *Cloud Computing* (o computación en la nube) funciona exactamente igual. En lugar de tener que instalar programas de programación complejos y pesados en tu laptop, Google Colab nos permite conectarnos a través del navegador a una supercomputadora de Google.

### ¿Por qué usamos Google Colab?

Elegimos esta herramienta para nuestro curso en lugar de instalar Python en sus equipos por tres grandes razones:

1. **Cero instalaciones y configuraciones:** No importa si tienes una computadora Windows antigua o una Mac nuevecita; si tienes internet y un navegador web, ya estás listo para programar. ¡Cero dolores de cabeza informáticos!
2. **Poder de supercomputadora gratis:** La ciencia de datos a veces requiere cálculos matemáticos inmensos. Con Colab, los procesadores de Google hacen todo el trabajo pesado por ti de forma gratuita, evitando que tu computadora personal se vuelva lenta o se congele.
3. **Colaboración en tiempo real:** Funciona exactamente igual que un documento de Google Docs. Puedes compartir tu trabajo con un enlace, colaborar con tus compañeros, y todo se guarda automáticamente en tu Google Drive.

---

### ¿Por qué le llamamos "Cuaderno" (Notebook)?

A los archivos que creamos dentro de Google Colab se les conoce como **Cuadernos** (o *Notebooks* en inglés).

Piensa en una libreta escolar tradicional donde tomas tus notas de clase. Ahora, imagina que ese cuaderno fuera mágico: te permite escribir texto normal (apuntes, títulos, teorías) y, justo debajo, insertar "bloques" especiales donde puedes escribirle órdenes directas a la computadora y ver el resultado inmediatamente.

Esta increíble capacidad de mezclar texto explicativo para humanos y código ejecutable para la máquina en un solo documento interactivo es lo que convierte a los cuadernos en la herramienta favorita de los científicos de datos en todo el mundo para documentar y compartir sus descubrimientos.

#### La Anatomía de tu Cuaderno: Las Celdas

Tu cuaderno se construye apilando bloques horizontales que llamamos **Celdas**. Si pasas el ratón por el centro de la pantalla (o miras arriba a la izquierda), verás dos botones principales:

* **`+ Texto`:** Crea un bloque en blanco como este que estás leyendo ahora. Sirve para dejar notas, poner títulos y documentar tu proceso analítico.
* **`+ Código`:** Crea un bloque gris. Es aquí donde utilizamos Python y nuestras librerías para procesar información.

#### El botón mágico: "Conectar"

Mira la esquina superior derecha de tu pantalla. ¿Ves un botón que dice **"Conectar"** o un pequeño medidor con una palomita verde (que dice RAM / Disco)?

Cuando abres tu cuaderno, Google busca una computadora disponible en sus servidores y te la "asigna" temporalmente. Si ves la palomita verde, significa que tu supercomputadora personal está encendida, conectada y lista para recibir tus órdenes.

---

### Ejercicio 2: El Arquitecto del Cuaderno

Vamos a comprobar que dominas la interfaz de tu laboratorio.

**Tu Tarea:**

1. Ve a la parte superior de esta pantalla (o pasa el ratón debajo de esta línea) y haz clic en el botón **`+ Texto`**.
2. En esa nueva celda blanca, escribe un título usando el formato Markdown: `# Mi Primer Apunte en Colab`. Escribe debajo una breve nota sobre qué te parece la herramienta hasta ahora.
3. Ahora haz clic en el botón **`+ Código`** para crear una celda gris debajo de tu texto.
4. Escribe una operación matemática sencilla (por ejemplo, `print(100 / 4)`) y dale al botón de "Play" para asegurarte de que tu supercomputadora en la nube está conectada y respondiendo correctamente.

---

# Parte 3: Un Tour Guiado por tu Nuevo Laboratorio

Ahora que ya sabemos cómo crear celdas y comprobar que nuestra supercomputadora está conectada, vamos a terminar nuestro recorrido visual por la interfaz. No te preocupes por todos los menús complejos de arriba; por ahora, solo necesitas dominar estos dos elementos clave que serán tus herramientas de todos los días:

### 1. El Ícono de la Carpeta (Tu Alacena de Datos)

Si miras el menú lateral izquierdo de tu pantalla, verás varios íconos pequeños. Hay uno que tiene la forma de una **carpeta de archivos**.

Si le das clic, se abrirá un panel. Piensa en este espacio como la "alacena" o el refrigerador de nuestra cocina. Es exactamente aquí donde, más adelante, subiremos nuestros archivos de Excel o bases de datos (nuestros ingredientes crudos) para que Python pueda analizarlos. ¡Por ahora está vacía, pero pronto la llenaremos!

### 2. El Orden de Ejecución (Los números mágicos `[ ]`)

Hay un error muy común cuando empezamos a programar: pensar que la computadora lee nuestro cuaderno de arriba hacia abajo, como si fuera un libro de texto. **¡Falso!**

Colab lee las instrucciones *en el orden exacto en el que tú presionas el botón de Play*.
Si observas bien, cuando ejecutas una celda de código, aparecen unos pequeños corchetes con un número adentro a la izquierda (por ejemplo, `[1]`, `[2]`, `[3]`). Ese número te indica qué bloque ejecutó la máquina primero y cuál después. Si alguna vez tu código marca un error extraño, revisa esos números; ¡quizá olvidaste darle Play a una celda importante de más arriba!

---

### La Memoria de Colab en Acción

Vamos a ver cómo la memoria RAM de Colab trabaja para nosotros siguiendo ese orden de ejecución.

Imagina que estamos planificando el presupuesto de un proyecto de investigación (ya sea sociológica, biológica o de ingeniería). Sabemos cuánto podemos gastar al mes y queremos que Python calcule el total anual.

Ve a la celda de código de abajo y presiona el botón de **Play**:

"""

# 1. Guardamos nuestros datos en la memoria
presupuesto_mensual = 500
meses = 12

# 2. Le pedimos a Python que haga la multiplicación
presupuesto_total = presupuesto_mensual * meses

# 3. Mostramos el resultado
print("El presupuesto total calculado es de:", presupuesto_total, "dólares.")

"""#### ¿Qué acaba de pasar en el "cerebro" de Colab?

Al presionar Play (y ver que apareció el número `[1]`), no solo se mostró el resultado en la pantalla. Lo más importante es que la memoria RAM de tu computadora prestada acaba de "aprenderse" tus variables.

Ahora mismo, Google recuerda perfectamente que `presupuesto_total` equivale a `6000`. Si creamos otra celda de código más abajo, Colab ya sabrá exactamente de qué número le estás hablando sin que tengas que volver a escribir el 6000. ¡Esta capacidad de recordar es lo que hace que los cuadernos sean tan poderosos para analizar datos paso a paso!

---

### Ejercicio 3: Poniendo a Prueba la Memoria

¡Es tu turno de comprobar que la computadora realmente memorizó tu información!

Imagina que este proyecto de investigación lo vas a realizar junto con otros 3 colegas (son 4 personas en total). Queremos saber cuánto dinero le toca a cada investigador.

**Tu Tarea:**

1. Haz clic en **"+ Código"** debajo de este texto para crear una celda nueva.
2. Crea una variable llamada `presupuesto_por_persona`.
3. Haz que esa variable sea igual a dividir el `presupuesto_total` entre `4`. *(💡 **Tip matemático:** En Python, el símbolo de división es la barra diagonal `/`).*
4. En la siguiente línea, usa `print()` para mostrar el resultado en pantalla de forma amigable (combinando texto y tu nueva variable, como aprendiste en la sesión anterior).
5. Dale Play a tu celda. ¡Si no te marca error y te da el resultado de 1500, significa que Colab recordó la variable de la celda de arriba a la perfección!

*(Ejemplo de cómo debe verse tu código antes de ejecutarlo)*:

"""

# Dividimos el presupuesto memorizado arriba entre los 4 miembros del equipo
presupuesto_por_persona = presupuesto_total / 4

print("A cada investigador le tocan:", presupuesto_por_persona, "dólares.")

"""---

# Parte 3b: Conociendo a tus Electrodomésticos en Acción

### 🔢 NumPy — La Calculadora Industrial

Ya importamos NumPy con el apodo `np`. Ahora vamos a verlo trabajar. La diferencia entre una lista normal de Python y un **array de NumPy** es como la diferencia entre sumar números a mano vs. usar una calculadora científica.

**¿Por qué no usar listas normales para matemáticas?**

```python
# Con lista normal de Python — esto NO hace lo que esperas:
precios = [10, 20, 30]
print(precios * 2)  # → [10, 20, 30, 10, 20, 30]  ← ¡duplica la lista!

# Con array NumPy — esto SÍ multiplica cada precio por 2:
precios_np = np.array([10, 20, 30])
print(precios_np * 2)  # → [20, 40, 60]  ← ¡lo que queríamos!
```

Ejecuta la celda de abajo para ver NumPy en acción con datos de un estudio de investigación:

"""

# ============================================================
# NUMPY EN ACCIÓN: Procesando datos de temperatura
# ============================================================

import numpy as np

# Imagina que tienes las temperaturas corporales de 8 pacientes
temperaturas = np.array([36.5, 37.0, 38.2, 36.8, 37.5, 39.1, 36.6, 37.8])

print("🌡️ Temperaturas de los pacientes:")
print(temperaturas)

# NumPy calcula estadísticas en una sola línea
print(f"\n📊 Estadísticas automáticas con NumPy:")
print(f"   Temperatura promedio : {np.mean(temperaturas):.2f} °C")
print(f"   Temperatura mínima   : {np.min(temperaturas):.1f} °C")
print(f"   Temperatura máxima   : {np.max(temperaturas):.1f} °C")
print(f"   Desviación estándar  : {np.std(temperaturas):.2f} °C")

# Operación sobre todos los elementos a la vez (imposible con listas normales)
fiebre = temperaturas > 37.5
print(f"\n🚨 ¿Qué pacientes tienen fiebre (>37.5°C)?")
print(f"   {fiebre}")
print(f"   Total con fiebre: {np.sum(fiebre)} de {len(temperaturas)} pacientes")

"""---

### 🗂️ Pandas — Tu Primera Tabla de Datos (DataFrame)

Si NumPy es la calculadora, **Pandas** es el Excel con superpoderes. La estructura más importante de Pandas se llama **DataFrame** — básicamente una tabla con filas y columnas, igual que una hoja de cálculo, pero completamente controlable desde Python.

Vamos a crear nuestro **primer DataFrame desde cero**, simulando los datos de los mismos 8 pacientes:

"""

# ============================================================
# PANDAS EN ACCIÓN: Creando y explorando una tabla de datos
# ============================================================

import pandas as pd
import numpy as np

# Creamos un DataFrame (tabla) con datos de pacientes
datos_pacientes = {
    'paciente_id':  [1, 2, 3, 4, 5, 6, 7, 8],
    'temperatura':  [36.5, 37.0, 38.2, 36.8, 37.5, 39.1, 36.6, 37.8],
    'edad':         [25, 43, 67, 31, 55, 28, 72, 40],
    'sexo':         ['M', 'F', 'M', 'F', 'F', 'M', 'F', 'M'],
    'asistio_cita': [True, True, False, True, False, True, True, True]
}

df = pd.DataFrame(datos_pacientes)

print("📋 Nuestra tabla de pacientes:")
print(df)

print(f"\n📐 Dimensiones: {df.shape[0]} filas × {df.shape[1]} columnas")
print(f"\n🔍 Tipos de datos por columna:")
print(df.dtypes)

# Filtrar solo los pacientes con fiebre (temperatura > 37.5)
pacientes_fiebre = df[df['temperatura'] > 37.5]

print("🚨 Pacientes con fiebre (temperatura > 37.5°C):")
print(pacientes_fiebre[['paciente_id', 'temperatura', 'edad', 'sexo']])

# Estadísticas descriptivas automáticas
print("\n📊 Resumen estadístico de las columnas numéricas:")
print(df[['temperatura', 'edad']].describe().round(2))

# Porcentaje de pacientes que asistieron
pct_asistencia = df['asistio_cita'].mean() * 100
print(f"\n✅ Tasa de asistencia a citas: {pct_asistencia:.1f}%")

"""---

### 📊 Matplotlib + Seaborn — Tu Primera Visualización

Los números en una tabla a veces son difíciles de interpretar a simple vista. Los gráficos convierten esos números en conocimiento visual instantáneo. Vamos a crear **nuestra primera gráfica** con los datos de los pacientes:

"""

# ============================================================
# MATPLOTLIB + SEABORN: Primera visualización de datos
# ============================================================

import matplotlib.pyplot as plt
import seaborn as sns

# Configuramos el estilo visual
sns.set_theme(style="whitegrid", palette="husl")
fig, axes = plt.subplots(1, 2, figsize=(12, 4))

# --- Gráfica 1: Temperaturas por paciente (gráfica de barras) ---
colores = ['#e74c3c' if t > 37.5 else '#3498db' for t in df['temperatura']]
axes[0].bar(df['paciente_id'], df['temperatura'], color=colores, edgecolor='white')
axes[0].axhline(y=37.5, color='red', linestyle='--', alpha=0.7, label='Límite fiebre')
axes[0].set_title('Temperatura por Paciente', fontsize=13, fontweight='bold')
axes[0].set_xlabel('ID Paciente')
axes[0].set_ylabel('Temperatura (°C)')
axes[0].legend()

# --- Gráfica 2: Distribución de temperaturas (histograma) ---
axes[1].hist(df['temperatura'], bins=5, color='#9b59b6', edgecolor='white', alpha=0.8)
axes[1].axvline(x=df['temperatura'].mean(), color='orange',
                linestyle='--', linewidth=2, label=f'Promedio: {df["temperatura"].mean():.2f}°C')
axes[1].set_title('Distribución de Temperaturas', fontsize=13, fontweight='bold')
axes[1].set_xlabel('Temperatura (°C)')
axes[1].set_ylabel('Número de pacientes')
axes[1].legend()

plt.suptitle('Análisis de Temperatura — Clínica Comunitaria', fontsize=14, y=1.02)
plt.tight_layout()
plt.show()

print("\n✅ ¡Acabas de crear tu primera visualización de datos real!")
print("   Azul = temperatura normal  |  Rojo = fiebre")

"""---

# Parte 4: Reto Práctico: El Poder de la Nube

Para cerrar nuestra sesión de hoy, vamos a analizar un caso hipotético y a practicar cómo agregar nuevas celdas en tu cuaderno de trabajo de forma completamente independiente.

> **El Escenario:** Imagina que eres un investigador principal en un hospital muy importante. Te han asignado la tarea urgente de analizar una base de datos que contiene los historiales clínicos completos de **1 millón de pacientes** para encontrar patrones de una enfermedad. El gran problema es que tu computadora personal tiene 10 años de antigüedad y se traba por completo con tan solo intentar abrir un archivo de Excel un poco pesado.

Responde a las siguientes preguntas basándote en lo que aprendimos hoy sobre la nube:

1. ¿Por qué intentar abrir y analizar ese archivo de 1 millón de pacientes localmente en tu computadora (usando Excel) sería un problema casi imposible?
2. ¿Cómo solucionaría exactamente este problema técnico el uso de Google Colab? *(Pista: Recuerda de quién es el "cerebro" y la "memoria" que estamos usando al conectarnos).*

---

### Tu turno en la interfaz:

Sigue estos pasos cuidadosamente para completar tu reto de hoy:

1. Pasa el ratón justo debajo de este bloque de texto y haz clic en el botón **`+ Texto`** que aparecerá (o búscalo en el menú superior). Esto creará una nueva celda en blanco.
2. Escribe en esa nueva celda tus respuestas a las dos preguntas del escenario. *(💡 **Tip extra:** Intenta usar el formato Markdown poniendo doble asterisco alrededor de las palabras clave para hacerlas **negritas**).*
3. Luego, vuelve a pasar el ratón por debajo de tus respuestas y haz clic en el botón **`+ Código`** para agregar una nueva celda gris.
4. En esa celda de código, escribe exactamente las siguientes instrucciones:

"""

# Terminando mi tercera sesión con éxito
# Ahora conozco mis 4 herramientas principales:
herramientas = ["NumPy", "Pandas", "Matplotlib", "Seaborn"]

print("🎓 ¡Sesión 3 completada!")
print(f"Domino {len(herramientas)} herramientas del científico de datos:")
for i, h in enumerate(herramientas, 1):
    print(f"  {i}. {h}")
print("\n🚀 ¡Estoy listo para dominar Colab y seguir avanzando!")