# -*- coding: utf-8 -*-
"""Sesión 16: Visualización de Datos con Pandas y Seaborn (Práctica)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cM455rzeNwYbbHLgKelK3lnIyR6ZYwJj

# Sesión 16: Visualización de Datos con Pandas y Seaborn (Práctica)


### Preparando el Lienzo: Nuestro Estudio de Arte

Antes de empezar a trazar líneas, necesitamos traer nuestros materiales al área de trabajo. Ejecuta la celda de abajo para importar a nuestros tres grandes aliados y configurar el estilo visual "elegante" por defecto.
"""

# Importamos nuestros materiales de arte digital
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Configuramos el estilo 'whitegrid' para que todos los gráficos se vean profesionales
sns.set_theme(style="whitegrid")

print("¡Estudio de arte preparado y listo para pintar!")

"""---

### 📋 Los 3 Ingredientes de Todo Gráfico en Seaborn

Seaborn simplifica la creación de gráficos al pedirte siempre los mismos 3 datos:

| Ingrediente | Parámetro | ¿Qué le dices? | Ejemplo |
|---|---|---|---|
| 🗂️ **Los datos** | `data=` | ¿De qué DataFrame saco la información? | `data=df` |
| ➡️ **Eje horizontal** | `x=` | ¿Qué columna va en el eje X? | `x="Mes"` |
| ⬆️ **Eje vertical** | `y=` | ¿Qué quiero medir en el eje Y? | `y="Ingresos"` |

La receta básica siempre es:
```python
sns.barplot(data=df, x="columna_categoría", y="columna_número")
plt.title("Mi Título")
plt.show()
```

> 💡 **Tip profesional:** Siempre termina con `plt.title()`, `plt.xlabel()`,
> `plt.ylabel()` y `plt.show()`. Un gráfico sin etiquetas es como un reporte sin nombre.

---

### La Anatomía de un Gráfico en Código

Escribir código para dibujar es más sencillo de lo que parece. Para crear la gran mayoría de nuestras obras, la computadora solo nos pedirá **tres piezas clave**:

1. **`data`:** ¿De qué tabla de datos (DataFrame) vamos a sacar la información?
2. **`x`:** ¿Qué variable queremos poner en la línea horizontal?
3. **`y`:** ¿Qué queremos medir en la línea vertical?

---

## Parte 2: Nuestros Primeros Trazos

Primero, crearemos una base de datos de ejemplo sobre el desempeño mensual de una clínica para tener datos reales que analizar:
"""

# Nuestro "modelo" a pintar: un DataFrame de una clínica
datos_clinica = {
    "Mes":                ["Enero", "Febrero", "Marzo", "Abril", "Mayo"],
    "Ingresos":           [15000, 18000, 12000, 25000, 21000],
    "Pacientes_Atendidos": [100, 120, 95, 160, 145]
}
df = pd.DataFrame(datos_clinica)

print("¡Base de datos preparada!")
df.head()

"""### 1. El Gráfico de Barras: Comparando Categorías

Ideal para identificar rápidamente qué mes fue el más exitoso financieramente.

"""

# Gráfico de barras
# Usamos 'hue' para dar color a cada barra y evitar advertencias técnicas
sns.barplot(data=df, x="Mes", y="Ingresos", hue="Mes", palette="magma", legend=False)

# Buenas prácticas: Título y etiquetas claras
plt.title("Ingresos Mensuales de la Clínica")
plt.xlabel("Mes del Año")
plt.ylabel("Ingresos en USD ($)")

plt.show()

"""---

### Ejercicio 2.1: Tu Primer Gráfico de Barras

Acabas de ver cómo visualizar los **Ingresos** por mes. Ahora te toca practicar
con la otra variable del mismo DataFrame: los **Pacientes Atendidos**.

**Tu tarea:**
1. En la celda de abajo, crea un `sns.barplot()` usando el mismo `df` de la clínica.
2. Cambia `y="Ingresos"` por `y="Pacientes_Atendidos"`.
3. Cambia la paleta a `palette="Blues_d"`.
4. Actualiza el título y las etiquetas de los ejes para que sean descriptivos.
5. 💎 **Bonus:** Agrega `plt.ylim(0, 200)` antes de `plt.show()` para ajustar el
   rango del eje Y y observa cómo cambia la percepción del gráfico.

---

"""

# Escribe aquí tu código para el Ejercicio 2.1:

"""### 2. El Gráfico de Líneas: Evolución en el Tiempo

Perfecto para observar la **tendencia** de afluencia de pacientes: ¿estamos creciendo o perdiendo pacientes?

"""

# Gráfico de líneas con marcador de puntos ('o')
sns.lineplot(data=df, x="Mes", y="Pacientes_Atendidos", marker="o", color="teal")

plt.title("Evolución de Pacientes Atendidos")
plt.xlabel("Mes")
plt.ylabel("Cantidad de Pacientes")
plt.show()

"""---

### 🎨 Paletas de Color de Seaborn — Guía Rápida

El parámetro `palette=` cambia completamente el aspecto visual de tus gráficas.
Aquí están las paletas más usadas en presentaciones profesionales:

| Paleta | Tipo | Ideal para... |
|---|---|---|
| `"viridis"` | Secuencial (morado → amarillo) | Datos con gradiente o rango numérico |
| `"magma"` | Secuencial (negro → amarillo) | Presentaciones oscuras o de impacto |
| `"Blues_d"` | Secuencial (azul claro → oscuro) | Reportes corporativos, salud |
| `"Set2"` | Cualitativo (colores distintos) | Categorías sin orden (ciudades, grupos) |
| `"pastel"` | Cualitativo (tonos suaves) | Presentaciones ligeras o educativas |
| `"coolwarm"` | Divergente (azul → rojo) | Datos con extremos opuestos (pérdida/ganancia) |

> 🔑 **Regla de oro:** Usa paletas **secuenciales** cuando los datos tienen orden
> (bajo → alto). Usa paletas **cualitativas** cuando las categorías son independientes.
> Usa **divergentes** cuando hay un punto medio importante (cero, presupuesto equilibrado).

---

"""

# ──────────────────────────────────────────────────────────
# Demo visual: 3 paletas en el mismo gráfico lado a lado
# ──────────────────────────────────────────────────────────

fig, axes = plt.subplots(1, 3, figsize=(14, 4))

paletas = ["magma", "Blues_d", "Set2"]
titulos = ["palette='magma'", "palette='Blues_d'", "palette='Set2'"]

for ax, paleta, titulo in zip(axes, paletas, titulos):
    sns.barplot(data=df, x="Mes", y="Ingresos",
                hue="Mes", palette=paleta, legend=False, ax=ax)
    ax.set_title(titulo)
    ax.set_xlabel("")
    ax.set_ylabel("Ingresos ($)")
    ax.tick_params(axis='x', rotation=30)

plt.suptitle("Comparación de Paletas de Color", fontsize=14, y=1.02)
plt.tight_layout()
plt.show()

"""---

### Ejercicio 2.2: Gráfico de Líneas Personalizado

Ahora practícalo tú. El director quiere una gráfica de líneas de los **Ingresos**
(no de pacientes) para ver la tendencia financiera, y quiere que se vea profesional.

**Tu tarea:**
1. En la celda de abajo, crea un `sns.lineplot()` con `x="Mes"` y `y="Ingresos"`.
2. Usa `color="darkgreen"` y `marker="s"` (cuadrados en los puntos).
3. Agrega título y etiquetas de ejes.
4. 💎 **Bonus:** Agrega esta línea antes de `plt.show()`:
   `plt.axhline(y=df["Ingresos"].mean(), color="red", linestyle="--")`
   Esto dibuja una línea horizontal en el promedio. ¿En qué meses estuvieron por encima?

---

"""

# Escribe aquí tu código para el Ejercicio 2.2:

"""---

## Parte 3: Cazando Patrones y Errores

### El Gráfico de Dispersión (Scatter plot)

Es el radar favorito de los científicos de datos. Sirve para ver la relación entre
dos variables y, sobre todo, para detectar **Valores Atípicos (Outliers)** o errores
de captura.

Ejecuta este radar sobre los datos de estudio de un grupo de alumnos:

"""

# Base de datos con un posible error de captura (Outlier)
datos_estudio = {
    "Horas_Estudio": [2, 3, 4, 4.5, 5, 6, 7, 8, 9, 1],   # El '1' parece sospechoso
    "Calificacion":  [40, 50, 60, 65, 70, 80, 85, 90, 95, 100]  # ¡100 estudiando 1 hora!
}
df_alumnos = pd.DataFrame(datos_estudio)

# Encendemos el radar visual (s=100 aumenta el tamaño de los puntos)
sns.scatterplot(data=df_alumnos, x="Horas_Estudio", y="Calificacion", s=100, color="purple")

plt.title("Relación: Horas de Estudio vs Calificación")
plt.xlabel("Horas de Estudio")
plt.ylabel("Calificación Final")
plt.show()

"""> **Análisis Detective:** Observa el punto en la esquina superior izquierda.
> Representa a alguien que estudió solo 1 hora y sacó 100. El gráfico nos permite
> detectar este error de inmediato para investigarlo.

---

### El Superpoder de `hue=` — Colorear por Categoría

El parámetro `hue=` le dice a Seaborn que coloree cada punto según el valor
de una columna de texto. Es como iluminar grupos dentro de tu gráfica sin
escribir ningún código extra.

En el dataset anterior solo veíamos puntos sin contexto. Ahora agrega la columna
`"Turno"` (Matutino/Vespertino) y observa cómo el `hue=` revela un patrón oculto:
¿Los alumnos de un turno estudian más horas que los del otro?

---

"""

# Dataset extendido: mismos datos + columna de Turno
datos_alumnos_grupo = {
    "Horas_Estudio": [2, 3, 4, 4.5, 5, 6, 7, 8, 9, 1],
    "Calificacion":  [40, 50, 60, 65, 70, 80, 85, 90, 95, 100],
    "Turno":         ["Matutino", "Matutino", "Vespertino", "Matutino",
                      "Vespertino", "Vespertino", "Matutino", "Vespertino",
                      "Vespertino", "Matutino"]
}
df_alumnos_grupo = pd.DataFrame(datos_alumnos_grupo)

# Con hue= cada Turno tiene su propio color automáticamente
sns.scatterplot(data=df_alumnos_grupo,
                x="Horas_Estudio",
                y="Calificacion",
                hue="Turno",
                s=120,
                palette="Set2")

plt.title("Horas de Estudio vs Calificación por Turno")
plt.xlabel("Horas de Estudio")
plt.ylabel("Calificación Final")
plt.show()

"""---

### El Histograma: Distribución de una Variable

Antes de presentar resultados, un analista siempre revisa **cómo están distribuidos**
los datos. `sns.histplot()` con `kde=True` agrega una curva suavizada encima de
las barras para ver la "forma" de la distribución de un solo vistazo.

---

"""

# ──────────────────────────────────────────────────────────
# Histograma de calificaciones con curva de densidad (KDE)
# ──────────────────────────────────────────────────────────

calificaciones = [40, 50, 55, 60, 62, 65, 68, 70, 72, 75,
                  78, 80, 82, 85, 85, 88, 90, 92, 95, 100]

sns.histplot(calificaciones, bins=6, kde=True, color="steelblue")

plt.title("Distribución de Calificaciones del Grupo")
plt.xlabel("Calificación")
plt.ylabel("Número de Alumnos")
plt.show()

print(f"Promedio del grupo: {sum(calificaciones)/len(calificaciones):.1f}")
print("Calificación más frecuente (moda visual): observa la barra más alta")

"""---

## Parte 4: Reto Práctico (El Presentador de Datos)

Imagina que el director de la institución te pide un resumen urgente sobre la
carga de trabajo mensual para decidir dónde asignar más personal.

**Instrucciones:**
1. Completa el código para generar un gráfico de barras.
2. Personaliza los nombres de los ejes para que sean profesionales.
3. Escribe tu conclusión ejecutiva basada en lo que ves.

"""

# Base de datos de carga de trabajo por departamento
datos_hospital = {
    "Departamento":        ["Urgencias", "Pediatría", "Cardiología", "Neurología", "Oncología"],
    "Pacientes_Atendidos": [250, 180, 150, 120, 90]
}
df_reporte = pd.DataFrame(datos_hospital)

# --- Escribe tu código de visualización debajo de esta línea ---

"""---

### 🧠 El Diagnóstico Ejecutivo

Haz doble clic aquí y responde:

> *Basándote en el gráfico que acabas de crear, ¿en qué departamento es más urgente contratar personal nuevo y por qué?*

**(Respuesta):**

---

---

### 🔥 Reto Extra: Dashboard Ejecutivo con `plt.subplots()`

El director quiere un **reporte visual completo** de la clínica en una sola imagen
para presentar en la junta. Necesita ver 4 métricas a la vez.

**Tu pipeline:**
1. Ejecuta la celda para crear `df_clinica_completa`.
2. Crea la figura: `fig, axes = plt.subplots(2, 2, figsize=(12, 8))`
3. **Panel 1** (arriba izq) — Barras de Ingresos:
   `sns.barplot(data=df_clinica_completa, x="Mes", y="Ingresos", hue="Mes", palette="magma", legend=False, ax=axes[0,0])`
4. **Panel 2** (arriba der) — Línea de Pacientes:
   `sns.lineplot(data=df_clinica_completa, x="Mes", y="Pacientes", marker="o", color="teal", ax=axes[0,1])`
5. **Panel 3** (abajo izq) — Histograma de Satisfacción:
   `axes[1,0].hist(df_clinica_completa["Satisfaccion"], bins=5, color="steelblue", edgecolor="white")`
6. **Panel 4** (abajo der) — Scatter Ingresos vs Pacientes:
   `sns.scatterplot(data=df_clinica_completa, x="Pacientes", y="Ingresos", hue="Mes", ax=axes[1,1])`
7. Agrega un título a cada panel con `axes[fila,col].set_title("...")`
8. Cierra con:
   ```python
   plt.suptitle("Reporte Ejecutivo — Clínica 2025", fontsize=14)
   plt.tight_layout()
   plt.show()
   ```

---
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Dataset completo de la clínica para el dashboard
datos_clinica_completa = {
    "Mes":          ["Enero", "Febrero", "Marzo", "Abril", "Mayo"],
    "Ingresos":     [15000, 18000, 12000, 25000, 21000],
    "Pacientes":    [100, 120, 95, 160, 145],
    "Satisfaccion": [82, 88, 75, 92, 89]
}
df_clinica_completa = pd.DataFrame(datos_clinica_completa)

sns.set_theme(style="whitegrid")

# Escribe aquí tu dashboard de 4 paneles: