# -*- coding: utf-8 -*-
"""Sesión 9: Fundamentos de Estadística y Matemáticas (Teoría)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k9HQWkH_a6BHrhvkl3T5xgUHpjbW_DX-

# Sesión 9: Fundamentos de Estadística y Matemáticas (Teoría)


---

### ¿Qué es la Estadística Descriptiva?
Imagina que fuiste a ver una película de tres horas al cine y un amigo te pregunta de qué trata. No le vas a contar cada segundo, cada diálogo y cada escena; simplemente le das una **sinopsis** con lo más importante.

La **Estadística Descriptiva** hace exactamente lo mismo. En lugar de obligarnos a leer una tabla con un millón de pacientes o encuestas, nos permite **resumir y describir** todas esas filas de información utilizando unos cuantos números clave.

> 💡 **Conexión con Python:** En programación, ese "millón de datos" los guardaremos dentro de las **Listas** (`[ ]`) que aprendimos a crear en la sesión pasada.

---

### Medidas de Tendencia Central: El centro de la historia
Cuando queremos resumir una lista de datos, lo primero que buscamos es su "centro". Hay tres formas principales de encontrarlo:

1. **El Promedio (Media):** Es el "punto de equilibrio". Es la suma de todos los valores dividida entre el número total de datos. Piensa en el promedio como la bandeja de un mesero: busca el punto exacto donde el peso de los datos se equilibra. Sin embargo, tiene una debilidad: *se deja engañar fácilmente por los valores extremos.*
2. **La Mediana:** Es el "corazón de la fila". Si acomodamos a todas las personas de nuestra base de datos en una fila, desde la más baja hasta la más alta, la mediana es el valor de la persona que queda *exactamente en el centro*. Es muy justa. Si estamos midiendo el ingreso de un vecindario y de pronto se muda un multimillonario allí, el promedio se dispararía haciéndonos creer que todos son ricos, pero la mediana se mantendría intacta, contándonos la historia real de la mayoría.
3. **La Moda:** Es lo más "popular". Simplemente es el valor que más se repite. Si en un hospital la queja más frecuente es "dolor de cabeza", esa es nuestra moda.

---

### Medidas de Dispersión (Variabilidad): ¿Qué tan confiable es el resumen?
Saber el centro de nuestros datos no es suficiente; necesitamos saber qué tan esparcidos o agrupados están. A esto le llamamos **variabilidad**.

* **El Rango:** Es la distancia más básica. Simplemente tomamos al dato numérico más grande y le restamos el más pequeño. Nos da una idea rápida de qué tan ancha es nuestra base de datos.
* **La Desviación Estándar:** Es nuestra medida estrella. Nos dice, en promedio, qué tan alejados están los datos de su propio centro.

**Para entenderla, imagina la puntualidad de dos rutas de autobús:**
* **La Ruta A (Baja desviación estándar):** Pasa todos los días a las 8:02, 7:58, 8:01 y 7:59. En promedio pasa a las 8:00 am, y como los tiempos están muy juntitos (poca dispersión), puedes confiar plenamente en ese promedio para llegar a tiempo a tus clases.
* **La Ruta B (Alta desviación estándar):** Pasa a las 7:30, 8:30, 7:15 y 8:45. ¡Sorpresa! Matemáticamente, su promedio también son las 8:00 am. Sin embargo, los datos están tan dispersos y alejados del centro que el promedio por sí solo es una mentira.

Como científicos de datos, siempre revisamos la desviación estándar para saber si nuestro arquero tiró todas sus flechas justo en el centro del blanco, o si las esparció por toda la pared.

---

### Ejercicio 1.1: Gimnasio Mental (El Analista)
Antes de ir al código, reflexiona sobre este escenario multidisciplinario:

Eres el analista de una universidad y te piden un reporte sobre la edad de los estudiantes de primer ingreso. Revisas la lista y notas que el 99% de los alumnos tienen entre 18 y 19 años. Sin embargo, hay un estudiante de 65 años que decidió retomar sus estudios este semestre.

Si tuvieras que enviar un solo número al rector para describir la edad típica de los estudiantes de nuevo ingreso: **¿Usarías el Promedio o la Mediana? ¿Por qué?**

*(Piénsalo un momento. La respuesta correcta es la **Mediana**, porque el estudiante de 65 años es un valor extremo que empujaría el promedio hacia arriba, dando una imagen falsa de la juventud general del grupo).*

---

## 🆕 Guía de Referencia Rápida: ¿Cuándo usar cada medida?

Antes de escribir código, necesitas saber **cuál herramienta elegir** según el problema. Esta tabla es tu mapa:

| Medida | ¿Cuándo usarla? | ¿Cuándo NO usarla? | Ejemplo real |
|---|---|---|---|
| **Promedio (Media)** | Datos sin valores extremos, distribuciones simétricas | Cuando hay outliers que distorsionan el resultado | Temperatura promedio del día |
| **Mediana** | Cuando hay outliers o desigualdad | Cuando todos los datos son similares entre sí | Ingreso típico de un vecindario |
| **Moda** | Datos categóricos o para identificar lo más frecuente | Datos numéricos continuos donde casi nada se repite | Diagnóstico más común en urgencias |
| **Rango** | Primera revisión rápida de la amplitud de los datos | Como única medida de dispersión (es muy básico) | Diferencia entre el paciente más joven y el más viejo |
| **Desviación Estándar** | Evaluar consistencia y confiabilidad del promedio | Sin calcular primero el promedio (no tiene contexto) | Confiabilidad de tiempos de entrega |

> 🔑 **Regla de oro del Científico de Datos:** Un promedio **sin** su desviación estándar es una historia incompleta. Siempre reporta ambos juntos.

---

## Parte 2: De la Teoría a la Práctica (Python como tu Súper-Calculadora)

Ahora que entendemos la teoría detrás del promedio, vamos a calcularlo. La buena noticia es que en la ciencia de datos no hacemos los cálculos a mano; usamos a Python como nuestra **súper-calculadora**.

Para empezar, no necesitamos herramientas complejas. Podemos utilizar el Python puro que ya conoces, combinando nuestras "cajas" (variables), nuestras "filas de datos" (listas) y dos herramientas integradas muy sencillas:
* **`sum()`:** Que suma absolutamente todo lo que hay en una lista.
* **`len()`:** Que cuenta cuántos elementos (longitud) hay en esa lista.

### Código Paso a Paso: Calculando el Promedio
Imagina que trabajas en una clínica y acabas de recibir las mediciones de glucosa de cinco pacientes. Vamos a calcular el promedio (nuestro "punto de equilibrio") para entender la salud general de este pequeño grupo.

Ejecuta la siguiente celda:
"""

# 1. Nuestros datos: Niveles de glucosa en la sangre guardados en una Lista
niveles_glucosa = [95.5, 102.3, 88.0, 110.5, 99.2]

# 2. Paso a paso: Sumamos todos los valores y contamos a los pacientes
suma_total = sum(niveles_glucosa)
cantidad_pacientes = len(niveles_glucosa)

# 3. Aplicamos la lógica matemática (Suma total dividida entre la cantidad)
promedio_glucosa = suma_total / cantidad_pacientes

print("El promedio exacto de glucosa es:", promedio_glucosa)

"""¡Felicidades! Al hacer esto, acabas de programar tu primer cálculo estadístico desde cero. Entender esta lógica básica es vital antes de usar herramientas automatizadas.

---

### Introducción a la Precisión: Reportes legibles para humanos

Si ejecutaste el código anterior, es probable que Python te haya devuelto un número con muchos decimales (ej. `99.10000000000001`). Las computadoras aman esa hiper-precisión, pero si le entregas ese reporte a un médico o a un gerente, se verá confuso y poco profesional.

Para solucionar esto, Python nos ofrece la herramienta `round()` (redondear), que nos permite limpiar nuestros resultados para que sean legibles por humanos. Funciona pasándole el número que queremos redondear y la cantidad de decimales que deseamos:

"""

# Redondeando nuestro resultado a solo 1 decimal
promedio_reporte = round(promedio_glucosa, 1)

# Usando f-string para un reporte más profesional
print(f"Promedio para el reporte médico: {promedio_reporte} mg/dL")

"""---

## 🆕 Calculando la Mediana a mano (antes de automatizar)

Ya vimos cómo calcular el promedio con Python puro. Pero el Ejercicio 2.1 usa `round()` y la lógica del promedio. Antes de avanzar al reto, veamos cómo calcular **la mediana manualmente** usando `sorted()`, para entender qué hace Python internamente cuando la automatizamos en la Sesión 10.

**El proceso de la mediana en 3 pasos:**
1. **Ordenar** la lista de menor a mayor → `sorted(lista)`
2. **Encontrar el índice del centro** → `len(lista) // 2`
3. **Extraer ese valor** → `lista_ordenada[indice_centro]`

Ejecuta la siguiente celda para verlo en acción:

"""

# Demostración: Mediana calculada "a mano" con Python puro
salarios = [10000, 12000, 10500, 11000, 9500]

# Paso 1: Ordenamos la lista de menor a mayor
salarios_ordenados = sorted(salarios)
print(f"Lista ordenada: {salarios_ordenados}")

# Paso 2: Encontramos el índice del centro
indice_centro = len(salarios_ordenados) // 2
print(f"Índice del centro: {indice_centro}")

# Paso 3: Extraemos el valor del centro
mediana_manual = salarios_ordenados[indice_centro]
print(f"Mediana (el salario real de la mayoría): ${mediana_manual:,}")

# Comparamos con el promedio para ver el engaño
promedio_salarios = round(sum(salarios) / len(salarios), 2)
print(f"Promedio (distorsionado por el director): ${promedio_salarios:,}")
print("\n¿Cuál número representa mejor a la mayoría de los empleados?")

"""---

### Ejercicio 2.1: El Auditor Financiero

¡Es tu turno de usar la súper-calculadora! Imagina que el departamento de contabilidad te pide el promedio de los costos de los últimos 4 tratamientos médicos realizados en la clínica.

**Tu Tarea:**

1. En la celda de abajo, usa la lista `costos_tratamientos` que ya te dejamos preparada.
2. Crea una variable llamada `suma` y usa `sum()` para sumar la lista completa.
3. Crea una variable llamada `cantidad` y usa `len()` para contar los elementos de la lista.
4. Calcula el promedio dividiendo la suma entre la cantidad y guárdalo en una nueva variable.
5. Usa `round()` para redondear tu resultado final a **2 decimales** (ya que estamos hablando de dinero).
6. Usa `print()` con un **f-string** para mostrar tu reporte final en pantalla.

> 💡 **Recordatorio de f-string:** `print(f"El promedio es: ${variable}")`

"""

costos_tratamientos = [1500.50, 3200.00, 850.75, 4100.20]

# Escribe aquí tu código para el Ejercicio 2.1:

"""---

## Parte 3: Exploración con Datos (La Estadística en el Mundo Real)

Ahora que entendemos cómo Python hace los cálculos básicos, veamos qué nos dicen estos números sobre los *datasets* (conjuntos de datos) que utilizaremos en futuros análisis.

### ¿Qué nos cuenta el promedio en el Titanic?

Piensa en el famoso registro de pasajeros del Titanic. Si le pedimos a Python que calcule el promedio de edad, nos dirá que era de aproximadamente 29 años. Ese es nuestro "punto de equilibrio" y nos cuenta una historia humana clara: era un barco con una población predominantemente joven. De igual forma, el precio promedio del boleto nos indicaría el punto medio matemático de los ingresos generados por la tripulación.

---

### Valores Atípicos (*Outliers*): El engaño de las mansiones

Imagina que ahora analizamos un dataset de viviendas en un vecindario de clase media donde las casas cuestan alrededor de $100,000. De pronto, un multimillonario construye una mansión de $50 millones en la misma calle.

Si calculamos el promedio de los precios, el resultado se disparará y nos hará creer falsamente que todos en ese vecindario son millonarios. A estos datos extremos que distorsionan la realidad los llamamos **valores atípicos** u ***outliers***.

¡Vamos a comprobar este engaño con Python! Recuerda que en la sesión pasada aprendimos a usar `append` para agregar datos a una lista. Ejecuta esta celda:

"""

# 1. El vecindario original (5 casas de clase media)
precios_casas = [100000, 105000, 98000, 102000, 100000]

promedio_real = sum(precios_casas) / len(precios_casas)
print(f"Promedio original del vecindario: ${promedio_real:,.2f}")

# 2. ¡Llega el multimillonario y construye su mansión!
precios_casas.append(50000000)

# 3. Recalculamos el promedio con la mansión incluida
promedio_engañoso = sum(precios_casas) / len(precios_casas)
print(f"Promedio tras el Outlier: ${round(promedio_engañoso, 2):,.2f}")
print("¡El promedio dice que todos son millonarios! (Lo cual es falso)")

"""Por eso, en escenarios con mucha desigualdad (como salarios o precios), los científicos de datos preferimos usar la **mediana**: al ordenar las casas de menor a mayor, la casa del centro seguirá costando cerca de $100,000, contándonos la verdadera historia de la mayoría.

---

### Cazando extremos: `max()` y `min()`

Para identificar si en nuestra base de datos hay algún valor atípico absurdo, Python nos regala otras dos herramientas integradas súper útiles que buscan el valor máximo y el mínimo al instante:

* **`max(lista)`:** Encuentra el número más grande.
* **`min(lista)`:** Encuentra el número más pequeño.

---

### Visualización mental: La Moda en gráficas

Finalmente, imagina un gráfico de barras (*bar chart*) que compara a los pasajeros del Titanic según su clase social (Primera, Segunda y Tercera). Visualmente, verías tres columnas.

La columna más alta de todas representa nuestra **moda**: la categoría que más se repite. En el caso del Titanic, la barra de la Tercera Clase es la más alta por mucho. Sin hacer una sola operación matemática, esa visualización nos indica de inmediato que la experiencia del viaje estuvo dominada por la clase trabajadora.

---

### Ejercicio 3.1: El Cazador de Anomalías

Imagina que eres el analista de control de calidad de una fábrica de botellas de agua. Las botellas deberían contener exactamente 500 ml. Te envían los datos de la última hora de producción y sospechas que la máquina está fallando y rellenando algunas botellas de más.

**Tu tarea:**

1. En la celda de abajo, tienes la lista `mililitros_botellas`.
2. Usa la función `max()` para encontrar la botella más llena y guárdala en una variable.
3. Usa la función `min()` para encontrar la botella más vacía y guárdala en otra variable.
4. Calcula el **Rango** de dispersión (restándole el mínimo al máximo) y guárdalo en una variable.
5. Usa `print()` con **f-strings** para imprimir tus 3 descubrimientos y demostrar numéricamente si hay valores atípicos.

"""

mililitros_botellas = [500, 502, 498, 501, 499, 500, 850, 497]

# Escribe aquí tu código para el Ejercicio 3.1:
max_mililitros = max(mililitros_botellas)
print (f"La botella con el mayor contenido es de {max_mililitros} ml")
min_mililitros = min(mililitros_botellas)
print(f"La botella con el menor contenido es de: {min_mililitros} ml")
rango = max_mililitros - min_mililitros
print(f"Rango: {rango}")
suma = 0
for i in mililitros_botellas:
  suma += i
media = suma/len(mililitros_botellas)
print(f"El promedio es: {media}")

"""---

## 🆕 ¿Cómo encuentra Python la Moda? (La lógica detrás del código)

En el Reto Final te pedimos identificar la moda "a ojo". Pero en el mundo real, con miles de datos, necesitamos que Python la encuentre por nosotros. En la **Sesión 10** aprenderemos el comando automático (`statistics.mode()`), pero primero veamos la lógica que ese comando ejecuta internamente — ¡usando todo lo que ya sabemos!

El truco es usar un **diccionario como contador**: recorremos la lista con un `for` y registramos cuántas veces aparece cada valor.

"""

# Encontrando la Moda "a mano" usando un diccionario como contador
# (Así es como trabaja statistics.mode() internamente)

niveles_colesterol_demo = [185, 210, 195, 185, 205, 185]

# Paso 1: Creamos un diccionario vacío para contar frecuencias
conteo = {}

# Paso 2: Recorremos la lista y contamos cada valor
for valor in niveles_colesterol_demo:
    if valor in conteo:
        conteo[valor] = conteo[valor] + 1   # ya lo vimos antes: sumamos 1
    else:
        conteo[valor] = 1                   # primera vez que lo vemos

print("Tabla de frecuencias:", conteo)

# Paso 3: Encontramos el valor con el conteo más alto
moda_manual = max(conteo, key=conteo.get)
print(f"La Moda es: {moda_manual}  →  aparece {conteo[moda_manual]} veces")
print("En la Sesión 10 haremos esto mismo con: statistics.mode(lista)")

"""---

## Parte 4: Reto Práctico (El Analista de Datos)

Para cerrar nuestra sesión de hoy, vas a ponerte la bata de investigador y analizarás la salud general de un pequeño grupo de pacientes.

Imagina que tienes los resultados de los niveles de colesterol (en mg/dL) de 10 personas. Copia este bloque en una nueva celda de código y sigue las instrucciones.

**Tus instrucciones paso a paso:**

1. **Calcula el Promedio:** En la celda, crea una variable llamada `promedio` y calcúlalo utilizando las herramientas automáticas de Python que aprendimos hoy (`sum()` dividido entre `len()`).
2. **Aplica formato:** Usa la herramienta `round()` para redondear tu promedio a 1 solo decimal.
3. **Imprime tu reporte:** Usa `print()` con **f-string** para mostrar el resultado en pantalla.
4. **Identifica la Moda (Visualmente):** Revisa la lista de números en el código e identifica "a ojo" cuál es el valor exacto que más se repite.
5. **🔥 RETO EXTRA:** Usando `max()` y `min()`, calcula también el **Rango** del grupo y agrégalo a tu reporte.

"""

# Niveles de colesterol de 10 pacientes
niveles_colesterol = [185, 210, 195, 240, 185, 205, 185, 220, 190, 250]

# 1 y 2. Calcula aquí el promedio y redondéalo:


# 3. Imprime tu reporte aquí (usa f-string):


# 🔥 RETO EXTRA: Calcula el Rango (max - min) e inclúyelo en el reporte:

"""---

### 🧠 Reflexión Analítica (Tu diagnóstico)

Haz doble clic en esta celda de texto y escribe debajo una breve interpretación de tus descubrimientos respondiendo a lo siguiente:

> *Sabiendo que un nivel de colesterol saludable debe estar por debajo de los 200 mg/dL: ¿Qué te dice el promedio sobre la salud general de este grupo? ¿Cuál fue la moda y qué historia nos cuenta sobre la mayoría de los pacientes? ¿Hay algún "engaño" estadístico aquí? ¿Qué te dice el Rango sobre la variabilidad del grupo?*

**(Escribe tu reflexión aquí abajo):**

*

---

## 🆕 Puente hacia la Sesión 10: Del cálculo manual a la automatización

¡Excelente trabajo de hoy! Calculaste promedios, detectaste outliers y encontraste la moda usando **Python puro** — sin ninguna librería extra. Eso es poderoso porque ahora entiendes la lógica matemática detrás de cada número.

Sin embargo, imagina que en lugar de 10 pacientes tuvieras **100,000 registros de un censo nacional**. Escribir `sum() / len()` para cada variable sería lento. Por eso, en la **Sesión 10** aprenderemos el módulo `statistics` de Python — una caja de herramientas especializada que automatiza todo lo que hiciste hoy en una sola línea.

**Anticipo de lo que viene:**

```python
import statistics

# Lo que hoy hiciste en 3 líneas...
suma = sum(niveles_colesterol)
cantidad = len(niveles_colesterol)
promedio = round(suma / cantidad, 1)

# ...en la Sesión 10 lo harás en 1 línea:
promedio_auto = statistics.mean(niveles_colesterol)
mediana_auto  = statistics.median(niveles_colesterol)
moda_auto     = statistics.mode(niveles_colesterol)
```

> 🎯 **Tu misión para la próxima clase:** Llega sabiendo qué es un `import` en Python. Pista: es como llamar a una "caja de herramientas especializada" que alguien más ya construyó para ti.

---
"""