# -*- coding: utf-8 -*-
"""Sesión 7: Estructuras de Datos y Control de Flujo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_J5yOlBtqDBi-MjcMzytqlKwFJkn3G6A

# Sesión 7: Estructuras de Datos y Control de Flujo

### Estructuras de Datos: Los "Muebles" Organizadores
Imagina que ya no tienes una sola caja, sino un sistema de archivo completo. En programación, usamos diferentes "muebles" dependiendo de cómo necesitemos manejar la información:

1. **Listas (`list`):** Son como una lista del supermercado. Te permiten guardar múltiples elementos en un orden específico, uno detrás de otro, y puedes tachar, modificar o agregar nuevos artículos en cualquier momento.
2. **Tuplas (`tuple`):** Son como un acta de nacimiento o un contrato. Tienen un orden igual que las listas, pero están **"selladas" bajo llave**. Una vez que creas una tupla, no puedes modificar, añadir ni borrar sus elementos. Son perfectas para proteger información que jamás debería cambiar por accidente, como las coordenadas geográficas de una clínica o las fechas históricas en una investigación.
3. **Diccionarios (`dict`):** Funcionan exactamente como una agenda de contactos telefónicos o el expediente de un paciente. En lugar de buscar un dato por su posición en la fila, lo buscas a través de una "llave" o etiqueta. Por ejemplo, buscas la llave *"Diagnóstico"* y el diccionario te devuelve el valor *"Hipertensión"*.
4. **Conjuntos (`set`):** Son como la lista de invitados a un club exclusivo donde **no se admiten duplicados**. Son la herramienta perfecta si tienes una base de datos con un millón de respuestas a una encuesta y solo quieres extraer una lista limpia de los países únicos de origen, ignorando automáticamente todas las repeticiones.

---

### ⚠️ El Secreto Informático: Contar desde Cero (Índices)
Hay una regla universal que debes aprender hoy antes de programar: **los humanos empezamos a contar desde el 1, pero las computadoras empiezan a contar desde el 0.**

Si tienes una Lista con tres encuestados: `["Ana", "Beto", "Carlos"]`
* Para la computadora, "Ana" está en la posición **`0`**.
* "Beto" está en la posición **`1`**.
* "Carlos" está en la posición **`2`**.

A esto se le llama **Indexación**, y dominar este concepto te ahorrará muchos dolores de cabeza cuando busques información.

---

### Control de Flujo: Tomando Decisiones y Repitiendo Tareas
Tener los datos bien organizados es solo la mitad del trabajo; necesitamos que la computadora actúe de manera inteligente. El "Control de Flujo" es el volante con el que manejamos nuestro programa.

**1. Los Condicionales (`If`, `Elif`, `Else`):**
Piensa en ellos como un **protocolo de triaje médico** en la sala de urgencias. Le enseñamos a la máquina a bifurcar su comportamiento según las condiciones que encuentre:
* **Si (`if`)** el paciente tiene fiebre mayor a 39°, pásalo a urgencias inmediatamente.
* **O si (`elif`)** el paciente tiene temperatura entre 37.5° y 39°, ponlo en la sala de espera.
* **De lo contrario (`else`)**, para cualquier otra situación no prevista, envíalo a consulta general.

**2. Los Bucles (`For`, `While`):**
Si los condicionales toman decisiones, los bucles son los trabajadores incansables. Un bucle `for` es como un profesor pasando lista en el aula: *"Revisa al alumno 1, luego al 2, luego al 3... hasta que se acaben"*. El bucle `while` es diferente: trabaja **mientras** una condición sea verdadera, como una alarma que sigue sonando hasta que la apagas.

---

### Funciones: Nuestras Recetas de Cocina
Finalmente, las **Funciones** son como las recetas de un libro de cocina.
Para preparar un pastel, tomas ciertos ingredientes (tus datos de entrada), sigues una serie de pasos específicos y automatizados, y obtienes un platillo terminado (tu resultado).

Si en tu investigación descubres que debes realizar exactamente la misma limpieza de datos y cálculos estadísticos todos los días, en lugar de escribir las instrucciones paso a paso una y otra vez, simplemente las empaquetas dentro de una "función". Así, cuando quieras repetir el proceso, solo tienes que llamar a tu receta por su nombre y la computadora hará el resto automáticamente.

---

### Ejercicio 1: Gimnasio Mental (El Arquitecto de Datos)
Antes de ir al código, vamos a entrenar tu intuición analítica. Lee los siguientes 4 escenarios y decide mentalmente qué estructura de datos (`Lista`, `Tupla`, `Diccionario` o `Conjunto/Set`) sería la mejor opción para organizar esa información. *(Las respuestas están al final)*.

1. Quieres guardar la edad, el peso, el nombre y el nivel de estrés de un participante para acceder a ellos rápidamente por su nombre de categoría.
2. Tienes una base de datos de 5,000 encuestas y quieres saber exactamente cuántas ciudades diferentes participaron, eliminando todas las ciudades repetidas al instante.
3. Quieres guardar las fechas exactas de los días festivos nacionales del año para tu sistema. ¡No quieres que nadie pueda modificarlas o borrarlas por accidente!
4. Quieres hacer un registro de los alumnos que van entrando al taller, uno por uno, y necesitas poder agregar a los que lleguen tarde.

> **Respuestas del Ejercicio 1:**
> *1. Diccionario (Usando llaves como "peso" o "edad") | 2. Conjunto/Set (Elimina duplicados automáticamente) | 3. Tupla (Es inmutable/está sellada) | 4. Lista (Es modificable y mantiene el orden de llegada).*

---

## Parte 2: De la Teoría a la Práctica: Traduciendo al Código

Ya conocemos la teoría, ahora vamos a materializar nuestros "organizadores", "decisiones" y "recetas" en Google Colab usando código real.

### 1. Creando Estructuras de Datos
En Python, le indicamos a la computadora qué tipo de organizador queremos usar a través de símbolos visuales muy específicos en nuestro teclado. Observa cómo creamos nuestra lista, diccionario y tupla:
"""

# La Lista [Corchetes]: Ordenada y modificable
edades_pacientes = [25, 34, 18, 45, 60]

# El Diccionario {Llaves}: Etiquetas (llaves) y sus valores
perfil_paciente = {
    "nombre": "Laura",
    "edad": 28,
    "peso": 65.5,
    "diagnostico": "Asma"
}

# La Tupla (Paréntesis): Fija e inmodificable (ideal para coordenadas)
coordenadas_hospital = (19.4326, -99.1332)

print("Datos guardados correctamente en la memoria.")
print(f"Lista: {edades_pacientes}")
print(f"Diccionario: {perfil_paciente}")
print(f"Tupla: {coordenadas_hospital}")

"""**El poder de los símbolos:**

* **Los Corchetes `[]`:** Le dicen a la computadora *"crea una fila de datos donde el orden importa y que puedo modificar después"* (Lista).
* **Las Llaves `{}`:** Indican *"crea un expediente donde cada dato está asociado a una etiqueta clave que yo defina"* (Diccionario).
* **Los Paréntesis `()`:** Significan *"guarda estos datos bajo llave, son seguros y no deben ser modificados nunca por accidente"* (Tupla).

---

### 2. Las Decisiones (Control de Flujo con `if/else`)

Vamos a pedirle a la computadora que actúe como un filtro de seguridad en la recepción, revisando si un paciente es mayor de edad.

**Reglas de escritura obligatorias:**
- Los **dos puntos `:`** al final de `if` y `else` son **obligatorios**.
- La **indentación** (4 espacios hacia la derecha) le indica a Python qué instrucciones van *adentro* de cada decisión. Si los omites, Python dará un `IndentationError`.

"""

edad_actual = 20

if edad_actual >= 18:
    print(f"✅ El paciente de {edad_actual} años es mayor de edad. Puede firmar el consentimiento.")
else:
    print(f"⚠️  El paciente de {edad_actual} años es menor de edad. Requiere la firma de un tutor.")

# Prueba cambiando el valor de 'edad_actual' a 15 y vuelve a ejecutar

"""**Explicación línea por línea:**

* `if edad_actual >= 18:` Le planteamos la condición a evaluar. Los **dos puntos (`:`)** al final son obligatorios; le indican a Python: *"presta atención, si esto es verdad, entonces haz lo siguiente"*.
* **⚠️ La Indentación (Los espacios en blanco):** Nota que la instrucción `print` está empujada hacia la derecha. En Python, estos 4 espacios son **obligatorios**. Le dicen a la máquina qué instrucciones van "adentro" de la decisión. Si omites los espacios, Python se confundirá y te dará un error.
* `else:` Significa *"De lo contrario (si la primera condición fue falsa), entonces haz esto"*. (Nota que también lleva dos puntos al final).

---

### 🆕 `elif`: La Tercera Rama (y las que necesites)

El `if/else` solo tiene dos caminos: verdadero o falso. Pero la vida real raramente es binaria. En medicina, un paciente puede estar bien, con síntomas leves, o en estado crítico — son **tres** niveles, no dos.

Para eso existe `elif` (contracción de *"else if"* = "de lo contrario, si..."). Te permite agregar tantas ramas como necesites:

```
if   → Primera condición (se evalúa siempre)
elif → Segunda condición (solo si la primera fue falsa)
elif → Tercera condición (solo si las anteriores fueron falsas)
else → Cajón de sastre (cuando ninguna condición fue verdadera)
```

> ⚠️ **Regla importante:** Python evalúa las ramas **de arriba hacia abajo** y se detiene en la **primera** que sea verdadera. El orden importa: pon siempre la condición más restrictiva (el número más grande o más pequeño) primero.

Vamos a implementar el triaje médico completo que describimos en la teoría:
"""

# ============================================================
# ELIF EN ACCIÓN: Triaje médico con 3 niveles
# ============================================================

temperatura = 38.2   # ← cambia este valor y vuelve a ejecutar

# ─── Protocolo de triaje ────────────────────────────────────
if temperatura >= 39.0:
    print(f"🚨 URGENCIAS: Temperatura {temperatura}°C. ¡Atención inmediata!")

elif temperatura >= 37.5:   # Solo llega aquí si NO fue >= 39.0
    print(f"⏳ SALA DE ESPERA: Temperatura {temperatura}°C. Síntomas leves.")

else:                       # Solo llega aquí si ninguna condición fue verdadera
    print(f"✅ CONSULTA GENERAL: Temperatura {temperatura}°C. Dentro del rango normal.")

# ─── Prueba los 3 casos ─────────────────────────────────────
print("\n--- Probando los 3 casos automáticamente ---")
for temp_prueba in [40.1, 38.5, 36.6]:
    if temp_prueba >= 39.0:
        nivel = "🚨 URGENCIAS"
    elif temp_prueba >= 37.5:
        nivel = "⏳ ESPERA"
    else:
        nivel = "✅ CONSULTA"
    print(f"  {temp_prueba}°C → {nivel}")

# ─── Bucle for: recorre la lista automáticamente ───────────
# Le decimos: "Por cada 'numero' dentro de 'edades_pacientes', imprimelo"
for numero in edades_pacientes:
    print(f"Revisando paciente con edad: {numero} años")

# len() nos dice cuántos elementos tiene una lista
print(f"\nTotal de pacientes procesados: {len(edades_pacientes)}")

"""---

### 4. Creando una Función (Nuestra propia receta)

Imagina que debemos evaluar la temperatura de 5,000 pacientes distintos. No vamos a escribir ese `if/elif/else` 5,000 veces. Mejor, empaquetamos esas instrucciones en una **Función** usando la palabra clave `def` (de definir):

```python
def nombre_de_la_funcion(parametro):
    # instrucciones adentro (con indentación)
    return resultado
```

* `def` → le dice a Python: *"voy a definir una receta nueva"*.
* `parametro` → el "ingrediente" que le pasas cada vez que usas la función.
* `return` → el "platillo terminado" que la función devuelve al finalizar.

"""

# Definimos nuestra receta de triaje reutilizable
def clasificar_temperatura(temp):
    """Recibe una temperatura y regresa el nivel de urgencia."""
    if temp >= 39.0:
        return "🚨 URGENCIAS — atención inmediata"
    elif temp >= 37.5:
        return "⏳ SALA DE ESPERA — síntomas leves"
    else:
        return "✅ CONSULTA GENERAL — temperatura normal"

# Usamos la receta con diferentes pacientes
pacientes_temp = [("Ana",  40.1), ("Beto", 38.0), ("Carla", 36.8)]

print("--- Reporte de Triaje ---")
for nombre, temp in pacientes_temp:
    resultado = clasificar_temperatura(temp)
    print(f"  {nombre} ({temp}°C): {resultado}")

"""Al usar `def`, creaste tu propia mini-herramienta que automatiza un proceso lógico. A partir de ese momento, solo debes llamarla por su nombre y entregarle el dato que necesita procesar entre los paréntesis.

---

### Ejercicio 2: Creando tu primer Expediente Clínico (Diccionario)

¡Es tu turno! Vamos a comprobar que dominas los "organizadores".

**Tu Tarea:**

1. En la celda de abajo, crea un **Diccionario** llamado `mi_expediente`.
2. Recuerda abrir y cerrar con **llaves `{}`**.
3. Añade al menos **cuatro etiquetas** sobre ti: `"nombre"`, `"edad"`, `"carrera"` y `"promedio"`, con sus respectivos datos. *(Recuerda separar cada par con una coma `,`).*
4. Usa un `print()` con f-string para mostrar al menos dos valores del diccionario, accediendo a ellos así: `mi_expediente["nombre"]`.

"""

# Escribe aquí tu código para el Ejercicio 2:
mi_expediente = {

}

# Accede a los valores con mi_expediente["llave"] y muéstralos con f-string

"""---

### 🆕 `len()` y `range()`: Las Herramientas del `for` Profesional

Hasta ahora el `for` recorrió una lista existente. Pero en ciencia de datos también necesitamos hacer cosas con **posiciones** (índices) o repetir algo un **número exacto de veces**.

| Función | ¿Qué hace? | Ejemplo | Resultado |
|---|---|---|---|
| `len(lista)` | Cuenta cuántos elementos tiene | `len([10, 20, 30])` | `3` |
| `range(n)` | Genera una secuencia de 0 a n-1 | `range(3)` | `0, 1, 2` |
| `range(inicio, fin)` | Genera desde inicio hasta fin-1 | `range(1, 4)` | `1, 2, 3` |

**¿Por qué combinarlos?** Cuando necesitas saber la *posición* de cada elemento ("el paciente número 1", "el paciente número 2"...), usar `range(len(lista))` te da acceso al índice y al valor al mismo tiempo.

"""

# ============================================================
# len() y range() EN ACCIÓN
# ============================================================

nombres = ["Ana", "Beto", "Carla", "Diego"]

# len() — cuántos hay
print(f"Total de participantes: {len(nombres)}")

# range(n) — repetir algo n veces
print("\n--- Conteo con range ---")
for i in range(3):
    print(f"  Vuelta número {i}")

# range(len(lista)) — recorrer con índice
print("\n--- Lista numerada con range(len()) ---")
for i in range(len(nombres)):
    print(f"  Participante #{i + 1}: {nombres[i]}")
    #                 ↑ sumamos 1 para que empiece en 1, no en 0

# Acceso directo por índice
print(f"\nPrimer nombre (índice 0): {nombres[0]}")
print(f"Último nombre (índice -1): {nombres[-1]}")  # -1 = el último, siempre

"""---

### 🆕 El Bucle `while`: Trabaja *Mientras* la Condición Sea Verdadera

El `for` recorre colecciones de tamaño conocido. El `while` es diferente: **sigue ejecutándose mientras una condición sea `True`**, sin importar cuántas vueltas tome.

La analogía perfecta: una alarma médica. No sabes cuántas veces va a sonar — solo sabes que **parará cuando el paciente presione el botón**.

```python
while condicion_verdadera:
    # instrucciones que se repiten
    # ⚠️ OBLIGATORIO: algo dentro del while debe modificar
    # la condición, o el bucle nunca terminará (bucle infinito)
```

> ⚠️ **El error más común con `while`:** Olvidar modificar la variable que controla la condición. Si `while conteo < 5` pero nunca sumas a `conteo`, el programa corre para siempre. ¡Siempre incluye una línea que acerque el bucle a su fin!

"""

# ============================================================
# WHILE EN ACCIÓN: Acumulando mediciones hasta alcanzar el límite
# ============================================================

# Escenario: un sensor registra pacientes hasta llenar el cupo del día
cupo_maximo   = 5
registros     = 0

print("--- Sistema de registro iniciado ---")

while registros < cupo_maximo:
    registros += 1          # ← CRÍTICO: incrementamos para no crear bucle infinito
    print(f"  Paciente #{registros} registrado. Cupo restante: {cupo_maximo - registros}")

print(f"\n✅ Cupo lleno. Se registraron {registros} pacientes.")

# ─── Comparativa visual: for vs while ───────────────────────
print("\n--- for (lista conocida) ---")
for i in range(3):          # sabemos exactamente cuántas vueltas: 3
    print(f"  for: vuelta {i}")

print("\n--- while (condición variable) ---")
contador = 10
while contador > 7:         # no sabemos cuántas vueltas hasta ejecutar
    print(f"  while: contador = {contador}")
    contador -= 1

"""---

## Parte 3: Exploración con Datos (La Perspectiva de la Ciencia de Datos)

¿Por qué necesitamos aprender sobre listas y diccionarios si nuestro objetivo es hacer Ciencia de Datos? La respuesta es sencilla: estas piezas básicas son los **ladrillos** con los que se construyen los *datasets* (conjuntos de datos) que analizarás en el mundo real, como los censos poblacionales, registros médicos o bases de datos financieras.

Piensa en una hoja de cálculo de Excel. En Python, esa tabla gigante no es más que una combinación inteligente de las estructuras que acabamos de conocer.

### De Excel a Python: Filas y Columnas

En la ciencia de datos, cada paciente, cliente o evento es un "registro" (una fila), y cada característica (edad, peso, diagnóstico) es una "variable" (una columna).

Observa cómo traducimos esto a código. Ejecuta la siguiente celda para guardar nuestra base de datos en la memoria:

"""

# Un Diccionario es exactamente igual a UNA FILA en Excel (un solo registro)
fila_paciente = {
    "ID": 105,
    "Edad": 45,
    "Diagnostico": "Diabetes"
}

# Una Lista es exactamente igual a UNA COLUMNA en Excel (datos de múltiples pacientes)
columna_edades = [45, 32, 58, 22, 65]

# ¡Un Dataset completo es simplemente una Lista que contiene muchos Diccionarios adentro!
base_de_datos = [
    {"ID": 105, "Edad": 45, "Diagnostico": "Diabetes"},
    {"ID": 106, "Edad": 32, "Diagnostico": "Asma"},
    {"ID": 107, "Edad": 58, "Diagnostico": "Hipertensión"},
    {"ID": 108, "Edad": 65, "Diagnostico": "Diabetes"}
]

print(f"Base de datos cargada: {len(base_de_datos)} registros.")

"""### El verdadero poder: La Iteración Automática

Aquí es donde la programación justifica todo el esfuerzo de aprendizaje. Si tuvieras que buscar a mano en Excel a todos los pacientes mayores de 50 años dentro de una base de datos de 100,000 registros, te tomaría horas o días enteros.

Sin embargo, podemos combinar nuestras estructuras de datos (`base_de_datos`) con nuestro control de flujo. Le diremos a Python: *"Pasa por cada paciente de la lista (`for`) y, si (`if`) la edad es mayor a 50, muéstramelo"*.

Ejecuta la celda de abajo para ver la magia de la automatización:

"""

print("--- Iniciando búsqueda de pacientes mayores de 50 años ---")

# El bucle recorre toda la lista de pacientes, uno por uno
encontrados = 0
for paciente in base_de_datos:

    # El condicional filtra solo a los que cumplen la regla
    if paciente["Edad"] > 50:
        print(f"  ⚠️  Alerta: ID {paciente['ID']} | Edad: {paciente['Edad']} | Dx: {paciente['Diagnostico']}")
        encontrados += 1

print(f"--- Búsqueda finalizada: {encontrados} pacientes encontrados ---")

"""¡La computadora revisó todos los registros y tomó la decisión lógica por ti en fracciones de segundo!

---

### Ejercicio 3: Tu Primer Filtro de Datos (El Analista)

Ahora eres tú quien dirige la investigación. La Secretaría de Salud te ha pedido un reporte urgente solo de los pacientes que tienen "Diabetes".

*(💡 **Tip informático:** Para preguntarle a Python si un texto es exactamente igual a otro, no usamos un solo signo de igual `=`, usamos doble signo `==`).*

**Tu Tarea:**

1. En la celda de abajo, escribe un bucle `for` que recorra la `base_de_datos`.
2. Adentro del bucle (con su debida indentación), usa un `if` para revisar si el `"Diagnostico"` del paciente es `==` a `"Diabetes"`. (¡No olvides la mayúscula inicial y las comillas!).
3. Si la condición es verdad, usa `print()` con **f-string** para mostrar el ID y diagnóstico del paciente.
4. Ejecuta tu celda y comprueba que solo aparezcan los pacientes 105 y 108.
5. **RETO EXTRA:** Usa un contador para que al final imprima: `"Reporte: X pacientes con Diabetes encontrados."`

"""

# Escribe aquí tu código para el Ejercicio 3:
# Tip: accede al diagnóstico con paciente["Diagnostico"]

"""---

## Parte 4: Reto Práctico (El Sistema de Evaluación)

Para cerrar con broche de oro nuestra sesión de hoy, vas a construir un sistema automático de evaluación combinando un **Diccionario**, **`elif`** con tres niveles y **f-strings**.

**El Escenario:** Eres el analista de datos de una universidad y debes clasificar automáticamente el rendimiento de los estudiantes.

Sigue estos pasos cuidadosamente:

1. **Crea el perfil:** Define un Diccionario llamado `sujeto_prueba` con las llaves: `"nombre"`, `"area_estudio"` y `"calificacion"` (número sin comillas).
2. **Construye el clasificador con `elif`:** Escribe un bloque `if`/`elif`/`else` con **tres niveles**:
   - Si calificación `>= 90` → `"Sobresaliente 🏆"`
   - Si calificación `>= 70` → `"Aprobado ✅"`
   - De lo contrario → `"Necesita mejorar ⚠️"`
3. **El resultado:** Usa `print()` con **f-string** para mostrar un mensaje que incluya el nombre, la calificación y el nivel obtenido.

> 💡 **Pista:** Accede a los valores del diccionario así: `sujeto_prueba["calificacion"]`

"""

# 1. Crea el diccionario de tu sujeto de prueba:
sujeto_prueba = {

}

# 2. Construye tu clasificador con if / elif / else:
# (¡No olvides los dos puntos : y la indentación!)

# 3. Imprime el resultado con f-string