# -*- coding: utf-8 -*-
"""Sesión 14: Limpieza de Datos con Pandas (Práctica)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pFs3_NdxQc2AXRLarN9jFXCAGK9NCyNj

# Sesión 14: Limpieza de Datos con Pandas (Práctica)


### ¿Qué es Pandas?
Imagina que Pandas es un "Excel con superpoderes" o un asistente analítico que trabaja a la velocidad de la luz. En el mundo profesional de la ciencia de datos, Pandas es la herramienta estándar global para manipular información estructurada, realizando operaciones muy similares a las que harías en una hoja de cálculo o en una base de datos, pero de forma automática y masiva.

### ¿Por qué dejar de usar listas y diccionarios?
Hemos pasado varias clases trabajando con listas y diccionarios puros de Python. Aprender con esas herramientas fue como aprender a andar en bicicleta: era el ejercicio perfecto para que desarrollaras tu equilibrio analítico y entendieras la lógica detrás de los datos.

Sin embargo, cuando te enfrentas al mundo real y tienes que limpiar registros de dos millones de pacientes o censos nacionales, la bicicleta se vuelve agotadora. **Pandas es como subirte a un tren bala.** Está diseñado para realizar esos procesos complejos en milisegundos y, a menudo, requiriendo una sola línea de código.

Mira la diferencia visual. Ejecuta esta celda para convertir un viejo diccionario (bicicleta) en tu primer objeto de Pandas (tren bala):
"""

# 1. Le decimos a Python que traiga la caja de herramientas de Pandas
# (La abreviamos como 'pd' por costumbre profesional)
import pandas as pd

# Nuestro viejo y confiable diccionario (difícil de leer si fuera muy grande)
datos_diccionario = {
    "Nombre": ["Ana", "Luis", "Carlos"],
    "Edad": [28, 34, 45],
    "Diagnóstico": ["Sano", "Gripe", "Migraña"]
}

# ¡La magia de Pandas! Lo convertimos en una tabla estructurada
mi_primera_tabla = pd.DataFrame(datos_diccionario)

# Imprimimos la tabla para ver el resultado
mi_primera_tabla

"""### La Anatomía de Pandas

Si observaste la tabla de arriba, acabas de conocer la estructura de Pandas. Para dominar esta herramienta sin escribir código complejo, solo necesitas entender sus dos bloques de construcción fundamentales:

1. **DataFrame:** Piensa en esto como una hoja de cálculo completa (toda la tabla que acabas de imprimir arriba). Es una estructura bidimensional que contiene múltiples filas y columnas debidamente etiquetadas.
2. **Series:** Imagina que tomas unas tijeras y recortas una sola columna de esa tabla gigante (por ejemplo, solo la columna "Edad"). Esa columna individual, con su propia lista de datos, es una `Series`. Todo DataFrame está construido simplemente pegando varias Series una al lado de la otra.

---

### Ejercicio 1.1: Gimnasio Mental (Identificando la Anatomía)

Para asegurar que dominas el lenguaje de los datos, analiza el siguiente escenario y responde mentalmente:

Imagina que descargas el registro nacional de vacunación. Tienes un archivo inmenso con 500,000 filas y 10 columnas (Nombre, Edad, Vacuna aplicada, Fecha, etc.).

* Si tu jefe te pide que le envíes el archivo completo para revisarlo, ¿le estás enviando un DataFrame o una Series?
* Si tu jefe te pide que le extraigas **únicamente** la lista de "Vacunas aplicadas" para contar cuáles se usaron más, ¿qué estructura vas a extraer?

*(Respuestas: El archivo completo es un **DataFrame**. La columna individual de "Vacunas aplicadas" que vas a extraer es una **Series**).*

---

---

### 📋 Tabla de Referencia: Los 6 Comandos de Inspección de Pandas

Antes de limpiar, siempre debes **conocer** tus datos. Estos son los 6 comandos
que todo analista profesional ejecuta al recibir un nuevo dataset:

| Comando | ¿Qué te dice? | Cuándo usarlo |
|---|---|---|
| `df.head(n)` | Las primeras `n` filas (5 por defecto) | Para ver cómo lucen los datos |
| `df.tail(n)` | Las últimas `n` filas | Para ver si el final está correcto |
| `df.shape` | `(filas, columnas)` — las dimensiones exactas | Para saber el tamaño del dataset |
| `df.info()` | Tipos de datos + cuántos no-nulos hay por columna | Para detectar columnas con nulos |
| `df.describe()` | Estadísticas (media, mín, máx, std) de columnas numéricas | Para detectar outliers y rangos |
| `df.isnull().sum()` | Conteo exacto de nulos por columna | Para auditar la calidad del dataset |

> 💡 **Regla profesional:** Siempre ejecuta estos 6 comandos en este orden
> antes de tocar cualquier dato. Es tu "diagnóstico clínico" inicial.

---

## Parte 2: De la Teoría a la Práctica (Primeros Pasos con Pandas)

Para empezar a usar este asistente analítico, primero debemos traer nuestra caja de herramientas. En Google Colab (y en todo el mundo de la programación), la instrucción que se ha convertido en el estándar global es `import pandas as pd`.

Ese `pd` es simplemente un alias o "apodo"; lo declaramos para no tener que escribir la palabra completa "pandas" cada vez que queramos ejecutar una de sus funciones.

### Creando un DataFrame "Sucio"

Vamos a simular un escenario del mundo real con registros que contienen errores intencionales: datos faltantes (`None`) y filas repetidas. Copia y ejecuta este bloque de código en una nueva celda:
"""

import pandas as pd

# Nuestro registro médico con valores nulos y un paciente duplicado (Luis)
datos_sucios = {
    "ID_Paciente": [101, 102, 103, 104, 102],
    "Nombre": ["Ana", "Luis", "Carmen", "Jorge", "Luis"],
    "Edad": [28, 35, None, 42, 35],
    "Diagnostico": ["Gripe", "COVID", "Migraña", None, "COVID"]
}

# Convertimos el diccionario normal en un DataFrame (una tabla con superpoderes)
# Por convención, a los DataFrames se les suele llamar simplemente 'df'
df = pd.DataFrame(datos_sucios)

# Imprimimos para ver nuestra tabla
df

"""### Inspección Visual Rápida

Si tuvieras dos millones de registros, intentar imprimir la tabla completa colapsaría tu pantalla. En su lugar, Pandas nos ofrece comandos de diagnóstico para explorar rápidamente.

Ejecuta este código en una nueva celda para lanzar tu primer escaneo automatizado:

"""

# Vistazo a las primeras filas
print("--- VISTAZO A LOS DATOS ---")
print(df.head(3))

print("\n--- RESUMEN TÉCNICO ---")
# Resumen médico del dataset (nota: .info() no necesita 'print' porque se imprime solo)
df.info()

"""### ¿Qué hace exactamente cada comando?

* **`.head()`:** Te muestra por defecto únicamente las **primeras cinco filas** de tu tabla. Es ideal para darte una idea inmediata de cómo lucen tus datos y qué columnas tienes sin saturar tu pantalla.
* **`.info()`:** Funciona como el **"historial clínico"** de tu base de datos. En su salida te dirá cuántas columnas tienes, el número total de registros y el tipo de dato que hay en cada columna. Además, te muestra la cantidad exacta de valores *Non-Null* (no nulos), lo que te permite detectar como un radar en qué columnas te falta información. (¡Nota cómo `Edad` y `Diagnostico` dicen tener solo 4 datos válidos en lugar de 5!).

---

### Ejercicio 2.1: El Inspector Completo

Así como `.head()` te muestra la "cabeza" de tus datos, Pandas tiene otras dos herramientas vitales para inspeccionar la anatomía completa de tu archivo.

**Tu tarea:**

1. En la celda de abajo, usa el comando `df.tail()` (que significa "cola") para imprimir las **últimas** filas de tu tabla en lugar de las primeras.
2. En la siguiente línea, usa el comando `df.shape` (sin paréntesis, porque es un atributo, no una función). Esto te devolverá las "medidas" exactas de tu tabla en formato `(filas, columnas)`.

"""

# Escribe aquí tu código para el Ejercicio 2.1:
# 1. Usa tail() para ver el final de los datos



# 2. Usa shape para ver las dimensiones exactas de tu tabla

df.shape

# ──────────────────────────────────────────────────────────
# .describe() — El resumen estadístico en una sola línea
# ──────────────────────────────────────────────────────────

print("--- RESUMEN ESTADÍSTICO DE COLUMNAS NUMÉRICAS ---")
print(df.describe())

print("\n¿Por qué es útil?")
print("→ 'count' nos dice cuántos valores NO nulos hay (si es menor al total, hay nulos)")
print("→ 'mean'  nos da el promedio (si parece raro, puede haber un outlier)")
print("→ 'min/max' nos muestra el rango (¿una edad de 200? ¡Alerta roja!)")

"""### Cómo leer el resultado de `.describe()`

Cuando ejecutas `df.describe()`, Pandas te devuelve una tabla con 8 filas para
cada columna numérica. Aquí está la guía de lectura rápida:

| Fila | Nombre | ¿Qué significa? | 🚨 Señal de alerta |
|---|---|---|---|
| 1 | `count` | Cuántos valores no-nulos hay | Si es menor al total de filas → hay nulos |
| 2 | `mean` | Promedio de la columna | Si parece muy alto/bajo → posible outlier |
| 3 | `std` | Qué tan dispersos están los datos | Muy alto → los datos varían mucho |
| 4 | `min` | El valor más pequeño | Valor imposible (ej: edad negativa) → error |
| 5 | `25%` | El 25% de los datos está por debajo de este valor | — |
| 6 | `50%` | La mediana (el valor del centro) | — |
| 7 | `75%` | El 75% de los datos está por debajo de este valor | — |
| 8 | `max` | El valor más grande | Valor imposible (ej: edad 200) → error |

> **Truco profesional:** El `count` de `.describe()` y el conteo de `.isnull().sum()`
> son dos caras de la misma moneda. Si `count` dice 4 pero tienes 5 filas, hay 1 nulo en esa columna.

---

## Parte 3: Exploración con Datos (Limpieza a un Clic)

### El Escáner Definitivo

¿Recuerdan los bucles `for` largos y los condicionales `if` que escribimos en la Sesión 12 para cazar valores nulos uno por uno? Con Pandas, ese trabajo manual desaparece.

Podemos usar el comando `.isnull().sum()` para escanear millones de registros en un segundo. Este "escáner definitivo" nos devolverá una lista exacta de cuántos datos faltantes (`NaN` o `None`) existen en cada columna, ahorrándonos horas de trabajo. Ejecuta esta celda:
"""

print("--- REPORTE DEL ESCÁNER DE NULOS ---")
# Esto suma todos los valores nulos encontrados por columna
print(df.isnull().sum())

# ──────────────────────────────────────────────────────────────────
# .duplicated() — VER los duplicados ANTES de borrarlos
# ──────────────────────────────────────────────────────────────────

print("--- MAPA DE DUPLICADOS (True = es copia) ---")
print(df.duplicated())

print("\n--- CONTEO TOTAL DE FILAS DUPLICADAS ---")
print("Duplicados encontrados:", df.duplicated().sum())

print("\n--- ¿CUÁLES SON LAS FILAS DUPLICADAS? ---")
# keep=False marca TODAS las copias, no solo la segunda
print(df[df.duplicated(keep=False)])

"""### `.duplicated()` vs `.drop_duplicates()` — Ver antes de borrar

En medicina, ningún cirujano opera sin diagnóstico previo. En datos es igual:
**primero identificas, luego eliminas.**

| Comando | ¿Qué hace? | Resultado |
|---|---|---|
| `df.duplicated()` | **Muestra** qué filas son copia | Serie de `True`/`False` por fila |
| `df.duplicated().sum()` | **Cuenta** cuántos duplicados hay | Un número entero |
| `df[df.duplicated(keep=False)]` | **Muestra** TODAS las filas repetidas | Un DataFrame filtrado |
| `df.drop_duplicates()` | **Elimina** las copias, conserva el original | DataFrame limpio |

> 🚨 **Error común de principiantes:** Saltar directo a `.drop_duplicates()` sin
> verificar primero qué se va a borrar. Siempre usa `.duplicated()` para confirmar
> que realmente son duplicados y no registros diferentes con datos coincidentes.

---

### Borrando la Basura

Una vez detectados los errores, Pandas nos ofrece métodos directos para eliminarlos o reemplazarlos.

**El Secreto del Guardado (¡Muy Importante!)**
Aquí hay una regla de oro: cuando usas métodos de limpieza, Pandas crea y te muestra una copia temporal para proteger tu tabla original de accidentes. Si quieres que la limpieza sea **permanente** en la memoria de la computadora, tienes dos caminos:

1. **Sobrescribir tu variable:** `df = df.dropna()`
2. **Usar el comando de acción directa:** `df.dropna(inplace=True)` (Significa: hazlo "en el lugar").

Si olvidas aplicar uno de estos dos secretos, ¡tus datos seguirán igual de sucios en la siguiente línea de código!

Ejecuta este bloque para limpiar la "basura" en un instante usando el primer método (sobreescritura):
"""

print("1. Eliminando clones...")
# Borramos registros (filas) que están exactamente repetidos
df = df.drop_duplicates()
print("¡Duplicados eliminados!\n")

print("2. Estrategia de Imputación (Rellenando huecos)...")
# Rellenamos cualquier nulo en la tabla con la palabra "Desconocido"
df_rellenado = df.fillna("Desconocido")
print(df_rellenado)

print("\n--------------------------------------------------\n")

print("3. Estrategia de Eliminación (Borrando nulos)...")
# Borramos cualquier fila que contenga al menos un nulo
df_borrado = df.dropna()
print(df_borrado)

# ──────────────────────────────────────────────────────────────────────
# .fillna() con la MEDIANA — Imputación profesional para datos numéricos
# ──────────────────────────────────────────────────────────────────────

import pandas as pd

# Dataset con edades faltantes
datos_edad = {
    "Paciente":    ["Ana", "Luis", "Carmen", "Jorge", "Sofía"],
    "Edad":        [28, 35, None, 42, None],
    "Diagnostico": ["Gripe", "COVID", "Migraña", "Asma", "Gripe"]
}
df_edad = pd.DataFrame(datos_edad)

print("ANTES de imputar:")
print(df_edad)

# Calculamos la mediana SOLO de los valores que sí existen
mediana_edad = df_edad["Edad"].median()
print(f"\nMediana de edad calculada: {mediana_edad}")

# Rellenamos los nulos con la mediana
df_edad["Edad"] = df_edad["Edad"].fillna(mediana_edad)

print("\nDESPUÉS de imputar con la mediana:")
print(df_edad)

"""### ¿Cuándo usar cada estrategia de limpieza?

Esta es la decisión más importante que toma un Data Analyst. Aquí está la guía:

| Situación | Estrategia recomendada | Comando |
|---|---|---|
| La columna tiene texto y el dato es desconocido | Rellenar con texto neutro | `fillna("Desconocido")` |
| La columna tiene números y hay pocos nulos | Rellenar con la **mediana** | `fillna(df["col"].median())` |
| La columna tiene números y hay pocos nulos | Rellenar con el **promedio** | `fillna(df["col"].mean())` |
| El registro tiene muchos campos vacíos (poco valor) | Eliminar la fila completa | `dropna()` |
| La columna entera tiene demasiados nulos (>50%) | Eliminar la columna completa | `dropna(axis=1)` |

> ⚠️ **¿Por qué mediana y no promedio?**
> Si tienes los salarios `[30000, 32000, 31000, 28000, 500000]`, el promedio es `124200`
> (distorsionado por el outlier de 500K), pero la mediana es `31000` (el valor real del centro).
> La mediana es más robusta ante valores extremos — por eso los profesionales la prefieren.

---

### Ejercicio 3.1: Limpiando la Base de Contactos Médicos

El hospital central te ha enviado una lista rápida de pacientes y sus números de contacto. Te advierten que el sistema duplicó algunas filas por error. Tu objetivo es limpiar la tabla para que el equipo de enfermería pueda empezar a llamar.

**Tu tarea:**

1. Ejecuta la celda de abajo para crear el DataFrame `df_contactos`.
2. En la línea indicada, aplica el comando para eliminar los duplicados. ¡Asegúrate de usar `inplace=True` o de sobrescribir la variable `df_contactos` para que el cambio se guarde permanentemente!
3. Usa un `print()` para mostrar tu tabla final limpia. (Solo deberías ver 3 pacientes).
"""

# Base de datos de contactos con un error (Carlos está repetido)
datos = {
    "Paciente":  ["Laura", "Carlos", "Diana", "Carlos"],
    "Telefono":  ["555-1234", "555-9876", "555-4567", "555-9876"]
}

df_contactos = pd.DataFrame(datos)
df_contactos = df_contactos.drop_duplicates()
df_contactos

"""---

### Ejercicio 3.2: Limpieza de Texto con Pandas (`.str`)

¿Recuerdas los poderes de limpieza de texto que aprendiste en la Sesión 13?
(`.strip()`, `.lower()`, `.replace()`). En Pandas, esos mismos poderes funcionan
en **columnas enteras** usando el prefijo `.str`.

El hospital te envió un DataFrame con diagnósticos escritos de forma inconsistente.
Tu objetivo es estandarizar toda la columna en una sola línea.

**Tu tarea:**

1. Ejecuta la celda de abajo para crear el DataFrame `df_diagnosticos`.
2. En la línea indicada, usa `df_diagnosticos["Diagnostico"].str.strip().str.lower()`
   para limpiar toda la columna y guarda el resultado sobreescribiendo la columna.
3. Imprime el DataFrame limpio con `print(df_diagnosticos)`.
4. 💎 **Bonus:** Usa `df_diagnosticos["Diagnostico"].value_counts()` para contar
   cuántas veces aparece cada diagnóstico ya estandarizado.

---

"""

import pandas as pd

datos_diag = {
    "ID":          [1, 2, 3, 4, 5, 6],
    "Paciente":    ["Ana", "Luis", "Carmen", "Jorge", "Sofía", "Pedro"],
    "Diagnostico": [" Gripe ", "GRIPE", "gripe  ", " COVID ", "Covid", "  COVID  "]
}


# Escribe aquí tu código para el Ejercicio 3.2:
df_diagnosticos = pd.DataFrame(datos_diag)
df_diagnosticos["Diagnostico"] = df_diagnosticos["Diagnostico"].str.strip().str.lower()
print(df_diagnosticos)
print("-"*40)
print("Conteo de diagnosticos")
print(df_diagnosticos["Diagnostico"].value_counts())

"""---

## Parte 4: Reto Práctico (El Especialista de Datos)

Llegó el momento de aplicar sus nuevos superpoderes. Imaginen que trabajan en la recepción de urgencias y les acaban de entregar la base de datos de los ingresos del día. Sin embargo, por las prisas, el archivo viene con pacientes duplicados y edades sin registrar.

Abre una nueva celda de código en tu Google Colab, copia este bloque para generar tus datos y resuelve el reto siguiendo las instrucciones:

"""

import pandas as pd

# Base de datos clínica con errores (Nulos y el paciente Luis duplicado)
datos = {
    "ID_Paciente": [101, 102, 103, 104, 102, 105],
    "Paciente":    ["Ana", "Luis", "Carlos", "Marta", "Luis", "Sofía"],
    "Edad":        [28, 34, None, 45, 34, None],
    "Diagnostico": ["Gripe", "COVID", "Asma", "Gripe", "COVID", "Migraña"]
}

# Creamos nuestro DataFrame
datos_clinicos = pd.DataFrame(datos)
print("--- DATOS ORIGINALES SUCIOS ---")
print(datos_clinicos)
print("\n-------------------------------\n")

# ¡Tu turno! Escribe tu código de limpieza debajo de esta línea:

print(datos_clinicos.isnull().sum())

datos_clinicos.duplicated().sum()

datos_clinicos = datos_clinicos.drop_duplicates()

datos_clinicos = datos_clinicos.fillna(0)

print(datos_clinicos)

"""**Tus instrucciones paso a paso:**

1. **Auditoría rápida:** Usa un `print` con el comando `datos_clinicos.isnull().sum()` para identificar exactamente cuántos valores nulos hay en tu tabla.
2. **Identifica duplicados:** Usa `datos_clinicos.duplicated().sum()` para confirmar cuántos hay antes de borrar.
3. **Elimina los clones:** Utiliza el método `.drop_duplicates()` para borrar el registro que está repetido. *(¡Recuerda sobrescribir tu variable o usar `inplace=True` para guardar el cambio!)*.
4. **Rellena los vacíos:** Usa `.fillna(0)` para reemplazar las edades faltantes con un `0` (indicando al sistema que la edad es desconocida temporalmente). Asegúrate de guardar este cambio también.
5. **El reporte final:** Utiliza `print(datos_clinicos)` para mostrar tu tabla totalmente limpia y estandarizada. (Si lo hiciste bien, solo deberían quedar 5 pacientes y ninguna celda dirá `NaN`).

---

### 🧠 Reflexión Clínica

Haz doble clic en esta celda y responde brevemente:

> *Rellenar los vacíos con `.fillna(0)` resolvió nuestro problema técnico, pero ¿por qué usar un `0` en la columna de 'Edad' podría causar problemas más adelante si queremos calcular el promedio de edad de nuestros pacientes?*

**(Escribe tu respuesta aquí):**

* ---

### 📋 Respuesta de Referencia — Reflexión Clínica (Guía del Instructor)

> *¿Por qué usar un `0` en la columna 'Edad' podría causar problemas más adelante?*

**Respuesta esperada:** Al rellenar con `0`, estamos diciéndole al sistema que esos
pacientes tienen **0 años de edad**. Si después calculamos el promedio de edad con
`df["Edad"].mean()`, el `0` jalará el promedio hacia abajo artificialmente, dándonos
un resultado estadísticamente incorrecto.

La solución profesional sería una de estas dos:
1. **Imputar con la mediana:** `datos_clinicos["Edad"].fillna(datos_clinicos["Edad"].median())` — mantiene el promedio real.
2. **Dejar el nulo:** Si la edad no es crítica para el análisis actual, es mejor tener `NaN` (reconocido por Pandas como "dato ausente") que un `0` que miente.

> 🎯 **Punto clave para el alumno:** Un `0` y un `NaN` son completamente distintos.
> `NaN` = "no sé el valor". `0` = "el valor ES cero". En la columna Edad, `0` es una mentira.

---

### 🔥 Reto Extra: Pipeline de Limpieza Completo

¡El hospital central te asignó una base de datos caótica para limpiarla antes de que el director la use en su presentación del lunes! El dataset tiene nulos, duplicados y texto inconsistente en la misma tabla.

**Tu pipeline de limpieza (en orden):**

1. **Auditoría:** Usa `df_hospital.info()` y `df_hospital.isnull().sum()` para diagnosticar.
2. **Estadísticas:** Usa `df_hospital.describe()` para revisar rangos de las columnas numéricas.
3. **Identifica duplicados:** Usa `df_hospital.duplicated().sum()` para contarlos.
4. **Elimina duplicados:** Usa `.drop_duplicates(inplace=True)`.
5. **Imputa edades:** Rellena los nulos de `"Edad"` con la **mediana**.
6. **Estandariza texto:** Limpia la columna `"Ciudad"` con `.str.strip().str.lower()`.
7. **Reporte final:** Imprime `df_hospital` limpio y verifica con `df_hospital.isnull().sum()`.

---
"""

import pandas as pd

# Dataset caótico del hospital
datos_hospital = {
    "ID":       [101, 102, 103, 104, 102, 105, 106],
    "Paciente": ["Ana García", "Luis Ramos", "Carmen Vega", "Jorge Díaz",
                 "Luis Ramos", "Sofía Luna", "Pedro Cruz"],
    "Edad":     [28, 35, None, 42, 35, None, 31],
    "Ciudad":   [" guadalajara", "MONTERREY", "guadalajara ", "  CDMX  ",
                 "MONTERREY", " cdmx", "Guadalajara "]
}
df_hospital = pd.DataFrame(datos_hospital)

print("--- DATOS ORIGINALES ---")
print(df_hospital)
print()

# Escribe aquí tu pipeline de limpieza completo: