# -*- coding: utf-8 -*-
"""Sesión 4: Primeros Pasos Propios en Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n8GmYqS3f8fbDnZrLdQqqc-Wih_hGJ0W

# Sesión 4: Primeros Pasos Propios en Colab

### Creando tu Cuaderno de Laboratorio (.ipynb)

A diferencia de leer un documento estático como un PDF, el formato **.ipynb** (*Interactive Python Notebook*) es un documento vivo. Pero para vivir la experiencia, primero necesitas saber cómo fabricar uno.

Dado que Colab es un servicio de Google, todos tus cuadernos vivirán de forma segura en tu cuenta de Google Drive.

**La ruta para crear un cuaderno nuevo es muy sencilla:**

1. Abre tu Google Drive en el navegador web.
2. Haz clic en el botón de **+ Nuevo** (arriba a la izquierda).
3. Ve hasta abajo en el menú a donde dice **Más**.
4. Selecciona **Google Colaboratory**.

Al hacer esto, se abrirá una pestaña nueva con un cuaderno totalmente en blanco. ¡Ese es tu nuevo dominio!

### El "Síndrome" del Archivo Sin Título

Por defecto, Colab nombra a tu nuevo archivo como `Untitled0.ipynb`. Uno de los peores hábitos es tener una carpeta llena de archivos sin nombre claro. Tu primera acción siempre debe ser ir a la esquina superior izquierda, hacer clic en el nombre y cambiarlo por algo descriptivo, como `Sesion4_MiPrimerProyecto.ipynb`.

---

### ⚠️ Advertencia Crucial: Lo Eterno vs. Lo Efímero

* **LO ETERNO (Tu Código y Texto):** Todo lo que escribas en las celdas se guarda de forma automática y **para siempre** en tu Google Drive.
* **LO EFÍMERO (Tus Datos Subidos):** Si subes un archivo de Excel al panel de la izquierda, ese archivo vive en la *memoria temporal*. **Si cierras la sesión o Colab se desconecta, tu archivo de datos se borrará** y tendrás que volver a subirlo la próxima vez.

---

### Ejercicio 1: El Ritual de Inicio

Es momento de que crees el lienzo en el que trabajarás el resto de esta sesión.

**Tu Tarea:**

1. Abre una nueva pestaña y entra a tu Google Drive.
2. Crea un nuevo cuaderno (`+ Nuevo` > `Más` > `Google Colaboratory`).
3. Cámbiale el nombre a: `Mi_Primer_Proyecto.ipynb`.
4. En la celda de código de abajo, escribe un mensaje de celebración.

---
"""

# Mi primera instrucción en mi propio cuaderno
print("¡Este es mi propio cuaderno y estoy listo para programar!")

"""---

## Parte 2: Dominando tu Laboratorio (Atajos y Formato)

Los expertos rara vez usan el ratón para todo; prefieren exprimir al máximo el teclado.

### ⌨️ Tus "Superpoderes": Atajos de Teclado Completos

Colab tiene dos **modos de trabajo**, igual que un editor de texto profesional:

* **Modo Comando** (celda azul/sin cursor parpadeando): navegas entre celdas
* **Modo Edición** (celda verde/con cursor parpadeando): escribes dentro de una celda
* Presiona `Esc` para pasar a Modo Comando. Presiona `Enter` para pasar a Modo Edición.

| Atajo | Acción | Modo |
|---|---|---|
| `Shift` + `Enter` | Ejecuta celda y pasa a la siguiente | Edición |
| `Ctrl` + `Enter` | Ejecuta celda y se queda en ella | Edición |
| `Ctrl` + `M` luego `B` | Inserta celda de código **abajo** (*Below*) | Comando |
| `Ctrl` + `M` luego `A` | Inserta celda de código **arriba** (*Above*) | Comando |
| `Ctrl` + `M` luego `D` | **Borra** la celda actual (*Delete*) | Comando |
| `Ctrl` + `M` luego `M` | Convierte celda a **Texto/Markdown** | Comando |
| `Ctrl` + `M` luego `Y` | Convierte celda a **Código** | Comando |
| `Ctrl` + `Z` | Deshacer el último cambio | Edición |
| `Ctrl` + `/` | Comenta/descomenta la línea seleccionada | Edición |
| `Tab` | Autocompletar nombre de variable o función | Edición |

> 💡 **Tip pro:** El atajo `Ctrl` + `/` es uno de los más útiles: selecciona varias líneas y las comenta todas de golpe — perfecto para desactivar código temporalmente sin borrarlo.

### ⚠️ El Botón de Pánico: Reiniciar el Entorno

Si tu código se vuelve un caos o la memoria se traba, ve al menú superior: **Entorno de ejecución > Reiniciar sesión**. Esto limpia la mente de la computadora sin borrar tus apuntes.

---

### 🎨 La Magia de Markdown — Guía Visual Completa

Markdown convierte texto plano en documentos con formato profesional. Aquí tienes todo lo que necesitas saber:

| Sintaxis que escribes | Resultado que ves |
|---|---|
| `# Título principal` | Título enorme (H1) |
| `## Subtítulo` | Título mediano (H2) |
| `### Sección` | Título pequeño (H3) |
| `**texto**` | **negrita** |
| `*texto*` | *cursiva* |
| `~~texto~~` | ~~tachado~~ |
| `` `código` `` | `código en línea` |
| `- elemento` | • lista con viñetas |
| `1. elemento` | 1. lista numerada |
| `> texto` | > cita destacada |
| `---` | Línea divisora horizontal |

> 💡 **Para crear una celda de texto:** Haz clic en **`+ Texto`** en el menú superior, o usa `Ctrl+M` luego `M` para convertir la celda actual.

---

### Ejercicio 2: Diseñando tu Bitácora

Usa el teclado para realizar lo siguiente:

1. Crea una celda de texto con un título principal: `# Mi Bitácora de Datos`.
2. Haz una lista de dos cosas que quieras aprender hoy.
3. Prueba al menos 3 tipos de formato diferentes (negrita, cursiva, lista).
4. Crea una celda de código debajo con esta operación:

---
"""

# Operación matemática combinada
(20 * 5) + 26

"""---

### 🔍 ¿Qué pasa cuando ejecutas una celda de código sin `print()`?

Observa que la celda anterior devuelve `126` sin necesidad de `print()`. En Python, la **última expresión** de una celda se muestra automáticamente como resultado. Esto es muy útil para explorar datos rápidamente:

```python
# Estas tres formas muestran resultados:
2 + 2          # → muestra: 4  (solo si es la última línea)
print(2 + 2)   # → muestra: 4  (siempre, en cualquier posición)
```

En ciencia de datos usarás mucho esta característica para ver tablas y gráficas sin necesidad de `print()`.

---

## Parte 3: Manejo de Archivos (La Alacena de Datos)

En el lado izquierdo verás el icono de una **carpeta**. Esa es tu "alacena". Google siempre nos deja una carpeta llamada `sample_data` con archivos de prueba para practicar.

### Comandos "Mágicos" (`!`)

Para hablar directamente con el sistema de la computadora usamos el signo `!`:

1. **`!ls`:** Lista los archivos disponibles en una carpeta.
2. **`!cat`:** Nos permite "espiar" el contenido de un archivo sin abrirlo.
3. **`!pwd`:** Muestra en qué carpeta estás trabajando en este momento.
4. **`!wc -l`:** Cuenta cuántas líneas (registros) tiene un archivo.

---

### Ejercicio 3: El Espía de Datos

Vamos a investigar qué hay dentro de los archivos de Google. Ejecuta las siguientes celdas en orden:

---
"""

# Listar archivos de muestra disponibles en Colab
!ls sample_data

# Leer el contenido del archivo de instrucciones
!cat sample_data/README.md

# ¿Cuántos registros tiene el dataset de California Housing?
print("📊 Conteo de líneas en los archivos disponibles:")
!wc -l sample_data/*.csv

"""---

### 📂 De los archivos a las tablas: `pd.read_csv()`

Hasta ahora exploramos los archivos como texto crudo con `!ls` y `!cat`. Pero los científicos de datos necesitamos cargarlos como **tablas de datos** para poder analizarlos. Para eso usamos `pd.read_csv()` — el comando más usado en todo el diplomado.

La anatomía del comando es muy simple:

```python
import pandas as pd

# Cargamos el archivo CSV como una tabla (DataFrame)
df = pd.read_csv('ruta/del/archivo.csv')
```

Vamos a cargar el dataset real de **California Housing** que viene incluido en Colab. Este dataset contiene información sobre precios de casas en California, USA — es uno de los más usados para enseñar ciencia de datos:

"""

import pandas as pd

# Cargamos el dataset de precios de viviendas en California
df_casas = pd.read_csv('sample_data/california_housing_test.csv')

# Ver las primeras 5 filas (como abrir el archivo en Excel)
print(f"✅ Archivo cargado correctamente.")
print(f"   Dimensiones: {df_casas.shape[0]:,} filas × {df_casas.shape[1]} columnas")
print(f"\n📋 Primeras 5 filas del dataset:")
df_casas.head()
df_casas.tail()

# ¿Cuáles son las columnas? ¿Qué tipo de datos tiene cada una?
print("🔍 Nombres de columnas y tipos de datos:")
print(df_casas.dtypes)

print(f"\n📊 Estadísticas descriptivas automáticas:")
df_casas.describe().round(2)

"""---

### 💡 La Solución a "Lo Efímero": Montar tu Google Drive

¿Recuerdas la advertencia del inicio sobre los archivos que se pierden? Existe una solución profesional: **montar tu Google Drive directamente dentro de Colab**. Esto significa que todos tus archivos en Drive quedan accesibles como si fueran carpetas normales — y **nunca se borran**.

El proceso solo requiere 2 líneas de código y **una vez que das permiso, tu Drive queda conectado**:

```python
from google.colab import drive
drive.mount('/content/drive')
```

Colab te pedirá que inicies sesión en tu cuenta de Google y des permiso. Después podrás leer tus archivos así:

```python
# Leer un archivo Excel directamente desde tu Drive
df = pd.read_csv('/content/drive/MyDrive/mi_carpeta/mis_datos.csv')
```

> ⚠️ **Nota:** En este notebook del curso no ejecutaremos el montado de Drive porque cada alumno tiene su propia cuenta. Pero en tus proyectos personales, **siempre monta tu Drive al inicio** para no perder tus datos.

---

## Parte 4: Reto de Consolidación: Tu Primer Reporte

Tu misión final es crear un mini-reporte combinando todo lo que aprendiste hoy:

1. **Texto:** Crea una celda de texto con título `# Mi Primer Reporte de Datos` y explica qué área te apasiona (salud, ingeniería, negocio, etc.).
2. **Atajos:** Usa `Ctrl+M` luego `B` para insertar una nueva celda de código — sin tocar el ratón.
3. **Cálculo:** Calcula cuántos datos tendrías si recolectas 1 dato por segundo durante un año completo.
4. **Formato:** En tu celda de texto usa al menos **negrita**, una *cursiva* y una lista.

---
"""

# ============================================================
# RETO FINAL: Calculando el volumen de datos en el tiempo
# ============================================================

# ¿Cuántos registros generaría un sensor según la frecuencia?
segundos_minuto = 60
minutos_hora    = 60
horas_dia       = 24
dias_ano        = 365

# Datos por hora
datos_por_hora = horas_dia * dias_ano

# Datos por minuto
datos_por_minuto = minutos_hora * horas_dia * dias_ano

# Datos por segundo
datos_por_segundo = segundos_minuto * minutos_hora * horas_dia * dias_ano

print("📈 Volumen de datos generados en 1 año según frecuencia:")
print(f"   1 dato/hora    → {datos_por_hora:>12,} registros al año")
print(f"   1 dato/minuto  → {datos_por_minuto:>12,} registros al año")
print(f"   1 dato/segundo → {datos_por_segundo:>12,} registros al año")
print(f"\n💡 Un solo sensor de frecuencia cardíaca (1 dato/seg)")
print(f"   genera {datos_por_segundo:,} registros al año.")
print(f"   ¡Eso es por qué necesitamos Python y no Excel!")
print("\n🎓 ¡Sesión 4 completada! Ya eres dueño de tu laboratorio Colab.")