# -*- coding: utf-8 -*-
"""Ejercicio Integrador: Sistema de Análisis de una Aerolínea — SkyData Airlines

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mwoQAluq8OtYUgq6v1mESrKsjpMKEDbn

# ✈️ Ejercicio Integrador: Sistema de Análisis de una Aerolínea — SkyData Airlines
### Diplomado en Ciencia de Datos — Sesiones 1 a 12

---

**Escenario:**
Eres el **Científico de Datos Junior** de *SkyData Airlines*, una aerolínea regional mexicana.
El Director de Operaciones necesita un sistema que:
1. Clasifique automáticamente el nivel de satisfacción de los pasajeros.
2. Detecte y reporte anomalías en los datos antes de analizarlos.
3. Calcule estadísticas de puntualidad y satisfacción para el reporte mensual.
4. Genere visualizaciones para la junta directiva.

---

| # | Sección | Temas cubiertos | Sesiones |
|---|---|---|---|
| 1 | Conceptos y formulación de preguntas | Flujo de trabajo, Target, Features | 1 y 2 |
| 2 | Variables y tipos de datos | str, int, float, bool, f-strings | 2, 5, 6 |
| 3 | Limpieza de strings y casting | .strip(), .replace(), int(), float() | 6 |
| 4 | Listas y operaciones | indexación, slicing, len, append, in | 2 y 7 |
| 5 | Diccionarios, tuplas y sets | Expediente, coordenadas, únicos | 7 |
| 6 | Control de flujo | if / elif / else | 7 y 8 |
| 7 | Bucles y funciones | for, while, def, return | 7 y 8 |
| 8 | Estadística manual | sum/len, sorted, max, min, round | **9** |
| 9 | Módulo statistics | mean, median, mode, stdev | **10** |
| 10 | Los 4 sospechosos | None, duplicados, inconsistencias, outliers | **11** |
| 11 | Detección de nulos y duplicados | for + if + is None + set | **12** |
| 12 | NumPy y Pandas | array, stats, DataFrame, groupby | 3 |
| 13 | Visualización | Matplotlib y Seaborn | 3 |
| 🏆 | Reto Final | Función integradora completa | 1–12 |

---
## 📌 Sección 1 — Conceptos y Formulación de Preguntas
*(Sesiones 1 y 2)*

El Director de Operaciones te presenta el problema:

> *"Hemos notado que muchos pasajeros no vuelven a comprar con nosotros después de su primer vuelo.
> No sabemos exactamente por qué, pero sospechamos que tiene que ver con los retrasos y el servicio a bordo."*

**Ejercicio 1.1 — Piensa como Científico de Datos**
Haz **doble clic** en esta celda y completa todos los espacios:

**Problema vago (original):** *(copia el texto del Director)*

**Traducción a pregunta de datos:** *(específica, medible, con Target y Features claros)*

**Tipo de análisis que usarías y por qué:**
- [ ] Descriptivo — *¿Qué pasó?*
- [ ] Diagnóstico — *¿Por qué pasó?*
- [ ] Predictivo — *¿Qué pasará?*
- [ ] Prescriptivo — *¿Qué debemos hacer?*

**Columna Objetivo (Target):** *(¿qué quieres predecir o clasificar?)*

**Pistas (Features) — mínimo 5 columnas que pedirías al área de sistemas:**
1.
2.
3.
4.
5.

**Tu rol en este proyecto:** *(Data Analyst / Data Scientist / Data Engineer — justifica)*

---
## 🐍 Sección 2 — Variables, Tipos de Datos y f-strings
*(Sesiones 2, 5 y 6)*

Registra los datos del primer pasajero que completó la encuesta de satisfacción.
"""

# ─────────────────────────────────────────────────────
# EJERCICIO 2.1 — Crea el perfil del pasajero con el tipo correcto
# ─────────────────────────────────────────────────────
# nombre_pasajero    → str   → "Gabriela Torres"
# numero_vuelo       → str   → "SK-471"
# calificacion       → int   → 7   (escala 1-10)
# retraso_minutos    → float → 23.5
# es_cliente_frecuente → bool → True
# destino            → str   → "Cancún"

nombre_pasajero      = ___
numero_vuelo         = ___
calificacion         = ___
retraso_minutos      = ___
es_cliente_frecuente = ___
destino              = ___

# ─────────────────────────────────────────────────────
# EJERCICIO 2.2 — Imprime el ticket de encuesta con f-strings
# Salida esperada:
#   ✈ Pasajero: Gabriela Torres | Vuelo: SK-471 | Destino: Cancún
#   Calificación: 7/10 | Retraso: 23.5 min | Cliente frecuente: True
# ─────────────────────────────────────────────────────
print(f"✈ Pasajero: {___} | Vuelo: {___} | Destino: {___}")
print(f"Calificación: {___}/10 | Retraso: {___} min | Cliente frecuente: {___}")

# ─────────────────────────────────────────────────────
# EJERCICIO 2.3 — Verifica los tipos con type()
# ─────────────────────────────────────────────────────
print("\nVerificación de tipos:")
print(f"  nombre_pasajero       → {type(nombre_pasajero)}")
print(f"  calificacion          → {___}")
print(f"  retraso_minutos       → {___}")
print(f"  es_cliente_frecuente  → {___}")

"""---
## 🧹 Sección 3 — Limpieza de Strings y Casting
*(Sesión 6)*

El sistema exportó los datos de las encuestas con errores de formato.
Necesitas limpiarlos antes de analizarlos.

"""

# Datos SUCIOS exportados por el sistema antiguo
nombre_sucio    = "  MARIA FERNANDEZ "   # espacios extra + todo en mayúsculas
ciudad_sucia    = "ciudad de mexico"     # todo en minúsculas
retraso_texto   = "18,5"                 # coma en lugar de punto decimal
asientos_texto  = "142"                  # número guardado como texto

# ─────────────────────────────────────────────────────
# EJERCICIO 3.1 — Limpia cada variable con métodos de strings
# Métodos disponibles: .strip()  .title()  .upper()  .lower()  .replace(v, n)
# ─────────────────────────────────────────────────────
nombre_limpio  = nombre_sucio.___().___()    # quita espacios + título
ciudad_limpia  = ciudad_sucia.___()          # cada palabra con mayúscula
retraso_limpio = retraso_texto.___(",",".")  # reemplaza coma por punto

# ─────────────────────────────────────────────────────
# EJERCICIO 3.2 — Casting: convierte textos a números para operar
# ─────────────────────────────────────────────────────
retraso_real  = ___(retraso_limpio)    # float
asientos_real = ___(asientos_texto)    # int

# Calcula el costo por minuto de retraso ($85 MXN por minuto de compensación)
costo_compensacion = retraso_real * 85
total_compensacion = costo_compensacion * asientos_real

print("=== Datos del Vuelo Limpiados ===")
print(f"  Pasajero   : {nombre_limpio}")
print(f"  Ciudad     : {ciudad_limpia}")
print(f"  Retraso    : {retraso_real} min")
print(f"  Asientos   : {asientos_real}")
print(f"  Costo/min  : $85.00 MXN × {asientos_real} pasajeros")
print(f"  Compensación total: ${total_compensacion:,.2f} MXN")

"""---
## 📋 Sección 4 — Listas y sus Operaciones
*(Sesiones 2 y 7)*

"""

# ─────────────────────────────────────────────────────
# EJERCICIO 4.1 — Define las listas del dataset
# ─────────────────────────────────────────────────────
columnas_dataset = ["pasajero", "vuelo", "destino", "calificacion",
                    "retraso_min", "es_frecuente", "clase", "repite_vuelo"]

calificaciones_semana = [8, 6, 9, 4, 7, 5, 10, 3, 8, 6]

# ─────────────────────────────────────────────────────
# EJERCICIO 4.2 — Opera con las listas
# ─────────────────────────────────────────────────────

# a) Total de columnas
print(f"Total columnas     : {___(columnas_dataset)}")

# b) Primera columna (índice 0)
print(f"Primera columna    : {columnas_dataset[___]}")

# c) Última columna (índice negativo)
print(f"Última columna     : {columnas_dataset[___]}")

# d) Solo las Features (todas menos la última — slicing)
solo_features = columnas_dataset[___]
print(f"Features           : {solo_features}")

# e) Agrega la columna "num_vuelos_previos"
columnas_dataset.___("num_vuelos_previos")
print(f"Dataset actualizado: {columnas_dataset}")

# f) ¿Está "calificacion" en el dataset?
if ___ in columnas_dataset:
    print("✅ 'calificacion' SÍ está en el dataset")

# g) Calificación máxima y mínima de la semana (sin importar las libreras)
print(f"\nCalif. máxima semana: {max(calificaciones_semana)}")
print(f"Calif. mínima semana: {min(calificaciones_semana)}")
print(f"Rango              : {max(calificaciones_semana) - min(calificaciones_semana)}")

"""---
## 🗂️ Sección 5 — Diccionarios, Tuplas y Sets
*(Sesión 7)*

"""

# ─────────────────────────────────────────────────────
# EJERCICIO 5.1 — Perfil del pasajero como Diccionario
# ─────────────────────────────────────────────────────
perfil_pasajero = {
    "nombre"         : ___,   # str   → "Carlos Mendoza"
    "vuelo"          : ___,   # str   → "SK-203"
    "calificacion"   : ___,   # int   → 4
    "retraso_min"    : ___,   # float → 87.0
    "es_frecuente"   : ___,   # bool  → True
    "repite_vuelo"   : ___,   # bool  → False
    "num_vuelos_prev": ___    # int   → 12
}

print("=== Perfil del Pasajero ===")
print(f"Nombre          : {perfil_pasajero[___]}")
print(f"Vuelo           : {perfil_pasajero['vuelo']}")
print(f"Calificación    : {perfil_pasajero[___]}/10")
print(f"Retraso         : {perfil_pasajero['retraso_min']} min")
print(f"Repetirá vuelo  : {perfil_pasajero[___]}")

# ─────────────────────────────────────────────────────
# EJERCICIO 5.2 — Tupla con datos fijos del aeropuerto
# ─────────────────────────────────────────────────────
info_aeropuerto = ("AICM", "Ciudad de México", 19.4361, -99.0719)  # nombre, ciudad, lat, lon

print(f"\nAeropuerto base : {info_aeropuerto[0]}, {info_aeropuerto[1]}")
print(f"Coordenadas     : {info_aeropuerto[2]}, {info_aeropuerto[3]}")

# ─────────────────────────────────────────────────────
# EJERCICIO 5.3 — Set para obtener destinos únicos
# ─────────────────────────────────────────────────────
todos_destinos = ["Cancún", "Monterrey", "Cancún", "Guadalajara",
                  "Cancún", "Monterrey", "Los Cabos", "Guadalajara",
                  "Los Cabos", "Cancún"]

destinos_unicos = ___(todos_destinos)

print(f"\nRegistros de destino  : {len(todos_destinos)}")
print(f"Destinos únicos       : {len(destinos_unicos)}")
print(f"Rutas operadas        : {destinos_unicos}")

"""---
## 🚦 Sección 6 — Control de Flujo: if / elif / else
*(Sesiones 7 y 8)*

El sistema necesita clasificar automáticamente el **nivel de satisfacción**
y la **acción de retención** para cada pasajero.

| Calificación | Nivel | Acción |
|---|---|---|
| ≥ 9 | 😊 PROMOTOR | Programa de referidos |
| 7 u 8 | 😐 NEUTRO | Email de agradecimiento |
| ≤ 6 | 😠 DETRACTOR | Llamada y cupón del 20% |

**Regla adicional:** Si el pasajero tuvo retraso > 60 min, baja automáticamente un nivel.

"""

# Datos del pasajero de la Sección 5
calif    = perfil_pasajero["calificacion"]   # 4
retraso  = perfil_pasajero["retraso_min"]    # 87.0
nombre_p = perfil_pasajero["nombre"]

# ─────────────────────────────────────────────────────
# EJERCICIO 6.1 — Clasifica por calificación
# ─────────────────────────────────────────────────────
if calif >= ___:
    nivel  = "😊 PROMOTOR"
    accion = "Programa de referidos"
elif calif >= ___:
    nivel  = "😐 NEUTRO"
    accion = "Email de agradecimiento"
else:
    nivel  = "😠 DETRACTOR"
    accion = "Llamada y cupón del 20%"

# ─────────────────────────────────────────────────────
# EJERCICIO 6.2 — Penalización por retraso mayor a 60 minutos
# ─────────────────────────────────────────────────────
if retraso > 60 and nivel != "😠 DETRACTOR":
    nivel  = "😠 DETRACTOR"
    accion = "Llamada urgente por retraso + cupón del 30%"

print(f"=== Clasificación NPS: {nombre_p} ===")
print(f"Calificación : {calif}/10")
print(f"Retraso      : {retraso} min")
print(f"Nivel NPS    : {nivel}")
print(f"Acción       : {accion}")

"""---
## 🔄 Sección 7 — Bucles for / while y Funciones
*(Sesiones 7 y 8)*

"""

# Base de datos del mes — lista de diccionarios
pasajeros_mes = [
    {"nombre":"Gabriela Torres",  "vuelo":"SK-471","calificacion":8, "retraso_min":23.5,"es_frecuente":True, "repite_vuelo":True},
    {"nombre":"Carlos Mendoza",   "vuelo":"SK-203","calificacion":4, "retraso_min":87.0,"es_frecuente":True, "repite_vuelo":False},
    {"nombre":"Sofía Ramírez",    "vuelo":"SK-115","calificacion":9, "retraso_min":5.0, "es_frecuente":False,"repite_vuelo":True},
    {"nombre":"Luis Herrera",     "vuelo":"SK-308","calificacion":6, "retraso_min":42.0,"es_frecuente":False,"repite_vuelo":False},
    {"nombre":"Andrea Vega",      "vuelo":"SK-471","calificacion":10,"retraso_min":0.0, "es_frecuente":True, "repite_vuelo":True},
    {"nombre":"Roberto Castillo", "vuelo":"SK-590","calificacion":3, "retraso_min":110.0,"es_frecuente":False,"repite_vuelo":False},
]

# ─────────────────────────────────────────────────────
# EJERCICIO 7.1 — Función reutilizable de clasificación NPS
# ─────────────────────────────────────────────────────
def clasificar_nps(calificacion, retraso_min):
    """Devuelve el nivel NPS considerando calificación y retraso."""
    if calificacion >= ___:
        nivel = "😊 PROMOTOR"
    elif calificacion >= ___:
        nivel = "😐 NEUTRO"
    else:
        nivel = "😠 DETRACTOR"

    if retraso_min > 60 and nivel != "😠 DETRACTOR":
        nivel = "😠 DETRACTOR"
    return nivel

# Prueba
print(clasificar_nps(10, 0.0))    # 😊 PROMOTOR
print(clasificar_nps(8, 110.0))   # 😠 DETRACTOR (penalización por retraso)
print(clasificar_nps(3, 20.0))    # 😠 DETRACTOR

# ─────────────────────────────────────────────────────
# EJERCICIO 7.2 — Bucle for: reporte NPS automático
# ─────────────────────────────────────────────────────
print("\n=== REPORTE NPS — SKYDATA AIRLINES ===")
print(f"{'#':<4}{'Pasajero':<22}{'Calif':>6}{'Retraso':>9}  Nivel")
print("-" * 60)

detractores = 0
for i, p in enumerate(pasajeros_mes, 1):
    nivel = clasificar_nps(p["calificacion"], p["retraso_min"])
    print(f"{i:<4}{p['nombre']:<22}{p['calificacion']:>5}/10 {p['retraso_min']:>6.1f}min  {nivel}")
    if "DETRACTOR" in nivel:
        detractores += 1

print("-" * 60)
print(f"Total pasajeros   : {len(pasajeros_mes)}")
print(f"Detractores       : {detractores}")
print(f"Tasa detractores  : {detractores/len(pasajeros_mes)*100:.1f}%")

# ─────────────────────────────────────────────────────
# EJERCICIO 7.3 — Bucle while: acumula pasajeros hasta llenar el avión
# ─────────────────────────────────────────────────────
print("\n=== Sistema de check-in (capacidad: 4 pasajeros) ===")
capacidad = 4
abordaron = 0

while abordaron < capacidad:
    abordaron += 1
    print(f"  Abordó pasajero {abordaron}: {pasajeros_mes[abordaron-1]['nombre']}")

print(f"Vuelo completo. {abordaron} pasajeros a bordo.")

"""---
## 📐 Sección 8 — Estadística Manual: Promedio, Mediana, Rango y Outliers
*(Sesión 9)*

Antes de usar librerías, calcula las estadísticas **desde cero con Python puro**,
tal como se aprendió en la Sesión 9 usando `sum`, `len`, `sorted`, `max` y `min`.

"""

# ─────────────────────────────────────────────────────
# EJERCICIO 8.1 — Promedio manual (sum / len)
# ─────────────────────────────────────────────────────
retrasos = [23.5, 87.0, 5.0, 42.0, 0.0, 110.0]

suma_retrasos   = ___(retrasos)            # suma todos los valores
cantidad        = ___(retrasos)            # cuenta los elementos
promedio_manual = suma_retrasos / cantidad # fórmula del promedio
promedio_reporte= round(promedio_manual, ___)  # redondea a 1 decimal

print(f"Suma total de retrasos   : {suma_retrasos} min")
print(f"Número de vuelos         : {cantidad}")
print(f"Promedio manual          : {promedio_reporte} min")

# ─────────────────────────────────────────────────────
# EJERCICIO 8.2 — Mediana manual (sorted + índice central)
# ─────────────────────────────────────────────────────
retrasos_ordenados = ___(retrasos)            # ordena de menor a mayor
indice_centro      = len(retrasos_ordenados) // ___  # índice del centro
mediana_manual     = retrasos_ordenados[___]

print(f"\nRetrasos ordenados       : {retrasos_ordenados}")
print(f"Índice central           : {indice_centro}")
print(f"Mediana                  : {mediana_manual} min")
print(f"¿Promedio ({promedio_reporte}) o Mediana ({mediana_manual}) representa mejor la realidad?")

# ─────────────────────────────────────────────────────
# EJERCICIO 8.3 — Rango y detección de outlier
# ─────────────────────────────────────────────────────
maximo = ___(retrasos)
minimo = ___(retrasos)
rango  = maximo - minimo

print(f"\nRetraso máximo           : {maximo} min")
print(f"Retraso mínimo           : {minimo} min")
print(f"Rango                    : {rango} min")

# ¿Hay un outlier? Si algún valor supera el promedio × 3, es sospechoso
umbral_outlier = promedio_reporte * 3
print(f"\nUmbral de outlier (×3)   : {umbral_outlier} min")
for r in retrasos:
    if r > umbral_outlier:
        print(f"⚠️  Posible outlier detectado: {r} min")

# ─────────────────────────────────────────────────────
# EJERCICIO 8.4 — Moda manual (diccionario contador)
# ─────────────────────────────────────────────────────
califs = [8, 4, 9, 6, 10, 3, 8, 9, 8, 6]
conteo = {}

for valor in califs:
    if valor in conteo:
        conteo[valor] += 1
    else:
        conteo[valor] = ___       # primera vez que aparece

moda_manual = max(conteo, key=conteo.get)
print(f"\nTabla de frecuencias     : {conteo}")
print(f"Moda (calificación más frecuente): {moda_manual} — aparece {conteo[moda_manual]} veces")

"""---
## 🧮 Sección 9 — Módulo `statistics`: Automatizando el Análisis
*(Sesión 10)*

Ahora usa la **caja de herramientas** `statistics` para automatizar los cálculos
que hiciste a mano en la Sección 8. Una función → un resultado.

"""

import statistics

retrasos  = [23.5, 87.0, 5.0, 42.0, 0.0, 110.0]
califs    = [8, 4, 9, 6, 10, 3, 8, 9, 8, 6]

# ─────────────────────────────────────────────────────
# EJERCICIO 9.1 — mean, median, mode con statistics
# ─────────────────────────────────────────────────────
prom_retraso = statistics.___(retrasos)
med_retraso  = statistics.___(retrasos)
moda_calif   = statistics.___(califs)

print("=== Análisis Estadístico — SkyData Airlines ===")
print(f"  Retraso promedio : {round(prom_retraso, 1)} min")
print(f"  Retraso mediana  : {med_retraso} min")
print(f"  Calificación moda: {moda_calif}/10")

# Compara promedio vs mediana — ¿cuál representa mejor la mayoría?
diferencia = abs(prom_retraso - med_retraso)
print(f"\n  Diferencia promedio-mediana: {round(diferencia,1)} min")
if diferencia > 15:
    print("  ⚠️  Diferencia alta — probable outlier. Usa la MEDIANA para reportar.")
else:
    print("  ✅ Diferencia baja — el promedio es confiable.")

# ─────────────────────────────────────────────────────
# EJERCICIO 9.2 — stdev: ¿qué tan consistentes son nuestros retrasos?
# ─────────────────────────────────────────────────────
desv_retraso = statistics.___(retrasos)
pct_variab   = round((desv_retraso / prom_retraso) * 100, 1)

print(f"\n  Desv. estándar   : {round(desv_retraso, 2)} min")
print(f"  % de variabilidad: {pct_variab}%")

if pct_variab > 20:
    print("  ⚠️  Alta variabilidad — los retrasos son muy INCONSISTENTES.")
else:
    print("  ✅ Baja variabilidad — los retrasos son predecibles.")

# ─────────────────────────────────────────────────────
# EJERCICIO 9.3 — multimode: ¿hay empate en la calificación más frecuente?
# ─────────────────────────────────────────────────────
todas_modas = statistics.___(califs)
print(f"\n  Todas las modas  : {todas_modas}")
if len(todas_modas) > 1:
    print("  ℹ️  Hay empate — usa multimode para no perder información.")

"""---
## 🔍 Sección 10 — Los 4 Sospechosos: Datos Sucios
*(Sesión 11)*

Antes de analizar, aplica el principio **GIGO** (*Garbage In, Garbage Out*).
Identifica y clasifica los errores en el dataset de encuestas exportado.

| Sospechoso | Símbolo en Python | Riesgo si se ignora |
|---|---|---|
| Valor Nulo | `None` | `TypeError` al calcular estadísticas |
| Duplicado | Fila repetida | Conteos y promedios inflados |
| Inconsistencia | Mismo dato, distinta escritura | Grupos divididos incorrectamente |
| Valor Atípico | Número imposible o extremo | Promedio completamente sesgado |

"""

# Dataset exportado del sistema de encuestas — TIENE TRAMPAS
encuestas_sucias = [
    {"id": 1,  "nombre": "Ana López",    "calificacion": 8,   "ciudad": "Cancún"},
    {"id": 2,  "nombre": "pedro ramos",  "calificacion": 5,   "ciudad": "cancun"},    # inconsistencia
    {"id": 3,  "nombre": "María García", "calificacion": None,"ciudad": "Monterrey"}, # valor nulo
    {"id": 4,  "nombre": "Luis Torres",  "calificacion": 850, "ciudad": "CDMX"},      # outlier (escala 1-10)
    {"id": 5,  "nombre": "Rosa Vega",    "calificacion": 7,   "ciudad": "Guadalajara"},
    {"id": 2,  "nombre": "pedro ramos",  "calificacion": 5,   "ciudad": "cancun"},    # duplicado
]

print("=== Dataset Crudo ===")
for e in encuestas_sucias:
    print(f"  {e}")

# ─────────────────────────────────────────────────────
# EJERCICIO 10.1 — ¿Qué pasa si ignoras los datos sucios?
# Intenta calcular el promedio — observa el error
# ─────────────────────────────────────────────────────
import statistics

try:
    calificaciones_sucias = [e["calificacion"] for e in encuestas_sucias]
    promedio_sucio = statistics.mean(calificaciones_sucias)
    print(f"\nPromedio (datos sucios): {promedio_sucio}")
except TypeError as e:
    print(f"\n❌ ERROR: {e}")
    print("   Python no puede calcular el promedio con valores None.")
    print("   Debes limpiar los datos ANTES de analizar. (Sesión 11)")

# ─────────────────────────────────────────────────────
# EJERCICIO 10.2 — Identifica manualmente los 4 sospechosos
# Completa las listas vacías con los hallazgos
# ─────────────────────────────────────────────────────
nulos          = []   # id de registros con calificacion == None
duplicados     = []   # id de registros que se repiten
outliers       = []   # id de registros con calificacion fuera de rango 1-10
inconsistencias= []   # id de registros con nombre o ciudad en minúsculas

for enc in encuestas_sucias:
    # Nulos
    if enc["calificacion"] is ___:
        nulos.append(enc["id"])
    # Outliers (calificación válida: 1-10)
    elif isinstance(enc["calificacion"], int) and (enc["calificacion"] < 1 or enc["calificacion"] > ___):
        outliers.append(enc["id"])
    # Inconsistencias (nombre o ciudad con minúsculas al inicio)
    if enc["nombre"][0].islower() or enc["ciudad"][0].islower():
        inconsistencias.append(enc["id"])

# Duplicados (ids que aparecen más de una vez)
ids = [e["id"] for e in encuestas_sucias]
duplicados = [i for i in set(ids) if ids.count(i) > ___]

print("\n=== Reporte de Sospechosos ===")
print(f"  Valores nulos      : {len(nulos)} → IDs {nulos}")
print(f"  Duplicados         : {len(duplicados)} → IDs {duplicados}")
print(f"  Outliers           : {len(outliers)} → IDs {outliers}")
print(f"  Inconsistencias    : {len(inconsistencias)} → IDs {inconsistencias}")

"""---
## 🛡️ Sección 11 — Detección Programática de Nulos y Duplicados
*(Sesión 12)*

Construye un **radar de auditoría reutilizable** usando lo que aprendiste en la Sesión 12:
`for` + `if` + `is None` + `set` para detectar errores automáticamente.

"""

# ─────────────────────────────────────────────────────
# EJERCICIO 11.1 — Radar de nulos con None in lista
# ─────────────────────────────────────────────────────
calificaciones_raw = [8, 5, None, 850, 7, 5]

# Primer chequeo rápido: ¿existe algún None?
if ___ in calificaciones_raw:
    print("🚨 ALERTA: Se detectaron valores nulos en calificaciones.")
else:
    print("✅ No hay valores nulos.")

# ─────────────────────────────────────────────────────
# EJERCICIO 11.2 — Radar avanzado: localiza la posición exacta del nulo
# ─────────────────────────────────────────────────────
print("\n=== Escáner de posiciones nulas ===")
total_nulos = 0

for posicion, valor in enumerate(calificaciones_raw):
    if valor ___ None:    # usa "is None" (forma correcta)
        print(f"  ⚠️  Nulo en posición {posicion}")
        total_nulos += 1

print(f"Total nulos encontrados: {total_nulos} de {len(calificaciones_raw)}")
print(f"% de fallas: {round(total_nulos/len(calificaciones_raw)*100, 1)}%")

# ─────────────────────────────────────────────────────
# EJERCICIO 11.3 — Radar de duplicados: lista de control + set
# ─────────────────────────────────────────────────────
ids_vuelos = ["SK-471", "SK-203", "SK-115", "SK-471", "SK-308", "SK-203"]

print("\n=== Escáner de IDs duplicados ===")
ids_vistos   = []
duplicados   = 0

for vid in ids_vuelos:
    if vid in ids_vistos:
        print(f"  🔁 Duplicado detectado: {vid}")
        duplicados += 1
    else:
        ids_vistos.append(vid)

print(f"Total duplicados   : {duplicados}")
print(f"IDs únicos (lista) : {ids_vistos}")

# Forma rápida con set
ids_set = list(set(ids_vuelos))
ids_set.sort()
print(f"IDs únicos (set)   : {ids_set}")

# ─────────────────────────────────────────────────────
# EJERCICIO 11.4 — Función de auditoría reutilizable
# ─────────────────────────────────────────────────────
def auditar_dataset(lista_datos, campo_id, campo_verificar):
    """
    Audita una lista de diccionarios.
    Reporta nulos en campo_verificar y duplicados en campo_id.
    """
    ids_vistos = []
    nulos      = 0
    duplicados = 0

    for registro in lista_datos:
        # Radar de nulos
        if registro[campo_verificar] ___ None:
            print(f"  🔴 Nulo: {registro['nombre']} — '{campo_verificar}' vacío")
            nulos += 1

        # Radar de duplicados
        pid = registro[campo_id]
        if pid in ids_vistos:
            print(f"  🔁 Duplicado: {campo_id}={pid} ({registro['nombre']})")
            duplicados += 1
        else:
            ids_vistos.append(pid)

    print("─" * 45)
    print(f"  Registros totales : {len(lista_datos)}")
    print(f"  Nulos encontrados : {nulos}")
    print(f"  Duplicados        : {duplicados}")
    print(f"  Registros limpios : {len(lista_datos) - duplicados} (estimado)")

print("\n=== Auditoría automática del dataset ===")
auditar_dataset(encuestas_sucias, campo_id="id", campo_verificar="calificacion")

"""---
## 🐼 Sección 12 — NumPy y Pandas: Análisis de Datos
*(Sesión 3)*

Con los datos ya identificados y limpios, aplica NumPy y Pandas.

"""

import numpy as np
import pandas as pd

# ─────────────────────────────────────────────────────
# EJERCICIO 12.1 — NumPy: estadísticas de retrasos
# ─────────────────────────────────────────────────────
retrasos_np = np.array([p["retraso_min"] for p in pasajeros_mes])

print("=== Estadísticas NumPy — Retrasos ===")
print(f"  Array         : {retrasos_np}")
print(f"  Promedio      : {np.mean(retrasos_np):.1f} min")
print(f"  Mediana       : {np.median(retrasos_np):.1f} min")
print(f"  Máximo        : {np.max(retrasos_np):.1f} min")
print(f"  Mínimo        : {np.min(retrasos_np):.1f} min")
print(f"  Desv. estándar: {np.std(retrasos_np):.2f} min")

# Filtrado booleano: vuelos con retraso > 60 min
vuelos_tardios = retrasos_np > ___
print(f"\n  Vuelos con retraso >60 min: {np.sum(vuelos_tardios)} de {len(retrasos_np)}")

# ─────────────────────────────────────────────────────
# EJERCICIO 12.2 — Pandas: crea el DataFrame
# ─────────────────────────────────────────────────────
df = pd.DataFrame(___)

print("\n=== DataFrame SkyData Airlines ===")
print(df[["nombre","vuelo","calificacion","retraso_min","es_frecuente"]])
print(f"\nDimensiones: {df.shape[0]} filas × {df.shape[1]} columnas")

# ─────────────────────────────────────────────────────
# EJERCICIO 12.3 — Agrega la columna NPS al DataFrame
# ─────────────────────────────────────────────────────
df["nivel_nps"] = df.apply(
    lambda row: clasificar_nps(row["calificacion"], row["retraso_min"]), axis=1
)

# ─────────────────────────────────────────────────────
# EJERCICIO 12.4 — Filtros y agregaciones
# ─────────────────────────────────────────────────────
# Filtra solo detractores
detractores_df = df[df["nivel_nps"].str.contains(___)]  # "DETRACTOR"
print(f"\n=== Detractores ({len(detractores_df)}) ===")
print(detractores_df[["nombre","calificacion","retraso_min","nivel_nps"]])

# Estadísticas por nivel NPS
print("\n=== Calificación promedio por nivel NPS ===")
print(df.groupby("nivel_nps")["calificacion"].mean().round(2))

# Estadísticas descriptivas
print("\n=== Resumen estadístico ===")
print(df[["calificacion","retraso_min"]].describe().round(2))

"""---
## 📊 Sección 13 — Visualización con Matplotlib y Seaborn
*(Sesión 3)*

Genera las 3 gráficas para la presentación de la junta directiva.

"""

import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="whitegrid", palette="husl")
fig, axes = plt.subplots(1, 3, figsize=(17, 5))

# ── Gráfica 1: Calificación por pasajero (barras + línea del promedio) ──
colores_nps = []
for _, row in df.iterrows():
    if "PROMOTOR"  in row["nivel_nps"]: colores_nps.append("#2ecc71")
    elif "NEUTRO"  in row["nivel_nps"]: colores_nps.append("#f39c12")
    else:                               colores_nps.append("#e74c3c")

axes[0].bar(df["nombre"].str.split().str[0], df["calificacion"],
            color=colores_nps, edgecolor="white")
axes[0].axhline(df["calificacion"].mean(), color="navy", linestyle="--", linewidth=2,
                label=f"Promedio: {df['calificacion'].mean():.1f}")
axes[0].set_title("Calificación por Pasajero\n🟢PROMOTOR 🟡NEUTRO 🔴DETRACTOR",
                  fontsize=11, fontweight="bold")
axes[0].set_ylabel("Calificación (1-10)")
axes[0].set_ylim(0, 11)
axes[0].legend(fontsize=9)
axes[0].tick_params(axis="x", rotation=20)

# ── Gráfica 2: Retraso vs Calificación (dispersión) ──────────────────
for _, row in df.iterrows():
    if   "PROMOTOR"  in row["nivel_nps"]: c = "#2ecc71"
    elif "NEUTRO"    in row["nivel_nps"]: c = "#f39c12"
    else:                                  c = "#e74c3c"
    axes[1].scatter(row["retraso_min"], row["calificacion"],
                    color=c, s=120, edgecolors="white", linewidths=1.5)

axes[1].axvline(60, color="red",  linestyle="--", alpha=0.6, label="Umbral 60 min")
axes[1].axhline(7,  color="gray", linestyle="--", alpha=0.6, label="Umbral NPS 7")
axes[1].set_title("Retraso vs Calificación", fontsize=12, fontweight="bold")
axes[1].set_xlabel("Retraso (min)")
axes[1].set_ylabel("Calificación (1-10)")
axes[1].legend(fontsize=9)

# ── Gráfica 3: Distribución del nivel NPS (pastel) ───────────────────
conteo_nps = df["nivel_nps"].value_counts()
colores_p = ["#2ecc71" if "PROMOTOR" in x else "#f39c12" if "NEUTRO" in x else "#e74c3c"
             for x in conteo_nps.index]
axes[2].pie(conteo_nps, labels=conteo_nps.index, colors=colores_p,
            autopct="%1.1f%%", startangle=90,
            wedgeprops={"edgecolor":"white","linewidth":2})
axes[2].set_title("Distribución NPS", fontsize=12, fontweight="bold")

plt.suptitle("📊 Reporte Mensual — SkyData Airlines", fontsize=15, fontweight="bold", y=1.02)
plt.tight_layout()
plt.savefig("reporte_skydata.png", dpi=150, bbox_inches="tight")
plt.show()
print("✅ Gráfica guardada como reporte_skydata.png")

"""---
## 🏆 Reto Final — Sistema Integrador Completo
*(Sesiones 1–12)*

Completa la función `sistema_skydata()` que integra las 12 sesiones:
auditoría de datos, estadísticas completas y reporte ejecutivo final.

"""

def sistema_skydata(lista_pasajeros):
    """
    Sistema integrador completo para SkyData Airlines.
    Cubre sesiones 1-12 del Diplomado de Ciencia de Datos.
    """
    import statistics, numpy as np

    print("\n" + "="*60)
    print("   🛡️  FASE 1 — AUDITORÍA DE DATOS (S11 y S12)")
    print("="*60)

    # ── Detección de nulos y duplicados ──────────────────────
    ids_vistos, nulos, duplicados_cnt = [], 0, 0
    for p in lista_pasajeros:
        if p["calificacion"] ___ None:
            print(f"  🔴 Nulo: {p['nombre']} — calificación faltante")
            nulos += 1
        pid = p["vuelo"]
        if pid in ids_vistos:
            print(f"  🔁 Duplicado: vuelo {pid} ({p['nombre']})")
            duplicados_cnt += 1
        else:
            ids_vistos.append(pid)

    print(f"  Nulos: {nulos} | Duplicados: {duplicados_cnt}")

    print("\n" + "="*60)
    print("   📐  FASE 2 — ESTADÍSTICA (S9 y S10)")
    print("="*60)

    # ── Filtra solo datos válidos ─────────────────────────────
    validos = [p for p in lista_pasajeros if p["calificacion"] is not None]
    califs  = [p["calificacion"] for p in validos]
    retraso = [p["retraso_min"]  for p in validos]

    # Estadística manual (S9)
    prom_manual = round(sum(califs) / len(califs), 2)
    sorted_r    = sorted(retraso)
    mediana_man = sorted_r[len(sorted_r) // ___]

    # Módulo statistics (S10)
    prom_auto = statistics.___(califs)
    desv_auto = statistics.___(retraso)
    moda_auto = statistics.___(califs)

    print(f"  Promedio califs (manual)  : {prom_manual}")
    print(f"  Promedio califs (auto)    : {round(prom_auto, 2)}")
    print(f"  Mediana retrasos          : {mediana_man} min")
    print(f"  Desv. estándar retrasos   : {round(desv_auto, 2)} min")
    print(f"  Moda calificaciones       : {moda_auto}/10")

    print("\n" + "="*60)
    print("   🚦  FASE 3 — CLASIFICACIÓN NPS (S6, S7 y S8)")
    print("="*60)

    detractores, promotores = 0, 0
    for p in validos:
        nivel = clasificar_nps(p["calificacion"], p["retraso_min"])
        print(f"  {p['nombre']:<22} → {nivel}")
        if "DETRACTOR" in nivel: detractores += 1
        if "PROMOTOR"  in nivel: promotores  += 1

    print("\n" + "="*60)
    print("   📋  RESUMEN EJECUTIVO (f-strings)")
    print("="*60)
    tasa_ret = sum(1 for p in validos if p["repite_vuelo"]) / len(validos) * 100
    print(f"  Total pasajeros   : {len(lista_pasajeros)}")
    print(f"  Datos válidos     : {len(validos)}")
    print(f"  Promotores        : {promotores}")
    print(f"  Detractores       : {detractores}")
    print(f"  Tasa de retención : {tasa_ret:.1f}%")
    print(f"  Retraso promedio  : {round(prom_auto,1)} min")
    print("="*60)

# ── Ejecuta el sistema ────────────────────────────────────
sistema_skydata(pasajeros_mes)