# -*- coding: utf-8 -*-
"""Ejercicio_Clinica_San_Rafael

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gJa44q0Qb7dw_EINTPXBL5UfpBRqLhPG

# Ejercicio
## Sistema de Registro de Pacientes: Clínica San Rafael

---

Imagina que eres el **Analista de Datos** de la Clínica San Rafael. El director médico acaba de darte acceso al sistema de registro de pacientes del último trimestre. El problema: el sistema fue migrado desde papel a digital y **nadie revisó la calidad de los datos antes de importarlos**.

Tu misión, si decides aceptarla:

1. **Auditar** los datos como un detective 🔍
2. **Calcular estadísticas** manualmente y con `statistics` 📊
3. **Identificar los 4 sospechosos** de datos sucios 🚨
4. **Escanear nulos y duplicados** con código  🛡️
5. **Redactar un reporte ejecutivo** para el director médico 📋

---

---

## 📂 El Dataset: Registros del Último Trimestre

Antes de comenzar cualquier análisis, siempre **primero observamos los datos en crudo**. Ejecuta la siguiente celda para cargar el dataset oficial de la Clínica San Rafael y ver exactamente lo que recibiste.
"""

# ════════════════════════════════════════════════
# DATASET OFICIAL — CLÍNICA SAN RAFAEL
# 30 registros de pacientes del último trimestre
# ════════════════════════════════════════════════

pacientes = [
    {"id": 1001, "nombre": "Ana Torres",       "edad": 34, "ciudad": "CDMX",              "diagnostico": "Hipertensión",  "tension": 140, "glucosa": 95.0,  "colesterol": 185, "dias_hosp": 3},
    {"id": 1002, "nombre": "Luis Mendoza",     "edad": 28, "ciudad": "Guadalajara",        "diagnostico": "Gripe",         "tension": 118, "glucosa": 88.5,  "colesterol": 172, "dias_hosp": 1},
    {"id": 1003, "nombre": "Carmen Ruiz",      "edad": 45, "ciudad": "Ciudad de México",   "diagnostico": "Diabetes",      "tension": 135, "glucosa": None,  "colesterol": 210, "dias_hosp": 5},
    {"id": 1004, "nombre": "jorge perez",      "edad": 52, "ciudad": "MTY",                "diagnostico": "Migraña",       "tension": 120, "glucosa": 92.0,  "colesterol": 195, "dias_hosp": 2},
    {"id": 1005, "nombre": "Sofía Gómez",      "edad": 29, "ciudad": "Monterrey",          "diagnostico": "Gripe",         "tension": 112, "glucosa": 85.0,  "colesterol": 168, "dias_hosp": 1},
    {"id": 1006, "nombre": "Roberto Castillo", "edad": 850, "ciudad": "Puebla",            "diagnostico": "Hipertensión",  "tension": 155, "glucosa": 105.0, "colesterol": 230, "dias_hosp": 4},
    {"id": 1007, "nombre": "María López",      "edad": 41, "ciudad": "CDMX",              "diagnostico": "Diabetes",      "tension": 130, "glucosa": 112.0, "colesterol": 245, "dias_hosp": 6},
    {"id": 1008, "nombre": "Carlos Vega",      "edad": 37, "ciudad": "guadalajara",        "diagnostico": "Migraña",       "tension": 118, "glucosa": 90.0,  "colesterol": 188, "dias_hosp": 2},
    {"id": 1009, "nombre": "Patricia Núñez",   "edad": 60, "ciudad": "Monterrey",          "diagnostico": "Artritis",      "tension": 145, "glucosa": 98.0,  "colesterol": 220, "dias_hosp": 7},
    {"id": 1010, "nombre": "Fernando Díaz",    "edad": 33, "ciudad": "Puebla",             "diagnostico": "Gripe",         "tension": 115, "glucosa": None,  "colesterol": 175, "dias_hosp": 1},
    {"id": 1004, "nombre": "jorge perez",      "edad": 52, "ciudad": "MTY",                "diagnostico": "Migraña",       "tension": 120, "glucosa": 92.0,  "colesterol": 195, "dias_hosp": 2},
    {"id": 1011, "nombre": "Valeria Moreno",   "edad": 25, "ciudad": "Ciudad de México",   "diagnostico": "Gripe",         "tension": 110, "glucosa": 82.0,  "colesterol": 162, "dias_hosp": 1},
    {"id": 1012, "nombre": "Héctor Ramírez",   "edad": 48, "ciudad": "CDMX",              "diagnostico": "Hipertensión",  "tension": 150, "glucosa": 101.0, "colesterol": 238, "dias_hosp": 4},
    {"id": 1013, "nombre": "Gabriela Soto",    "edad": 31, "ciudad": "Monterrey",          "diagnostico": "Ansiedad",      "tension": 108, "glucosa": 87.0,  "colesterol": 170, "dias_hosp": 2},
    {"id": 1014, "nombre": "Andrés Flores",    "edad": None, "ciudad": "Guadalajara",      "diagnostico": "Diabetes",      "tension": 128, "glucosa": 118.0, "colesterol": 252, "dias_hosp": 5},
    {"id": 1015, "nombre": "Isabel Castro",    "edad": 55, "ciudad": "Puebla",             "diagnostico": "Artritis",      "tension": 138, "glucosa": 96.0,  "colesterol": 215, "dias_hosp": 6},
    {"id": 1016, "nombre": "Miguel Ángel Ríos","edad": 43, "ciudad": "GDL",                "diagnostico": "Hipertensión",  "tension": 148, "glucosa": 103.0, "colesterol": 228, "dias_hosp": 3},
    {"id": 1017, "nombre": "Laura Jiménez",    "edad": 27, "ciudad": "CDMX",              "diagnostico": "Gripe",         "tension": 112, "glucosa": 84.0,  "colesterol": 165, "dias_hosp": 1},
    {"id": 1018, "nombre": "David Herrera",    "edad": 38, "ciudad": "Monterrey",          "diagnostico": "Migraña",       "tension": 122, "glucosa": 91.0,  "colesterol": 190, "dias_hosp": 2},
    {"id": 1019, "nombre": "Elena Vargas",     "edad": 50, "ciudad": "Ciudad de México",   "diagnostico": "Diabetes",      "tension": 133, "glucosa": None,  "colesterol": 242, "dias_hosp": 5},
    {"id": 1020, "nombre": "Raúl Gutiérrez",   "edad": 44, "ciudad": "Puebla",             "diagnostico": "Hipertensión",  "tension": 142, "glucosa": 99.0,  "colesterol": 218, "dias_hosp": 3},
    {"id": 1007, "nombre": "María López",      "edad": 41, "ciudad": "CDMX",              "diagnostico": "Diabetes",      "tension": 130, "glucosa": 112.0, "colesterol": 245, "dias_hosp": 6},
    {"id": 1021, "nombre": "Natalia Reyes",    "edad": 36, "ciudad": "Guadalajara",        "diagnostico": "Ansiedad",      "tension": 116, "glucosa": 86.0,  "colesterol": 174, "dias_hosp": 2},
    {"id": 1022, "nombre": "Sergio Morales",   "edad": 62, "ciudad": "MTY",                "diagnostico": "Artritis",      "tension": 152, "glucosa": 107.0, "colesterol": 235, "dias_hosp": 8},
    {"id": 1023, "nombre": "Diana Mendoza",    "edad": 30, "ciudad": "CDMX",              "diagnostico": "Gripe",         "tension": 114, "glucosa": 83.0,  "colesterol": 163, "dias_hosp": 1},
    {"id": 1024, "nombre": "Ernesto Figueroa", "edad": 47, "ciudad": "monterrey",          "diagnostico": "Hipertensión",  "tension": 146, "glucosa": 102.0, "colesterol": 222, "dias_hosp": 4},
    {"id": 1025, "nombre": "Cecilia Herrera",  "edad": 58, "ciudad": "Puebla",             "diagnostico": "Diabetes",      "tension": 136, "glucosa": None,  "colesterol": 248, "dias_hosp": 6},
    {"id": 1026, "nombre": "Tomás Navarro",    "edad": 22, "ciudad": "Guadalajara",        "diagnostico": "Gripe",         "tension": 108, "glucosa": 80.0,  "colesterol": 158, "dias_hosp": 1},
    {"id": 1027, "nombre": "Lucía Peña",       "edad": 39, "ciudad": "Ciudad de México",   "diagnostico": "Migraña",       "tension": 124, "glucosa": 93.0,  "colesterol": 192, "dias_hosp": 2},
    {"id": 1028, "nombre": "Osvaldo Bravo",    "edad": 53, "ciudad": "CDMX",              "diagnostico": "Artritis",      "tension": 144, "glucosa": 100.0, "colesterol": 212, "dias_hosp": 5},
]

print(f"{'ID':<6} {'Nombre':<22} {'Edad':<6} {'Ciudad':<20} {'Diagnóstico':<16} {'Glucosa'}")
print("─" * 85)
for p in pacientes:
    edad_str  = str(p["edad"])  if p["edad"]    is not None else "❌ NULO"
    gluc_str  = str(p["glucosa"]) if p["glucosa"] is not None else "❌ NULO"
    print(f"{p['id']:<6} {p['nombre']:<22} {edad_str:<6} {p['ciudad']:<20} {p['diagnostico']:<16} {gluc_str}")

print()
print(f"📦 Total de registros cargados: {len(pacientes)}")

"""---

## Parte 1 — Gimnasio Mental: El Detective a Simple Vista 🔍
### (Los 4 Sospechosos)

Antes de escribir una sola línea de código, un buen Científico de Datos entrena su **ojo clínico**. Observa el listado impreso arriba con atención.

### Ejercicio 1.1 — Clasificación Visual

Revisa el output del dataset y responde en la celda de texto siguiente:

**Pregunta 1:** ¿Cuántos tipos de errores puedes identificar a simple vista? Clasifica cada uno según los **4 sospechosos** (Nulo, Duplicado, Inconsistencia, Valor Atípico) y da al menos un ejemplo de cada tipo con el nombre o ID del paciente.

**Pregunta 2:** El campo `ciudad` tiene un problema específico. ¿Cuál es? ¿Cuántas variantes del mismo lugar puedes encontrar?

**Pregunta 3:** ¿Qué pasaría si intentáramos calcular el promedio de edades incluyendo al paciente 1006? ¿Estaría sesgado hacia arriba o hacia abajo?

### ✏️ Responde aquí (haz doble clic para editar):

**Pregunta 1 — Los 4 Sospechosos:**

| Sospechoso | ID / Nombre del paciente | Descripción del error |
|---|---|---|
| Valor Nulo | *escribe aquí* | *escribe aquí* |
| Duplicado | *escribe aquí* | *escribe aquí* |
| Inconsistencia | *escribe aquí* | *escribe aquí* |
| Valor Atípico | *escribe aquí* | *escribe aquí* |

**Pregunta 2 — Ciudades:**

*Escribe aquí cuántas variantes encontraste y cuáles son...*

**Pregunta 3 — Impacto del Outlier:**

*Escribe aquí tu análisis...*

---

## Parte 2 — Estadística Manual con Python Puro 📐
### ( sum, len, sorted, max, min, round)

En esta parte calcularás las estadísticas de los datos **limpios** (solo los registros válidos, sin nulos ni outliers) usando únicamente las herramientas de Python puro que aprendiste en la Sesión 9. **No uses `import statistics` aquí.**

---

### Ejercicio 2.1 — Preparando los Datos

Primero necesitamos extraer solo los valores válidos. Crea listas limpias para trabajar.
"""

# ─────────────────────────────────────────────────────────────
# PASO 1: Extrae las edades válidas (sin None y sin el outlier 850)
# ─────────────────────────────────────────────────────────────
# Recuerda: usa un for + if para filtrar
# Condición: la edad no debe ser None Y debe ser menor a 120

edades_validas = []

# Escribe aquí tu código para el filtro:


print(f"Edades válidas extraídas: {edades_validas}")
print(f"Total de edades válidas: {len(edades_validas)}")

# ─────────────────────────────────────────────────────────────
# PASO 2: Extrae los niveles de glucosa válidos (sin None)
# ─────────────────────────────────────────────────────────────
glucosa_valida = []

# Escribe aquí tu código:


print(f"Glucosa válida extraída: {glucosa_valida}")
print(f"Total de registros con glucosa: {len(glucosa_valida)}")

# ─────────────────────────────────────────────────────────────
# PASO 3: Extrae los días de hospitalización (todos son válidos)
# ─────────────────────────────────────────────────────────────
# Crea una lista con todos los valores de "dias_hosp"
# Usa for + .append() para construirla

dias_hospitalizacion = []

# Escribe aquí tu código:


print(f"Días de hospitalización: {dias_hospitalizacion}")

"""---

### Ejercicio 2.2 — Promedio, Mediana y Rango (Manual)

Usa **solo** `sum()`, `len()`, `sorted()`, `max()`, `min()` y `round()`.

"""

# ─────────────────────────────────────────────────────────────
# ANÁLISIS DE EDADES (Python Puro)
# ─────────────────────────────────────────────────────────────

# 1. Promedio de edades (sum / len), redondeado a 1 decimal
promedio_edad = ...   # ← escribe tu fórmula aquí

# 2. Mediana de edades (sorted → índice del centro)
edades_ordenadas = ...
indice_centro    = ...
mediana_edad     = ...

# 3. Rango de edades (max - min)
edad_max   = ...
edad_min   = ...
rango_edad = ...

# 4. Imprime el reporte con f-strings
print("📋 REPORTE DE EDADES — Clínica San Rafael")
print("─" * 45)
print(f"  Promedio : {promedio_edad} años")
print(f"  Mediana  : {mediana_edad} años")
print(f"  Mínima   : {edad_min} años")
print(f"  Máxima   : {edad_max} años")
print(f"  Rango    : {rango_edad} años")

# ─────────────────────────────────────────────────────────────
# ANÁLISIS DE DÍAS DE HOSPITALIZACIÓN (Python Puro)
# ─────────────────────────────────────────────────────────────

# Calcula: promedio, mediana, mínimo, máximo y rango
# Redondea el promedio a 2 decimales

# Escribe aquí tu código completo:


# Al final imprime un reporte similar al de edades

"""---

### Ejercicio 2.3 — Moda Manual (diccionario contador)

Encuentra el **diagnóstico más frecuente** usando un diccionario como contador.

"""

# ─────────────────────────────────────────────────────────────
# MODA DEL DIAGNÓSTICO (diccionario contador)
# ─────────────────────────────────────────────────────────────
# Nota: primero elimina los duplicados del dataset para no contar
# el mismo paciente dos veces. Puedes usar un set de IDs ya vistos.

ids_vistos    = []
diagnosticos  = []

for p in pacientes:
    if p["id"] not in ids_vistos:
        ids_vistos.append(p["id"])
        diagnosticos.append(p["diagnostico"])

# Ahora construye el diccionario contador:
conteo_diagnosticos = {}

# Escribe aquí el for que llena el diccionario:


# Encuentra la moda usando max(..., key=...) :
diagnostico_mas_frecuente = ...

print("📊 Tabla de frecuencias de diagnósticos:")
for diag, freq in conteo_diagnosticos.items():
    barra = "█" * freq
    print(f"  {diag:<16} {barra} ({freq})")

print()
print(f"🏆 Diagnóstico más frecuente: {diagnostico_mas_frecuente}")
print(f"   Apareció {conteo_diagnosticos[diagnostico_mas_frecuente]} veces")

"""---

## Parte 3 — Estadística Automatizada 🤖
### (S10 — import statistics)

Ahora repetirás el análisis anterior pero usando el módulo `statistics`. Compara los resultados con los que obtuviste en la Parte 2 — deben ser **exactamente iguales**.

Además, calcularás la **desviación estándar** (`stdev`) para evaluar la consistencia de los datos.

---

### Ejercicio 3.1 — El Reporte Clínico Completo

"""

import statistics

# ─────────────────────────────────────────────────────────────
# REPORTE COMPLETO DE EDADES (con statistics)
# ─────────────────────────────────────────────────────────────
# Usa las listas que ya creaste: edades_validas, glucosa_valida

# 1. Medidas de tendencia central
promedio_edad_auto  = statistics.mean(edades_validas)
mediana_edad_auto   = statistics.median(edades_validas)
moda_edad_auto      = statistics.multimode(edades_validas)   # puede haber empate

# 2. Medida de dispersión
desv_edad = round(statistics.stdev(edades_validas), 2)

# 3. Porcentaje de variabilidad
variabilidad_edad = round((desv_edad / promedio_edad_auto) * 100, 1)

print("📋 REPORTE CLÍNICO COMPLETO — Edades")
print("─" * 50)
print(f"  Media    : {round(promedio_edad_auto, 1)} años")
print(f"  Mediana  : {mediana_edad_auto} años")
print(f"  Moda(s)  : {moda_edad_auto} años")
print(f"  Desv. Est: {desv_edad} años")
print(f"  Variab.  : {variabilidad_edad}%")
print()
if variabilidad_edad > 20:
    print("⚠️  Alta variabilidad: el promedio solo debe reportarse junto a la mediana.")
else:
    print("✅  Variabilidad aceptable: el promedio es representativo.")

# ─────────────────────────────────────────────────────────────
# REPORTE COMPLETO DE GLUCOSA (con statistics)
# ─────────────────────────────────────────────────────────────
# Calcula mean, median, stdev y % de variabilidad para glucosa_valida
# Imprime el reporte con el mismo formato del bloque anterior

# Escribe aquí tu código:

# ─────────────────────────────────────────────────────────────
# COMPARATIVA: ¿QUÉ PASA SI INCLUIMOS EL OUTLIER DE EDAD = 850?
# ─────────────────────────────────────────────────────────────
# Extrae TODAS las edades no nulas (incluyendo el 850 del paciente 1006)
import statistics

edades_con_outlier = [p["edad"] for p in pacientes if p["edad"] is not None]
# Eliminar duplicados de IDs primero
ids_unicos_set = []
edades_sin_dup  = []
for p in pacientes:
    if p["id"] not in ids_unicos_set and p["edad"] is not None:
        ids_unicos_set.append(p["id"])
        edades_sin_dup.append(p["edad"])

# ¿Incluye el 850?
edades_sin_dup_con_outlier = edades_sin_dup.copy()

# Calcula promedio y mediana en ambos escenarios
prom_limpio    = round(statistics.mean(edades_validas), 1)
prom_con_outl  = round(statistics.mean(edades_sin_dup_con_outlier), 1)
med_limpio     = statistics.median(edades_validas)
med_con_outl   = statistics.median(edades_sin_dup_con_outlier)

print("📊 IMPACTO DEL OUTLIER (edad = 850 años)")
print("─" * 55)
print(f"{'Escenario':<28} {'Promedio':>10} {'Mediana':>10}")
print("─" * 55)
print(f"{'Sin outlier (datos limpios)':<28} {prom_limpio:>10} {med_limpio:>10}")
print(f"{'Con outlier (paciente 1006)':<28} {prom_con_outl:>10} {med_con_outl:>10}")
print()
diferencia = prom_con_outl - prom_limpio
print(f"⚠️  El outlier infla el promedio +{diferencia:.1f} años")
print(f"✅  La mediana cambia solo {abs(med_con_outl - med_limpio):.1f} años → es más robusta")

"""---

### 🧠 Reflexión 3.1 (haz doble clic para editar)

Basándote en los reportes anteriores, responde:

1. ¿La desviación estándar de las edades supera el 20% del promedio? ¿Qué significa eso para el reporte del director?

2. Compara el promedio y la mediana de glucosa. ¿Son muy diferentes? ¿Hay algún outlier en los niveles de glucosa?

3. ¿Por qué la mediana cambia muy poco al incluir el outlier de 850 años, mientras el promedio se dispara?

*Escribe tu análisis aquí...*

---

## Parte 4 — Auditoría Programática de Datos 🚨
### (Nulos, Duplicados, Inconsistencias, Outliers)

Ahora construirás un **sistema de auditoría automático** que detecte los 4 sospechosos usando código. Así es como trabajan los analistas en la vida real con datasets grandes.

---

### Ejercicio 4.1 — Radar de Valores Nulos
"""

# ─────────────────────────────────────────────────────────────
# RADAR 1: DETECTOR DE NULOS por campo
# ─────────────────────────────────────────────────────────────
# Revisa los campos: "edad" y "glucosa"
# Para cada campo: detecta en qué posición está el nulo,
# el nombre del paciente afectado, y el total de nulos

campos_a_revisar = ["edad", "glucosa"]

print("🔍 AUDITORÍA — RADAR DE VALORES NULOS")
print("═" * 55)

for campo in campos_a_revisar:
    total_nulos = 0
    print(f"
📌 Campo: '{campo}'")
    print("─" * 40)

    for posicion, paciente in enumerate(pacientes):
        # Escribe aquí la condición is None:
        if paciente[campo] is None:
            print(f"  🚨 Posición {posicion:>2} | ID {paciente['id']} | {paciente['nombre']}")
            total_nulos += 1

    porcentaje = round(total_nulos / len(pacientes) * 100, 1)
    print(f"
  📊 Total nulos en '{campo}': {total_nulos} de {len(pacientes)} ({porcentaje}%)")

print()
print("═" * 55)
print("  Revisión de nulos completada.")

"""---

### Ejercicio 4.2 — Radar de Duplicados

"""

# ─────────────────────────────────────────────────────────────
# RADAR 2: DETECTOR DE DUPLICADOS por ID de paciente
# ─────────────────────────────────────────────────────────────
# Un duplicado ocurre cuando el mismo ID aparece más de una vez.
# Reporta: el ID duplicado, el nombre del paciente y en qué posición.

ids_seguros      = []
total_duplicados = 0

print("🔍 AUDITORÍA — RADAR DE DUPLICADOS")
print("═" * 55)

for posicion, paciente in enumerate(pacientes):
    # Escribe aquí la lógica if/else para detectar duplicados:
    if paciente["id"] in ids_seguros:
        print(f"  🔁 Duplicado! Posición {posicion:>2} | ID {paciente['id']} | {paciente['nombre']}")
        total_duplicados += 1
    else:
        ids_seguros.append(paciente["id"])

print()
print(f"  📊 Total duplicados: {total_duplicados}")
print(f"  📦 Registros únicos: {len(ids_seguros)}")
print()
print("═" * 55)
print("  Revisión de duplicados completada.")

"""---

### Ejercicio 4.3 — Radar de Inconsistencias de Ciudad

"""

# ─────────────────────────────────────────────────────────────
# RADAR 3: DETECTOR DE INCONSISTENCIAS — campo "ciudad"
# ─────────────────────────────────────────────────────────────
# Primero: muestra todas las variantes únicas del campo ciudad
# Segundo: cuenta cuántos registros tiene cada variante
# Tercero: identifica cuáles son inconsistencias del mismo lugar

# Paso 1: Recopila todas las ciudades únicas
ciudades_encontradas = {}

for paciente in pacientes:
    ciudad = paciente["ciudad"]
    if ciudad in ciudades_encontradas:
        ciudades_encontradas[ciudad] += 1
    else:
        ciudades_encontradas[ciudad] = 1

print("🔍 AUDITORÍA — RADAR DE INCONSISTENCIAS (ciudad)")
print("═" * 55)
print(f"
{'Ciudad registrada':<25} {'Frecuencia':>12}")
print("─" * 40)
for ciudad, freq in ciudades_encontradas.items():
    print(f"  {ciudad:<23} {freq:>10}")

print()
print("⚠️  ¿Cuáles de las anteriores representan el mismo lugar?")
print("     Escribe tu respuesta en la celda de reflexión siguiente.")

"""### ✏️ Reflexión 4.3 (haz doble clic para editar)

Basándote en el output anterior:

1. ¿Cuántas variantes encontraste de Ciudad de México? ¿Y de Guadalajara? ¿Y de Monterrey?

2. ¿Qué estrategia de limpieza usarías para estandarizar el campo `ciudad`? (Consulta la **Tabla de Estrategias** de la Sesión 11)

3. Si contáramos pacientes por ciudad sin limpiar las inconsistencias, ¿qué problema tendría nuestro análisis?

*Escribe tu análisis aquí...*

---

### Ejercicio 4.4 — Radar de Valores Atípicos (Outliers)
"""

# ─────────────────────────────────────────────────────────────
# RADAR 4: DETECTOR DE OUTLIERS — campo "edad"
# ─────────────────────────────────────────────────────────────
# Definimos un rango válido: edad entre 0 y 120 años.
# Cualquier valor fuera de ese rango se considera un outlier.

EDAD_MINIMA_VALIDA = 0
EDAD_MAXIMA_VALIDA = 120

total_outliers = 0

print("🔍 AUDITORÍA — RADAR DE OUTLIERS (edad)")
print("═" * 55)

for paciente in pacientes:
    edad = paciente["edad"]
    if edad is not None:   # Solo revisamos los que no son nulos
        # Escribe aquí la condición del outlier:
        if edad < EDAD_MINIMA_VALIDA or edad > EDAD_MAXIMA_VALIDA:
            print(f"  💥 Outlier! ID {paciente['id']} | {paciente['nombre']} | Edad: {edad}")
            total_outliers += 1

print()
print(f"  📊 Total outliers detectados: {total_outliers}")
print()
print("═" * 55)
print("  Revisión de outliers completada.")

"""---

## 🏆 Reto Final — El Reporte Ejecutivo Completo

¡Llegaste al desafío máximo! El director médico de la Clínica San Rafael necesita el **reporte ejecutivo final** para presentarlo ante el consejo médico mañana.

Tu tarea es construir **un solo bloque de código** que:

1. **Limpie el dataset automáticamente** (elimina nulos, duplicados y outliers)
2. **Calcule el reporte estadístico completo** de las variables numéricas (edades, glucosa, colesterol, días de hospitalización)
3. **Genere la tabla de diagnósticos** con frecuencias
4. **Imprima un reporte final ejecutivo** formateado profesionalmente

---

### 🔧 Instrucciones Paso a Paso

**Paso 1:** Crea la lista `dataset_limpio` eliminando: registros duplicados (por ID), registros con edad nula o > 120, y registros con glucosa nula.

**Paso 2:** Extrae listas separadas de: `edades`, `glucosas`, `colesteroles`, `dias_hosp`.

**Paso 3:** Usa `statistics` para calcular `mean`, `median`, `stdev` de cada variable. Calcula también el `% de variabilidad`.

**Paso 4:** Construye la tabla de diagnósticos con un diccionario contador.

**Paso 5:** Imprime el reporte final con el siguiente formato exacto (llena los `???` con tus cálculos):

```
══════════════════════════════════════════════════════
        REPORTE EJECUTIVO — CLÍNICA SAN RAFAEL
══════════════════════════════════════════════════════

  📦 DATOS DEL DATASET
     Registros originales  : 30
     Registros limpios     : ???
     Nulos eliminados      : ???
     Duplicados eliminados : ???
     Outliers eliminados   : ???

  📐 ESTADÍSTICAS DE PACIENTES
  ┌─────────────────────────────────────────────────┐
  │ Variable        │  Media │ Mediana │  Desv. │  % │
  ├─────────────────────────────────────────────────┤
  │ Edad (años)     │    ??? │     ??? │    ??? │ ???│
  │ Glucosa (mg/dL) │    ??? │     ??? │    ??? │ ???│
  │ Colesterol      │    ??? │     ??? │    ??? │ ???│
  │ Días hosp.      │    ??? │     ??? │    ??? │ ???│
  └─────────────────────────────────────────────────┘

  🏥 DIAGNÓSTICOS MÁS FRECUENTES
     1° ??? — ??? pacientes
     2° ??? — ??? pacientes
     3° ??? — ??? pacientes

  📌 CONCLUSIÓN DEL ANALISTA
     ??? (escribe tu interpretación aquí)

══════════════════════════════════════════════════════
```

"""

import statistics

# ════════════════════════════════════════════════════════
# RETO FINAL — REPORTE EJECUTIVO CLÍNICA SAN RAFAEL
# ════════════════════════════════════════════════════════

# ── PASO 1: Limpiar el dataset ───────────────────────────
dataset_limpio    = []
ids_procesados    = []
nulos_elim        = 0
duplicados_elim   = 0
outliers_elim     = 0

for paciente in pacientes:

    # 1a. Verificar duplicado
    if paciente["id"] in ids_procesados:
        duplicados_elim += 1
        continue                    # salta al siguiente registro

    # 1b. Verificar outlier de edad
    if paciente["edad"] is None or paciente["edad"] > 120:
        if paciente["edad"] is None:
            nulos_elim += 1
        else:
            outliers_elim += 1
        ids_procesados.append(paciente["id"])
        continue

    # 1c. Verificar nulo en glucosa
    if paciente["glucosa"] is None:
        nulos_elim += 1
        ids_procesados.append(paciente["id"])
        continue

    # Si pasó todos los filtros → registro limpio
    ids_procesados.append(paciente["id"])
    dataset_limpio.append(paciente)


# ── PASO 2: Extraer listas de variables ─────────────────
# Escribe aquí la extracción de las 4 listas:
edades      = ...   # lista de edades
glucosas    = ...   # lista de glucosas
colesteroles= ...   # lista de colesterol
dias_hosp   = ...   # lista de días de hospitalización


# ── PASO 3: Calcular estadísticas ───────────────────────
# Para cada lista calcula: mean, median, stdev, % variabilidad
# Ejemplo:
# prom_edad  = round(statistics.mean(edades), 1)
# ...
# Escribe aquí todos los cálculos:




# ── PASO 4: Tabla de diagnósticos ───────────────────────
conteo_diag = {}
for p in dataset_limpio:
    d = p["diagnostico"]
    conteo_diag[d] = conteo_diag.get(d, 0) + 1

# Ordena de mayor a menor frecuencia
diag_ordenados = sorted(conteo_diag.items(), key=lambda x: x[1], reverse=True)


# ── PASO 5: Imprimir reporte ejecutivo ──────────────────
print("═" * 56)
print("        REPORTE EJECUTIVO — CLÍNICA SAN RAFAEL")
print("═" * 56)

print()
print("  📦 DATOS DEL DATASET")
print(f"     Registros originales  : {len(pacientes)}")
print(f"     Registros limpios     : {len(dataset_limpio)}")
print(f"     Nulos eliminados      : {nulos_elim}")
print(f"     Duplicados eliminados : {duplicados_elim}")
print(f"     Outliers eliminados   : {outliers_elim}")

print()
print("  📐 ESTADÍSTICAS DE PACIENTES")
print("  ┌" + "─" * 51 + "┐")
print(f"  │ {'Variable':<16} │ {'Media':>6} │ {'Mediana':>7} │ {'Desv.':>6} │ {'%':>4} │")
print("  ├" + "─" * 51 + "┤")
# Escribe las 4 filas de la tabla con los valores calculados:
# print(f"  │ {'Edad (años)':<16} │ {prom_edad:>6} │ {med_edad:>7} │ {desv_edad:>6} │ {var_edad:>3}% │")
# ... (repite para glucosa, colesterol, dias_hosp)
print("  └" + "─" * 51 + "┘")

print()
print("  🏥 DIAGNÓSTICOS MÁS FRECUENTES")
for i, (diag, freq) in enumerate(diag_ordenados[:3], 1):
    print(f"     {i}° {diag:<18} — {freq} pacientes")

print()
print("  📌 CONCLUSIÓN DEL ANALISTA")
print("     (Escribe aquí tu interpretación del estado de salud")
print("      general de los pacientes de la Clínica San Rafael)")

print()
print("═" * 56)

"""---

## 🧠 Diagnóstico Final del Analista

Esta es la parte más importante de cualquier análisis: **comunicar los hallazgos con claridad**. Un reporte técnico sin interpretación no tiene valor para la dirección médica.

Haz doble clic y responde las siguientes preguntas con base en los resultados que obtuviste:

---

### 1. Sobre la Calidad de los Datos

- ¿Qué porcentaje de los registros originales tuviste que descartar?
- ¿Cuál fue el problema más grave que encontraste: los nulos, los duplicados o el outlier? Justifica.
- ¿Cuál campo tenía más problemas de calidad?

*Escribe aquí...*

---

### 2. Sobre la Salud General de los Pacientes

- ¿El promedio de edad es representativo? Compara con la desviación estándar.
- Los niveles de colesterol saludables deben estar por debajo de 200 mg/dL. ¿Qué te dice el promedio del grupo?
- ¿Cuántos días pasan en promedio hospitalizados? ¿Hay mucha variabilidad entre pacientes?

*Escribe aquí...*

---

### 3. Tu Recomendación Operativa

Redacta en 3-4 oraciones la recomendación que le darías al director médico de la Clínica San Rafael basándote en todos tus hallazgos. Incluye:

- Un problema de calidad de datos que deben corregir en su sistema
- Una alerta de salud pública basada en las estadísticas
- Una sugerencia para el próximo ciclo de recolección de datos

*Escribe aquí tu recomendación...*

"""