# -*- coding: utf-8 -*-
"""Ejercicio_Integrador_Sesiones_5_6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PaVLq_IsmI1r6qVLbui4Un5gNvh8CpcU

# 🏥 Ejercicio Integrador — Sesiones 5 y 6
## «El Sistema de Registro de la Clínica Digital»

---

### 🎯 Objetivo del ejercicio

Este ejercicio integrador pone a prueba **todos** los conceptos vistos en las sesiones 5 y 6 del diplomado. Vas a construir, paso a paso, un mini sistema de registro para una clínica digital.

Al terminar habrás practicado:

| Tema | Sesión |
|---|---|
| Variables y tipos de datos (`str`, `int`, `float`, `bool`) | 5 |
| Regla de oro: comillas vs. sin comillas | 5 |
| Función `type()` | 5 |
| f-strings | 5 y 6 |
| Operadores aritméticos (`+`, `-`, `*`, `/`, `//`, `%`, `**`) | 5 |
| Operadores de comparación (`==`, `!=`, `>`, `<`, `>=`, `<=`) | 5 |
| Concatenación de strings | 6 |
| Casting: `str()`, `int()`, `float()` | 6 |
| Métodos de strings: `.upper()`, `.lower()`, `.strip()`, `.replace()`, `len()` | 6 |

---

### 📋 Instrucciones generales

- Lee cada sección **completa** antes de empezar a escribir código.
- Escribe tu código únicamente en las celdas marcadas con `# ✏️ TU CÓDIGO AQUÍ`.
- Ejecuta cada celda con **Shift + Enter** para ver el resultado.
- Los comentarios con `💡 Pista:` son opcionales, pero te ayudarán si te atascas.

---
## 🗂️ PARTE 1 — El Expediente del Paciente
### Tema: Variables, Tipos de Datos y `type()`

El sistema de la clínica necesita registrar la información de un nuevo paciente. Tu primer trabajo es crear las variables del expediente correctamente, eligiendo el tipo de dato adecuado para cada campo.

### 📝 Ejercicio 1.1 — Registrar el expediente

Crea las siguientes variables con los valores indicados. **Respeta la regla de oro de las comillas:**

| Variable | Valor | Tipo esperado |
|---|---|---|
| `nombre_paciente` | `"Valentina Ríos"` | `str` |
| `edad` | `31` | `int` |
| `peso_kg` | `62.4` | `float` |
| `talla_m` | `1.63` | `float` |
| `es_asegurado` | `True` | `bool` |
| `numero_expediente` | `4872` | `int` |

Después, usa `print(type( ))` para mostrar el tipo de dato de **cada una** de las seis variables.
"""

# ✏️ TU CÓDIGO AQUÍ — Ejercicio 1.1
# 1. Declara las 6 variables del expediente



# 2. Usa print(type( )) para escanear cada una

"""### 📝 Ejercicio 1.2 — El Clasificador Mental

Lee los siguientes datos de la clínica e identifica el tipo de dato correcto. Responde creando una variable para cada dato y escaneándola con `type()`.

1. El número de consultas realizadas en el mes (ej. 127)
2. El nombre del médico a cargo (ej. "Dra. Morales")
3. La temperatura corporal del paciente (ej. 37.2)
4. ¿El paciente tiene antecedentes de hipertensión? (Sí/No)

> 💡 **Pista:** Recuerda: texto → comillas; número o lógico → sin comillas.
"""

# ✏️ TU CÓDIGO AQUÍ — Ejercicio 1.2
# Crea una variable para cada dato y usa type() para verificar

"""---
## 🧮 PARTE 2 — Calculando Indicadores Médicos
### Tema: Operadores Aritméticos y f-strings

Con el expediente listo, el sistema necesita calcular automáticamente algunos indicadores clínicos usando los datos que guardaste en la Parte 1.

### 📝 Ejercicio 2.1 — Índice de Masa Corporal (IMC)

Usando las variables `peso_kg` y `talla_m` del expediente (Ejercicio 1.1), calcula el IMC de Valentina.

**Fórmula:** `IMC = peso / (talla ** 2)`

Muestra el resultado con exactamente **2 decimales** usando f-string.

El resultado esperado debe verse así:
```
Paciente: Valentina Ríos
IMC calculado: 23.47
```

> 💡 **Pista:** Recuerda usar `{variable:.2f}` dentro del f-string para controlar los decimales.
"""

# ✏️ TU CÓDIGO AQUÍ — Ejercicio 2.1
# Calcula el IMC usando las variables del Ejercicio 1.1

"""### 📝 Ejercicio 2.2 — Estadísticas de la Clínica

El administrador de la clínica necesita un reporte mensual. Usa los siguientes datos y los operadores que aprendiste para calcular cada métrica:

```python
total_consultas    = 340
consultas_urgentes = 85
ingresos_total     = 127500.0   # pesos
dias_del_mes       = 30
```

Calcula y muestra con f-string:
1. **Porcentaje de urgencias:** `(consultas_urgentes / total_consultas) * 100`  → muestra con 1 decimal y el símbolo `%`
2. **Promedio diario de consultas:** `total_consultas / dias_del_mes`  → muestra con 2 decimales
3. **Ingreso por consulta:** `ingresos_total / total_consultas`  → muestra con 2 decimales
4. **Consultas regulares:** `total_consultas - consultas_urgentes`  → muestra como entero
5. **BONUS:** Usa el operador `//` para calcular cuántas semanas completas tiene el mes y el operador `%` para saber cuántos días sobran.
"""

# ✏️ TU CÓDIGO AQUÍ — Ejercicio 2.2
# Datos del mes
total_consultas    = 340
consultas_urgentes = 85
ingresos_total     = 127500.0
dias_del_mes       = 30

# Calcula y muestra las 4 métricas (+ el bonus)

"""---
## 🔍 PARTE 3 — El Sistema de Alertas
### Tema: Operadores de Comparación

El sistema necesita generar alertas automáticas revisando los indicadores del paciente. Los operadores de comparación devuelven `True` o `False` y son el primer paso para crear decisiones automáticas.

### 📝 Ejercicio 3.1 — Panel de Alertas del Paciente

Usando los datos de Valentina del Ejercicio 1.1 (o los que declares nuevamente abajo), responde las siguientes preguntas con operadores de comparación. Cada respuesta debe mostrarse con un f-string descriptivo:

1. ¿Valentina es mayor de 30 años? (usa `>`)
2. ¿Su temperatura es normal (menor a 37.5°C)? Usa `temperatura = 37.2` (usa `<`)
3. ¿Tiene exactamente 31 años? (usa `==`)
4. ¿Su peso es diferente a 70 kg? (usa `!=`)
5. ¿Su IMC calculado es mayor o igual a 18.5 (rango normal)? (usa `>=`)

El resultado de cada línea debe verse así:
```
¿Es mayor de 30 años?: True
¿Temperatura normal?: True
...
```

> ⚠️ **Recuerda:** No confundas `=` (guardar) con `==` (comparar).
"""

# ✏️ TU CÓDIGO AQUÍ — Ejercicio 3.1
# Puedes reutilizar las variables del Ejercicio 1.1 si corriste esa celda primero
# Si no, redecláralas aquí arriba antes de las comparaciones

temperatura = 37.2

# Escribe las 5 comparaciones con sus print() de f-string

"""---
## 🔤 PARTE 4 — Procesando Texto del Expediente
### Tema: Concatenación, f-strings y Métodos de Strings

El sistema recibe datos de distintas fuentes (formularios en línea, sistemas externos, digitación manual) y los textos llegan sucios o en formatos inconsistentes. Tu trabajo es limpiarlos y generar reportes profesionales.

### 📝 Ejercicio 4.1 — Generando el Gafete del Congreso Médico

La clínica enviará a dos médicos a un congreso. El sistema debe generar sus gafetes automáticamente.

Tienes estos datos:
```python
nombre_medico  = "Roberto"
apellido_medico = "Castañeda"
especialidad   = "Cardiología"
anos_exp       = 12
```

**Parte A:** Construye el gafete usando **concatenación** con `+`.
```
Dr. Roberto Castañeda — Cardiología
```

**Parte B:** Construye el mismo gafete usando **f-string**, e incluye también los años de experiencia.
```
Dr. Roberto Castañeda — Cardiología | 12 años de experiencia
```

> 💡 **Pista Parte A:** Necesitas usar `str(anos_exp)` para concatenar el número. Con f-string no necesitas hacerlo.
"""

# ✏️ TU CÓDIGO AQUÍ — Ejercicio 4.1
nombre_medico   = "Roberto"
apellido_medico = "Castañeda"
especialidad    = "Cardiología"
anos_exp        = 12

# PARTE A: con concatenación (+)


# PARTE B: con f-string (incluye años de experiencia)

"""### 📝 Ejercicio 4.2 — El Normalizador de Formularios

El sistema recibió estos registros de un formulario en línea. Como puedes ver, los usuarios los escribieron de maneras muy inconsistentes. Normaliza cada uno usando los métodos de strings que aprendiste:

```python
nombre_crudo    = "  luisa fernanda  "   # espacios extra, todo minúsculas
ciudad_cruda    = "GUADALAJARA "         # mayúsculas y espacio al final  
diagnostico_crd = "  GRIPE ESTACIONAL"   # mayúsculas y espacio al inicio
codigo_crd      = "PAC-2024-001"         # guiones que deben eliminarse
```

Para cada variable, aplica los métodos necesarios y guarda el resultado en una variable limpia. Luego muestra los resultados con f-strings.

**Resultado esperado:**
```
Nombre limpio:      'Luisa Fernanda'
Ciudad limpia:      'Guadalajara'
Diagnóstico limpio: 'gripe estacional'
Código limpio:      'PAC2024001'
Longitud del código limpio: 9 caracteres
```

| Método | Lo que hace |
|---|---|
| `.strip()` | Quita espacios al inicio y al final |
| `.title()` | Pone Mayúscula Inicial En Cada Palabra |
| `.lower()` | convierte todo a minúsculas |
| `.replace("viejo", "nuevo")` | Sustituye texto |
| `len()` | Cuenta caracteres |
"""

# ✏️ TU CÓDIGO AQUÍ — Ejercicio 4.2
nombre_crudo    = "  luisa fernanda  "
ciudad_cruda    = "GUADALAJARA "
diagnostico_crd = "  GRIPE ESTACIONAL"
codigo_crd      = "PAC-2024-001"

# Limpieza — aplica los métodos necesarios a cada variable


# Muestra los resultados con f-strings

"""---
## 🔄 PARTE 5 — Casting: Los Traductores de Datos
### Tema: `str()`, `int()`, `float()` y el Error Intencional

Al importar datos de sistemas externos, es común que los números lleguen disfrazados de texto. Aquí practicarás el casting para "traducirlos" antes de operar con ellos.

### 📝 Ejercicio 5.1 — Detecta el Error (sin ejecutar)

Antes de correr cualquier celda, **lee el siguiente bloque** e identifica mentalmente por qué cada línea va a fallar y qué tipo de error esperas ver (`TypeError` o `ValueError`).

Después escribe debajo del código, en un comentario, tu explicación.
"""

# ─── Lee este bloque, NO lo ejecutes todavía ───────────────
# Línea A:
# resultado_a = "Consultas: " + 127

# Línea B:
# resultado_b = int("treinta y cinco")

# ✏️ Escribe AQUÍ tu explicación para cada línea (en comentarios):
# Línea A falla porque...

# Línea B falla porque...

"""### 📝 Ejercicio 5.2 — El Ticket de Cobro de la Clínica

El sistema exportó los datos de facturación, pero los guardó como texto. Debes limpiarlos y generar el ticket de cobro.

**Instrucciones:**
1. Convierte `precio_consulta` a `float` y guárdalo en `precio_num`.
2. Convierte `num_sesiones` a `int` y guárdalo en `sesiones_num`.
3. Calcula el subtotal: `subtotal = precio_num * sesiones_num`
4. Calcula el IVA (16%): `iva = subtotal * 0.16`
5. Calcula el total: `total = subtotal + iva`
6. Genera el ticket con f-string mostrando todos los valores con 2 decimales.
7. **RETO EXTRA:** Muestra el nombre del paciente en MAYÚSCULAS en el ticket usando `.upper()`.

**Salida esperada:**
```
=============================
   CLÍNICA DIGITAL — TICKET
=============================
Paciente:    VALENTINA RÍOS
Consultas:   4
Precio/ses.: $850.00
Subtotal:    $3400.00
IVA (16%):   $544.00
TOTAL:       $3944.00
=============================
```
"""

# ✏️ TU CÓDIGO AQUÍ — Ejercicio 5.2
# Datos exportados por el sistema (números disfrazados de texto)
paciente_ticket  = "Valentina Ríos"
precio_consulta  = "850"      # precio guardado como texto
num_sesiones     = "4"         # cantidad guardada como texto

# Paso 1: casting

# Paso 2: cálculos

# Paso 3: ticket con f-string

"""---
## 🏆 PARTE 6 — Reto Final Integrador
### «El Reporte Completo del Paciente»

Aquí combinas **absolutamente todo** lo que aprendiste en las Sesiones 5 y 6. Vas a construir el reporte de alta de un paciente desde cero.

### 📝 Reto Final — Reporte de Alta del Paciente

El sistema recibió los siguientes datos **sucios** de un formulario. Tu misión:

**A. Limpieza de datos (métodos de strings + casting):**
- `nombre_raw`: quita espacios y aplica `.title()`
- `ciudad_raw`: quita espacios y convierte a título
- `diagnostico_raw`: quita espacios y convierte a minúsculas
- `peso_raw` y `talla_raw`: conviértelos de texto a `float`
- `dias_hospitalizado_raw`: conviértelo de texto a `int`

**B. Cálculos (operadores aritméticos):**
- IMC: `peso / (talla ** 2)` → 2 decimales
- Costo total: `dias_hospitalizados * costo_por_dia` (usa `costo_por_dia = 2300.0`)
- IVA (16%) sobre el costo total
- Total final con IVA

**C. Comparaciones (operadores de comparación):**
- ¿Tiene fiebre? (`temperatura > 37.5`)
- ¿Es paciente de riesgo (edad >= 60)?
- ¿Su IMC es normal (entre 18.5 y 24.9)? Evalúa las dos condiciones por separado.

**D. Reporte final con f-string:** Muestra un reporte organizado con todos los datos limpios, los cálculos y las alertas.

> 💡 **Pista:** Puedes calcular el rango del IMC así: `imc_normal_bajo = imc >= 18.5` e `imc_normal_alto = imc <= 24.9`
"""

# ✏️ TU CÓDIGO AQUÍ — Reto Final

# ═══════════════════════════════════════════
# DATOS SUCIOS DEL FORMULARIO (no modificar)
# ═══════════════════════════════════════════
nombre_raw             = "  jorge mendoza  "
ciudad_raw             = "MONTERREY "
diagnostico_raw        = "  HIPERTENSIÓN ARTERIAL"
peso_raw               = "88.5"       # texto
talla_raw              = "1.78"       # texto
temperatura_raw        = 38.1         # ya es float, no necesita casting
edad_raw               = 63           # ya es int
dias_hospitalizado_raw = "5"          # texto
costo_por_dia          = 2300.0

# ───────────────────────────────────────────
# PARTE A: Limpieza de datos
# ───────────────────────────────────────────


# ───────────────────────────────────────────
# PARTE B: Cálculos
# ───────────────────────────────────────────


# ───────────────────────────────────────────
# PARTE C: Comparaciones / Alertas
# ───────────────────────────────────────────


# ───────────────────────────────────────────
# PARTE D: Reporte final con f-string
# ───────────────────────────────────────────
print("="*45)
print("       REPORTE DE ALTA — CLÍNICA DIGITAL")
print("="*45)

# Continúa el reporte aquí...

"""---
## 🧠 Pregunta de Reflexión Final

En una celda de **Texto** nueva debajo de este bloque, responde brevemente:

> *En el Reto Final, los datos `peso_raw` y `talla_raw` llegaron como texto (`str`). ¿Qué error hubiera ocurrido si intentabas calcular el IMC directamente sin usar `float()` primero? ¿A qué se debe ese error?*
>
> *Además, ¿por qué usamos f-strings en lugar de concatenación con `+` para construir el reporte final?*

✏️ **Escribe tu respuesta aquí (doble clic para editar):**

_(Borra este texto y escribe tu respuesta)_
"""