# -*- coding: utf-8 -*-
"""PROYECTO FINAL INTEGRADOR — Módulo 1 de Ciencia de Datos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t77JvNSVyNRjxj7GffLURrjnlsd2HT45

# 💳 PROYECTO FINAL INTEGRADOR — Módulo 1 de Ciencia de Datos
## CreditGuard FinTech: Análisis de Riesgo Crediticio BNPL
### *Buy Now, Pay Later — ¿Quién va a incumplir su pago?*

---

**Escenario:**
Eres el **Científico de Datos** de *CreditGuard*, una FinTech global que ofrece crédito BNPL
(*Compra Ahora, Paga Después*) en 6 países. Cada mes miles de clientes no pagan sus cuotas
y la empresa pierde millones. El Director de Riesgo te entrega un dataset de **3,500 transacciones**
y una sola misión:

> *"Dime quién va a incumplir su pago, por qué ocurre y qué podemos hacer al respecto."*

---

| # | Sección | Temas | Sesiones |
|---|---|---|---|
| 1 | Conceptos y preguntas de datos | Target, Features, tipos de análisis, rol | **1 y 2** |
| 2 | Variables, tipos y f-strings | str, int, float, bool, f-strings | 2, 5, 6 |
| 3 | Poderes del texto Python puro | .lower .strip .title .replace, encadenamiento, for | **6 y 13** |
| 4 | Listas y operaciones | indexación, slicing, max, min, append, in | 2 y 7 |
| 5 | Diccionarios, Tuplas, Sets | perfil cliente, info empresa, categorías únicas | **7** |
| 6 | Control de flujo | if/elif/else con penalización | 7 y 8 |
| 7 | Bucles y Funciones | def, return, for/enumerate, while | 7 y 8 |
| 8 | Estadística manual | sum/len, sorted, max/min, moda con dict | **9** |
| 9 | Módulo statistics | mean, median, mode, multimode, stdev | **10** |
| 10 | Los 4 Sospechosos + detección | None, duplicados, inconsistencias, outliers | 11 y 12 |
| 11 | Limpieza con Pandas | 6 comandos inspección, dropduplicates, fillna, .str | **13 y 14** |
| 12 | NumPy | array, stats, filtrado booleano | 3 |
| 13 | Visualización Matplotlib | plt.bar .plot .hist, axhline, personalización | **15** |
| 14 | Visualización Seaborn | barplot lineplot scatterplot(hue) histplot(kde) dashboard | **16** |
| 15 | EDA Parte 1 | 3 fases, groupby, comparación de grupos | **17** |
| 16 | EDA Parte 2 | correlación, selectdtypes, heatmap, pairplot | **18** |
| 🏆 | Reto Final — Pipeline S1–S19 | Pipeline end-to-end, Markdown analítico | **19** |
| 📢 | Data Storytelling | Marco CPDA, Grfico Estrella, Pitch ejecutivo | **20** |

---
## 📖 Diccionario del Dataset — Conoce tus Variables

Antes de programar, lee esta tabla. Es tu mapa de navegación.

| Columna | Tipo | Descripción |
|---|---|---|
| `user_id` | int | Identificador único del cliente |
| `age` | int | Edad del cliente (años) |
| `employment_type` | str | Tipo de empleo: `Salaried`, `Student`, `Self-Employed`, `Unemployed` |
| `monthly_income` | float | Ingreso mensual en USD |
| `credit_score` | int | Puntaje crediticio (300–850) |
| `purchase_amount` | float | Monto de la compra BNPL en USD |
| `product_category` | str | Categoría: `Electronics`, `Fashion`, `Sports`, `Home`, `Beauty` |
| `bnpl_installments` | int | Número de cuotas pactadas: 3, 6, 9 o 12 |
| `repayment_delay_days` | int | Días de retraso en el último pago |
| `missed_payments` | int | Número de pagos omitidos |
| `default_flag` | int | **TARGET** → 0 = Pagó / 1 = Incumplió |
| `app_usage_frequency` | float | Frecuencia de uso de la app (veces/semana) |
| `location` | str | País: Australia, USA, UK, Germany, India, Canada |
| `transaction_date` | str | Fecha de la transacción (YYYY-MM-DD) |
| `debt_to_income_ratio` | float | Ratio deuda/ingreso (0–1, mayor = más riesgo) |
| `risk_score` | float | Puntaje de riesgo calculado por el sistema |
| `customer_segment` | str | Segmento: `Low Risk`, `Medium Risk`, `High Risk` |

---
## 📌 Sección 1 — Conceptos y Formulación de Preguntas de Datos
*(Sesiones 1 y 2)*

El Director de Riesgo de CreditGuard te presenta el problema en lenguaje de negocios.
Tu trabajo es traducirlo al lenguaje de la Ciencia de Datos.

**Ejercicio 1.1 — Traduce el problema (haz doble clic para editar)**

**Problema vago del Director:**
> *"Cada mes perdemos dinero porque algunos clientes no pagan. No sé quiénes son ni por qué."*

**Tu traducción a pregunta de datos (específica y medible):**
*(escribe aquí)*

**Tipo de análisis** *(Descriptivo / Diagnóstico / Predictivo / Prescriptivo — elige y justifica):*
*(escribe aquí)*

**Tu TARGET** *(columna que quieres predecir):*
*(escribe aquí)*

**Features (variables pista) — identifica mínimo 6:**
1. 2. 3. 4. 5. 6.

**Tu rol en este proyecto** *(Data Analyst / Data Scientist / Data Engineer — justifica):*
*(escribe aquí)*

---
## 🐍 Sección 2 — Variables, Tipos de Datos y f-strings
*(Sesiones 2, 5 y 6)*
"""

# ─────────────────────────────────────────────────────
# EJERCICIO 2.1 — Perfil del primer cliente del dataset
# ─────────────────────────────────────────────────────
user_id          = ___        # int   →  1
age              = ___        # int   →  56
employment_type  = ___        # str   →  "Salaried"
monthly_income   = ___        # float →  68529.50
credit_score     = ___        # int   →  552
product_category = ___        # str   →  "Electronics"
default_flag     = ___        # int   →  0   (0=pagó, 1=incumplió)
customer_segment = ___        # str   →  "Medium Risk"

# ─────────────────────────────────────────────────────
# EJERCICIO 2.2 — Reporte con f-strings
# Salida esperada (exacta):
#   🧾 Cliente #1 | Edad: 56 años | Empleo: Salaried
#   💰 Ingreso: $68,529.50 | Score: 552 | Segmento: Medium Risk
#   ⚠️  Default: 0 (Pagó correctamente)
# ─────────────────────────────────────────────────────
estado = "Pagó correctamente" if default_flag == 0 else "⛔ INCUMPLIÓ"
print(f"🧾 Cliente #{user_id} | Edad: {___} años | Empleo: {___}")
print(f"💰 Ingreso: ${___:,.2f} | Score: {___} | Segmento: {___}")
print(f"⚠️  Default: {___} ({estado})")

# ─────────────────────────────────────────────────────
# EJERCICIO 2.3 — Verifica los tipos de dato
# ─────────────────────────────────────────────────────
print("\n=== Verificación de Tipos ===")
for nombre, valor in [("user_id", user_id), ("monthly_income", monthly_income),
                      ("credit_score", credit_score), ("default_flag", default_flag)]:
    print(f"  {nombre:<18} → {type(valor)}")

"""---
## 🧹 Sección 3 — Los 5 Poderes del Texto: Limpieza en Python Puro
*(Sesiones 6 y 13)*

El sistema de captura de CreditGuard tiene inconsistencias en las columnas de texto.
Usa los poderes del texto para estandarizar antes de que lleguen a Pandas.

"""

# ─────────────────────────────────────────────────────
# EJERCICIO 3.1 — Limpia cada campo individualmente
# REGLA DE ORO: siempre sobrescribe la variable para guardar el cambio
# ─────────────────────────────────────────────────────
segmento_sucio   = "  HIGH RISK "        # espacios + mayúsculas
pais_sucio       = "  australia "        # espacios
tipo_empleo_s    = " Self-employed "     # espacio + capitalización
categoria_sucia  = "  ELECTRONICS  "     # todo en mayúsculas

# Limpia con los poderes del texto
segmento_limpio  = segmento_sucio.___().___()      # strip + lower → "high risk"
pais_limpio      = pais_sucio.___().___()           # strip + title → "Australia"
tipo_limpio      = tipo_empleo_s.___().___()        # strip + title → "Self-Employed"
categoria_limpia = categoria_sucia.___().___()      # strip + title → "Electronics"

print("=== Campos Limpios ===")
print(f"  Segmento  : '{segmento_limpio}'")
print(f"  País      : '{pais_limpio}'")
print(f"  Empleo    : '{tipo_limpio}'")
print(f"  Categoría : '{categoria_limpia}'")

# ─────────────────────────────────────────────────────
# EJERCICIO 3.2 — .replace() para estandarizar abreviaturas
# ─────────────────────────────────────────────────────
tipo_abreviado = "self-emp"
tipo_completo  = tipo_abreviado.replace("self-emp", "Self-Employed")
print(f"\nAbreviado → Completo: '{tipo_abreviado}' → '{tipo_completo}'")

# ─────────────────────────────────────────────────────
# EJERCICIO 3.3 — Encadenamiento en una sola línea (estilo profesional)
# ─────────────────────────────────────────────────────
registro_crudo = "  HIGH RISK  "
limpio_pro     = registro_crudo.strip().lower().replace("high risk", "High Risk")
print(f"\nEncadenado: '{registro_crudo}' → '{limpio_pro}'")

# ─────────────────────────────────────────────────────
# EJERCICIO 3.4 — Automatiza la limpieza de una lista con for
# El sistema exportó una lista de segmentos con inconsistencias
# ─────────────────────────────────────────────────────
segmentos_sucios = ["High Risk ", " HIGH RISK", "high risk  ", "Low Risk",
                    " LOW RISK", "Medium Risk ", "MEDIUM RISK "]
segmentos_limpios = []

for seg in segmentos_sucios:
    limpio = seg.___().___()     # strip + lower
    segmentos_limpios.append(limpio)

print(f"\nSucios  : {segmentos_sucios}")
print(f"Limpios : {segmentos_limpios}")
print(f"Clientes High Risk : {segmentos_limpios.count('high risk')}")

# ─────────────────────────────────────────────────────
# EJERCICIO 3.5 — Limpia múltiples campos de un diccionario
# ─────────────────────────────────────────────────────
cliente_sucio = {
    "nombre"    : "  MARÍA FERNÁNDEZ ",
    "segmento"  : "  HIGH RISK  ",
    "pais"      : "  AUSTRALIA ",
    "categoria" : " ELECTRONICS "
}
cliente_sucio["nombre"]    = cliente_sucio["nombre"].___.___()     # strip + title
cliente_sucio["segmento"]  = cliente_sucio["segmento"].___.___()   # strip + lower
cliente_sucio["pais"]      = cliente_sucio["pais"].___.___()       # strip + title
cliente_sucio["categoria"] = cliente_sucio["categoria"].___.___()  # strip + title

print(f"\nRegistro limpio: {cliente_sucio}")

"""---
## 📋 Sección 4 — Listas y sus Operaciones
*(Sesiones 2 y 7)*

"""

# ─────────────────────────────────────────────────────
# Dataset de muestra para los ejercicios con listas
# ─────────────────────────────────────────────────────
columnas_bnpl = ["user_id","age","employment_type","monthly_income","credit_score",
                 "purchase_amount","product_category","bnpl_installments",
                 "repayment_delay_days","missed_payments","default_flag",
                 "app_usage_frequency","location","transaction_date",
                 "debt_to_income_ratio","risk_score","customer_segment"]

credit_scores_muestra = [552, 300, 471, 300, 512, 729, 511, 369, 306, 318,
                         571, 481, 630, 372, 370, 380, 385, 599, 550, 764]

# a) Total de columnas del dataset
print(f"Total columnas        : {___(columnas_bnpl)}")

# b) Primera columna (índice 0) y última (índice negativo)
print(f"Primera columna       : {columnas_bnpl[___]}")
print(f"Última columna (target): {columnas_bnpl[___]}")

# c) Solo las Features (todas menos las dos últimas — slicing)
features = columnas_bnpl[___]
print(f"Features ({len(features)})         : {features}")

# d) ¿Está 'credit_score' en el dataset?
if ___ in columnas_bnpl:
    print("✅ 'credit_score' está en el dataset")

# e) El score máximo, mínimo y rango de la muestra
score_max = ___(credit_scores_muestra)
score_min = ___(credit_scores_muestra)
rango     = score_max - score_min
print(f"\nScore máximo : {score_max}")
print(f"Score mínimo : {score_min}")
print(f"Rango total  : {rango} puntos")

# f) Cuántos clientes tienen score mínimo (300 = peor score posible)
en_minimo = credit_scores_muestra.count(___)
print(f"Clientes con score 300 (mín): {en_minimo} de {len(credit_scores_muestra)}")

# g) Agrega un nuevo cliente con score 685
credit_scores_muestra.append(___)
print(f"\nMuestra actualizada ({len(credit_scores_muestra)} clientes): {credit_scores_muestra}")

"""---
## 🗂️ Sección 5 — Diccionarios, Tuplas y Sets
*(Sesión 7)*

"""

# ─────────────────────────────────────────────────────
# EJERCICIO 5.1 — Perfil completo del cliente como Diccionario
# ─────────────────────────────────────────────────────
perfil_cliente = {
    "user_id"           : ___,     # int   → 9
    "age"               : ___,     # int   → 45
    "employment_type"   : ___,     # str   → "Student"
    "monthly_income"    : ___,     # float → 14821.44
    "credit_score"      : ___,     # int   → 306
    "purchase_amount"   : ___,     # float → 3628.68
    "missed_payments"   : ___,     # int   → 2
    "default_flag"      : ___,     # int   → 1  (¡INCUMPLIÓ!)
    "customer_segment"  : ___      # str   → "High Risk"
}

print("=== Expediente de Riesgo ===")
print(f"  ID              : {perfil_cliente[___]}")
print(f"  Edad            : {perfil_cliente['age']} años")
print(f"  Empleo          : {perfil_cliente[___]}")
print(f"  Ingreso mensual : ${perfil_cliente['monthly_income']:,.2f}")
print(f"  Credit Score    : {perfil_cliente[___]}/850")
print(f"  Pagos perdidos  : {perfil_cliente['missed_payments']}")
print(f"  Segmento        : {perfil_cliente[___]}")
alerta = "⛔ INCUMPLIMIENTO" if perfil_cliente["default_flag"] == 1 else "✅ Al corriente"
print(f"  Estado          : {alerta}")

# ─────────────────────────────────────────────────────
# EJERCICIO 5.2 — Tupla con datos fijos de CreditGuard
# (no deben cambiar → usa una tupla, no una lista)
# ─────────────────────────────────────────────────────
info_empresa = ("CreditGuard FinTech", 2019, 6, 3500)  # nombre, fundación, países, clientes
print(f"\n🏢 Empresa   : {info_empresa[0]}")
print(f"   Fundada   : {info_empresa[1]}")
print(f"   Países    : {info_empresa[2]}")
print(f"   Clientes  : {info_empresa[3]:,}")

# ─────────────────────────────────────────────────────
# EJERCICIO 5.3 — Set para obtener categorías y ubicaciones únicas
# ─────────────────────────────────────────────────────
todas_categorias = ["Electronics","Fashion","Electronics","Sports","Home",
                    "Beauty","Fashion","Electronics","Sports","Home","Beauty","Fashion"]
todos_paises     = ["Australia","USA","Australia","Germany","India","Canada",
                    "UK","USA","India","Germany","Canada","Australia"]

categorias_unicas = ___(todas_categorias)
paises_unicos     = ___(todos_paises)

print(f"\nRegistros de categorías  : {len(todas_categorias)}")
print(f"Categorías únicas        : {len(categorias_unicas)} → {categorias_unicas}")
print(f"Países únicos            : {len(paises_unicos)} → {paises_unicos}")

"""---
## 🚦 Sección 6 — Control de Flujo: Clasificador de Riesgo
*(Sesiones 7 y 8)*

CreditGuard necesita un motor de decisión automático.

| Condición | Nivel | Decisión |
|---|---|---|
| `credit_score` ≥ 700 Y `missed_payments` == 0 | 🟢 LOW RISK | Aprobar crédito |
| `credit_score` 500–699 Y `missed_payments` ≤ 1 | 🟡 MEDIUM RISK | Aprobar con límite |
| `credit_score` < 500 O `missed_payments` ≥ 2 | 🔴 HIGH RISK | Rechazar crédito |

**Regla adicional:** Si `debt_to_income_ratio` > 0.40 → baja automáticamente a **HIGH RISK**, sin importar el score.

"""

# Usa el perfil del cliente de la Sección 5
credit_score     = perfil_cliente["credit_score"]       # 306
missed_payments  = perfil_cliente["missed_payments"]    # 2
dti              = 0.2448  # debt_to_income_ratio

# ─────────────────────────────────────────────────────
# EJERCICIO 6.1 — Clasificador de riesgo crediticio
# ─────────────────────────────────────────────────────
if credit_score >= ___ and missed_payments == ___:
    nivel    = "🟢 LOW RISK"
    decision = "Aprobar crédito"
elif credit_score >= ___ and missed_payments <= ___:
    nivel    = "🟡 MEDIUM RISK"
    decision = "Aprobar con límite reducido"
else:
    nivel    = "🔴 HIGH RISK"
    decision = "Rechazar crédito"

# ─────────────────────────────────────────────────────
# EJERCICIO 6.2 — Penalización por DTI alto (> 0.40)
# ─────────────────────────────────────────────────────
if dti > ___ and nivel != "🔴 HIGH RISK":
    nivel    = "🔴 HIGH RISK"
    decision = "Rechazado — DTI excesivo"

print("=== Motor de Decisión CreditGuard ===")
print(f"  Credit Score          : {credit_score}/850")
print(f"  Pagos perdidos        : {missed_payments}")
print(f"  Ratio Deuda/Ingreso   : {dti:.2%}")
print(f"  ─────────────────────────────────")
print(f"  Nivel de Riesgo       : {nivel}")
print(f"  Decisión              : {decision}")

"""---
## 🔄 Sección 7 — Bucles y Funciones
*(Sesiones 7 y 8)*

"""

# Dataset de 10 clientes para los ejercicios
clientes_bnpl = [
    {"id":1,  "age":56,"employment":"Salaried",     "income":68529.5,"score":552,"missed":1,"dti":0.073,"default":0,"segment":"Medium Risk"},
    {"id":2,  "age":19,"employment":"Student",      "income":7247.8, "score":300,"missed":1,"dti":0.148,"default":0,"segment":"High Risk"},
    {"id":4,  "age":21,"employment":"Salaried",     "income":14423.5,"score":300,"missed":5,"dti":0.283,"default":1,"segment":"High Risk"},
    {"id":6,  "age":52,"employment":"Self-Employed","income":79950.3,"score":729,"missed":0,"dti":0.063,"default":0,"segment":"Low Risk"},
    {"id":9,  "age":45,"employment":"Student",      "income":14821.4,"score":306,"missed":2,"dti":0.245,"default":1,"segment":"High Risk"},
    {"id":20, "age":53,"employment":"Self-Employed","income":94896.0,"score":764,"missed":1,"dti":0.053,"default":0,"segment":"Low Risk"},
    {"id":31, "age":55,"employment":"Self-Employed","income":104642.7,"score":832,"missed":0,"dti":0.048,"default":0,"segment":"Low Risk"},
    {"id":55, "age":19,"employment":"Salaried",     "income":52914.7,"score":462,"missed":3,"dti":0.082,"default":1,"segment":"High Risk"},
    {"id":73, "age":50,"employment":"Self-Employed","income":97571.5,"score":682,"missed":3,"dti":0.051,"default":1,"segment":"Medium Risk"},
    {"id":100,"age":26,"employment":"Unemployed",   "income":8661.97,"score":300,"missed":3,"dti":0.418,"default":1,"segment":"High Risk"},
]

# ─────────────────────────────────────────────────────
# EJERCICIO 7.1 — Función reutilizable del motor de riesgo
# ─────────────────────────────────────────────────────
def clasificar_riesgo_bnpl(credit_score, missed_payments, dti):
    """Motor de decisión de CreditGuard. Devuelve nivel y decisión."""
    if credit_score >= ___ and missed_payments == ___:
        nivel = "🟢 LOW RISK"
    elif credit_score >= ___ and missed_payments <= ___:
        nivel = "🟡 MEDIUM RISK"
    else:
        nivel = "🔴 HIGH RISK"
    if dti > ___ and nivel != "🔴 HIGH RISK":
        nivel = "🔴 HIGH RISK"
    return nivel

# Prueba de la función
print(clasificar_riesgo_bnpl(832, 0, 0.048))    # 🟢 LOW RISK
print(clasificar_riesgo_bnpl(552, 1, 0.073))    # 🟡 MEDIUM RISK
print(clasificar_riesgo_bnpl(300, 5, 0.283))    # 🔴 HIGH RISK
print(clasificar_riesgo_bnpl(729, 0, 0.420))    # 🔴 HIGH RISK (penalización DTI)

# ─────────────────────────────────────────────────────
# EJERCICIO 7.2 — Bucle for: Reporte de Riesgo de la Cartera
# ─────────────────────────────────────────────────────
print("\n=== REPORTE DE RIESGO — CREDITGUARD ===")
print(f"{'#':<5}{'ID':<7}{'Empleo':<17}{'Score':>7}{'DTI':>8}  Nivel")
print("-" * 60)

high_risk_cnt = 0
for i, c in enumerate(clientes_bnpl, 1):
    nivel = clasificar_riesgo_bnpl(c["score"], c["missed"], c["dti"])
    print(f"{i:<5}{c['id']:<7}{c['employment']:<17}{c['score']:>6} {c['dti']:>7.1%}  {nivel}")
    if "HIGH" in nivel:
        high_risk_cnt += 1

print("-" * 60)
print(f"Clientes High Risk: {high_risk_cnt} de {len(clientes_bnpl)} ({high_risk_cnt/len(clientes_bnpl)*100:.0f}%)")

# ─────────────────────────────────────────────────────
# EJERCICIO 7.3 — while: Acumula hasta llegar a 3 clientes de bajo riesgo
# ─────────────────────────────────────────────────────
print("\n=== Búsqueda de Clientes Low Risk (meta: 3) ===")
low_risk_encontrados = 0
i = 0
while low_risk_encontrados < ___ and i < len(clientes_bnpl):
    nivel = clasificar_riesgo_bnpl(clientes_bnpl[i]["score"],
                                   clientes_bnpl[i]["missed"],
                                   clientes_bnpl[i]["dti"])
    if "LOW" in nivel:
        low_risk_encontrados += 1
        print(f"  ✅ ID {clientes_bnpl[i]['id']} — Score: {clientes_bnpl[i]['score']} | DTI: {clientes_bnpl[i]['dti']:.1%}")
    i += 1
print(f"  Revisados: {i} clientes | Low Risk encontrados: {low_risk_encontrados}")

"""---
## 📊 Sección 8 — Estadística Manual en Python Puro
*(Sesión 9)*

Antes de usar librerías, demuestra que entiendes las matemáticas.

"""

import math

# Datos de 20 clientes de la cartera CreditGuard
ingresos = [68529.5, 7247.8, 41582.3, 14423.5, 42845.5,
            79950.3, 43192.3, 9434.8, 14821.4, 6737.9,
            46828.6, 39976.3, 71683.6, 13389.7, 13114.8,
            15372.7, 6381.7, 61140.9, 47350.5, 94896.0]

credit_scores_20 = [552, 300, 471, 300, 512, 729, 511, 369, 306, 318,
                    571, 481, 630, 372, 370, 380, 385, 599, 550, 764]

dti_20           = [0.073, 0.148, 0.120, 0.283, 0.117, 0.063, 0.116, 0.179,
                    0.245, 0.015, 0.086, 0.125, 0.070, 0.084, 0.117, 0.102,
                    0.295, 0.082, 0.106, 0.053]

# ─────────────────────────────────────────────────────
# EJERCICIO 8.1 — Promedio (Media)
# ─────────────────────────────────────────────────────
media_ingresos = ___(ingresos) / ___(ingresos)
media_score    = sum(credit_scores_20) / len(credit_scores_20)
print(f"💰 Ingreso promedio      : ${media_ingresos:>12,.2f}")
print(f"📈 Credit score promedio : {media_score:>10.1f} / 850")

# ─────────────────────────────────────────────────────
# EJERCICIO 8.2 — Mediana
# ─────────────────────────────────────────────────────
def calcular_mediana(lista):
    ordenada = sorted(___)
    n        = len(ordenada)
    if n % 2 == 0:
        return (ordenada[n//2 - 1] + ordenada[n//2]) / 2
    else:
        return ordenada[n // 2]

mediana_ingresos = calcular_mediana(ingresos)
mediana_score    = calcular_mediana(credit_scores_20)
print(f"💰 Ingreso mediano       : ${mediana_ingresos:>12,.2f}")
print(f"📈 Score mediano         : {mediana_score:>10.0f} / 850")

# ─────────────────────────────────────────────────────
# EJERCICIO 8.3 — Rango, máximo y mínimo
# ─────────────────────────────────────────────────────
print(f"\n📉 Score mínimo          : {___(credit_scores_20)} (peor puntaje)")
print(f"📈 Score máximo          : {___(credit_scores_20)} (mejor puntaje)")
print(f"📐 Rango del score       : {max(credit_scores_20) - min(credit_scores_20)} puntos")
print(f"📐 Rango de ingresos     : ${max(ingresos) - min(ingresos):,.2f}")

# ─────────────────────────────────────────────────────
# EJERCICIO 8.4 — Moda (valor más frecuente con diccionario)
# ─────────────────────────────────────────────────────
def calcular_moda(lista):
    frecuencias = {}
    for valor in lista:
        if valor in frecuencias:
            frecuencias[valor] += 1
        else:
            frecuencias[valor] = ___
    moda = max(frecuencias, key=frecuencias.get)
    return moda, frecuencias[moda]

moda_score, freq_moda = calcular_moda(credit_scores_20)
print(f"\n🔢 Moda del credit score : {moda_score} (aparece {freq_moda} veces)")
print(f"   Dato: Score 300 es el piso del sistema (peor posible)")

# ─────────────────────────────────────────────────────
# EJERCICIO 8.5 — ¿Media o Mediana? El caso del ingreso
# ─────────────────────────────────────────────────────
diferencia = abs(media_ingresos - mediana_ingresos)
print(f"\n📊 Diferencia Media−Mediana: ${diferencia:,.2f}")
print("💡 Reflexión (haz doble clic en la celda de texto):")
print("   ¿Cuál métrica representa mejor la 'realidad' del cliente promedio?")

"""**Tu reflexión: Media vs. Mediana del Ingreso**

*Cuando la Media > Mediana, la distribución es _____.
Eso significa que pocos clientes con ingresos muy altos están "jalando" el promedio hacia arriba.
En este contexto, la _____ representa mejor al cliente típico de CreditGuard, porque ___.*

*(Haz doble clic para completar)*

---
## 📐 Sección 9 — Módulo `statistics`
*(Sesión 10)*
"""

import statistics as stats

# ─────────────────────────────────────────────────────
# EJERCICIO 9.1 — Módulo statistics vs. cálculo manual
# ─────────────────────────────────────────────────────
scores_extendidos = [552,300,471,300,512,729,511,369,306,318,
                     571,481,630,372,370,380,385,599,550,764,
                     682,462,637,560,448,515,706,490,324,590]

media_lib   = stats.___(scores_extendidos)
mediana_lib = stats.___(scores_extendidos)
moda_lib    = stats.___(scores_extendidos)
desv_lib    = stats.___(scores_extendidos)
var_lib     = stats.___(scores_extendidos)

print("=== Estadísticas del Credit Score (30 clientes) ===")
print(f"  Media              : {media_lib:.2f}")
print(f"  Mediana            : {mediana_lib:.1f}")
print(f"  Moda               : {moda_lib}")
print(f"  Desviación estándar: {desv_lib:.2f}")
print(f"  Varianza           : {var_lib:.2f}")

# ─────────────────────────────────────────────────────
# EJERCICIO 9.2 — multimode: ¿cuántos valores son la moda?
# ─────────────────────────────────────────────────────
multimoda = stats.___(scores_extendidos)
print(f"\n  Multimoda          : {multimoda}")
print(f"  Total modas        : {len(multimoda)}")

# ─────────────────────────────────────────────────────
# EJERCICIO 9.3 — Interpretación de la desviación estándar
# ─────────────────────────────────────────────────────
rango_tipico_inf = media_lib - desv_lib
rango_tipico_sup = media_lib + desv_lib
print(f"\n  Rango típico (±1σ) : {rango_tipico_inf:.0f} – {rango_tipico_sup:.0f}")
fuera_rango = [s for s in scores_extendidos if s < rango_tipico_inf or s > rango_tipico_sup]
print(f"  Clientes fuera de rango: {len(fuera_rango)} → scores: {fuera_rango}")

"""---
## 🔍 Sección 10 — Los 4 Sospechosos + Detección en Python Puro
*(Sesiones 11 y 12)*

El analista anterior te entregó una muestra **sin limpiar**. Detecta los 4 problemas.

"""

# Dataset con los 4 problemas clásicos inyectados
registros_bnpl_sucios = [
    {"id": 1,  "score": 552,  "income": 68529.5,  "segment": "Medium Risk",  "default": 0},
    {"id": 2,  "score": None, "income": 7247.8,   "segment": "High Risk",    "default": 0},  # 🔴 NULO
    {"id": 3,  "score": 471,  "income": 41582.3,  "segment": "HIGH RISK",    "default": 0},  # 🔴 INCONSISTENCIA
    {"id": 4,  "score": 300,  "income": None,     "segment": "High Risk",    "default": 1},  # 🔴 NULO
    {"id": 5,  "score": 512,  "income": 42845.5,  "segment": "Medium Risk",  "default": 0},
    {"id": 5,  "score": 512,  "income": 42845.5,  "segment": "Medium Risk",  "default": 0},  # 🔴 DUPLICADO
    {"id": 6,  "score": 729,  "income": 79950.3,  "segment": "Low Risk",     "default": 0},
    {"id": 7,  "score": 9500, "income": 43192.3,  "segment": "High Risk",    "default": 0},  # 🔴 OUTLIER (score máx=850)
    {"id": 8,  "score": 369,  "income": 9434.8,   "segment": "  high risk ", "default": 1},  # 🔴 INCONSISTENCIA
    {"id": 9,  "score": 306,  "income": 14821.4,  "segment": "High Risk",    "default": 1},
    {"id": 10, "score": 318,  "income": 6737.9,   "segment": "High Risk",    "default": 0},
]

# ─────────────────────────────────────────────────────
# EJERCICIO 10.1 — Sospechoso 1: NULOS (None)
# ─────────────────────────────────────────────────────
nulos_score  = [r for r in registros_bnpl_sucios if r["score"] ___ None]
nulos_income = [r for r in registros_bnpl_sucios if r["income"] ___ None]
print(f"🔴 Sospechoso 1 - Nulos en 'score'   : {len(nulos_score)} registros → IDs: {[r['id'] for r in nulos_score]}")
print(f"🔴 Sospechoso 1 - Nulos en 'income'  : {len(nulos_income)} registros → IDs: {[r['id'] for r in nulos_income]}")

# ─────────────────────────────────────────────────────
# EJERCICIO 10.2 — Sospechoso 2: DUPLICADOS
# ─────────────────────────────────────────────────────
ids_vistos   = []
ids_duplicados = []
for r in registros_bnpl_sucios:
    if r["id"] in ids_vistos:
        ids_duplicados.append(r["id"])
    else:
        ids_vistos.append(r["id"])
print(f"🔴 Sospechoso 2 - Duplicados          : {len(ids_duplicados)} → IDs: {ids_duplicados}")

# ─────────────────────────────────────────────────────
# EJERCICIO 10.3 — Sospechoso 3: INCONSISTENCIAS de texto
# ─────────────────────────────────────────────────────
segmentos_validos = {"Low Risk", "Medium Risk", "High Risk"}
inconsistencias = [r for r in registros_bnpl_sucios
                   if r["segment"].strip() not in ___]
print(f"🔴 Sospechoso 3 - Inconsistencias     : {len(inconsistencias)}")
for r in inconsistencias:
    print(f"   ID {r['id']} → segmento: '{r['segment']}'")

# ─────────────────────────────────────────────────────
# EJERCICIO 10.4 — Sospechoso 4: OUTLIERS (credit_score fuera de 300–850)
# ─────────────────────────────────────────────────────
outliers_score = [r for r in registros_bnpl_sucios
                  if r["score"] is not None and (r["score"] < ___ or r["score"] > ___)]
print(f"🔴 Sospechoso 4 - Outliers de score   : {len(outliers_score)}")
for r in outliers_score:
    print(f"   ID {r['id']} → score: {r['score']} (fuera del rango 300–850)")

print(f"\n✅ Resumen: {len(nulos_score)+len(nulos_income)} nulos | {len(ids_duplicados)} duplicados | {len(inconsistencias)} inconsistencias | {len(outliers_score)} outliers")

"""---
## 🐼 Sección 11 — Limpieza con Pandas
*(Sesiones 13 y 14)*

Ahora sí cargamos el dataset real con **3,500 transacciones** de CreditGuard.

"""

import pandas as pd

# ─────────────────────────────────────────────────────
# FASE 0 — Carga del dataset real
# ─────────────────────────────────────────────────────
# Opción A: Google Colab — subir el archivo y usar este path:
# df = pd.read_csv("Buy_Now_Pay_Later_BNPL_CreditRisk_Dataset.csv")
# Opción B: URL directa (si el instructor la publica):
# df = pd.read_csv("URL_DEL_ARCHIVO")

# Para el ejercicio, usamos la ruta local:
df = pd.read_csv("Buy_Now_Pay_Later_BNPL_CreditRisk_Dataset.csv")
print("✅ Dataset CreditGuard cargado exitosamente")

"""### 🔬 Los 6 Comandos de Inspección Profesional
*(Sesión 14)*
"""

# ─────────────────────────────────────────────────────
# EJERCICIO 11.1 — Radiografía del Dataset (los 6 comandos)
# ─────────────────────────────────────────────────────

# Comando 1 — Shape: ¿de qué tamaño es nuestro expediente?
print("=" * 50)
print(f"Registros: {df.shape[0]:,}  |  Columnas: {df.shape[1]}")

# Comando 2 — Head: primer vistazo a los datos
print("\n📋 Primeras 3 filas:")
display(df.___(3))

# Comando 3 — Info: tipos de datos y valores nulos
print("\n📋 Estructura del dataset:")
df.___()

# Comando 4 — Describe: estadísticas instantáneas
print("\n📋 Estadísticas descriptivas:")
display(df.___().round(2))

# Comando 5 — isnull().sum(): mapa de valores faltantes
print("\n❓ Valores nulos por columna:")
print(df.isnull().___())
print(f"   Total nulos en todo el dataset: {df.isnull().sum().sum()}")

# Comando 6 — value_counts: distribución de la variable target
print("\n🎯 Distribución del TARGET (default_flag):")
print(df["default_flag"].___())
print("\n🎯 Distribución por Segmento:")
print(df["customer_segment"].___())

# ─────────────────────────────────────────────────────
# EJERCICIO 11.2 — dropna, fillna y drop_duplicates
# ─────────────────────────────────────────────────────
print(f"Filas antes de limpieza: {len(df):,}")

# a) Duplicados: detectar y eliminar
duplicados = df.___(subset="user_id").sum()
print(f"Duplicados detectados  : {duplicados}")
df = df.___(subset=["user_id","transaction_date"]).reset_index(drop=True)
print(f"Filas después de drop_duplicates: {len(df):,}")

# b) Nulos: verifica la columna más probable de tener nulos
nulos_por_col = df.isnull().sum()
cols_con_nulos = nulos_por_col[nulos_por_col > 0]
if len(cols_con_nulos) > 0:
    print(f"\nColumnas con nulos:\n{cols_con_nulos}")
    # Rellena columnas numéricas con la mediana (práctica clínica recomendada)
    for col in df.select_dtypes(include="number").columns:
        if df[col].isnull().sum() > 0:
            df[col] = df[col].fillna(df[col].___)
            print(f"  ✅ '{col}' rellenada con mediana: {df[col].median():.2f}")
else:
    print("\n✅ No hay valores nulos en el dataset. ¡Expediente limpio!")

print(f"\nFilas finales: {len(df):,}")

# ─────────────────────────────────────────────────────
# EJERCICIO 11.3 — .str para estandarizar columnas de texto
# ─────────────────────────────────────────────────────
# Imprime los valores únicos antes de estandarizar
print("Antes de limpieza:")
print(f"  employment_type : {sorted(df['employment_type'].unique())}")
print(f"  customer_segment: {sorted(df['customer_segment'].unique())}")
print(f"  location        : {sorted(df['location'].unique())}")

# Estandariza: quita espacios y aplica Title Case
df["employment_type"]  = df["employment_type"].str.___.str.___()
df["customer_segment"] = df["customer_segment"].str.___.str.___()
df["location"]         = df["location"].str.___.str.___()
df["product_category"] = df["product_category"].str.___.str.___()

print("\nDespués de limpieza:")
print(f"  employment_type : {sorted(df['employment_type'].unique())}")
print(f"  customer_segment: {sorted(df['customer_segment'].unique())}")

"""---
## ⚡ Sección 12 — NumPy: El Motor Matemático
*(Sesión 3)*

"""

import numpy as np

# ─────────────────────────────────────────────────────
# EJERCICIO 12.1 — Arrays NumPy desde el DataFrame
# ─────────────────────────────────────────────────────
arr_scores = np.array(df["credit_score"])
arr_dti    = np.array(df["debt_to_income_ratio"])
arr_risk   = np.array(df["risk_score"])

print("=== Arrays CreditGuard ===")
print(f"  arr_scores shape: {arr_scores.___}  dtype: {arr_scores.dtype}")
print(f"  arr_dti    shape: {arr_dti.shape}   dtype: {arr_dti.dtype}")

# ─────────────────────────────────────────────────────
# EJERCICIO 12.2 — Estadísticas vectorizadas (10x más rápido que listas)
# ─────────────────────────────────────────────────────
print("\n=== Estadísticas de Credit Score ===")
print(f"  Media   : {np.___(arr_scores):.2f}")
print(f"  Mediana : {np.___(arr_scores):.2f}")
print(f"  Std Dev : {np.___(arr_scores):.2f}")
print(f"  Mínimo  : {np.___(arr_scores)}")
print(f"  Máximo  : {np.___(arr_scores)}")
print(f"  P25     : {np.percentile(arr_scores, 25):.1f}")
print(f"  P75     : {np.percentile(arr_scores, ___):.1f}")

# ─────────────────────────────────────────────────────
# EJERCICIO 12.3 — Filtrado booleano (el poder real de NumPy)
# ─────────────────────────────────────────────────────
# a) ¿Cuántos clientes tienen score < 400? (zona de alto riesgo)
mask_alto_riesgo = arr_scores < ___
total_alto_riesgo = np.sum(___)
pct_alto_riesgo   = total_alto_riesgo / len(arr_scores) * 100
print(f"\n  Clientes con score < 400 (alto riesgo): {total_alto_riesgo:,} ({pct_alto_riesgo:.1f}%)")

# b) ¿Cuántos tienen DTI > 0.35? (deuda excesiva)
mask_dti_alto = arr_dti > ___
print(f"  Clientes con DTI > 35%: {np.sum(mask_dti_alto):,} ({np.sum(mask_dti_alto)/len(arr_dti)*100:.1f}%)")

# c) Clientes en zona CRÍTICA: score < 400 Y DTI > 0.35 (doble riesgo)
mask_critico = mask_alto_riesgo & mask_dti_alto
print(f"  Clientes en zona CRÍTICA (ambas condiciones): {np.sum(mask_critico):,}")
print(f"  Score promedio en zona crítica: {np.mean(arr_scores[mask_critico]):.1f}")

"""---
## 📊 Sección 13 — Visualización con Matplotlib
*(Sesión 15)*

"""

import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams['figure.dpi'] = 110

# ─────────────────────────────────────────────────────
# EJERCICIO 13.1 — Gráfico de barras: incumplimientos por tipo de empleo
# ─────────────────────────────────────────────────────
default_por_empleo = df.groupby("employment_type")["default_flag"].mean() * 100
empleos   = list(default_por_empleo.index)
tasas     = list(default_por_empleo.values)

plt.figure(figsize=(8, 5))
colores = ["#e74c3c" if t >= 40 else "#f39c12" if t >= 25 else "#2ecc71" for t in tasas]
barras  = plt.___(empleos, tasas, color=colores, edgecolor="white", linewidth=1.2)

# Etiquetas de valor sobre cada barra
for barra, tasa in zip(barras, tasas):
    plt.text(barra.get_x() + barra.get_width()/2, barra.get_height() + 0.5,
             f"{tasa:.1f}%", ha="center", va="bottom", fontsize=10, fontweight="bold")

plt.___("📊 Tasa de Incumplimiento por Tipo de Empleo — CreditGuard", fontsize=13)
plt.___("Tipo de Empleo", fontsize=11)
plt.___("Tasa de Default (%)", fontsize=11)
plt.axhline(y=df["default_flag"].mean()*100, color="navy", linestyle="--",
            linewidth=1.5, label=f"Promedio general: {df['default_flag'].mean()*100:.1f}%")
plt.legend(fontsize=9)
plt.ylim(0, max(tasas) + 10)
plt.tight_layout()
plt.show()

# ─────────────────────────────────────────────────────
# EJERCICIO 13.2 — Histograma: distribución del credit score
# ─────────────────────────────────────────────────────
plt.figure(figsize=(8, 5))
plt.___(df["credit_score"], bins=30, color="#3498db",
             edgecolor="white", linewidth=0.8)
plt.___("📈 Distribución del Credit Score — 3,500 Clientes", fontsize=13)
plt.___("Credit Score (300–850)", fontsize=11)
plt.___("Frecuencia", fontsize=11)
plt.axvline(df["credit_score"].mean(), color="red", linestyle="--",
            linewidth=1.8, label=f"Media: {df['credit_score'].mean():.0f}")
plt.axvline(df["credit_score"].median(), color="orange", linestyle=":",
            linewidth=1.8, label=f"Mediana: {df['credit_score'].median():.0f}")
plt.legend(fontsize=10)
plt.tight_layout()
plt.show()

# ─────────────────────────────────────────────────────
# EJERCICIO 13.3 — Subplots: 2x2 con plt.subplots
# ─────────────────────────────────────────────────────
fig, axes = plt.subplots(2, 2, figsize=(12, 8))
fig.suptitle("📊 Panel de Riesgo CreditGuard — Indicadores Clave", fontsize=14, fontweight="bold")

# Panel 1: Segmentos
segmentos = df["customer_segment"].value_counts()
axes[0,0].bar(segmentos.index, segmentos.values, color=["#2ecc71","#f39c12","#e74c3c"])
axes[0,0].set_title("Distribución por Segmento", fontsize=11)
axes[0,0].set_ylabel("Clientes")
for ax_item in axes[0,0].patches:
    axes[0,0].text(ax_item.get_x()+ax_item.get_width()/2,
                   ax_item.get_height()+10, f"{int(ax_item.get_height()):,}",
                   ha="center", fontsize=9, fontweight="bold")

# Panel 2: Ubicación con más defaults
df_loc = df.groupby("location")["default_flag"].mean() * 100
axes[0,1].bar(df_loc.index, df_loc.values, color="#9b59b6")
axes[0,1].set_title("Tasa de Default por País", fontsize=11)
axes[0,1].set_ylabel("Default (%)")
axes[0,1].axhline(df["default_flag"].mean()*100, color="red", linestyle="--", linewidth=1)

# Panel 3: Histograma DTI
axes[1,0].hist(df["debt_to_income_ratio"], bins=30, color="#e67e22", edgecolor="white")
axes[1,0].set_title("Distribución del Ratio Deuda/Ingreso", fontsize=11)
axes[1,0].set_xlabel("DTI")

# Panel 4: Evolución de cuotas (missed_payments promedio por número de cuotas)
df_cuotas = df.groupby("bnpl_installments")["missed_payments"].mean()
axes[1,1].plot(df_cuotas.index, df_cuotas.values,
               marker="o", color="#1abc9c", linewidth=2, markersize=7)
axes[1,1].set_title("Pagos Perdidos Promedio vs. Cuotas", fontsize=11)
axes[1,1].set_xlabel("Número de Cuotas BNPL")
axes[1,1].set_ylabel("Pagos perdidos promedio")

plt.tight_layout()
plt.show()

"""---
## 🎨 Sección 14 — Visualización Avanzada con Seaborn
*(Sesión 16)*

"""

import seaborn as sns
sns.set_theme(style="whitegrid")

# ─────────────────────────────────────────────────────
# EJERCICIO 14.1 — Barplot con hue: score por empleo y default
# ─────────────────────────────────────────────────────
plt.figure(figsize=(9, 5))
sns.barplot(data=df, x="employment_type", y="credit_score",
            hue="default_flag",
            palette={0:"#2ecc71", 1:"#e74c3c"})
plt.title("📈 Credit Score Promedio por Empleo — Pagó vs Incumplió", fontsize=13)
plt.xlabel("Tipo de Empleo")
plt.ylabel("Credit Score Promedio")
handles, labels = plt.gca().get_legend_handles_labels()
plt.legend(handles, ["✅ Pagó (0)", "⛔ Incumplió (1)"], title="Default", fontsize=9)
plt.tight_layout()
plt.show()

# ─────────────────────────────────────────────────────
# EJERCICIO 14.2 — Scatterplot con hue y alpha
# ─────────────────────────────────────────────────────
muestra = df.sample(n=600, random_state=42)
plt.figure(figsize=(9, 6))
sns.scatterplot(data=muestra,
                x="credit_score",
                y="debt_to_income_ratio",
                hue="customer_segment",
                palette={"Low Risk":"#2ecc71",
                         "Medium Risk":"#f39c12",
                         "High Risk":"#e74c3c"},
                alpha=0.65, s=45)
plt.title("🔍 Score vs. Ratio Deuda/Ingreso por Segmento de Riesgo", fontsize=13)
plt.xlabel("Credit Score")
plt.ylabel("Debt-to-Income Ratio")
plt.legend(title="Segmento", bbox_to_anchor=(1.01, 1))
plt.tight_layout()
plt.show()

# ─────────────────────────────────────────────────────
# EJERCICIO 14.3 — Histplot con kde: distribución del ingreso por segmento
# ─────────────────────────────────────────────────────
plt.figure(figsize=(10, 5))
for seg, color in [("Low Risk","#2ecc71"), ("Medium Risk","#f39c12"), ("High Risk","#e74c3c")]:
    subset = df[df["customer_segment"] == seg]
    sns.histplot(data=subset, x="monthly_income", kde=True,
                 color=color, alpha=0.40, label=seg, bins=30)
plt.title("💰 Distribución de Ingresos por Segmento de Riesgo", fontsize=13)
plt.xlabel("Ingreso Mensual (USD)")
plt.ylabel("Frecuencia")
plt.legend(title="Segmento")
plt.tight_layout()
plt.show()

# ─────────────────────────────────────────────────────
# EJERCICIO 14.4 — DASHBOARD EJECUTIVO: 4 paneles Seaborn
# ─────────────────────────────────────────────────────
fig, axes = plt.subplots(2, 2, figsize=(14, 9))
fig.suptitle("📊 DASHBOARD DE RIESGO — CreditGuard FinTech", fontsize=15, fontweight="bold")

# Panel 1: Tasa de default por tipo de empleo
sns.barplot(data=df, x="employment_type", y="default_flag",
            palette="Set2", errorbar=None, ax=axes[0,0])
axes[0,0].set_title("Default por Tipo de Empleo", fontsize=11)
axes[0,0].set_ylabel("Tasa de Default (0–1)")
axes[0,0].set_xlabel("")

# Panel 2: Boxplot de credit score por segmento
orden_seg = ["Low Risk","Medium Risk","High Risk"]
sns.boxplot(data=df, x="customer_segment", y="credit_score",
            order=orden_seg,
            palette={"Low Risk":"#2ecc71","Medium Risk":"#f39c12","High Risk":"#e74c3c"},
            ax=axes[0,1])
axes[0,1].set_title("Credit Score por Segmento", fontsize=11)
axes[0,1].set_xlabel("")

# Panel 3: Missed payments vs. segmento
sns.barplot(data=df, x="customer_segment", y="missed_payments",
            order=orden_seg,
            palette={"Low Risk":"#2ecc71","Medium Risk":"#f39c12","High Risk":"#e74c3c"},
            errorbar=None, ax=axes[1,0])
axes[1,0].set_title("Pagos Perdidos por Segmento", fontsize=11)
axes[1,0].set_xlabel("")

# Panel 4: Distribución de default por categoría de producto
cat_default = df.groupby("product_category")["default_flag"].mean().sort_values(ascending=False)
axes[1,1].bar(cat_default.index, cat_default.values * 100, color="#8e44ad", edgecolor="white")
axes[1,1].set_title("Tasa de Default por Categoría", fontsize=11)
axes[1,1].set_ylabel("Default (%)")
axes[1,1].axhline(df["default_flag"].mean()*100, color="red", linestyle="--", linewidth=1)

plt.tight_layout()
plt.show()

"""---
## 🕵️ Sección 15 — EDA Parte 1: Las 3 Fases del Detective de Datos
*(Sesión 17)*

Aplica el ciclo completo de Exploración con las 3 fases: Inspección → Limpieza → Interrogatorio.

### 🔬 Fase 1 — Inspección General (ya la hicimos en la Sección 11)

Antes de continuar, responde estas preguntas de diagnóstico:

**¿Cuántas filas y columnas tiene el dataset?** *(escribe aquí)*

**¿Hay columnas con valores nulos?** *(escribe aquí)*

**¿Cuál es el balance del TARGET (`default_flag`)?**
- Total incumplimientos (1): ___
- Total pagos correctos (0): ___
- ¿Está balanceado el dataset? *(escribe aquí)*

### 🔦 Fase 3 — El Interrogatorio: `groupby` y Comparación de Grupos
*(Recordatorio: la Fase 2 fue la limpieza — ya la ejecutamos)*
"""

# ─────────────────────────────────────────────────────
# EJERCICIO 15.1 — groupby: Comparar variables clave entre los que
#                  pagaron (0) y los que incumplieron (1)
# ─────────────────────────────────────────────────────
print("=" * 55)
print("COMPARACIÓN: CLIENTES QUE PAGARON vs. INCUMPLIERON")
print("=" * 55)

variables_clave = ["credit_score", "monthly_income",
                   "debt_to_income_ratio", "missed_payments",
                   "repayment_delay_days", "risk_score"]

for var in variables_clave:
    resultado = df.___("default_flag")[var].mean().round(2)
    print(f"\n  {var}:")
    print(f"    ✅ Pagó (0)    : {resultado[0]}")
    print(f"    ⛔ Incumplió (1): {resultado[1]}")

# ─────────────────────────────────────────────────────
# EJERCICIO 15.2 — Tasa de default por tipo de empleo y ubicación
# ─────────────────────────────────────────────────────
print("\n" + "=" * 55)
print("TASA DE INCUMPLIMIENTO POR TIPO DE EMPLEO")
print("=" * 55)
tasa_empleo = (df.groupby("___")["default_flag"].mean() * 100).round(2)
print(tasa_empleo.sort_values(ascending=False))

print("\n" + "=" * 55)
print("TASA DE INCUMPLIMIENTO POR PAÍS")
print("=" * 55)
tasa_pais = (df.groupby("___")["default_flag"].mean() * 100).round(2)
print(tasa_pais.sort_values(ascending=False))

# ─────────────────────────────────────────────────────
# EJERCICIO 15.3 — Resumen completo por tipo de empleo
# ─────────────────────────────────────────────────────
print("\n" + "=" * 55)
print("PERFIL DE RIESGO POR TIPO DE EMPLEO (RESUMEN)")
print("=" * 55)
resumen = df.groupby("employment_type")[["credit_score","monthly_income",
                                        "missed_payments","default_flag"]].mean().round(2)
display(resumen)

# ─────────────────────────────────────────────────────
# EJERCICIO 15.4 — Visualización del interrogatorio
# ─────────────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(13, 5))
fig.suptitle("⚖️ Diferencias Clave: ¿Qué distingue a quien incumple?", fontsize=13, fontweight="bold")

# Panel izquierdo: Credit Score promedio por grupo
colores_df = {0: "#2ecc71", 1: "#e74c3c"}
sns.barplot(data=df, x="default_flag", y="credit_score",
            palette=colores_df, errorbar=None, ax=axes[0])
axes[0].set_title("Credit Score Promedio", fontsize=12)
axes[0].set_xlabel("Default (0=Pagó | 1=Incumplió)")
axes[0].set_ylabel("Score promedio")
for p in axes[0].patches:
    axes[0].annotate(f"{p.get_height():.0f}",
                     (p.get_x() + p.get_width()/2, p.get_height()),
                     ha="center", va="bottom", fontsize=12, fontweight="bold")

# Panel derecho: Missed Payments promedio
sns.barplot(data=df, x="default_flag", y="missed_payments",
            palette=colores_df, errorbar=None, ax=axes[1])
axes[1].set_title("Pagos Perdidos Promedio", fontsize=12)
axes[1].set_xlabel("Default (0=Pagó | 1=Incumplió)")
axes[1].set_ylabel("Pagos perdidos promedio")
for p in axes[1].patches:
    axes[1].annotate(f"{p.get_height():.2f}",
                     (p.get_x() + p.get_width()/2, p.get_height()),
                     ha="center", va="bottom", fontsize=12, fontweight="bold")

plt.tight_layout()
plt.show()

"""**📝 Veredicto del Interrogatorio (haz doble clic)**

¿Qué diferencias numéricas encontraste entre los que pagan y los que incumplen?
¿Cuál variable muestra la mayor diferencia? ¿Qué le dirías al Director de Riesgo?

*Escribe aquí tu veredicto (2–3 oraciones basadas en los datos):*

---
## 🗺️ Sección 16 — EDA Parte 2: Correlaciones y Mapa de Calor
*(Sesión 18)*
"""

# ─────────────────────────────────────────────────────
# EJERCICIO 16.1 — Seleccionar solo columnas numéricas
# ─────────────────────────────────────────────────────
df_numerico = df.select_dtypes(include=___)
print(f"Columnas numéricas para correlación: {list(df_numerico.columns)}")
print(f"Total: {df_numerico.shape[1]} columnas")

# ─────────────────────────────────────────────────────
# EJERCICIO 16.2 — Matriz de correlación
# ─────────────────────────────────────────────────────
matriz_corr = df_numerico.___()
print("\n=== Top 5 Variables con Mayor Correlación con default_flag ===")
top_corr_default = matriz_corr["default_flag"].drop("default_flag").abs().sort_values(ascending=False).head(5)
print(top_corr_default)

# ─────────────────────────────────────────────────────
# EJERCICIO 16.3 — Mapa de Calor (Heatmap)
# ─────────────────────────────────────────────────────
plt.figure(figsize=(11, 8))
sns.heatmap(matriz_corr,
            annot=___,
            fmt=".2f",
            cmap="coolwarm",
            vmin=___,
            vmax=___,
            linewidths=0.5,
            linecolor="white",
            annot_kws={"size":8})
plt.title("🗺️ Mapa de Calor de Correlaciones — CreditGuard",
          fontsize=14, fontweight="bold", pad=15)
plt.tight_layout()
plt.show()

"""**📝 Leyendo el Mapa de Calor (haz doble clic)**

1. **¿Qué variable tiene la correlación más fuerte con `default_flag`?**
   ¿Es positiva o negativa? ¿Qué significa en términos del negocio?
   *Responde aquí:*

2. **¿Qué variables están más fuertemente correlacionadas entre sí?**
   ¿Tiene sentido lógico? ¿Por qué?
   *Responde aquí:*

3. **¿Qué par de variables tiene la correlación más cercana a 0?**
   ¿Qué significa eso?
   *Responde aquí:*

"""

# ─────────────────────────────────────────────────────
# EJERCICIO 16.4 — Pairplot: Vista de Pájaro
# ─────────────────────────────────────────────────────
muestra_pairplot = df.sample(n=500, random_state=99)

sns.pairplot(muestra_pairplot,
             vars=["credit_score", "debt_to_income_ratio",
                   "missed_payments", "risk_score"],
             hue="customer_segment",
             palette={"Low Risk":"#2ecc71",
                      "Medium Risk":"#f39c12",
                      "High Risk":"#e74c3c"},
             plot_kws={"alpha": 0.5, "s": 18},
             diag_kind="kde")
plt.suptitle("🔭 Pairplot: Detección de Patrones por Segmento de Riesgo",
             y=1.02, fontsize=13)
plt.show()

"""**📝 Interpretación del Pairplot (haz doble clic)**

*¿Los puntos `Low Risk` (verdes) se separan visualmente de los `High Risk` (rojos)?
¿En qué combinación de variables la separación es más clara?
¿Qué le dice esto a un futuro modelo de Machine Learning?*

*Escribe aquí:*

---
# 🏆 RETO FINAL — Pipeline Integrador End-to-End
## *"El Gran Veredicto de CreditGuard"*
*(Sesión 19)*

---

> **Ahora eres el Analista Principal de Riesgo.**
> El Director Ejecutivo y el equipo de Crédito te esperan mañana para una presentación.
> Tu misión: ejecutar el pipeline completo y dejar el cuaderno listo como **Reporte Ejecutivo**.

### 📐 Regla de Oro del Reto Final
> **Cada bloque de código debe ir acompañado de una celda de texto que explique qué hiciste y qué descubriste.**
> *Un código sin interpretación analítica es texto muerto.*

---

### Las 3 Preguntas de Investigación

**Pregunta 1 — La Cacería de Anomalías**
*¿Existen outliers o inconsistencias que deban limpiarse antes de emitir el diagnóstico?*

**Pregunta 2 — El Análisis de Grupos**
*¿Qué diferencias concretas (en números) hay entre los perfiles de clientes Low Risk vs. High Risk?*

**Pregunta 3 — El Veredicto Final**
*¿Cuál es la variable más determinante para predecir un incumplimiento?*

---

### 📏 Rúbrica de Evaluación

| Criterio | Descripción | Puntaje |
|---|---|---|
| Limpieza de datos | ¿Detectaste y trataste correctamente los problemas? ¿Justificaste `fillna` vs `dropna`? | 25 pts |
| Análisis `groupby` | ¿Comparaste los grupos con valores numéricos? ¿Interpretaste las diferencias en texto? | 25 pts |
| Visualización | ¿Tus gráficos tienen título, etiquetas y paleta? ¿Usaste `heatmap` con `annot=True`? | 25 pts |
| Resumen Ejecutivo | ¿Tu conclusión responde las 3 preguntas? ¿Puede entenderla alguien sin Python? | 25 pts |
"""

# ══════════════════════════════════════════════════════
# FASE 1 — PREPARANDO EL TERRENO: IMPORTACIÓN
# ══════════════════════════════════════════════════════
import pandas as pd, numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme(style="whitegrid")

df_final = pd.read_csv("Buy_Now_Pay_Later_BNPL_CreditRisk_Dataset.csv")
print("✅ Dataset CreditGuard listo para el análisis final")
printf = lambda msg: print(msg)
printf(f"   Registros: {df_final.shape[0]:,}  |  Variables: {df_final.shape[1]}")

"""**📝 Celda de texto Fase 1** *(haz doble clic)*

¿De qué trata este dataset? ¿Cuántos registros y variables tiene?
¿En qué industria aplica?

*Escribe aquí:*

"""

# ══════════════════════════════════════════════════════
# FASE 2 — RADIOGRAFÍA: INSPECCIÓN INICIAL
# ══════════════════════════════════════════════════════
print("=== ESTRUCTURA ===")
df_final.info()

print("\n=== ESTADÍSTICAS ===")
display(df_final.describe().round(2))

print("\n=== NULOS ===")
print(df_final.isnull().sum())

print("\n=== BALANCE DEL TARGET ===")
print(df_final["default_flag"].value_counts())
print(df_final["customer_segment"].value_counts())

"""**📝 Celda de texto Fase 2** *(haz doble clic)*

¿Hay valores nulos? ¿Cuántos duplicados detectaste?
¿El dataset está balanceado (50/50) en la variable `default_flag`?

*Escribe aquí:*

"""

# ══════════════════════════════════════════════════════
# FASE 3 — LIMPIEZA: CURAR LAS HERIDAS
# ══════════════════════════════════════════════════════
print(f"Filas antes de limpieza: {len(df_final):,}")

# Elimina duplicados
df_final = df_final.drop_duplicates(subset=["user_id","transaction_date"]).reset_index(drop=True)

# Estandariza columnas de texto
for col in ["employment_type","customer_segment","location","product_category"]:
    df_final[col] = df_final[col].str.strip().str.title()

# Maneja nulos numéricos (si existen)
for col in df_final.select_dtypes(include="number").columns:
    if df_final[col].isnull().sum() > 0:
        df_final[col] = df_final[col].fillna(df_final[col].median())

print(f"Filas después de limpieza: {len(df_final):,}")
print("✅ Dataset limpio y listo para el interrogatorio")

"""**📝 Celda de texto Fase 3** *(haz doble clic)*

¿Qué problemas encontraste y cómo los solucionaste?
¿Por qué elegiste `fillna` con la mediana en lugar de eliminar filas?

*Escribe aquí:*

"""

# ══════════════════════════════════════════════════════
# FASE 4 — EL INTERROGATORIO: groupby + Estadística
# (Pregunta 2: Low Risk vs. High Risk)
# ══════════════════════════════════════════════════════
print("=== PERFIL COMPARATIVO: LOW RISK vs. HIGH RISK ===")
perfil_segmento = df_final[df_final["customer_segment"].isin(["Low Risk","High Risk"])]    .groupby("customer_segment")[["credit_score","monthly_income",
                                   "debt_to_income_ratio","missed_payments",
                                   "repayment_delay_days","risk_score"]].mean().round(2)
display(perfil_segmento)

print("\n=== PREGUNTA 3: Top variables correlacionadas con default_flag ===")
corr_target = df_final.select_dtypes(include="number").corr()["default_flag"]    .drop("default_flag").abs().sort_values(ascending=False)
print(corr_target)

"""**📝 Celda de texto Fase 4 — El Interrogatorio** *(haz doble clic)*

¿Cuál es la diferencia numérica más grande entre Low Risk y High Risk?
¿Cuál es la variable con mayor correlación con `default_flag`?
¿Tiene sentido en la realidad? Explica con palabras simples.

*Escribe aquí:*

"""

# ══════════════════════════════════════════════════════
# FASE 5 — EL ALEGATO VISUAL
# Grfico Estrella: El hallazgo principal
# ══════════════════════════════════════════════════════
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle("⭐ GRÁFICO ESTRELLA: ¿Qué Variable Predice el Default?",
             fontsize=14, fontweight="bold", y=1.02)

# Panel izquierdo: Credit Score promedio por default
colores_def = {0:"#2ecc71", 1:"#e74c3c"}
sns.barplot(data=df_final, x="default_flag", y="credit_score",
            palette=colores_def, errorbar=None, ax=axes[0])
axes[0].set_title("Credit Score: Pagó vs. Incumplió", fontsize=12)
axes[0].set_xlabel("0 = Pagó   |   1 = Incumplió", fontsize=10)
axes[0].set_ylabel("Score promedio")
for p in axes[0].patches:
    axes[0].annotate(f"{p.get_height():.0f}",
                     (p.get_x() + p.get_width()/2, p.get_height()),
                     ha="center", va="bottom", fontsize=13, fontweight="bold")

# Panel derecho: Top 5 correlaciones con default_flag
top5 = df_final.select_dtypes(include="number").corr()["default_flag"]    .drop("default_flag").sort_values()
colores_barras = ["#e74c3c" if v > 0 else "#2ecc71" for v in top5.values]
top5.plot(kind="barh", color=colores_barras, ax=axes[1])
axes[1].set_title("Correlación de Variables con Default Flag", fontsize=12)
axes[1].set_xlabel("Coeficiente de Correlación", fontsize=10)
axes[1].axvline(x=0, color="black", linewidth=0.8, linestyle="--")
axes[1].set_ylabel("")

plt.tight_layout()
plt.show()

"""**📝 Celda de texto Fase 5 — El Gráfico Estrella** *(haz doble clic)*

¿Qué muestra el gráfico de la izquierda? ¿Cuántos puntos de diferencia hay en el score?
¿Qué muestra el gráfico de la derecha? ¿Cuál es la variable "culpable"?

*Escribe aquí:*

---
## 📋 Mi Resumen Ejecutivo — El Veredicto Final

*(Haz doble clic. Escribe para un Director, NO para un programador.)*

---

**Resumen en 1 oración (el hallazgo más importante):**
*Escribe aquí...*

---

**Factores de Riesgo Identificados:**
- Factor 1:
- Factor 2:
- Factor 3:

---

**Mi Recomendación Estratégica para CreditGuard:**
*Basado en los datos, propongo que la empresa... (escribe 2–3 oraciones concretas)*

---

---
# 📢 Sección Final — Data Storytelling: El Pitch Ejecutivo
*(Sesión 20)*

---

## Del Código a las Decisiones: El Traductor Universal

Recuerda: tu trabajo no termina cuando el código compila sin errores.
El verdadero éxito ocurre cuando el Director de Riesgo toma una decisión
basada en la evidencia que tú procesaste.

### Los 3 Pilares del Data Storytelling

| Pilar | Nombre | Herramienta |
|---|---|---|
| 1 | Los Datos — La Evidencia | `groupby`, `.corr()` |
| 2 | La Visualización — El Escenario | `sns.barplot`, `heatmap` |
| 3 | La Narrativa — El Mensaje | Celda Markdown en Colab |

### La Regla de Oro
> **Está estrictamente prohibido mencionar código en tu pitch.**
> El Director no sabe qué es `.groupby()`. Él habla de pérdidas, clientes y acciones.
> **Vende la historia, no la sintaxis.**

---
## Marco CPDA — Estructura el Pitch Ejecutivo (3 minutos)

| Letra | Elemento | Pregunta que responde | Tiempo |
|---|---|---|---|
| **C** | Contexto | ¿De qué trata el dataset y qué empresa representa? | 20 seg |
| **P** | Problema | ¿Qué pregunta o misterio intentabas resolver? | 20 seg |
| **D** | Descubrimiento | ¿Qué patrón encontraste? → *Muestra tu Gráfico Estrella* | 90 seg |
| **A** | Acción | ¿Qué política o solución recomiendas? | 30 seg |
"""

# ═══════════════════════════════════════════════════
# EL GRÁFICO ESTRELLA DEL PITCH — CreditGuard
# (Ejecuta esta celda para generar tu evidencia visual)
# ═══════════════════════════════════════════════════
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle("⭐ EVIDENCIA: ¿Qué perfil de cliente incumple su pago BNPL?",
             fontsize=14, fontweight="bold", y=1.02)

# Panel izquierdo: Score promedio por segmento
orden_seg = ["Low Risk","Medium Risk","High Risk"]
score_seg  = df_final.groupby("customer_segment")["credit_score"].mean().reindex(orden_seg)
colores_s  = ["#2ecc71","#f39c12","#e74c3c"]
bars = axes[0].bar(score_seg.index, score_seg.values, color=colores_s,
                   edgecolor="white", linewidth=1.2)
axes[0].set_title("Credit Score Promedio por Segmento", fontsize=12)
axes[0].set_ylabel("Credit Score (300–850)")
for bar, val in zip(bars, score_seg.values):
    axes[0].annotate(f"{val:.0f}",
                     (bar.get_x() + bar.get_width()/2, bar.get_height()),
                     ha="center", va="bottom", fontsize=12, fontweight="bold")

# Panel derecho: Top correlaciones con default_flag
corr_def = df_final.select_dtypes(include="number").corr()["default_flag"].drop("default_flag").sort_values()
colores_c = ["#e74c3c" if v > 0 else "#2ecc71" for v in corr_def.values]
corr_def.plot(kind="barh", color=colores_c, ax=axes[1], edgecolor="white")
axes[1].set_title("Factores que más influyen en el Incumplimiento", fontsize=12)
axes[1].set_xlabel("Correlación con Default Flag")
axes[1].axvline(x=0, color="black", linewidth=0.8, linestyle="--")
axes[1].set_ylabel("")

plt.tight_layout()
plt.show()

print("\n=== Números Clave para tu Pitch ===")
tasa_global = df_final["default_flag"].mean() * 100
print(f"📊 Tasa de incumplimiento global    : {tasa_global:.1f}%")
print(f"📈 Score promedio Low Risk          : {df_final[df_final['customer_segment']=='Low Risk']['credit_score'].mean():.0f}")
print(f"📉 Score promedio High Risk         : {df_final[df_final['customer_segment']=='High Risk']['credit_score'].mean():.0f}")
print(f"🏦 Empleado con mayor default       : {(df_final.groupby('employment_type')['default_flag'].mean()*100).idxmax()}")

"""---
## 📝 Mi Plantilla CPDA — Prepara tu Pitch Aquí

*(Haz doble clic. Completa cada sección. CERO código, CERO términos técnicos.)*

---

### C — Contexto *(20 segundos)*

> *¿De qué trata tu dataset? ¿Cuántos clientes analizaste? ¿En qué empresa aplica?*

**Escribe aquí:**
Analizamos el historial de transacciones de _______ clientes de CreditGuard,
una FinTech que opera en __ países y ofrece crédito en cuotas para compras de consumo.

---

### P — Problema *(20 segundos)*

> *¿Qué pregunta de investigación intentabas responder?*

**Escribe aquí:**
La pregunta central fue: ¿qué características tiene un cliente que...?

---

### D — Descubrimiento *(90 segundos — aquí proyectas tu Gráfico Estrella)*

> *¿Cuál fue tu hallazgo más importante? Incluye el número clave que lo respalda.*

**Escribe aquí:**
El hallazgo más importante es que... el factor más determinante es...
Los clientes de Alto Riesgo tienen un score promedio de ___ vs. ___ en los de Bajo Riesgo,
una diferencia de ___ puntos que explica el ___% de los incumplimientos.

---

### A — Acción *(30 segundos)*

> *¿Qué recomendación concreta propones? ¿Quién debe decidir? ¿Qué recursos se necesitan?*

**Escribe aquí:**
Recomendamos que CreditGuard implemente una política de...
Clientes con score < ___ y ratio deuda/ingreso > ___% deberían...
Esta medida podría reducir los incumplimientos en un estimado de...

---

---
## 🏅 Rúbrica de Evaluación — Examen Final Módulo 1

| Sección | Tema | Sesiones | Puntaje |
|---|---|---|---|
| Sección 1 | Formulación del problema, Target, Features, tipo de análisis | 1–2 | 5 pts |
| Sección 2 | Variables, tipos de datos, f-strings | 2, 5–6 | 5 pts |
| Sección 3 | Limpieza de texto: .strip .lower .title .replace, for | 6, 13 | 5 pts |
| Sección 4 | Listas: indexación, slicing, max, min, count, append | 2, 7 | 5 pts |
| Sección 5 | Diccionarios, Tuplas, Sets | 7 | 5 pts |
| Sección 6 | if/elif/else con penalización DTI | 7–8 | 5 pts |
| Sección 7 | Funciones, for con enumerate, while | 7–8 | 5 pts |
| Sección 8 | Estadística manual: media, mediana, moda, rango | 9 | 5 pts |
| Sección 9 | Módulo statistics: mean, median, mode, stdev | 10 | 5 pts |
| Sección 10 | Detección de los 4 sospechosos en Python puro | 11–12 | 5 pts |
| Sección 11 | Pandas: 6 comandos, fillna, dropna, drop_duplicates, .str | 13–14 | 10 pts |
| Sección 12 | NumPy: arrays, estadísticas, filtrado booleano | 3 | 5 pts |
| Sección 13 | Matplotlib: bar, hist, subplots 2×2, personalización | 15 | 5 pts |
| Sección 14 | Seaborn: barplot(hue), scatterplot(hue), histplot(kde), dashboard | 16 | 5 pts |
| Sección 15 | EDA Fase 1: groupby, comparación de grupos, veredicto | 17 | 5 pts |
| Sección 16 | EDA Fase 2: heatmap, selectdtypes, pairplot, interpretación | 18 | 5 pts |
| 🏆 Reto Final | Pipeline end-to-end + Markdown analítico (4 criterios S19) | 19 | 10 pts |
| 📢 Data Storytelling | Plantilla CPDA completa + Pitch oral de 3 min | 20 | 10 pts |
| **TOTAL** | | | **100 pts** |

---

### 🎓 Criterios de Calidad Transversales (aplican a todo el cuaderno)
- ✅ Cada bloque de código va acompañado de una celda Markdown de interpretación
- ✅ Todos los gráficos tienen título, etiquetas en ambos ejes y leyenda
- ✅ El Resumen Ejecutivo puede ser leído por un directivo sin conocimientos de Python
- ✅ El cuaderno corre de principio a fin sin errores (Run All)
"""