# -*- coding: utf-8 -*-
"""Ejercicio Integrador: Sistema de Análisis de Ventas — ModaData

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u-YfXBx9ScHutxHqmxJntwGml0dhKqFh

# 👗 Ejercicio Integrador: Sistema de Análisis de Ventas — ModaData
### Fecha limite de entrega Domingo 3 de mayo 23:59 horas, compartir por este medio

---

**Escenario:**
Eres el **Analista de Datos** de *ModaData*, una cadena de tiendas de ropa.
El gerente general necesita un reporte que:
1. Identifique qué productos se venden más según temporada y categoría.
2. Detecte clientes con alto riesgo de no regresar (churn).
3. Calcule estadísticas de ventas y genere visualizaciones para la junta mensual.

---
| Sección | Temas cubiertos | Sesiones |
|---|---|---|
| 1 | Conceptos, flujo de trabajo y formulación de preguntas | 1 y 2 |
| 2 | Variables, tipos de datos, print y f-strings | 2, 5 y 6 |
| 3 | Limpieza de strings y casting | 6 |
| 4 | Listas y sus operaciones | 2 y 7 |
| 5 | Diccionarios, Tuplas y Sets | 7 |
| 6 | Control de flujo: if / elif / else | 7 y 8 |
| 7 | Bucles for / while y Funciones | 7 y 8 |
| 8 | NumPy: estadísticas básicas | 3 |
| 9 | Pandas: DataFrame y filtrado | 3 |
| 10 | Visualización con Matplotlib y Seaborn | 3 |

---
## 📌 Sección 1 — Conceptos y Formulación de Preguntas
*(Sesiones 1 y 2)*

El gerente te presenta el problema:

> *"Las ventas bajaron un 20% este trimestre y no sé por qué.
> Necesito entender qué está pasando con nuestros clientes."*

**Ejercicio 1.1 — Piensa como Científico de Datos**

Haz **doble clic** en esta celda y completa los espacios:

- **Problema vago (original):** *"Las ventas bajaron un 20% este trimestre y no sé por qué. Necesito entender qué está pasando con nuestros clientes."*

- **Traducción a pregunta de datos:** *(específica y medible)*

- **Tipo de análisis:** *(Descriptivo / Diagnóstico / Predictivo / Prescriptivo)*
  - Justificación:

- **Columna Objetivo (Target):**

- **Pistas (Features) — mínimo 4 columnas:**
  1.
  2.
  3.
  4.

- **Tu rol en este proyecto:** *(Data Analyst / Data Scientist / Data Engineer)*

---
## 🐍 Sección 2 — Variables, Tipos de Datos y f-strings
*(Sesiones 2, 5 y 6)*

Registra los datos del primer cliente del día en la tienda.
"""

# ─────────────────────────────────────────────────────
# EJERCICIO 2.1 — Crea el perfil del cliente con el tipo de dato correcto
# ─────────────────────────────────────────────────────
# nombre_cliente   → str   → "Laura Martínez"
# edad_cliente     → int   → 29
# total_compra     → float → 1250.75
# es_cliente_vip   → bool  → True
# categoria_compra → str   → "Ropa de mujer"

nombre_cliente   = ___
edad_cliente     = ___
total_compra     = ___
es_cliente_vip   = ___
categoria_compra = ___

# ─────────────────────────────────────────────────────
# EJERCICIO 2.2 — Imprime el ticket usando f-strings
# Salida esperada:
#   Cliente: Laura Martínez | Edad: 29 | VIP: True | Total: $1250.75 MXN
# ─────────────────────────────────────────────────────
print(f"___")

# ─────────────────────────────────────────────────────
# EJERCICIO 2.3 — Verifica los tipos con type()
# ─────────────────────────────────────────────────────
print("\nVerificación de tipos:")
print(f"  nombre_cliente  → {type(nombre_cliente)}")
print(f"  edad_cliente    → {___}")
print(f"  total_compra    → {___}")
print(f"  es_cliente_vip  → {___}")

"""---
## 🧹 Sección 3 — Limpieza de Strings y Casting
*(Sesión 6)*

El sistema de caja exportó los datos con errores. ¡Hay que limpiarlos!

"""

# Datos SUCIOS del sistema de caja
nombre_sucio    = "  SOFIA REYES "    # espacios + todo mayúsculas
ciudad_sucia    = "guadalajara"       # todo minúsculas
precio_texto    = "899,99"            # coma en lugar de punto
cantidad_texto  = "3"                 # número guardado como texto

# ─────────────────────────────────────────────────────
# EJERCICIO 3.1 — Limpia cada variable
# ─────────────────────────────────────────────────────
nombre_limpio  = nombre_sucio.___().___()     # strip + title
ciudad_limpia  = ciudad_sucia.___()           # title
precio_limpio  = precio_texto.___(",", ".")   # reemplaza coma

# ─────────────────────────────────────────────────────
# EJERCICIO 3.2 — Casting: convierte a números para operar
# ─────────────────────────────────────────────────────
precio_real    = ___(precio_limpio)    # float
cantidad_real  = ___(cantidad_texto)   # int
subtotal       = precio_real * cantidad_real
descuento      = subtotal * 0.10       # 10% descuento VIP
total_final    = subtotal - descuento

print("=== Ticket de Compra ===")
print(f"  Cliente  : {nombre_limpio}")
print(f"  Ciudad   : {ciudad_limpia}")
print(f"  Precio   : ${precio_real:.2f} × {cantidad_real} pzas")
print(f"  Subtotal : ${subtotal:.2f}")
print(f"  Desc. 10%: -${descuento:.2f}")
print(f"  TOTAL    : ${total_final:.2f} MXN")

"""---
## 📋 Sección 4 — Listas y sus Operaciones
*(Sesiones 2 y 7)*

"""

# ─────────────────────────────────────────────────────
# EJERCICIO 4.1 — Listas del dataset de ventas
# ─────────────────────────────────────────────────────
columnas_ventas = ["cliente", "edad", "categoria", "total_compra",
                   "es_vip", "dias_sin_comprar", "ciudad", "calificacion"]

ventas_semana = [1250.75, 890.00, 3400.50, 450.00, 2100.00, 780.25]

# ─────────────────────────────────────────────────────
# EJERCICIO 4.2 — Operaciones con listas
# ─────────────────────────────────────────────────────

# a) ¿Cuántas columnas tiene el dataset?
print(f"Total de columnas: {___(columnas_ventas)}")

# b) Primera columna (índice correcto)
print(f"Primera columna  : {columnas_ventas[___]}")

# c) Última columna (índice negativo)
print(f"Última columna   : {columnas_ventas[___]}")

# d) Solo las pistas / Features (todas menos la última)
solo_pistas = columnas_ventas[___]
print(f"Features         : {solo_pistas}")

# e) Agrega la columna "num_devoluciones"
columnas_ventas.___("num_devoluciones")
print(f"Dataset actualizado: {columnas_ventas}")

# f) ¿Está "total_compra" en las columnas?
if ___ in columnas_ventas:
    print("✅ La columna 'total_compra' SÍ está en el dataset")
else:
    print("❌ No está")

# g) ¿Cuál fue la venta más alta de la semana? (usa max())
print(f"Venta máxima     : ${max(ventas_semana):.2f}")
print(f"Venta mínima     : ${min(ventas_semana):.2f}")

"""---
## 🗂️ Sección 5 — Diccionarios, Tuplas y Sets
*(Sesión 7)*

"""

# ─────────────────────────────────────────────────────
# EJERCICIO 5.1 — Perfil del cliente como Diccionario
# ─────────────────────────────────────────────────────
perfil_cliente = {
    "nombre"           : ___,   # str   → "Pedro Sánchez"
    "edad"             : ___,   # int   → 35
    "total_compra"     : ___,   # float → 2350.00
    "es_vip"           : ___,   # bool  → True
    "dias_sin_comprar" : ___,   # int   → 45
    "categoria"        : ___    # str   → "Ropa de hombre"
}

print("=== Perfil del Cliente ===")
print(f"Nombre           : {perfil_cliente[___]}")
print(f"Última compra    : hace {perfil_cliente['dias_sin_comprar']} días")
print(f"Total gastado    : ${perfil_cliente[___]:.2f}")
print(f"VIP              : {perfil_cliente['es_vip']}")

# ─────────────────────────────────────────────────────
# EJERCICIO 5.2 — Tupla con datos fijos de la tienda (no deben cambiar)
# ─────────────────────────────────────────────────────
info_tienda = ("ModaData CDMX", "Av. Insurgentes 500", 2019)  # nombre, dirección, año apertura

print(f"\nTienda  : {info_tienda[0]}")
print(f"Dirección: {info_tienda[1]}")
print(f"Fundada  : {info_tienda[2]}")

# ─────────────────────────────────────────────────────
# EJERCICIO 5.3 — Set para obtener categorías únicas
# ─────────────────────────────────────────────────────
todas_categorias = ["Ropa de mujer", "Calzado", "Ropa de mujer",
                    "Accesorios", "Calzado", "Ropa de hombre",
                    "Accesorios", "Ropa de mujer"]

categorias_unicas = ___(todas_categorias)

print(f"\nRegistros totales  : {len(todas_categorias)}")
print(f"Categorías únicas  : {len(categorias_unicas)}")
print(f"Categorías         : {categorias_unicas}")

"""---
## 🚦 Sección 6 — Control de Flujo: if / elif / else
*(Sesiones 7 y 8)*

Clasifica automáticamente el **riesgo de churn** (abandono) de cada cliente
según cuántos días lleva sin comprar.

| Días sin comprar | Riesgo | Acción |
|---|---|---|
| > 90 días | 🔴 CRÍTICO | Llamar y ofrecer cupón del 30% |
| 30 – 90 días | 🟡 MODERADO | Enviar email con promoción |
| < 30 días | 🟢 ACTIVO | Ninguna acción requerida |

Adicionalmente: si el cliente **es VIP** y está en riesgo MODERADO → sube a CRÍTICO.

"""

# Usa el perfil del cliente de la Sección 5
dias        = perfil_cliente["dias_sin_comprar"]   # 45
es_vip      = perfil_cliente["es_vip"]             # True
nombre_cli  = perfil_cliente["nombre"]

# ─────────────────────────────────────────────────────
# EJERCICIO 6.1 — Clasifica el riesgo de churn
# ─────────────────────────────────────────────────────
if dias > ___:
    riesgo = "🔴 CRÍTICO"
    accion = "Llamar y ofrecer cupón del 30%"
elif dias >= ___:
    riesgo = "🟡 MODERADO"
    accion = "Enviar email con promoción"
else:
    riesgo = "🟢 ACTIVO"
    accion = "Ninguna acción requerida"

# Si es VIP y está en MODERADO → sube a CRÍTICO
if es_vip and riesgo == "🟡 MODERADO":
    riesgo = "🔴 CRÍTICO"
    accion = "Llamar al cliente VIP con oferta exclusiva"

print(f"=== Análisis de Churn: {nombre_cli} ===")
print(f"Días sin comprar : {dias}")
print(f"Cliente VIP      : {es_vip}")
print(f"Riesgo           : {riesgo}")
print(f"Acción sugerida  : {accion}")

"""---
## 🔄 Sección 7 — Bucles for / while y Funciones
*(Sesiones 7 y 8)*

"""

# Base de datos del mes
clientes_mes = [
    {"nombre": "Laura Martínez",  "edad": 29, "total_compra": 1250.75, "es_vip": True,  "dias_sin_comprar": 10, "categoria": "Ropa de mujer"},
    {"nombre": "Pedro Sánchez",   "edad": 35, "total_compra": 2350.00, "es_vip": True,  "dias_sin_comprar": 45, "categoria": "Ropa de hombre"},
    {"nombre": "Sofía Reyes",     "edad": 22, "total_compra":  890.00, "es_vip": False, "dias_sin_comprar": 95, "categoria": "Calzado"},
    {"nombre": "Andrés Jiménez",  "edad": 41, "total_compra": 3400.50, "es_vip": True,  "dias_sin_comprar": 5,  "categoria": "Accesorios"},
    {"nombre": "Carmen López",    "edad": 55, "total_compra":  450.00, "es_vip": False, "dias_sin_comprar": 120,"categoria": "Ropa de mujer"},
    {"nombre": "Roberto Fuentes", "edad": 38, "total_compra": 2100.00, "es_vip": False, "dias_sin_comprar": 60, "categoria": "Ropa de hombre"},
]

# ─────────────────────────────────────────────────────
# EJERCICIO 7.1 — Función reutilizable de riesgo de churn
# ─────────────────────────────────────────────────────
def clasificar_churn(dias_sin_comprar, es_vip):
    """Devuelve el nivel de riesgo de churn como string."""
    if dias_sin_comprar > ___:
        riesgo = "🔴 CRÍTICO"
    elif dias_sin_comprar >= ___:
        riesgo = "🟡 MODERADO"
    else:
        riesgo = "🟢 ACTIVO"

    if es_vip and riesgo == "🟡 MODERADO":
        riesgo = "🔴 CRÍTICO"
    return riesgo

# Prueba
print(clasificar_churn(45, True))    # 🔴 CRÍTICO
print(clasificar_churn(10, False))   # 🟢 ACTIVO

# ─────────────────────────────────────────────────────
# EJERCICIO 7.2 — Bucle for: reporte de churn
# ─────────────────────────────────────────────────────
print("\n=== REPORTE DE CHURN — MODADATA ===")
print(f"{'#':<4} {'Nombre':<20} {'Días':>5} {'Riesgo'}")
print("-" * 50)

criticos = 0
for i, cliente in enumerate(clientes_mes, 1):
    riesgo = clasificar_churn(cliente["dias_sin_comprar"], cliente["es_vip"])
    print(f"{i:<4} {cliente['nombre']:<20} {cliente['dias_sin_comprar']:>4}d  {riesgo}")
    if "CRÍTICO" in riesgo:
        criticos += 1

print("-" * 50)
print(f"Clientes en riesgo CRÍTICO: {criticos} de {len(clientes_mes)}")

# ─────────────────────────────────────────────────────
# EJERCICIO 7.3 — while: acumula ventas hasta alcanzar la meta
# ─────────────────────────────────────────────────────
print("\n=== Progreso hacia la meta mensual ===")
meta_ventas = 5000.00
acumulado   = 0
i = 0

while acumulado < meta_ventas and i < len(clientes_mes):
    acumulado += clientes_mes[i]["total_compra"]
    print(f"  + ${clientes_mes[i]['total_compra']:.2f} → Acumulado: ${acumulado:.2f}")
    i += 1

if acumulado >= meta_ventas:
    print(f"✅ Meta de ${meta_ventas:.2f} alcanzada con {i} clientes!")
else:
    print(f"⚠️ Meta no alcanzada. Faltan ${meta_ventas - acumulado:.2f}")

"""---
## 🔢 Sección 8 — NumPy: Estadísticas Básicas
*(Sesión 3)*

"""

import numpy as np

# ─────────────────────────────────────────────────────
# EJERCICIO 8.1 — Array NumPy con los totales de compra
# ─────────────────────────────────────────────────────
ventas = [c["total_compra"] for c in clientes_mes]
ventas_np = np.array(___)

print("=== Estadísticas de Ventas del Mes ===")
print(f"Ventas individuales: {ventas_np}")
print(f"Total del mes      : ${np.sum(ventas_np):,.2f}")
print(f"Ticket promedio    : ${np.mean(ventas_np):,.2f}")
print(f"Venta mínima       : ${np.min(ventas_np):,.2f}")
print(f"Venta máxima       : ${np.max(ventas_np):,.2f}")
print(f"Desv. estándar     : ${np.std(ventas_np):,.2f}")

# ─────────────────────────────────────────────────────
# EJERCICIO 8.2 — ¿Cuántos clientes superaron el ticket promedio?
# ─────────────────────────────────────────────────────
promedio = np.mean(ventas_np)
sobre_promedio = ventas_np > ___
print(f"\nClientes sobre el promedio: {np.sum(sobre_promedio)} de {len(ventas_np)}")
print(f"Sus ventas: {ventas_np[sobre_promedio]}")

"""---
## 🐼 Sección 9 — Pandas: DataFrame y Análisis
*(Sesión 3)*

"""

import pandas as pd

# ─────────────────────────────────────────────────────
# EJERCICIO 9.1 — Crea el DataFrame
# ─────────────────────────────────────────────────────
df = pd.DataFrame(___)

print("=== Dataset ModaData ===")
print(df)
print(f"\nDimensiones: {df.shape[0]} filas × {df.shape[1]} columnas")
print(f"\nTipos de datos:\n{df.dtypes}")

# ─────────────────────────────────────────────────────
# EJERCICIO 9.2 — Agrega la columna de riesgo de churn
# ─────────────────────────────────────────────────────
df["riesgo_churn"] = df.apply(
    lambda row: clasificar_churn(row["dias_sin_comprar"], row["es_vip"]), axis=1
)
print("\n=== Churn por cliente ===")
print(df[["nombre", "dias_sin_comprar", "es_vip", "riesgo_churn"]])

# ─────────────────────────────────────────────────────
# EJERCICIO 9.3 — Filtra solo los clientes en riesgo CRÍTICO
# ─────────────────────────────────────────────────────
criticos = df[df["riesgo_churn"].str.contains(___)]   # "CRÍTICO"
print(f"\n=== Clientes CRÍTICOS ({len(criticos)}) ===")
print(criticos[["nombre", "total_compra", "dias_sin_comprar"]])

# ─────────────────────────────────────────────────────
# EJERCICIO 9.4 — Ventas por categoría
# ─────────────────────────────────────────────────────
print("\n=== Ventas por Categoría ===")
print(df.groupby("categoria")["total_compra"].sum().sort_values(ascending=False).round(2))

# Estadísticas descriptivas
print("\n=== Estadísticas ===")
print(df[["edad", "total_compra", "dias_sin_comprar"]].describe().round(2))

"""---
## 📊 Sección 10 — Visualización con Matplotlib y Seaborn
*(Sesión 3)*

"""

import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="whitegrid", palette="husl")
fig, axes = plt.subplots(1, 3, figsize=(16, 5))

# ── Gráfica 1: Ventas por cliente (barras horizontales) ──────────
colores = ["#e74c3c" if "CRÍTICO" in r else "#f39c12" if "MODERADO" in r else "#2ecc71"
           for r in df["riesgo_churn"]]

axes[0].barh(df["nombre"], df["total_compra"], color=colores, edgecolor="white")
axes[0].set_title("Venta por Cliente\n🔴Crítico 🟡Moderado 🟢Activo", fontsize=12, fontweight="bold")
axes[0].set_xlabel("Total de compra (MXN)")

# ── Gráfica 2: Ventas por categoría (barras verticales) ──────────
ventas_cat = df.groupby("categoria")["total_compra"].sum().sort_values()
axes[1].bar(ventas_cat.index, ventas_cat.values, color="#3498db", edgecolor="white")
axes[1].set_title("Ventas por Categoría", fontsize=12, fontweight="bold")
axes[1].set_xlabel("Categoría")
axes[1].set_ylabel("Total (MXN)")
axes[1].tick_params(axis="x", rotation=15)

# ── Gráfica 3: Distribución del riesgo de churn (pastel) ─────────
conteo_riesgo = df["riesgo_churn"].value_counts()
colores_p = ["#e74c3c" if "CRÍTICO" in x else "#f39c12" if "MODERADO" in x else "#2ecc71"
             for x in conteo_riesgo.index]
axes[2].pie(conteo_riesgo, labels=conteo_riesgo.index, colors=colores_p,
            autopct="%1.1f%%", startangle=90,
            wedgeprops={"edgecolor": "white", "linewidth": 2})
axes[2].set_title("Distribución de Riesgo de Churn", fontsize=12, fontweight="bold")

plt.suptitle("📊 Reporte Mensual — ModaData", fontsize=15, fontweight="bold", y=1.02)
plt.tight_layout()
plt.savefig("reporte_modadata.png", dpi=150, bbox_inches="tight")
plt.show()
print("✅ Gráfica guardada como reporte_modadata.png")

"""---
## 🏆 Reto Final — Todo Junto
*(Integrador Sesiones 1–8)*

Completa la función `generar_reporte_ventas()` que resume todo el análisis en una sola llamada.

"""

def generar_reporte_ventas(lista_clientes):
    """Genera el reporte de ventas y churn automático del mes."""
    import numpy as np

    # Paso 1 — Total de clientes
    total = ___(lista_clientes)

    # Paso 2 — Ventas totales y promedio con NumPy
    ventas = [c["total_compra"] for c in lista_clientes]
    ventas_np   = np.array(ventas)
    total_ventas = np.___(ventas_np)
    ticket_prom  = np.___(ventas_np)

    # Paso 3 y 4 — Reporte de churn + conteo críticos
    criticos = 0
    print("\n" + "="*58)
    print("       REPORTE MENSUAL — MODADATA")
    print("="*58)
    for ___ in lista_clientes:
        riesgo = clasificar_churn(c["dias_sin_comprar"], c["es_vip"])
        print(f"  {c['nombre']:<22} ${c['total_compra']:>8.2f}  {riesgo}")
        if ___ in riesgo:
            criticos += 1

    # Paso 5 — % clientes VIP
    vips = sum(1 for c in lista_clientes if c[___] == True)
    pct_vip = (vips / total) * 100

    # Paso 6 — Resumen ejecutivo con f-string
    print("="*58)
    print(f"  Total clientes   : {total}")
    print(f"  Ventas del mes   : ${total_ventas:,.2f} MXN")
    print(f"  Ticket promedio  : ${ticket_prom:,.2f} MXN")
    print(f"  Riesgo crítico   : {criticos} clientes")
    print(f"  Clientes VIP     : {vips} ({pct_vip:.1f}%)")
    print("="*58)

# Ejecuta el reporte
generar_reporte_ventas(clientes_mes)