# -*- coding: utf-8 -*-
"""Sesión 8: Estructuras de Datos y Control de Flujo (Práctica)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13QiqwpVf-bNKjLAUhImRV1Lh1q5AYZnv

# Sesión 8: Estructuras de Datos y Control de Flujo (Práctica)

### La Analogía de la Automatización
Como científicos de datos, nos enfrentamos a bases de datos con miles o millones de registros (como expedientes de pacientes, encuestas o mediciones). Es humanamente imposible revisar dato por dato de forma manual.

Imagina que estás en una enorme central de correos. En lugar de clasificar cada carta a mano leyendo el código postal, instalas un sistema de clasificación automática que separa los envíos a la velocidad de la luz. En programación hacemos exactamente lo mismo: le enseñamos a la computadora las reglas lógicas para que ella revise miles de datos por nosotros en fracciones de segundo.
* **La banda transportadora** que mueve todas las cartas sin detenerse es nuestro bucle **`for`**.
* **Las compuertas** que deciden si una carta va a la derecha o a la izquierda son nuestros condicionales **`if/elif/else`**.

---

### El Poder de las Funciones: Tu Máquina de Procesamiento
Para empaquetar esta automatización, crearemos nuestras propias **Funciones** (`def`).

Piensa en una función como si fuera una "Máquina de Procesamiento" que tú mismo diseñas. A esta máquina:
1. Le introduces materia prima por un lado (tus **datos de entrada** o parámetros).
2. La máquina sigue una receta interna para procesarlos (usando **`if/elif/else`**).
3. Por el otro lado te entrega un producto terminado (usando la instrucción **`return`**).

¡Hoy dejarás de usar las herramientas que otros hicieron y empezarás a inventar tus propias máquinas personalizadas! Veamos cómo se construye una. Ejecuta la siguiente celda:
"""

# EJEMPLO GUIADO: Nuestra máquina clasificadora de pacientes

# 1. Diseñamos la máquina (def) y le decimos que recibirá una temperatura
def clasificar_fiebre(temperatura):

    # 2. La máquina procesa el dato (if / else)
    if temperatura >= 38.0:
        resultado = "🚨 Alerta: El paciente tiene fiebre."
    else:
        resultado = "✅ Normal: Temperatura estable."

    # 3. La máquina devuelve el producto terminado (return)
    return resultado

# ¡Vamos a probar la máquina!
paciente_1 = clasificar_fiebre(39.5)
paciente_2 = clasificar_fiebre(36.5)

print(f"Reporte 1: {paciente_1}")
print(f"Reporte 2: {paciente_2}")

"""> 💡 **La diferencia entre `print` y `return`:** Hasta ahora usábamos `print()` solo para que nosotros, los humanos, pudiéramos leer la pantalla. Pero `return` es mucho más poderoso: hace que la función *devuelva* el dato real a la computadora para que podamos guardarlo en una variable nueva y seguir trabajando con él.

---

### Ejercicio 1.1: Tu Primera Máquina de Procesamiento

¡Es tu turno de ser el ingeniero! Vamos a construir una máquina para el departamento de Recursos Humanos.

**Tu Tarea:**

1. En la celda de abajo, crea una función llamada `evaluar_candidato` que reciba un dato llamado `calificacion`.
2. Adentro de la función, usa un `if` para revisar si la calificación es **mayor o igual a 80**.
3. Si lo es, haz que la función **devuelva** (`return`) el texto `"Aprobado"`.
4. De lo contrario (`else`), haz que devuelva `"Rechazado"`.
5. Fuera de la función, pruébala con dos calificaciones (ej. 85 y 60) e imprime los resultados con **f-string**.

"""

# Escribe aquí tu código para el Ejercicio 1.1:
# def evaluar_candidato(calificacion):
#     ...

"""---

### 🆕 `elif` dentro de Funciones: Clasificadores de Más de 2 Niveles

Tu función `evaluar_candidato` tiene dos resultados posibles: Aprobado o Rechazado. Pero en el mundo real los sistemas de evaluación casi siempre tienen **más niveles**. Para eso combinamos `def` con `elif`.

La estructura es exactamente la misma que aprendiste en S7, solo que ahora vive *dentro* de una función:

```python
def mi_funcion(parametro):
    if parametro >= valor_alto:
        return "Nivel Alto"
    elif parametro >= valor_medio:
        return "Nivel Medio"
    else:
        return "Nivel Bajo"
```

> ⚠️ **Truco profesional:** Cuando una función hace `return`, se detiene inmediatamente. No necesitas escribir `elif` después de `return` — Python ya sabe que si llegó a la segunda condición, la primera fue falsa. Muchos programadores prefieren esta versión más limpia:
> ```python
> def mi_funcion(x):
>     if x >= 90: return "Alto"
>     if x >= 60: return "Medio"
>     return "Bajo"          # Si ninguna fue True, llega aquí
> ```

Vamos a actualizar nuestra máquina de RH para que clasifique en **tres niveles**:

"""

# ============================================================
# ELIF EN FUNCIONES: Clasificador de 3 niveles
# ============================================================

def evaluar_candidato_v2(calificacion):
    """Clasifica un candidato en 3 niveles según su calificación."""
    if calificacion >= 90:
        return "🏆 Sobresaliente — contratación inmediata"
    elif calificacion >= 70:
        return "✅ Aprobado — en lista de espera"
    else:
        return "❌ Rechazado — no cumple el mínimo"

# ─── Probamos los 3 niveles ──────────────────────────────────
candidatos_prueba = [("Ana", 95), ("Beto", 75), ("Carla", 58)]

print("--- Resultados de selección ---")
for nombre, cal in candidatos_prueba:
    nivel = evaluar_candidato_v2(cal)
    print(f"  {nombre} ({cal} pts): {nivel}")

# ─── Observa la diferencia con la versión anterior ──────────
print("\n--- Comparativa v1 vs v2 ---")
print(f"  evaluar_candidato(75)    → solo 'Aprobado'")
print(f"  evaluar_candidato_v2(75) → '{evaluar_candidato_v2(75)}'")

"""---

## Parte 2: De la Teoría a la Práctica (Manipulación de Colecciones)

Ahora que sabemos cómo organizar nuestra información, vamos a enseñarle a la computadora a modificarla en tiempo real.

### Jugando con Listas: Nuestro tren de datos

Una lista es una colección ordenada. Imagina que estás registrando las temperaturas de un paciente durante la semana o recolectando encuestas diarias, pero necesitas actualizar tu base de datos.

| Método | ¿Qué hace? | Ejemplo |
|---|---|---|
| `lista[0]` | Accede al elemento en la posición 0 | `temperaturas[0]` → `36.5` |
| `.append(x)` | Agrega `x` al **final** de la lista | `temperaturas.append(37.1)` |
| `.remove(x)` | Elimina la **primera aparición** de `x` | `temperaturas.remove(38.2)` |
| `len(lista)` | Cuenta cuántos elementos tiene | `len(temperaturas)` → `4` |

Ejecuta este código:

"""

# 1. Creamos nuestra lista inicial
temperaturas = [36.5, 37.0, 38.2, 36.8]
print(f"Lista inicial ({len(temperaturas)} registros): {temperaturas}")

# 2. Accedemos al primer día (recuerda, ¡Python empieza desde el 0!)
print(f"Temperatura del día 1 (índice 0): {temperaturas[0]}°C")
print(f"Temperatura del último día (índice -1): {temperaturas[-1]}°C")

# 3. Agregamos un nuevo registro al final usando 'append'
temperaturas.append(37.1)
print(f"\nDespués de append(37.1): {temperaturas}")

# 4. Quitamos un dato específico usando 'remove'
temperaturas.remove(38.2)
print(f"Después de remove(38.2): {temperaturas}")
print(f"Total de registros finales: {len(temperaturas)}")

"""### ¿Qué sucede en la memoria de la computadora paso a paso?

* **Al acceder (`[0]`):** La computadora va directamente a la posición inicial de la memoria. Es como saber el número exacto del vagón de un tren y abrir su puerta directamente sin tener que recorrer todos los demás.
* **Al agregar (`append`):** La máquina crea un espacio de memoria nuevo y lo "engancha" al final de tu lista original.
* **Al quitar (`remove`):** Busca el valor exacto que le pediste, lo destruye y recorre todos los elementos siguientes para cerrar el hueco.

---

### Diccionarios Dinámicos: Actualizando expedientes

Los diccionarios asocian valores a claves específicas (etiquetas). Son la estructura perfecta para perfiles de clientes, pacientes o trámites legales, porque la información cambia constantemente.

"""

# 1. Creamos el expediente inicial
expediente = {
    "nombre": "Carlos",
    "estado_tramite": "En revisión",
    "peso_kg": 75.5
}
print(f"Expediente original: {expediente}")

# 2. Actualizamos valores existentes (misma sintaxis que asignar una variable)
expediente["estado_tramite"] = "Aprobado"
expediente["peso_kg"] = 74.0
print(f"\nExpediente actualizado: {expediente}")

# 3. Accedemos a un valor específico por su llave
print(f"\nNombre del paciente: {expediente['nombre']}")
print(f"Estado del trámite: {expediente['estado_tramite']}")

"""---

### 🆕 Métodos Esenciales de los Diccionarios

Actualizar valores es solo el principio. Los diccionarios tienen tres métodos que usarás **constantemente** en Ciencia de Datos, especialmente cuando no sabes de antemano cuántas llaves tiene el diccionario:

| Método | ¿Qué devuelve? | Uso típico |
|---|---|---|
| `.keys()` | Todas las **llaves** (nombres de columnas) | Ver qué variables tiene un registro |
| `.values()` | Todos los **valores** | Operar sobre los datos sin saber las llaves |
| `.items()` | Pares **(llave, valor)** juntos | Recorrer el diccionario con `for` |
| `.get("llave", default)` | El valor, o `default` si la llave no existe | Evitar errores al acceder llaves opcionales |

El más importante para programar es **`.items()`** porque te permite recorrer un diccionario entero con un `for` sin escribir cada llave a mano:
```python
for llave, valor in mi_dict.items():
    print(llave, "→", valor)
```

"""

# ============================================================
# MÉTODOS DE DICCIONARIO EN ACCIÓN
# ============================================================

print("--- .keys() ---")
print(list(expediente.keys()))          # convierte a lista para verlo limpio

print("\n--- .values() ---")
print(list(expediente.values()))

print("\n--- .items() con for (el más útil) ---")
for llave, valor in expediente.items():
    print(f"  {llave}: {valor}")

# .get() — acceso seguro: si la llave no existe, devuelve el valor por defecto
print("\n--- .get() para acceso seguro ---")
diagnostico = expediente.get("diagnostico", "Sin diagnóstico registrado")
print(f"  Diagnóstico: {diagnostico}")   # no lanza error aunque la llave no exista

nombre = expediente.get("nombre", "Desconocido")
print(f"  Nombre: {nombre}")

"""### ¿Qué sucede en la memoria paso a paso?

A diferencia de las listas, aquí no hay posiciones numéricas. La computadora busca directamente la etiqueta `"peso_kg"` o `"estado_tramite"`. Al usar el signo de igual (`=`), le decimos a la máquina que abra esa "caja" específica, deseche el valor anterior e introduzca el nuevo dato. Si la etiqueta no existiera, Python crearía una nueva entrada automáticamente.

---

### Ejercicio 2.1: El Médico de Guardia

¡Es tu turno de modificar un expediente! Imagina que estás de guardia y necesitas actualizar los datos de tu paciente.

**Tu Tarea:**

1. En la celda de abajo, usa el diccionario `expediente` que acabamos de crear.
2. Agrega una **nueva llave** llamada `"alta_medica"` y asígnale el valor `True` (booleano, sin comillas, con mayúscula inicial).
3. Modifica la llave `"peso_kg"` y ponle el valor `73.5`.
4. Usa un `for` sobre `.items()` para imprimir **todo el expediente** línea por línea con f-string.
5. **RETO EXTRA:** Usa `.get()` para intentar acceder a la llave `"edad"` — si no existe, que imprima `"No registrada"`.

"""

# Escribe aquí tu código para el Ejercicio 2.1:
# Tip: expediente["nueva_llave"] = valor  ← agrega o modifica
# Tip: for llave, valor in expediente.items():  ← recorre el dict

"""---

## Parte 3: Ejemplos Paso a Paso (Creando tus propias herramientas)

Vamos a construir una nueva "máquina de procesamiento". Imagina que necesitas clasificar una medición de forma automática según sus rangos lógicos.

Esta función ya usa `elif` — observa cómo el orden de las condiciones es crítico: primero evaluamos el límite superior (`> 100`) y luego el inferior (`< 50`). Python se detiene en la **primera condición verdadera**.

Ejecuta la siguiente celda:

"""

# 1. Definimos nuestra herramienta y el "ingrediente" que necesita (el valor)
def evaluar_resultado(valor):

    # 2. Aplicamos nuestras reglas de decisión lógicas
    if valor > 100:
        return "🔴 Alto"
    elif valor < 50:
        return "🔵 Bajo"
    else:
        return "🟢 Normal"

print("Máquina 'evaluar_resultado' construida y lista para usarse.")

"""### Aplicación Multidisciplinaria

La verdadera magia de las funciones es que, una vez creadas, son universales: puedes reciclarlas para procesar datos de absolutamente cualquier área de estudio sin tener que reescribir todo el código `if/elif/else`.

Pruébala con estos tres escenarios distintos. Ejecuta la celda:

"""

# Medicina: Evaluando el ritmo cardíaco de un paciente
ritmo_cardiaco = evaluar_resultado(115)
print(f"Ritmo cardíaco (115 bpm): {ritmo_cardiaco}")

# Economía: Clasificando el precio de una acción
precio_accion = evaluar_resultado(45)
print(f"Precio de acción ($45): {precio_accion}")

# Ingeniería: Revisando la presión de una caldera
presion = evaluar_resultado(75)
print(f"Presión de caldera (75 psi): {presion}")

# Procesando una lista completa con for + función
print("\n--- Procesando lista completa automáticamente ---")
mediciones = [("Paciente A", 120), ("Paciente B", 45), ("Paciente C", 88)]
for nombre, valor in mediciones:
    print(f"  {nombre}: {valor} → {evaluar_resultado(valor)}")

"""---

### 🍰 El gran secreto: `return` vs `print`

Quizá notaste que dentro de nuestra función usamos la palabra clave `return` en lugar del clásico `print`. Entender la diferencia entre ambos es vital para un Científico de Datos:

* **`print()` es como mostrar la fotografía de un pastel.** Sirve para que tú (el humano) veas el resultado en la pantalla, pero la computadora no puede "comerse" la foto para seguir trabajando con ella.
* **`return` es como entregar el pastel real.** Le dice a la función: *"Devuélveme el dato concreto y tangible para que pueda guardarlo en una nueva variable o hacer cálculos matemáticos con él"*.

Precisamente porque usamos `return`, pudimos guardar el texto resultante directamente en nuestras variables (`ritmo_cardiaco`, `precio_accion`, `presion`) para imprimirlo después.

---

### Ejercicio 3.1: La Máquina de Descuentos

¡Ponte el delantal, es hora de cocinar tu propio pastel! Imagina que estás programando el sistema de cobro de una clínica. Si un paciente tiene seguro, se le hace un descuento.

**Tu Tarea:**

1. Crea una función llamada `aplicar_descuento` que reciba un parámetro llamado `precio`.
2. Adentro de la función, calcula el nuevo precio multiplicándolo por `0.80` (20% de descuento) y guárdalo en `precio_final`.
3. Usa `return` para devolver el `precio_final`.
4. Fuera de la función, pruébala con un precio de `1000` e imprime el resultado con f-string.
5. **RETO EXTRA:** Modifica la función para que reciba **dos parámetros**: `precio` y `porcentaje_descuento`. Así podrás llamarla con `aplicar_descuento(1000, 0.20)` para 20% o `aplicar_descuento(1000, 0.15)` para 15%.

"""

# Escribe aquí tu código para el Ejercicio 3.1:
# def aplicar_descuento(precio):
#     ...
#     return precio_final

"""---

## Parte 4: Reto Práctico (El Asistente Inteligente)

Llegó el momento de integrar absolutamente todo lo que has aprendido. Vas a construir un programa que evalúe automáticamente a los candidatos de un programa de apoyos económicos.

**Tus instrucciones:**

1. **Tu Base de Datos (Estructuras):** Llena la lista `candidatos` con 3 diccionarios. Cada diccionario debe representar a una persona con dos llaves exactas: `"nombre"` (texto) y `"puntuacion"` (un número del 0 al 100).
2. **El Cerebro (La Función):** Crea una función llamada `asignar_apoyo` que reciba un único parámetro llamado `puntuacion`.
3. **Las Reglas (Control de Flujo):** Dentro de tu función, usa `if`, `elif` y `else` para evaluar la puntuación y devolver (`return`) el resultado:
   * Si la puntuación es **90 o mayor** → `"🏆 Beca"`
   * Si la puntuación es **mayor o igual a 70** → `"✅ Apoyo Parcial"`
   * Si es **menor a 70** → `"❌ Sin Apoyo"`
4. **La Ejecución (Iteración):** Usa el ciclo `for` ya preparado para extraer a cada candidato, pasar su puntuación por tu función y mostrar el veredicto final con f-string.

> 💡 **Pista:** Para acceder al valor de una llave dentro del `for`, usa: `persona["puntuacion"]`

"""

# 1. Tu Base de Datos (Agrega tus 3 diccionarios aquí adentro)
candidatos = [

]

# 2 y 3. Tu Máquina Evaluadora (Define tu función con if/elif/else aquí)



# 4. La Ejecución (El ciclo 'for' revisará la lista completa automáticamente)
print("--- INICIANDO EVALUACIÓN AUTOMÁTICA ---")

for persona in candidatos:
    # Extraemos el nombre y la puntuación de cada diccionario
    nombre_actual   = persona["nombre"]
    puntos_actuales = persona["puntuacion"]

    # ¡Tu turno! Llama a tu función aquí y guarda el resultado en 'veredicto'
    # veredicto = ...

    # Imprime el resultado con f-string
    # print(f"{nombre_actual} ({puntos_actuales} pts): {veredicto}")

print("--- EVALUACIÓN FINALIZADA ---")

"""---

### 🎉 ¡Misión Cumplida!

¡Muchísimas felicidades! Acabas de integrar listas, diccionarios, condicionales (`if/elif/else`), bucles iterativos y funciones personalizadas con `return` en un solo sistema lógico. Al hacer esto, dejaste de ser un espectador de la tecnología y te convertiste en el creador de tus propias herramientas automáticas.

Con este gran hito, **¡has completado con éxito el primer tercio del Módulo 1 de tu diplomado!** Tómate un momento para sentirte muy orgulloso del camino recorrido; has pasado de guardar un simple número en una "caja" a programar asistentes virtuales que toman decisiones administrativas por ti.

---

### 🆕 Puente al Futuro: De tus Diccionarios a Pandas

¿Recuerdas la lista de diccionarios que construiste en el Reto? Acabas de crear, con código puro de Python, algo que tiene exactamente la misma estructura que una tabla de Excel.

En las próximas sesiones trabajaremos con **pandas**, la biblioteca más usada en Ciencia de Datos. Lo que tienes que saber ahora es que **pandas convierte tu lista de diccionarios en una tabla profesional con una sola línea de código**:

```python
import pandas as pd
tabla = pd.DataFrame(mi_lista_de_diccionarios)
```

Cada diccionario se convierte en una **fila** y cada llave se convierte en una **columna**. Exactamente lo que viste en S7 con la analogía de Excel.

> 🔮 **Spoiler:** Cuando en S9 escribas `df.head()`, `df.describe()` o `df[df['edad'] > 50]`, estarás haciendo exactamente lo mismo que hiciste hoy con `for` + `if` — solo que pandas lo hace en una sola línea para millones de filas.
"""

# ============================================================
# PUENTE A PANDAS: Tu lista de dicts → tabla profesional
# ============================================================
import pandas as pd

# La misma estructura que construiste en el Reto, con datos de ejemplo
candidatos_ejemplo = [
    {"nombre": "Ana",   "puntuacion": 95, "area": "Medicina"},
    {"nombre": "Beto",  "puntuacion": 73, "area": "Economía"},
    {"nombre": "Carla", "puntuacion": 58, "area": "Ingeniería"},
    {"nombre": "Diego", "puntuacion": 91, "area": "Medicina"},
]

# Una sola línea convierte tu lista en una tabla
df = pd.DataFrame(candidatos_ejemplo)

print("--- Tu lista de diccionarios como tabla pandas ---")
print(df)

print("\n--- El mismo filtro que hiciste con for+if, en una línea ---")
print(df[df["puntuacion"] >= 70])    # equivalente a tu bucle for con if

print("\n¡Esto es lo que aprenderás en profundidad en las próximas sesiones! 🚀")