# -*- coding: utf-8 -*-
"""Sesión 1: Introducción a la Ciencia de Datos (y tus primeras herramientas)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CtBbYcFwIRAvMe2Z4x-Bnpc2JQecGPUP

# Sesión 1: Introducción a la Ciencia de Datos (y tus primeras herramientas)

### ¿Qué es la Ciencia de Datos?

En términos sencillos, la ciencia de datos es el arte de extraer conocimiento valioso y respuestas útiles a partir de información desordenada. Es un campo interdisciplinario que combina tres grandes áreas:

1. **Conocimiento de Matemáticas y Estadística:** Para entender las probabilidades y los números.
2. **Habilidades de Programación (Informática):** Para procesar grandes cantidades de información rápidamente.
3. **Experiencia en tu área (Dominio):** Para saber qué preguntas hacer y cómo interpretar los resultados en tu campo específico (¡aquí es donde tu carrera actual brilla!).

**La analogía del Chef:** Imagina que la Ciencia de Datos es como la alta cocina. Los datos son tus ingredientes crudos. Las matemáticas y estadísticas son las proporciones y la receta que garantizan que el platillo tenga buen sabor. La programación representa tus herramientas de cocina (licuadoras, hornos, cuchillos). Y finalmente, tu experiencia es el paladar del chef: saber exactamente qué platillo quiere el cliente y cómo presentarlo.

---

### Aclarando Conceptos: Las Matrioshkas de los Datos

Es muy común que en las noticias escuches términos que parecen significar lo mismo, pero no lo son. Imagina estos conceptos como muñecas rusas (Matrioshkas), una dentro de la otra:

* **Inteligencia Artificial (IA):** Es la muñeca más grande. Es el concepto amplio de crear sistemas que puedan imitar la inteligencia y el comportamiento humano.
* **Machine Learning (Aprendizaje Automático):** Es la muñeca de en medio. Son las técnicas y algoritmos específicos que permiten a las computadoras "aprender" a partir de los datos para hacer predicciones, sin tener que programarles las reglas una por una.
* **Ciencia de Datos (Data Science):** Es una disciplina independiente que utiliza el Machine Learning y la IA (junto con la estadística y el análisis tradicional) para resolver problemas del mundo real.

---

### 🧠 Deep Learning: La Cuarta Muñeca

Dentro del Machine Learning existe una técnica tan poderosa que merece su propio nombre: el **Deep Learning (Aprendizaje Profundo)**. Si las Matrioshkas anteriores son las muñecas grandes, el Deep Learning es la más pequeña y más sofisticada de todas.

Utiliza redes de neuronas artificiales inspiradas en el cerebro humano para aprender de cantidades masivas de información. Es la tecnología detrás de:
- El reconocimiento de voz de Siri y Alexa
- Los autos autónomos de Tesla
- La generación de imágenes con IA (DALL-E, Midjourney)
- Los chatbots de lenguaje como ChatGPT

**Resumen visual de las Matrioshkas completas:**
- 🪆 **Inteligencia Artificial** → Todo sistema que imita la inteligencia humana
  - 🪆 **Machine Learning** → Aprende de los datos sin reglas programadas
    - 🪆 **Deep Learning** → Redes neuronales para datos complejos (imágenes, voz, texto)
- 🔬 **Ciencia de Datos** → Disciplina que usa todo lo anterior para resolver problemas reales

---

### 👥 ¿Cuál es tu Rol? Los 3 Perfiles del Mundo de los Datos

Cuando escuchas "ciencia de datos", en realidad hay tres profesiones distintas que trabajan juntas. Es importante que sepas cuál te interesa:

| Rol | ¿Qué hace? | Herramientas clave |
|---|---|---|
| **Data Analyst** (Analista) | Explora datos del pasado, crea reportes y dashboards para responder preguntas de negocio | Excel, SQL, Power BI, Tableau |
| **Data Scientist** (Científico) | Construye modelos predictivos y encuentra patrones ocultos usando estadística y ML | Python, R, Scikit-learn |
| **Data Engineer** (Ingeniero) | Construye y mantiene las "tuberías" por donde fluyen los datos a gran escala | SQL, Spark, Cloud (AWS/GCP) |

> 💡 **Analogía de la cocina:** El Data Engineer construye la cocina y trae los ingredientes. El Data Analyst lee el menú y reporta qué platillos se vendieron más. El Data Scientist inventa recetas nuevas y predice qué querrá comer el cliente mañana.

En este diplomado nos enfocaremos principalmente en las habilidades de **Data Analyst y Data Scientist**.

---

### La Materia Prima: Tipos de Datos

Para poder cocinar, necesitas conocer tus ingredientes. En el mundo real, los datos vienen en dos grandes sabores:

* **Datos Estructurados:** Son los que están perfectamente ordenados en filas y columnas, como una hoja de cálculo o la base de datos de pacientes de un hospital.
* **Datos No Estructurados:** Son más caóticos y libres. Incluyen textos de encuestas sociológicas, imágenes de radiografías, grabaciones de audio o secuencias genéticas. ¡La ciencia de datos moderna nos permite analizar ambos!

---

### Aplicaciones en el Mundo Real

La ciencia de datos no es ciencia ficción, ya está transformando todas las disciplinas:

* **Salud y Medicina:** Analizando historiales clínicos o genética para predecir la aparición de enfermedades complejas, permitiendo tratamientos tempranos y personalizados.
* **Ciencias Sociales:** Aplicando análisis de sentimiento en redes sociales para entender cómo reacciona la población ante una política pública, detectando tendencias sociales antes que las encuestas tradicionales.
* **Biología y Ecología:** Usando sensores y datos meteorológicos para predecir zonas de deforestación o rutas migratorias de especies en peligro, apoyando la conservación preventiva.
* **Química y Materiales:** Acelerando el descubrimiento de nuevos fármacos al simular cómo interactúan millones de compuestos a nivel molecular.
* **Ingeniería y Logística:** Optimizando las rutas de transporte público o de envío de mercancías considerando el tráfico y el clima, ahorrando combustible y reduciendo la huella de carbono.

---

### 💼 ¿Por Qué Aprender Esto Hoy? El Mercado Laboral

La ciencia de datos no es una moda pasajera. Es una de las profesiones con mayor crecimiento y mejor remuneración en México y Latinoamérica:

- 📈 El **World Economic Forum** la clasifica como una de las 5 profesiones más demandadas para 2025–2030
- 💰 En México, un **Data Analyst** gana entre **$18,000 y $35,000 MXN/mes**; un **Data Scientist** entre **$35,000 y $80,000 MXN/mes**
- 🌎 El trabajo es mayormente **remoto**, lo que abre oportunidades globales desde cualquier ciudad
- 🏢 Empresas como BBVA, Cemex, Mercado Libre, Rappi y el gobierno federal tienen equipos de datos en México

> **Lo más valioso:** No necesitas dejar tu carrera actual. Un biólogo que sabe datos vale más que un biólogo que no. Un contador con Python es imbatible. Tu experiencia de dominio + ciencia de datos = perfil único e irrepetible.

---

### El Flujo de Trabajo: El Detective de Datos

El trabajo de un Científico de Datos va mucho más allá de solo escribir código; se trata de resolver problemas. Para lograrlo, seguimos un flujo de trabajo parecido a la investigación de un detective:

1. **Definición del Problema (El Caso):** Antes de tocar los datos, debemos entender qué queremos resolver. ¿Queremos predecir la efectividad de un tratamiento o mejorar el diseño de un puente?
2. **Recolección de Datos (Búsqueda de Pistas):** Recopilamos información de diversas fuentes, como experimentos en el laboratorio, encuestas, o sensores.
3. **Limpieza de Datos (Filtrar el Ruido):** En la vida real, los datos vienen sucios (faltan valores, hay errores o duplicados). Aquí corregimos y preparamos la información.
4. **Análisis Exploratorio (Conectar los Hilos):** Usamos gráficos simples y estadísticas para buscar patrones o tendencias ocultas.
5. **Modelado (La Hipótesis Final):** Utilizamos algoritmos para crear modelos que nos permitan describir la situación actual o predecir el futuro.
6. **Visualización y Decisión (Ante el Juez):** Traducimos nuestros hallazgos matemáticos a un lenguaje que cualquier persona pueda entender usando gráficos, permitiendo decisiones inteligentes.

---

# Parte 2: Tu Entorno de Trabajo y tu Primer Código

### Nuestra Herramienta: Google Colab
Para hacer ciencia de datos necesitamos un lugar que nos permita anotar nuestras ideas, explicar nuestros análisis y, al mismo tiempo, realizar los cálculos matemáticos. Para lograr esto sin complicaciones, utilizaremos **Google Colab**.

Imagina que Google Colab es como un "cuaderno de notas inteligente" que vive en internet. En una libreta universitaria tradicional solo puedes escribir texto, pero en este cuaderno interactivo puedes intercalar tus apuntes (como si fueran las instrucciones de una receta) con "bloques mágicos" (celdas de código) donde la computadora hace el trabajo pesado por ti.

Lo mejor de todo es que no tienes que instalar absolutamente nada en tu computadora ni preocuparte por configuraciones complejas; todo el procesamiento lo hacen las supercomputadoras de Google. Tú solo necesitas tu navegador web, internet y tu curiosidad.

### Tu Primer Código en Python
En nuestro cuaderno inteligente, el idioma que usaremos para comunicarnos con la computadora se llama **Python**. Es uno de los lenguajes de programación más populares del mundo porque fue diseñado para ser amigable y fácil de leer, ¡casi como si estuvieras leyendo instrucciones en inglés!

Vamos a escribir tu primer programa. Es completamente normal sentir un poco de nervios si nunca has programado, pero te garantizo algo: **es imposible que rompas algo**. Lo peor que puede pasar es que la computadora no te entienda a la primera, y si eso ocurre, simplemente reescribimos la instrucción.

Aquí tienes tu primer bloque de código:
"""

print("¡Hola, Ciencia de Datos! Hoy descubro mi nuevo superpoder.")

"""#### ¿Qué está pasando exactamente aquí?

Vamos a desarmar esta pequeña instrucción pieza por pieza para entender su lógica:

* **`print`**: Esta es una *función* en Python. En programación, una función es como una orden directa o un verbo. La palabra *print* significa "imprimir", así que literalmente le estamos diciendo a la máquina: *"Imprime este mensaje en la pantalla"*.
* **`()` (Los paréntesis)**: Los paréntesis funcionan como una caja o un sobre de envío. Todo lo que pongas dentro de ellos es lo que la función `print` va a procesar y mostrar.
* **`""` (Las comillas)**: Las comillas son cruciales. Le dicen a Python: *"Oye, esto es texto puro para humanos, no intentes hacer cálculos matemáticos ni buscar instrucciones secretas aquí"*. Si omitiéramos las comillas, Python se confundiría intentando buscar una orden matemática que se llame "Hola".

#### ¡Es hora de la magia!

Si observas con atención, al lado izquierdo de la celda de código gris en tu cuaderno hay un pequeño botón redondo con el símbolo de "Play" (reproducir).

Adelante, haz clic en ese botón. Al presionarlo, le estás diciendo a la supercomputadora: *"Lee mis instrucciones y ejecútalas"*. En un par de segundos, verás aparecer tu mensaje justo debajo de la celda.

**¡Felicidades! Acabas de escribir y ejecutar tu primer programa en Python.**

---

### Python como tu Calculadora de Alta Potencia

Además de manejar texto, Python es excepcionalmente bueno con los números (una habilidad indispensable para la ciencia de datos en cualquier disciplina). En una nueva celda de código, intenta escribir una operación matemática simple, por ejemplo:

"""

print(2026 - 1995)

"""*(Nota importante: Aquí no usamos comillas porque queremos que Python reconozca los números y ejecute la operación matemática, en lugar de imprimir literalmente el texto "2026 - 1995").*

¡Presiona Play! Verás el resultado exacto al instante.

---

### El Arte de Equivocarse (¡Los errores son tus mejores maestros!)

En la programación te vas a equivocar. Mucho. Y eso es parte fundamental del aprendizaje. Un error en Python no significa que descompusiste el sistema, simplemente es la computadora diciéndote: *"Perdón, no entendí la gramática de lo que me escribiste, ¿me lo repites?"*.

Vamos a provocar un error a propósito para perderle el miedo a las alertas. En una celda nueva, escribe lo siguiente (nota que **hemos omitido intencionalmente la comilla del final**):

"""

print("Hola mundo )

"""Si le das Play a esa celda, la computadora te devolverá un mensaje de alerta en texto rojo que dice algo como `SyntaxError`. ¡No te asustes! Solo significa "Error de Sintaxis" (o un error de ortografía computacional). Python te está avisando amablemente que abriste una comilla para escribir un texto, pero olvidaste cerrarla al final.

**Tu misión ahora:** Agrega la comilla faltante justo antes del paréntesis final, vuelve a presionar Play y observa cómo el error desaparece mágicamente dando paso a tu mensaje. ¡Acabas de solucionar tu primer "bug" (falla) informático!

---

### ⚡ Errores Comunes en Python (¡Conócelos antes de cometerlos!)

Antes de avanzar, veamos los **3 errores más frecuentes** que cometen los estudiantes en las primeras sesiones. La celda de abajo los demuestra con código ejecutable. Observa bien los resultados:
"""

# ============================================================
# ERRORES COMUNES — Celda demostrativa
# ============================================================

# ❌ ERROR COMÚN #1: Confundir texto con número
# Si pones comillas a un número, Python NO puede hacer matemáticas con él.
edad_texto  = "25"   # Esto es TEXTO (string)
edad_numero = 25     # Esto es un NÚMERO (integer)

print("--- ERROR #1: Tipos de datos ---")
print("Con comillas, el tipo es:", type(edad_texto))    # <class 'str'>
print("Sin comillas, el tipo es:", type(edad_numero))   # <class 'int'>
print()

# ❌ ERROR COMÚN #2: Usar espacios o acentos en nombres de variables
# nombre con acento = "Ana"  ← ESTO FALLA (espacio en el nombre)
# nombre_sin_acento = "Ana"  ← ESTO FUNCIONA ✅
nombre_sin_acento = "Ana"
print("--- ERROR #2: Nombres de variables ---")
print("Variable válida:", nombre_sin_acento)
print()

# ❌ ERROR COMÚN #3: Python distingue MAYÚSCULAS de minúsculas
# Print("hola")  ← FALLA (P mayúscula no existe en Python)
# print("hola")  ← FUNCIONA ✅
print("--- ERROR #3: Mayúsculas y minúsculas ---")
print("Python es sensible a mayúsculas. 'print' funciona, 'Print' no.")
print()
print("✅ ¡Aprendiste los 3 errores más comunes antes de cometerlos!")

"""---

# Parte 3: ¿Qué tipo de información buscamos los Científicos de Datos?

Ahora que ya le perdimos el miedo a Python y a nuestra herramienta de trabajo, hablemos de nuestra materia prima: los datos.

Como científicos de datos, no solo recolectamos números o palabras al azar en una computadora; buscamos patrones ocultos, tendencias y respuestas a preguntas muy específicas del mundo real. Queremos saber cosas como: *¿Qué factores hacen que un tratamiento médico sea exitoso?*, *¿qué características definen a un votante indeciso?*, o *¿cómo influye el nivel educativo en los ingresos de una población?*.

Para responder a esto, primero necesitamos aprender a organizar nuestra información.

### Nuestros "Pacientes de Prueba": Los Datasets Famosos

Cuando un médico o médica está aprendiendo anatomía, no empieza operando a un paciente real en su primer día; primero estudia con modelos anatómicos y simuladores. En la ciencia de datos hacemos exactamente lo mismo.

Antes de enfrentarnos a bases de datos empresariales, hospitalarias o gubernamentales, que suelen estar desordenadas y caóticas, practicamos con conjuntos de datos (llamados **datasets**) de prueba que son famosos en todo el mundo. Algunos de los más conocidos son:

* **El dataset del Titanic:** Contiene información real sobre los pasajeros del famoso barco y quiénes sobrevivieron. Lo usamos para aprender a predecir si una persona sobreviviría basándonos en su edad, género o clase de boleto.
* **El dataset Iris:** Contiene medidas físicas (de pétalos y sépalos) de tres especies de flores. Es considerado el "Hola Mundo" para los biólogos y científicos de datos que aprenden a clasificar cosas en diferentes categorías.
* **El precio de las casas (Housing):** Datos sobre vecindarios (como la tasa de criminalidad o la cercanía a escuelas y carreteras) que usamos para aprender a predecir cuánto costará una vivienda.

Estos datasets son excelentes para aprender porque están limpios, son fáciles de entender y nos permiten ver rápidamente si nuestros análisis y códigos funcionan.

---

### 🚢 Cargando Datos Reales: Tu Primera Vista al Dataset del Titanic

La ciencia de datos de verdad comienza cuando tocamos **datos reales**. Vamos a cargar el dataset del Titanic directamente desde Python usando dos herramientas que serán tus mejores aliadas en el diplomado: **Pandas** y **Seaborn**.

No te preocupes si no entiendes cada línea todavía — eso lo veremos en detalle en las próximas sesiones. Por ahora, el objetivo es que veas con tus propios ojos cómo se ve una tabla de datos real en Python. ¡Ejecuta las tres celdas de abajo en orden!
"""

# ============================================================
# PRIMER VISTAZO A DATOS REALES: El Dataset del Titanic
# ============================================================

# Pandas es nuestra herramienta estrella para manejar tablas de datos
import pandas as pd

# Seaborn es una librería de visualización que incluye datasets famosos listos para usar
import seaborn as sns

# Cargamos el dataset del Titanic directamente (¡sin descargar nada!)
titanic = sns.load_dataset('titanic')

# .head() nos muestra las primeras 5 filas de la tabla
print("📋 Las primeras 5 filas del Titanic:")
titanic.head()

# ¿Cuántos pasajeros tiene este dataset?
filas, columnas = titanic.shape
print(f"📊 Este dataset tiene {filas} pasajeros (filas) y {columnas} características (columnas)")

# Veamos los nombres de todas las columnas (nuestras 'pistas' y nuestro 'objetivo')
print("\n🔍 Las columnas (variables) disponibles son:")
print(titanic.columns.tolist())

# .info() nos da un resumen técnico: tipos de datos y cuántos valores faltan
print("🛠️ Información técnica del dataset:")
titanic.info()

"""### 🔗 Conectando el Código con la Teoría

Acabas de ejecutar tu primer análisis de datos real. Observa lo que acabas de ver:

- Cada **fila** = un pasajero del Titanic (una observación única)
- Cada **columna** = una característica de ese pasajero (una variable)
- La columna **`survived`** = nuestro **Objetivo (Target)** — lo que queremos predecir
- El resto de columnas = nuestras **Pistas (Features)** — edad, clase, sexo, tarifa, etc.

Nota también algo importante en el resultado de `.info()`: algunas columnas muestran un número de valores `non-null` **menor** al total de filas. Eso significa que hay **datos faltantes** (valores vacíos) — y limpiarlos será uno de nuestros trabajos más importantes como Data Scientists. ¡Bienvenido a la vida real!

---

### Anatomía de los Datos: El Caso del Titanic

Imagina que los datos son como una hoja de cálculo gigante. Para entender su anatomía, vamos a mirar las primeras 5 líneas de la lista de pasajeros del Titanic:

| survived (¿Sobrevivió?) | pclass (Clase de boleto) | sex (Sexo) | age (Edad) | fare (Tarifa pagada) |
| --- | --- | --- | --- | --- |
| 0 | 3 | male | 22.0 | 7.2500 |
| 1 | 1 | female | 38.0 | 71.2833 |
| 1 | 3 | female | 26.0 | 7.9250 |
| 1 | 1 | female | 35.0 | 53.1000 |
| 0 | 3 | male | 35.0 | 8.0500 |

*(Nota: En la columna de supervivencia, un "0" significa No, y un "1" significa Sí).*

**¿Cómo se lee esta tabla?**
En la ciencia de datos, estructuramos casi toda nuestra información en dos dimensiones principales:

**1. Las Filas (Observaciones o Registros):** Si miras la tabla de forma horizontal, cada fila representa un caso único o un individuo.

* Si estudias **Sociología**, cada fila sería la respuesta de una persona diferente en tu encuesta.
* Si estudias **Medicina**, cada fila sería el expediente clínico de un paciente individual.
* En nuestra tabla, cada fila es un pasajero distinto del Titanic.

**2. Las Columnas (Variables o Características):** Si miras de forma vertical, cada columna representa una propiedad o atributo que describe a las filas.

* En **Medicina**, las columnas serían características como "Presión arterial", "Edad" o "Tipo de sangre".
* En **Derecho**, podrían ser "Tipo de delito" o "Años de condena".
* Aquí, nuestras variables nos dicen la edad del pasajero, su sexo o cuánto pagó por su boleto.

---

### El Secreto del Modelado: El "Objetivo" vs. las "Pistas"

A través de esta estructura de filas y columnas, nosotros le enseñaremos a la computadora a encontrar reglas lógicas. Para lograr que la máquina aprenda a predecir el futuro, solemos dividir nuestras columnas en dos grupos fundamentales:

* **El Objetivo (Target):** Es la columna que queremos adivinar o predecir. En nuestro ejemplo del Titanic, queremos predecir la columna `survived` (¿esta persona sobrevivió o no?).
* **Las Pistas (Features):** Son todas las demás columnas que usamos para intentar adivinar el objetivo. Usaremos la clase del boleto (`pclass`), el sexo (`sex`), la edad (`age`) y lo que pagaron (`fare`) como nuestras pistas investigativas.

Nuestra meta final en las próximas clases será que Python descubra reglas matemáticas ocultas entre estas variables, por ejemplo: *"Si la pista `sex` es female (mujer) y la pista `pclass` es 1 (primera clase), la probabilidad en la columna objetivo `survived` es muchísimo mayor"*.

---

### 🌸 Explorando el Dataset Iris — El "Hola Mundo" de la Clasificación

Ahora que viste el Titanic, vamos a explorar el segundo dataset famoso: **Iris**. Este conjunto de datos contiene medidas físicas de tres especies de flores. Es el ejemplo clásico para aprender a **clasificar** (separar cosas en categorías). Ejecuta la celda de abajo:
"""

# ============================================================
# EXPLORANDO EL DATASET IRIS
# ============================================================

# Cargamos el dataset Iris (flores con medidas de pétalos y sépalos)
iris = sns.load_dataset('iris')

print("🌸 Primeras 5 filas del Dataset Iris:")
print(iris.head())

print(f"\n📊 Tamaño: {iris.shape[0]} flores medidas, {iris.shape[1]} columnas")

print("\n🌿 Especies de flores incluidas (nuestros 3 posibles Objetivos/Target):")
print(iris['species'].unique())

print("\n📈 Estadísticas básicas de las medidas:")
print(iris.describe())

"""---

# Parte 4: Reto Práctico: Piensa como un Científico de Datos

Para nuestro ejercicio final de hoy, no escribiremos código. El trabajo más importante de un Científico o Científica de Datos ocurre en su cabeza mucho antes de tocar el teclado, estructurando el problema.

> **El Caso Clínico:** Imagina que eres la persona encargada de dirigir una clínica de salud comunitaria. Te has dado cuenta de que muchos pacientes faltan a sus consultas médicas sin cancelar previamente (lo que llamamos *Ausentismo* o *No-Show*). Esto genera pérdidas económicas, desperdicia el valioso tiempo del personal médico y retrasa la atención de personas que realmente lo necesitan de urgencia.

**Tu objetivo:** Usar el enfoque de la Ciencia de Datos para predecir *qué pacientes tienen mayor probabilidad de faltar a su cita médica de mañana*.

Aplicando el "Flujo de trabajo" que vimos al inicio de la clase, reflexiona y responde las siguientes preguntas.

*(💡 **Tip técnico:** Para escribir tus respuestas aquí mismo en Google Colab, simplemente haz **doble clic** sobre esta celda de texto, baja hasta la zona de "Tu respuesta aquí" y comienza a escribir).*

---

### 1. Recolección de Datos (Buscando Pistas)

Si pudieras pedirle al área de sistemas una tabla con la información histórica de todas las citas médicas del último año, ¿qué características (columnas o variables) pedirías porque crees que influyen en que una persona falte? *(Ejemplo: Distancia en kilómetros de su casa a la clínica, si es temporada de lluvias, edad del paciente, etc.)*. Menciona al menos 3 pistas que investigarías.

**Tu respuesta aquí:**

*

---

### 2. Limpieza de Datos (Filtrando el Ruido)

En la vida real, los datos nunca vienen perfectos. ¿Qué tipo de errores, datos absurdos o "suciedad" crees que podrías encontrarte en esa base de datos de pacientes que tendrías que limpiar o corregir antes de poder analizarla? *(Ejemplo: Que alguien haya escrito "mil" en lugar de "1000" en un campo de números).*

**Tu respuesta aquí:**

*

---

### 3. Visualización y Toma de Decisiones (El Veredicto)

Imagina que logramos construir un modelo matemático en Python sumamente exitoso que predice con alta precisión quién va a faltar a su consulta de mañana. ¿Qué decisiones estratégicas o acciones preventivas tomarías en la clínica utilizando esta información para resolver tu problema original?

**Tu respuesta aquí:**

*

"""