# -*- coding: utf-8 -*-
"""Sesión 15: Visualización de Datos (Teoría y Práctica)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Or2PEw0vKqQxKG7R2yV5itLftJ7jLgnM

# Sesión 15: Visualización de Datos (Teoría y Práctica)


### El Poder de la Imagen: ¿Por qué visualizamos datos?
Imagina intentar diagnosticar a un paciente leyendo únicamente una tabla con los millones de números que representan la intensidad de color de cada píxel en una radiografía. Sería humanamente imposible. Sin embargo, cuando la computadora transforma esos números en una imagen, el ojo humano detecta la fractura al instante.

En la ciencia de datos ocurre exactamente lo mismo. Visualizar datos nos permite hacer dos cosas esenciales: **explorar** la información para encontrar anomalías ocultas y **comunicar** nuestros descubrimientos de forma efectiva a los demás (directivos, médicos, clientes).

---

### El Cuarteto de Anscombe: La trampa de los promedios
Para demostrar el peligro de analizar datos "a ciegas", existe un concepto clásico llamado el "Cuarteto de Anscombe". Imagina cuatro conjuntos de datos distintos. Si le pides a Python que calcule su promedio, su mediana y su correlación, los cuatro te darán *exactamente el mismo resultado matemático*. Si solo confías en los números, asumirás que los cuatro grupos son idénticos.

Pero al graficarlos, la realidad te golpea:
* El primer grupo forma una línea recta dispersa.
* El segundo dibuja una curva perfecta.
* El tercero es una línea recta pero con un error extremo que distorsiona todo.
* El cuarto forma una línea totalmente vertical.

**La lección es clara:** las estadísticas puras pueden mentir o esconder información vital. La visualización es tu único mapa de navegación confiable.

---

### Tipos de Gráficos Básicos
No todos los gráficos sirven para lo mismo. Elegir la herramienta correcta es el 90% del éxito en un análisis visual:

1. **Gráfico de Barras:** Es la mejor opción cuando deseas mostrar cómo varía una cantidad a lo largo de un conjunto de categorías. *Ejemplo: Comparar el número total de pacientes por tipo de sangre (A, B, O, AB).*
2. **Gráfico de Líneas:** Úsalo exclusivamente para mostrar tendencias o la evolución de un dato a lo largo de un periodo de tiempo. *Ejemplo: El historial de temperatura de un paciente hora tras hora.*
3. **Gráfico de Dispersión (Scatter):** Es la opción adecuada para visualizar si existe una relación o correlación entre dos valores numéricos diferentes. *Ejemplo: Ver si hay relación entre los años de edad de un paciente y su nivel de colesterol.*
4. **Histograma:** Sirve para ver cómo se distribuye una sola variable continua agrupándola en rangos. *Ejemplo: Ver cuántos pacientes tienes en el rango de 0-10 años, cuántos de 11-20, cuántos de 21-30, etc.*

*(Nota: ¿Y el gráfico de pastel? Los analistas profesionales evitan los gráficos de pastel porque al ojo humano le cuesta mucho comparar áreas y ángulos con precisión. ¡Usa barras en su lugar!)*

---

---

### 📋 Tabla de Referencia: ¿Qué Gráfico Usar?

La elección del gráfico correcto es el 90% del éxito. Úsala como guía rápida:

| Gráfico | Comando Python | Pregunta que responde | Ejemplo médico |
|---|---|---|---|
| **Barras** | `plt.bar()` / `sns.barplot()` | ¿Cuánto hay en cada categoría? | Pacientes por tipo de sangre |
| **Líneas** | `plt.plot()` | ¿Cómo cambia algo a lo largo del tiempo? | Temperatura del paciente por hora |
| **Dispersión** | `sns.scatterplot()` | ¿Existe relación entre dos variables numéricas? | Edad vs nivel de colesterol |
| **Histograma** | `plt.hist()` / `sns.histplot()` | ¿Cómo se distribuye una sola variable? | Rango de edades de los pacientes |

> 🚫 **¿Y el gráfico de pastel?** Los analistas profesionales lo evitan porque el ojo humano
> no puede comparar ángulos con precisión. Si tienes 5 rebanadas parecidas, es imposible
> saber cuál es más grande sin etiquetas. **Usa barras siempre en su lugar.**

---

### Ejercicio 1.1: Gimnasio Mental (El Diseñador Analítico)

Vamos a poner a prueba tu intuición visual. Lee los siguientes tres escenarios de la vida real y decide mentalmente qué gráfico (Barras, Líneas, Dispersión o Histograma) sería el correcto para el reporte.

* **Caso A:** El director del hospital quiere ver si los casos de gripe han subido o bajado a lo largo de los 12 meses del año pasado.
* **Caso B:** Quieres saber qué marca de medicamento (Marca X, Marca Y o Marca Z) fue la más vendida durante el fin de semana.
* **Caso C:** Estás investigando si las personas que consumen más gramos de azúcar al día tienden a tener una presión arterial más alta.

*(**Respuestas:** Caso A: Líneas. Caso B: Barras. Caso C: Dispersión).*

---

## Parte 2: De la Teoría a la Práctica (Nuestros Pinceles Digitales)

Si Pandas es el "motor" que organiza la información, **Matplotlib** y **Seaborn** son nuestro "lienzo y pinceles".

* **Matplotlib:** Es la librería científica estándar para crear gráficos básicos.
* **Seaborn:** Funciona como un juego de pinceles "Premium". Facilita la creación de gráficos estadísticos modernos y atractivos.

### Importando las Herramientas
Ejecuta esta celda para preparar tu área de trabajo con los alias estándar de la industria:
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

print("✅ Herramientas cargadas: Matplotlib, Seaborn y Pandas listos.")

"""### Matplotlib vs Seaborn — ¿Cuándo usar cada uno?

Ambas librerías conviven en el mismo proyecto. La clave es saber el rol de cada una:

| Característica | Matplotlib (`plt`) | Seaborn (`sns`) |
|---|---|---|
| **Tipo** | Librería base / de bajo nivel | Librería de alto nivel (construida sobre Matplotlib) |
| **Cantidad de código** | Más líneas para el mismo resultado | Menos código, más automático |
| **Estética por defecto** | Básica (fondo blanco, sin grid) | Moderna y estadística (`whitegrid`, `darkgrid`) |
| **Mejor para...** | Control total, gráficas simples | Gráficas estadísticas rápidas y bonitas |
| **Ejemplo** | `plt.bar(x, y)` | `sns.barplot(x=x, y=y)` |

> 💡 **Regla práctica:** Usa `sns` para crear el gráfico rápido y bonito, y usa `plt`
> para los ajustes finales (`plt.title()`, `plt.xlabel()`, `plt.show()`).
> ¡Se pueden mezclar en la misma celda!

---

### Nuestro Primer Gráfico

Imagina que diriges una clínica y quieres ver la cantidad de pacientes que acudieron a urgencias en la semana. Ejecuta este código:
"""

# Nuestra base de datos en miniatura
dias_semana = ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes"]
pacientes   = [45, 52, 38, 41, 60]

# Trazamos la línea
plt.plot(dias_semana, pacientes)

# Buenas prácticas: Agregamos un título y etiquetas
plt.title("Ingresos a Urgencias (Semana 1)")
plt.xlabel("Día")
plt.ylabel("Número de Pacientes")

# Mostramos el gráfico
plt.show()

# ──────────────────────────────────────────────────────────────────────
# Personalizando la línea — color, marker y linestyle
# ──────────────────────────────────────────────────────────────────────

dias_semana = ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes"]
pacientes   = [45, 52, 38, 41, 60]

plt.plot(
    dias_semana,
    pacientes,
    color     = "steelblue",  # Color de la línea
    marker    = "o",          # Punto en cada dato (prueba: "s", "^", "D")
    linestyle = "--"          # Tipo de línea (prueba: "-", ":", "-.")
)

plt.title("Ingresos a Urgencias — Semana 1 (Versión Profesional)")
plt.xlabel("Día")
plt.ylabel("Número de Pacientes")
plt.tight_layout()
plt.show()

"""### Los 3 Parámetros de Personalización Esenciales

Con solo 3 parámetros extra en `plt.plot()`, tus gráficas pasan de "básicas"
a "presentables". Aquí las opciones más usadas:

| Parámetro | ¿Qué controla? | Valores comunes |
|---|---|---|
| `color=` | Color de la línea o barra | `"steelblue"`, `"red"`, `"#2ecc71"`, `"coral"` |
| `marker=` | Símbolo en cada punto de dato | `"o"` (círculo), `"s"` (cuadro), `"^"` (triángulo), `"D"` (diamante) |
| `linestyle=` | Tipo de línea | `"-"` (sólida), `"--"` (guiones), `":"` (punteada), `"-."` (rayas y puntos) |

> 🎨 **Consejo:** Cambia los valores en la celda anterior y vuelve a ejecutarla
> para ver el efecto en tiempo real. Probar combinaciones es la mejor forma de aprender.

---

### Ejercicio 2.1: El Gráfico de Barras

**Tu tarea:** Copia el código del primer gráfico en la celda de abajo, pero cambia la instrucción `plt.plot()` por `plt.bar()`. Observa cómo cambia la representación de los datos.
"""

# Escribe aquí tu código para el Ejercicio 2.1:

# ──────────────────────────────────────────────────────────────────────
# Histograma — plt.hist() — ¿Cómo se distribuyen las edades?
# ──────────────────────────────────────────────────────────────────────

edades_pacientes = [22, 25, 28, 30, 22, 35, 40, 38, 45, 50,
                    52, 28, 31, 33, 27, 41, 44, 23, 29, 36]

# bins = cuántas "cubetas" o rangos queremos dividir
plt.hist(edades_pacientes, bins=5, color="steelblue", edgecolor="white")

plt.title("Distribución de Edades de Pacientes")
plt.xlabel("Rango de Edad")
plt.ylabel("Cantidad de Pacientes")
plt.tight_layout()
plt.show()

print("\n¿Qué pasa si cambias bins=5 por bins=10? ¡Pruébalo!")

"""### ¿Qué es `bins` y por qué importa?

El parámetro `bins` controla cuántas **barras** (rangos o "cubetas") usará el
histograma para agrupar los datos. No existe un valor "correcto" universal —
depende de cuántos datos tienes y qué tan detallado quieres la distribución.

| Valor de `bins` | Efecto | Cuándo usarlo |
|---|---|---|
| **Muy bajo** (`bins=3`) | Pocas barras, vista muy general | Cuando quieres mostrar la tendencia gruesa |
| **Ideal** (`bins=10–15`) | Balance entre detalle y claridad | Para la mayoría de presentaciones |
| **Muy alto** (`bins=50`) | Muchas barras delgadas, muy detallado | Solo si tienes miles de datos |

> 🔑 **Regla rápida:** `bins ≈ √(número de datos)`. Si tienes 100 datos, prueba con
> `bins=10`. Si tienes 400 datos, prueba con `bins=20`. Siempre ajusta a ojo.

---

## Parte 3: Exploración con Datos (La Visualización como Análisis)

### El Radar Visual

Para un científico de datos, la visualización es una herramienta de diagnóstico continuo. Nos sirve para auditar la calidad de la información antes de presentar resultados.

### Cazando Valores Atípicos (Outliers)

Si alguien registra una edad de "200" por error, una tabla gigante lo ocultará, pero un **Gráfico de Dispersión** lo hará saltar a la vista inmediatamente como un punto solitario alejado de los demás.

### Código Demostrativo: La elegancia de Seaborn

Seaborn nos permite crear gráficos hermosos con una sola línea. Ejecuta este ejemplo:
"""

# Estilo elegante de Seaborn
sns.set_theme(style="whitegrid")

tratamientos      = ["Terapia A", "Terapia B", "Terapia C"]
pacientes_total   = [120, 85, 150]

# Gráfico de barras con paleta de colores automática
sns.barplot(x=tratamientos, y=pacientes_total, hue=tratamientos,
            palette="viridis", legend=False)

plt.title("Pacientes por Tratamiento")
plt.ylabel("Cantidad de Pacientes")
plt.show()

"""---

### Ejercicio 2.2: Histograma con Curva de Densidad (`kde=True`)

Seaborn tiene una versión mejorada del histograma que además dibuja una **curva
de densidad** (KDE — Kernel Density Estimate) encima de las barras. Esta curva
te muestra la "forma" de la distribución de manera continua y más elegante.

El hospital tiene registros de presión arterial sistólica de 20 pacientes.
Uno de los valores parece sospechosamente alto. Tu objetivo es visualizarlo.

**Tu tarea:**
1. Ejecuta la celda de abajo para crear la lista `presion_arterial`.
2. En la línea indicada, escribe: `sns.histplot(presion_arterial, bins=6, kde=True, color="coral")`
3. Agrega `plt.title("Distribución de Presión Arterial")` y `plt.show()`.
4. 🧠 **Reflexión:** ¿En qué rango se concentra la mayoría? ¿Ves algún valor extremo?

---

"""

# Registros de presión arterial sistólica (mmHg)
presion_arterial = [118, 122, 115, 130, 128, 125, 119, 121,
                    135, 127, 116, 190, 124, 118, 132, 120,
                    126, 123, 117, 129]

sns.set_theme(style="whitegrid")

# Escribe aquí tu código para el Ejercicio 2.2:

"""### Ejercicio 3.1: El Caza-Anomalías

**Tu tarea:** Tienes una lista de edades donde sospechas que hay un error. Usa `sns.scatterplot()` pasando `id_paciente` en el eje X y `edades` en el eje Y para detectar visualmente el error.

"""

# Base de datos sospechosa
id_paciente = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
edades      = [22, 28, 25, 30, 200, 24, 27, 29, 21, 26]  # ¡Error detectado!

# Escribe tu código aquí:

plt.title("Auditoría de Edades (Radar Visual)")
plt.xlabel("ID del Paciente")
plt.ylabel("Edad Registrada")
plt.show()

"""---

### Ejercicio 3.2: Dispersión con Color por Categoría (`hue=`)

El parámetro `hue=` de Seaborn es uno de sus superpoderes: colorea automáticamente
los puntos según una categoría (columna de texto), sin que tú tengas que asignar
colores manualmente.

El laboratorio quiere saber si hay relación entre la **edad** y el **nivel de
colesterol** de sus pacientes, y además quiere ver si el **grupo de riesgo** afecta
el patrón.

**Tu tarea:**
1. Ejecuta la celda para crear `df_clinico`.
2. Escribe: `sns.scatterplot(data=df_clinico, x="Edad", y="Colesterol", hue="Grupo")`
3. Agrega título y etiquetas, luego `plt.show()`.
4. 💎 **Bonus:** Agrega `size="Colesterol"` al scatterplot para que los puntos
   con colesterol más alto aparezcan más grandes.

---

"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

datos_clinico = {
    "Paciente":   ["Ana", "Luis", "Carmen", "Jorge", "Sofía", "Pedro",
                   "María", "Carlos", "Elena", "Roberto"],
    "Edad":       [28, 45, 34, 52, 29, 60, 38, 47, 33, 55],
    "Colesterol": [185, 240, 195, 280, 170, 310, 205, 260, 190, 295],
    "Grupo":      ["Bajo", "Alto", "Bajo", "Alto", "Bajo", "Alto",
                   "Bajo", "Alto", "Bajo", "Alto"]
}
df_clinico = pd.DataFrame(datos_clinico)

sns.set_theme(style="whitegrid")

# Escribe aquí tu código para el Ejercicio 3.2:

"""---

## Parte 4: Reto Práctico (El Pintor de Datos)

Para cerrar la sesión, pon a prueba tus habilidades de comunicación visual.

"""

# Datos de evaluación
nombres_grupos = ["Grupo A", "Grupo B", "Grupo C"]
rendimiento    = [85, 92, 58]

# Escribe tu código aquí:
# 1. Importa matplotlib.pyplot as plt
# 2. Crea un gráfico de barras (plt.bar)
# 3. Agrega título y etiquetas a los ejes
# 4. Usa un color diferente (ej: color='green')
# 5. Muestra el gráfico

"""---

### 🧠 El Diagnóstico Visual

Haz doble clic en esta celda y responde:

> *Viendo tu gráfico, ¿qué grupo tuvo el rendimiento más bajo? ¿Te tomó más de un segundo identificarlo?*

**(Escribe tu respuesta aquí):**

* ---

---

### 🔥 Reto Extra: Dashboard de 4 Gráficas con `plt.subplots()`

En el mundo profesional, los reportes muestran **múltiples gráficas al mismo tiempo**
en un solo panel llamado "dashboard". Python permite esto con `plt.subplots()`.

El hospital quiere un resumen visual de su base de pacientes con 4 vistas simultáneas.

**Tu pipeline:**
1. Ejecuta la celda para crear `df_hospital`.
2. Crea la figura con: `fig, axes = plt.subplots(2, 2, figsize=(12, 8))`
   *(Esto crea una cuadrícula de 2 filas × 2 columnas de gráficas)*
3. **Gráfica 1** (arriba izq): `df_hospital["Diagnostico"].value_counts().plot(kind="bar", ax=axes[0,0])`
4. **Gráfica 2** (arriba der): `axes[0,1].hist(df_hospital["Edad"], bins=5, color="steelblue")`
5. **Gráfica 3** (abajo izq): `sns.scatterplot(data=df_hospital, x="Edad", y="Colesterol", hue="Grupo", ax=axes[1,0])`
6. **Gráfica 4** (abajo der): `df_hospital["Ciudad"].value_counts().plot(kind="bar", ax=axes[1,1], color="coral")`
7. Agrega un título a cada `axes[fila, col]` con `axes[0,0].set_title("...")`
8. Cierra con `plt.tight_layout()` y `plt.show()`

---
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

datos_hospital = {
    "Paciente":   ["Ana", "Luis", "Carmen", "Jorge", "Sofía",
                   "Pedro", "María", "Carlos", "Elena", "Roberto"],
    "Edad":       [28, 45, 34, 52, 29, 60, 38, 47, 33, 55],
    "Diagnostico":["Gripe", "COVID", "Asma", "Gripe", "Migraña",
                   "COVID", "Asma", "Gripe", "Migraña", "COVID"],
    "Colesterol": [185, 240, 195, 280, 170, 310, 205, 260, 190, 295],
    "Ciudad":     ["CDMX", "Monterrey", "CDMX", "Guadalajara", "CDMX",
                   "Monterrey", "Guadalajara", "CDMX", "Monterrey", "CDMX"],
    "Grupo":      ["Bajo", "Alto", "Bajo", "Alto", "Bajo",
                   "Alto", "Bajo", "Alto", "Bajo", "Alto"]
}
df_hospital = pd.DataFrame(datos_hospital)

sns.set_theme(style="whitegrid")

# Escribe aquí tu dashboard de 4 gráficas:

"""### 📋 Referencia del Dashboard — Solución para el Instructor

```python
fig, axes = plt.subplots(2, 2, figsize=(12, 8))

# Gráfica 1 — Barras: Diagnósticos más frecuentes
df_hospital["Diagnostico"].value_counts().plot(kind="bar", ax=axes[0,0], color="steelblue")
axes[0,0].set_title("Diagnósticos más frecuentes")
axes[0,0].set_xlabel("Diagnóstico")
axes[0,0].set_ylabel("Cantidad")

# Gráfica 2 — Histograma: Distribución de edades
axes[0,1].hist(df_hospital["Edad"], bins=5, color="mediumseagreen", edgecolor="white")
axes[0,1].set_title("Distribución de Edades")
axes[0,1].set_xlabel("Edad")
axes[0,1].set_ylabel("Frecuencia")

# Gráfica 3 — Dispersión: Edad vs Colesterol por Grupo
sns.scatterplot(data=df_hospital, x="Edad", y="Colesterol",
                hue="Grupo", ax=axes[1,0])
axes[1,0].set_title("Edad vs Colesterol por Grupo")

# Gráfica 4 — Barras: Pacientes por Ciudad
df_hospital["Ciudad"].value_counts().plot(kind="bar", ax=axes[1,1], color="coral")
axes[1,1].set_title("Pacientes por Ciudad")
axes[1,1].set_xlabel("Ciudad")
axes[1,1].set_ylabel("Cantidad")

plt.tight_layout()
plt.show()
```

---

"""