# -*- coding: utf-8 -*-
"""Sesión 13: Limpieza de Datos en Python (Teoría y Práctica)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XAcZXYYkcoN0vyb1Qo5n_MkGmoU3ltXG

# Sesión 13: Limpieza de Datos en Python (Teoría y Práctica)


### El Dilema de los Datos Faltantes (`None`)
Cuando nuestro radar detecta un valor nulo, nos enfrentamos a una decisión crítica. Como Científicos de Datos, tenemos dos grandes estrategias para manejar los vacíos:

1. **Eliminación (Borrar la fila):** Imagina que recibes una encuesta de satisfacción que está casi en blanco; lo más lógico es tirarla a la basura. Borrar un registro es válido si tenemos millones de datos y solo faltan unos cuantos. Sin embargo, es peligroso si se hace sin cuidado. Si en un estudio médico borramos a todos los pacientes con datos incompletos, podríamos estar eliminando justo a aquellos que estaban demasiado graves para terminar la prueba, sesgando por completo nuestra investigación.
2. **Imputación (Rellenar el hueco):** Esto equivale a hacer una "suposición educada". En lugar de tirar a la basura todo el expediente valioso de un paciente solo porque olvidó anotar su edad, rellenamos ese hueco utilizando un valor lógico, como la **mediana** o el **promedio** del resto de los pacientes.

---

### ¿Qué hacemos con los Duplicados y los Textos?
Además de los nulos, tenemos a nuestros otros dos sospechosos de la Sesión 11:

* **Los Clones (Duplicados):** La regla aquí es sencilla y estricta: nos quedamos con el registro original y eliminamos las copias sin piedad para no alterar los conteos de la realidad.
* **Inconsistencias de Texto ("Planchar las arrugas"):** Para nosotros, "Ciudad de México", "ciudad de mexico " y "CDMX" representan el mismo lugar. Pero para una computadora, que es estrictamente literal, son tres ubicaciones completamente distintas. Resolver esto es como "planchar las arrugas" de una camisa antes de ponérsela. Necesitamos estandarizar el idioma de nuestros datos (convertir todo a minúsculas o quitar espacios invisibles) antes de que la máquina pueda agruparlos.

Como pueden ver, limpiar datos no es un trabajo mecánico de solo teclear código; requiere tomar decisiones críticas que definirán la calidad de todo nuestro proyecto.

---

### Ejercicio 1.1: Gimnasio Mental (El Cirujano de Datos)
Antes de programar nuestras soluciones, vamos a afinar tu criterio de toma de decisiones. Imagina que eres el analista principal de un hospital y te reportan tres errores en la base de datos de pacientes de urgencias.

**Tu tarea:**
Lee los tres escenarios de abajo. Sin usar código, decide qué acción tomarías en cada caso: **¿Eliminar el registro, Imputar (rellenar) el dato, o Estandarizar el texto?**

* **Caso A:** Un paciente llegó inconsciente y no se sabe su edad exacta, pero sí tenemos su tipo de sangre, alergias y ritmo cardíaco (datos vitales para su tratamiento).
* **Caso B:** En la columna de género de la base de datos, tienes registros que dicen: "Femenino", "fem", "femenino ", "F".
* **Caso C:** Un paciente entró al hospital a las 10:00 am. A las 10:01 am, el sistema se trabó y registró exactamente el mismo ingreso, con el mismo nombre y síntomas.


---

---

### 📋 Tabla de Referencia: Los 5 Poderes del Texto

Antes de programar, memoriza esta tabla. La usarás en cada proyecto de datos real:

| Método | ¿Qué hace? | Ejemplo de entrada | Resultado |
|---|---|---|---|
| `.lower()` | Todo a minúsculas | `"DiAbEtEs"` | `"diabetes"` |
| `.upper()` | Todo a mayúsculas | `"gripe"` | `"GRIPE"` |
| `.title()` | Primera letra de cada palabra en mayúscula | `"juan pérez"` | `"Juan Pérez"` |
| `.strip()` | Quita espacios al inicio y al final | `" covid "` | `"covid"` |
| `.replace("x","y")` | Sustituye un texto por otro | `"Tipo 2"` | `"Tipo II"` |

> **Regla de Oro:** Ninguno de estos métodos modifica tu dato original automáticamente.
> Siempre debes **guardar el resultado** sobreescribiendo tu variable: `dato = dato.lower()`

---

## Parte 2: De la Teoría a la Práctica (Los "Poderes" del Texto)

Ya sabemos que la computadora es muy estricta y que un simple espacio en blanco puede arruinar nuestro análisis. Afortunadamente, Python nos ofrece una serie de "poderes" o herramientas integradas para limpiar cadenas de texto de forma automática.

A estos poderes los llamamos **métodos de cadena** (*string methods*). Imagina que son como filtros de una lavadora por los que pasamos nuestro texto sucio para que salga impecable:

* **`.lower()`:** Convierte absolutamente todas las letras a minúsculas. Es tu mejor amigo para estandarizar.
* **`.upper()`:** Hace lo contrario, convierte todo a mayúsculas.
* **`.strip()`:** Actúa como unas tijeras que recortan todos los espacios en blanco invisibles o accidentales que están al principio y al final de tu texto.
* **`.replace("viejo", "nuevo")`:** Busca un pedazo de texto específico y lo reemplaza por otro. Úsalo para corregir errores de dedo sistemáticos.

### Código en Acción: Limpiando un Expediente
Vamos a tomar un diagnóstico médico mal escrito por las prisas en urgencias y lo dejaremos listo para nuestra base de datos. Ejecuta esta celda:
"""

# 1. Recibimos nuestro dato "sucio"
diagnostico = " DiaBetes Tipo 2 "
print("Texto original:", diagnostico)

# 2. Usamos .strip() para quitar los espacios accidentales de los extremos
diagnostico = diagnostico.strip()

# 3. Usamos .lower() para estandarizar todas las letras a minúsculas
diagnostico = diagnostico.lower()

# 4. Usamos .replace() para cambiar el número arábigo por romano
diagnostico = diagnostico.replace("2", "ii")

print("Texto limpio y estandarizado:", diagnostico)

# PISTA DE HACKER: ¡Incluso podrías encadenar estos poderes en una sola línea así!
# diagnostico = diagnostico.strip().lower().replace("2", "ii")

"""### Explicación Paso a Paso: La Regla de Oro de la Memoria

¿Notaste que en cada paso escribimos `diagnostico = diagnostico.metodo()` en lugar de solo poner `diagnostico.lower()`?

Esto es vital. En Python, las cadenas de texto son **inmutables**. Esto significa que cuando le aplicas un "poder" como `.lower()`, la computadora toma la caja de texto original, le saca una copia temporal, limpia la copia y te la muestra.

Si no tomas esa copia limpia y la guardas explícitamente **sobrescribiendo tu variable original** (usando el signo `=`), la computadora desechará la versión limpia y tu dato seguirá igual de sucio que al principio. ¡Siempre recuerda guardar el cambio para que sea permanente!

---

"""

# ──────────────────────────────────────────────────────────
# PISTA DE HACKER: Encadenamiento + .title()
# ──────────────────────────────────────────────────────────

# Dato sucio como llega de un formulario web
nombre_paciente = "  JUAN carlos PÉREZ  "

# Opción A: Paso a paso (más fácil de leer al aprender)
nombre = nombre_paciente.strip()
nombre = nombre.title()
print("Paso a paso:  ", nombre)

# Opción B: Encadenado en una sola línea (estilo profesional)
nombre_pro = nombre_paciente.strip().title()
print("Encadenado:   ", nombre_pro)

print("─" * 45)

# ¿Cuándo usar .title() vs .lower()?
ciudad = "  cIUdAd De MéXiCo  "
print("Con .lower() →", ciudad.strip().lower())   # Para comparar y buscar
print("Con .title() →", ciudad.strip().title())   # Para mostrar al usuario

"""### ¿Cuándo usar `.title()` y cuándo `.lower()`?

La respuesta depende del **propósito** de tu limpieza:

- **Usa `.lower()`** cuando vayas a **comparar, buscar o contar** datos.
  Python distingue entre `"Monterrey"` y `"monterrey"`, por eso bajar todo a minúsculas
  antes de un `.count()` es esencial para no perder registros.

- **Usa `.title()`** cuando vayas a **mostrar** el dato al usuario final (en un reporte,
  tabla o dashboard). Nadie quiere leer `"juan pérez"` en su expediente médico.

**La estrategia profesional es combinar los dos:**
1. Limpias con `.strip().lower()` para hacer tus análisis y conteos.
2. Presentas con `.strip().title()` cuando generas el reporte final para el usuario.

---

### Ejercicio 2.1: Limpiando la Base de Contactos

El departamento de recepción te pasó el correo electrónico de un paciente importante, pero lo escribieron pésimo y el sistema automatizado de envíos lo está rechazando.

**Tu tarea:**

1. En la celda de abajo tienes la variable `correo_paciente`.
2. En la siguiente línea, aplica la regla de oro: sobrescribe la variable usando el poder `.strip()` para quitar los espacios accidentales.
3. En la siguiente línea, sobrescribe nuevamente la variable aplicando el poder `.lower()` para quitar las mayúsculas raras.
4. Imprime tu resultado final. (Debería verse exactamente así: `juan.perez@mail.com`).
"""

correo_paciente = " jUaN.PeReZ@maiL.com "

# Escribe aquí tu código para el Ejercicio 2.1:

"""---

### Ejercicio 2.2: Limpiando Nombres del Directorio Médico

El sistema de admisiones registró los nombres de cuatro médicos con errores de capitalización. El director del hospital necesita el listado impreso en un formato profesional.

**Tu tarea:**

1. Tienes la lista `nombres_sucios` en la celda de abajo.
2. Crea una lista vacía llamada `nombres_limpios`.
3. Usa un bucle `for` para recorrer cada nombre.
4. Dentro del bucle, aplica `.strip().title()` encadenado en una sola línea.
5. Agrega el resultado a `nombres_limpios` con `.append()`.
6. Imprime la lista final. Deberías ver:
   `['Dra. Ana Torres', 'Dr. Luis Medina', 'Dra. Carmen Vega', 'Dr. Jorge Ruiz']`

---

"""

nombres_sucios = ["  DRA. ANA TORRES", "dr. luis MEDINA  ", "DRA. carmen vega", "  DR. JORGE ruiz  "]
nombres_limpios = []

# Escribe aquí tu código para el Ejercicio 2.2:

"""---

## Parte 3: Exploración con Datos (Limpiando una Lista Completa)

Limpiar un solo dato está bien para practicar, pero ¿qué pasa cuando descargas las respuestas de 100,000 pacientes o clientes desde un formulario de Google?

Aquí es donde combinamos nuestros "poderes" de texto con los bucles `for` para automatizar la limpieza de listas enteras en un abrir y cerrar de ojos.

### Automatizando la Limpieza y el Impacto Analítico

Imagina que aplicaste una evaluación y el sistema te entregó respuestas escritas a mano por los usuarios. Vamos a ver cómo esta "suciedad" engaña a Python y cómo nuestro bucle lo soluciona de inmediato.

Crea una nueva celda y ejecuta este código:

"""

# Nuestra colección de datos "sucios"
respuestas = [" Aprobado", "reprobado ", "Aprobado", "APROBADO"]

# EL ENGAÑO ANALÍTICO: Intentamos contar cuántos aprobaron ANTES de limpiar
print("Aprobados ANTES de limpiar:", respuestas.count("aprobado"))
print("--------------------------------------------------")

# Automatizando la limpieza
respuestas_limpias = []

for respuesta in respuestas:
    # 1. Planchamos las arrugas: quitamos espacios y pasamos a minúsculas
    texto_limpio = respuesta.strip().lower()

    # 2. Guardamos el dato impecable en nuestra lista nueva
    respuestas_limpias.append(texto_limpio)

# LA REALIDAD ANALÍTICA: Contamos DESPUÉS de limpiar
print("Lista limpia:", respuestas_limpias)
print("Aprobados DESPUÉS de limpiar:", respuestas_limpias.count("aprobado"))

"""### ¿Qué nos dice esto sobre la realidad?

Antes de limpiar, si le preguntabas a la computadora cuántos decían "aprobado", te respondía cero. Para Python, los espacios extra y las mayúsculas hacían que cada palabra fuera una categoría completamente distinta.

Al integrar `.strip()` y `.lower()` dentro del bucle `for`, estandarizamos toda la información automáticamente. Al final, la función `.count()` deja de estar "ciega" por los errores de formato y nos arroja el diagnóstico real: tenemos 3 aprobados. **¡Por esto nunca debes confiar en datos sin limpiar!**

---

"""

# ────────────────────────────────────────────────────────────────
# COMBINANDO PODERES: Limpiar texto dentro de un diccionario
# (Puente entre lo aprendido en S7-S8 y lo que harás con Pandas en S14)
# ────────────────────────────────────────────────────────────────

# Registro de un paciente tal como llega de un formulario web
paciente = {
    "nombre":      "  jUaN pAbLo RaMíReZ  ",
    "diagnostico": " DIABETES tipo 2 ",
    "ciudad":      "  Ciudad De Mexico  "
}

print("ANTES de limpiar:")
for campo, valor in paciente.items():
    print(f"  {campo}: '{valor}'")

print()

# Limpiamos cada campo con el poder adecuado al propósito
paciente["nombre"]      = paciente["nombre"].strip().title()                           # Para mostrar
paciente["diagnostico"] = paciente["diagnostico"].strip().lower().replace("2", "ii")  # Para analizar
paciente["ciudad"]      = paciente["ciudad"].strip().lower()                           # Para comparar

print("DESPUÉS de limpiar:")
for campo, valor in paciente.items():
    print(f"  {campo}: '{valor}'")

"""### 🔗 Puente hacia la Sesión 14: El Salto a Pandas

Lo que acabas de hacer —limpiar campo por campo dentro de un diccionario usando un `for`— funciona perfectamente para unos cuantos registros. Pero imagina que tienes 500,000 pacientes en tu base de datos.

Escribir un bucle `for` para cada campo sería agotador. Ahí es donde entra **Pandas**.

En la próxima sesión descubrirás que todos los poderes que aprendiste hoy tienen su versión turbo en Pandas usando el prefijo `.str`:

| Python puro (hoy) | Pandas (S14) | ¿Qué hace? |
|---|---|---|
| `nombre.strip()` | `df["Nombre"].str.strip()` | Limpia espacios en **toda la columna** |
| `nombre.lower()` | `df["Nombre"].str.lower()` | Pasa **toda la columna** a minúsculas |
| `nombre.replace("x","y")` | `df["Nombre"].str.replace("x","y")` | Reemplaza en **toda la columna** |

La lógica es exactamente la misma. La diferencia es que Pandas aplica el poder a **toda la columna entera** —todos los 500,000 registros— en una sola línea. ¡Acabas de aprender la base de lo que viene!

---

### Ejercicio 3.1: Auditoría de Envíos (Logística)

Trabajas en logística y necesitas saber cuántos paquetes van a la ciudad de Monterrey hoy. El problema es que los clientes escribieron la ciudad como quisieron en el formulario.

**Tu tarea:**

1. Abajo tienes la lista `destinos_sucios` y una lista vacía `destinos_limpios`.
2. Crea un bucle `for` para recorrer cada `ciudad` en `destinos_sucios`.
3. Adentro del bucle, crea una variable llamada `ciudad_limpia` y aplícale los poderes `.strip()` y `.lower()` en una sola línea encadenada.
4. Agrega (`.append()`) la `ciudad_limpia` a tu lista de `destinos_limpios`.
5. Fuera del bucle, usa un `print()` para imprimir tu lista limpia, y otro `print()` usando `.count("monterrey")` para revelar el número real de envíos.
"""

destinos_sucios = [" Monterrey", "monterrey", "MONTERREY ", "Guadalajara", " monterrey"]
destinos_limpios = []

# Escribe aquí tu código para el Ejercicio 3.1:

"""---

## Parte 4: Reto Práctico (El Estandarizador)

Para cerrar nuestra sesión de hoy, vamos a aplicar estos "poderes" del texto a gran escala. Imagina que descargaste las ubicaciones de varios usuarios desde un formulario en línea, pero cada persona escribió el nombre de su ciudad como quiso (con mayúsculas, minúsculas o espacios accidentales).

Abre una nueva celda en tu Google Colab y copia esta lista inicial para comenzar tu reto.

"""

# Nuestra base de datos "sucia"
ciudades_sucias = [" Madrid ", "LONDRES", " madrid", "Londres ", " MADRID"]
ciudades_limpias = []

# ¡Tu turno! Enciende la lavadora debajo de esta línea:

"""**Tus instrucciones paso a paso:**

1. **Enciende la lavadora:** Crea un bucle `for` para recorrer cada `ciudad` dentro de la lista `ciudades_sucias`.
2. **Plancha las arrugas:** Dentro del bucle, crea una variable donde a cada ciudad le quites los espacios extra de los extremos y la pases a minúsculas (Recuerda que puedes encadenar los métodos así: `ciudad.strip().lower()`).
3. **Guarda el resultado:** Añade (`.append()`) tu ciudad ya limpia a tu nueva lista `ciudades_limpias`.
4. **Muestra tu trabajo:** Fuera del bucle, usa `print()` para imprimir la lista limpia final. ¡Deberías ver que todas las ciudades ahora están perfectamente estandarizadas!
5. **💎 Bonus Hacker:** Imprime cuántas veces aparece la ciudad `"madrid"` en tu lista limpia usando la función `.count("madrid")`. (Si lo hiciste bien, la computadora debería detectar 3 exactos).

---

### 🧠 Reflexión del Analista

Haz doble clic en esta celda y responde brevemente:

> *Si hubieras intentado contar a los usuarios de "madrid" sin haber usado `.strip()` y `.lower()`, ¿qué número te habría arrojado la computadora y qué decisión de negocios equivocada podrías haber tomado?*

**(Escribe tu respuesta aquí):**

* ---

---

### 🔥 Reto Extra: El Expediente Multicampo

Limpiar una sola lista ya lo dominas. Ahora el reto es limpiar **múltiples campos a la vez** dentro de una lista de diccionarios — exactamente como trabaja un Data Analyst en el mundo real.

**Tu tarea:**

1. En la celda de abajo tienes `registros_medicos`, una lista con 3 diccionarios sucios.
2. Crea un bucle `for` que recorra cada `registro` de la lista.
3. Dentro del bucle, limpia **los tres campos** de cada registro:
   - `"paciente"` → usa `.strip().title()` (nombre propio para mostrar)
   - `"diagnostico"` → usa `.strip().lower()` (para análisis)
   - `"ciudad"` → usa `.strip().lower()` (para análisis y conteo)
4. Imprime cada registro limpio con un `print()` dentro del bucle.

💎 **Bonus:** Después del bucle, cuenta cuántos pacientes son de `"guadalajara"` usando una variable contador.

---
"""

registros_medicos = [
    {"paciente": "  ANA GARCIA ",  "diagnostico": " Gripe  ",      "ciudad": "  Guadalajara"},
    {"paciente": "LUIS raMírez  ", "diagnostico": "  DIABETES  ",  "ciudad": "guadalajara  "},
    {"paciente": " carmen VEGA",   "diagnostico": " migraña ",     "ciudad": "  MONTERREY  "}
]

# Escribe aquí tu código para el Reto Extra:

"""### 🧠 Reflexión Extra: El Sesgo de los Datos Sucios

Haz doble clic en esta celda y responde:

> *Imagina que tu empresa quiere saber en qué ciudad viven más sus clientes para abrir
> una nueva sucursal. Si la base de datos tiene `"guadalajara"`, `"Guadalajara"` y `"GUADALAJARA"`
> sin limpiar, ¿qué ciudad aparecería como la más popular en el reporte? ¿Qué decisión
> comercial equivocada podría tomarse por no haber limpiado los datos antes del análisis?*

**(Escribe tu respuesta aquí):**

* ---

"""