# -*- coding: utf-8 -*-
"""Sesión 6: Fundamentos de Python (Práctica)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iULnPAOJAIYRJ_uLlCFog2iyoH-hTdik

# Sesión 6: Fundamentos de Python (Práctica)


### Repaso Activo: Organizando nuestro archivo digital
Antes de empezar a teclear, recordemos rápidamente nuestro concepto de variables. Imagina que estás organizando el archivo central de un gran hospital o elaborando un censo poblacional. Las variables son las "cajas" o "carpetas" donde guardamos la información de cada persona con una etiqueta clara para encontrarla después.

Dependiendo de la naturaleza de la información, usamos distintos tipos de datos:

1. **Texto (`str` o string):** Para guardar palabras, nombres o diagnósticos. ¡Siempre van entre comillas! (ej. `"María"`, `"Diabetes"`).
2. **Enteros (`int` o integer):** Para números completos, ideales para contar elementos indivisibles. Sin comillas. (ej. `28` años, `3` hijos).
3. **Decimales (`float` o flotante):** Para mediciones exactas que requieren punto decimal. Sin comillas. (ej. `1.68` metros, `37.5` grados).
4. **Lógicos (`bool` o booleanos):** Para clasificaciones binarias o estatus. Solo aceptan `True` (Verdadero) o `False` (Falso). Sin comillas y con mayúscula inicial. (ej. ¿Seguro vigente? `True`).

---

### Más allá de guardar: El poder de operar los datos
Tener miles de cajas perfectamente etiquetadas y guardadas está muy bien, pero en la vida real, almacenar información no sirve de nada si no podemos hacer algo útil con ella.

Como científicos de datos, no nos conformamos con mirar datos estáticos. Necesitamos tomar esa información y operarla: sumar los pacientes del mes, calcular el promedio de edad, unir el nombre y apellido en un solo registro, o transformar un dato que se guardó mal.

Hoy le daremos instrucciones a la computadora para que sume, una y transforme estas "cajas" por nosotros. ¡Veamos cómo luce esto en la pantalla!
"""

# EJERCICIO GUIADO: El expediente de nuestro primer paciente
# Presiona el botón de Play (o Shift + Enter) para guardar esto en la memoria

nombre_paciente = "Carlos"
edad = 34
peso_kg = 75.5
tiene_alergias = False

# La función print() nos permite asomarnos adentro de las cajas
print("Expediente creado para:", nombre_paciente)
print("Edad registrada:", edad)

"""---

### Ejercicio 1.1: Tu turno en el teclado

¡Es hora de programar desde cero! Ya viste cómo registramos a "Carlos", ahora vas a crear tu propio expediente.

**Tu Tarea:**

1. En la celda de código vacía que está debajo, crea **cuatro variables** nuevas sobre ti mismo o un paciente ficticio (ejemplo: `nombre`, `edad`, `estatura` y `es_estudiante`).
2. Asígnales los valores correspondientes respetando las reglas de las comillas (`str`, `int`, `float`, `bool`).
3. Usa la instrucción `print()` para mostrar en pantalla al menos dos de tus variables.
4. Ejecuta tu celda.

"""

# Escribe aquí tu código para el Ejercicio 1.1:

"""---

## Parte 2: Operaciones con Textos (El arte de unirlos)

Tener miles de cajas (variables) perfectamente etiquetadas está muy bien, pero en la vida real, almacenar información no sirve de nada si no podemos hacer algo útil con ella. Como científicos de datos, necesitamos tomar esa información y operarla.

Vamos a empezar con los textos. A menudo necesitamos procesar y unir categorías, nombres completos o respuestas de encuestas. En Python, a la acción de unir diferentes textos se le llama **concatenación** y se realiza de forma muy sencilla usando el símbolo de suma (`+`).

Haz clic en la celda de abajo y ejecútala para crear un mensaje automatizado:

"""

nombre = "Ana"
apellido = "López"

# Unimos los textos usando el símbolo +
mensaje_bienvenida = "Hola, " + nombre + " " + apellido + ". ¡Gracias por participar!"

print(mensaje_bienvenida)

"""### ⚠️ El truco del espacio en blanco

Si te fijas detalladamente en el código anterior, notarás que tuvimos que agregar explícitamente un espacio en blanco entre comillas (`" "`) en medio de las dos variables.

Las computadoras son literales y obedecen exactamente lo que les pides; no asumen reglas gramaticales humanas. Si omites ese espacio y escribes `nombre + apellido`, las palabras se imprimirán amontonadas como `AnaLópez`.

---

### Ejercicio 2.1: Tu Gafete Virtual

¡Es tu turno de concatenar! Imagina que estás programando el sistema que imprime los gafetes para un congreso universitario.

**Tu Tarea:**

1. En la celda de abajo, crea tres variables de texto (`str`): tu nombre, tu apellido y tu área de estudio o profesión.
2. Crea una cuarta variable llamada `gafete` donde unas (concatenes) las tres variables anteriores usando el símbolo `+`.
3. Asegúrate de agregar texto adicional y espacios en blanco para que la frase tenga sentido (Ejemplo: *"Juan Pérez - Facultad de Medicina"*).
4. Usa `print()` para mostrar tu resultado y ejecuta la celda.

"""

# Escribe aquí tu código para el Ejercicio 2.1:

"""---

### 🆕 La Forma Profesional: f-strings vs. Concatenación

Ya aprendiste a concatenar con `+`. Funciona, pero tiene dos grandes problemas en la práctica:

1. **Es tedioso:** Tienes que agregar espacios manualmente (`" "`), lo que hace el código largo y difícil de leer.
2. **Explota con números:** Si intentas unir texto con un número, Python lanza un `TypeError` (¡lo veremos en la siguiente parte!).

Los profesionales de datos resuelven ambos problemas con los **f-strings** (cadenas de formato). La regla es sencilla:
- Pon una `f` justo **antes** de las comillas iniciales: `f"..."`
- Coloca tus variables **entre llaves** `{}` donde quieras que aparezcan

| Forma | Código | ¿Problema con números? |
|---|---|---|
| Concatenación | `"Hola, " + nombre + " " + apellido` | ❌ Sí, da TypeError |
| **f-string** | `f"Hola, {nombre} {apellido}"` | ✅ No, los maneja solos |

> 💡 **Regla de oro:** A partir de hoy, usa f-strings siempre que necesites combinar texto y variables. La concatenación con `+` queda solo para entender el concepto.

"""

# ============================================================
# F-STRINGS EN ACCIÓN: El mismo gafete, escrito de forma profesional
# ============================================================

mi_nombre   = "Ana"
mi_apellido = "López"
mi_area     = "Ciencia de Datos"
mi_edad     = 28        # ← número entero (¡sin comillas!)

# Forma antigua: concatenación (verbosa y rompe con números)
print("--- Concatenación ---")
gafete_viejo = "Hola, " + mi_nombre + " " + mi_apellido + " - " + mi_area
print(gafete_viejo)

# Forma profesional: f-string (limpia y maneja cualquier tipo de dato)
print("\n--- f-string ---")
gafete_nuevo = f"Hola, {mi_nombre} {mi_apellido} - {mi_area}"
print(gafete_nuevo)

# BONUS: incluye el número directamente (¡sin str()!)
print("\n--- f-string con número incluido ---")
print(f"Bienvenido/a {mi_nombre} {mi_apellido} | Área: {mi_area} | Edad: {mi_edad} años")

"""---

### 🧠 Pregunta para reflexionar antes de avanzar:

Ya vimos que el símbolo `+` sirve para unir texto con texto. Pero, ¿qué crees que pasaría si intentamos usar el `+` para unir un texto con un número entero (ej. `"Ana" + 28`)?

¿La computadora los sumará matemáticamente o los pegará como palabras? Lo descubriremos en la siguiente sección.

---

## Parte 3: El Error Intencional y la Conversión de Datos (*Casting*)

En la sección anterior nos preguntamos qué pasaría si intentamos unir un texto con un número. Aprender a programar significa encontrarse con mensajes de error todos los días, y eso es completamente normal. Un error no significa que descompusiste algo, es solo Python diciéndote: *"Oye, no entiendo qué me estás pidiendo, revisa tu lógica"*.

Vamos a cometer un error a propósito para perderle el miedo. Ejecuta esta celda y no te asustes si ves letras rojas:

"""

# CUIDADO: Este código está diseñado para fallar
edad = 25
mensaje_error = "El paciente tiene " + edad + " años."

print(mensaje_error)

"""### ¿Qué acaba de pasar?

Al ejecutarlo, la ejecución se detuvo y viste un bloque con texto que dice `TypeError` (Error de Tipo).

**¿Por qué?** Porque Python es muy estricto con sus "cajas". Le pediste que pegara letras (texto) con un valor matemático (entero) usando el símbolo `+`. Es como intentar sumar la palabra "Manzana" con el número 5 en una calculadora; son de naturalezas completamente distintas.

---

### La Solución: Los "Traductores" (*Casting*)

Para solucionar esto con concatenación, usamos la **conversión de datos** (conocida en inglés como *Casting*). Imagina que son "traductores" que toman el contenido de una caja y le cambian el disfraz temporalmente:

| Traductor | ¿Qué hace? | Ejemplo |
|---|---|---|
| `str()` | Número → Texto | `str(25)` → `"25"` |
| `int()` | Texto → Entero | `int("25")` → `25` |
| `float()` | Texto → Decimal | `float("37.5")` → `37.5` |

Vamos a corregir nuestro código usando el traductor `str()`. Ejecuta la celda de abajo:

> 💡 **Conexión con f-strings:** ¿Recuerdas el `f"{variable}"` que acabamos de ver? Los f-strings hacen el `str()` de forma **automática e invisible**, por eso son superiores a la concatenación con `+`. El casting sigue siendo esencial cuando necesitas operar matemáticamente con datos que vienen guardados como texto (muy común en la limpieza de datos reales).

"""

edad = 25

# Usamos str() para disfrazar el número como texto y poder unirlo
mensaje_corregido = "El paciente tiene " + str(edad) + " años."
print("Solución con str() + concatenación:", mensaje_corregido)

# La misma solución con f-string (sin necesitar str())
print(f"Solución con f-string: El paciente tiene {edad} años.")

"""---

### 🧹 Métodos de Strings: El Kit del Limpiador de Datos

Hasta ahora guardamos y unimos texto. Pero en ciencia de datos, el texto que llega de formularios, encuestas o sistemas externos casi nunca viene limpio. Llega con espacios de más, mayúsculas mezcladas o palabras incorrectas.

Python tiene herramientas llamadas **métodos** que transforman texto automáticamente. Se usan con un punto (`.`) después de la variable:

| Método | ¿Qué hace? | Ejemplo | Resultado |
|---|---|---|---|
| `.upper()` | Todo a MAYÚSCULAS | `"ciudad de mexico".upper()` | `"CIUDAD DE MEXICO"` |
| `.lower()` | Todo a minúsculas | `"DIABETES".lower()` | `"diabetes"` |
| `.strip()` | Quita espacios al inicio y final | `"  Carlos  ".strip()` | `"Carlos"` |
| `.replace(viejo, nuevo)` | Sustituye texto | `"Cd. Mx.".replace(".", "")` | `"Cd Mx"` |
| `len()` | Cuenta caracteres | `len("Hola")` | `4` |

> ⚠️ **Dato importante:** Estos métodos **no modifican la variable original**. Crean una versión nueva limpia. Para guardarla debes reasignarla: `nombre = nombre.strip()`.

"""

# ============================================================
# MÉTODOS DE STRINGS EN ACCIÓN
# Escenario: datos sucios llegados de un formulario en línea
# ============================================================

# Así llegaron los datos del formulario
nombre_formulario    = "  ana  "          # espacios extra al inicio y final
ciudad_formulario    = "CIUDAD DE MEXICO" # todo en mayúsculas
diagnostico_form     = "diabetes "        # espacio al final
codigo_hospital      = "HOS-001-MX"       # necesitamos quitar los guiones

print("--- Datos SUCIOS (tal como llegaron) ---")
print(f"Nombre:      '{nombre_formulario}'")
print(f"Ciudad:      '{ciudad_formulario}'")
print(f"Diagnóstico: '{diagnostico_form}'")
print(f"Código:      '{codigo_hospital}'")

# ─── Limpieza ───────────────────────────────────────────────
nombre_limpio      = nombre_formulario.strip()           # quita espacios
nombre_limpio      = nombre_limpio.capitalize()          # Primera letra mayúscula
ciudad_limpia      = ciudad_formulario.title()           # Cada Palabra Con Mayúscula
diagnostico_limpio = diagnostico_form.strip().lower()    # sin espacio + minúsculas
codigo_limpio      = codigo_hospital.replace("-", "")    # quita guiones

print("\n--- Datos LIMPIOS (después del procesamiento) ---")
print(f"Nombre:      '{nombre_limpio}'")
print(f"Ciudad:      '{ciudad_limpia}'")
print(f"Diagnóstico: '{diagnostico_limpio}'")
print(f"Código:      '{codigo_limpio}'")
print(f"\nLongitud del nombre limpio: {len(nombre_limpio)} caracteres")

"""---

### Ejercicio 3.2: El Normalizador de Encuestas

El equipo de investigación te entregó estas respuestas de una encuesta. El problema: cada persona escribió su información de manera diferente. Tu trabajo es limpiarlas y estandarizarlas.

**Tu Tarea:**

1. En la celda de abajo, tienes 3 variables con datos sucios ya declaradas.
2. Crea versiones limpias usando los métodos que aprendiste:
   - `respuesta_1`: quita los espacios extra con `.strip()`
   - `respuesta_2`: convierte a minúsculas con `.lower()` y luego quita espacios con `.strip()`
   - `respuesta_3`: reemplaza las comas por puntos con `.replace(",", ".")` para que pueda convertirse a float
3. Para `respuesta_3` limpia: conviértela a `float` con casting y guárdala en `temperatura_real`.
4. Usa `print()` con **f-string** para mostrar los 3 resultados limpios.

"""

# Datos sucios de la encuesta (¡no los modifiques!)
respuesta_1 = "  Ciudad de México  "   # ciudad con espacios extra
respuesta_2 = "  FEMENINO "             # género en mayúsculas con espacio
respuesta_3 = "36,8"                    # temperatura con coma en lugar de punto

# ─── Escribe tu código de limpieza aquí abajo ───────────────

"""---

### Un Ejemplo Real en Ciencia de Datos (Limpiando Datos Numéricos)

¿Por qué el casting es vital en tu día a día profesional?

Cuando importamos bases de datos del mundo real (como archivos de Excel, encuestas en línea o registros hospitalarios), es extremadamente común que la computadora lea los números disfrazados de texto (por ejemplo, el texto `"100"` en lugar del número `100`).

Si intentas sacar un promedio o sumar esos valores numéricos falsos, Python te dará un error. Como científicos de datos, usamos constantemente `int()` y `float()` para limpiar y traducir esos textos a números reales antes de poder analizarlos estadísticamente.

---

### Ejercicio 3.1: Limpiando Datos de un Termómetro

Imagina que exportaste datos de un termómetro digital, pero el sistema guardó la temperatura como texto. Necesitas sumarle 0.5 grados para calibrarlo.

**Tu Tarea:**

1. En la celda de abajo, la variable `temp_texto` ya tiene el valor `"37.5"`.
2. Crea una nueva variable llamada `temp_real` y usa el traductor `float()` para convertir `temp_texto` a un número matemático.
3. Crea una variable llamada `temp_calibrada` que sea la suma de `temp_real + 0.5`.
4. Usa `print()` con **f-string** para mostrar el resultado: `"Temperatura calibrada: XX.X °C"`.

"""

temp_texto = "37.5"

# Escribe aquí tu código para el Ejercicio 3.1:
# Tip: usa f"{temp_calibrada:.1f}" para mostrar solo 1 decimal

"""---

## Parte 4: Reto Práctico Final (El Ticket de Análisis)

Para cerrar nuestra práctica de hoy, vamos a resolver un problema clásico de la ciencia de datos en el mundo real.

**El Escenario:** El nuevo sistema de la clínica exportó los costos de los pacientes, pero cometió un error de configuración: guardó los valores matemáticos disfrazados de texto. Tu objetivo es limpiar los datos, calcular el total y generar un ticket profesional.

> 💡 **Tip de supervivencia:** En Python, el símbolo de multiplicación no es una "x", es el asterisco (`*`). Ejemplo: `5 * 2`.

**Tus instrucciones paso a paso:**

1. Utiliza `int()` o `float()` para convertir `costo_analisis` y `cantidad_estudios` en números reales. Guárdalos en nuevas variables (`costo_num` y `cantidad_num`).
2. Multiplica las dos variables matemáticas para calcular el costo total. Guárdalo en `total`.
3. Imprime el ticket usando un **f-string** que muestre el nombre del paciente, el costo unitario, la cantidad y el total.
4. **RETO EXTRA:** Aplica `.upper()` al nombre del paciente en el ticket para que aparezca en mayúsculas (como en un recibo real).

> 🎯 **Nota:** Ya no necesitas convertir `total` de vuelta a `str()` — ¡el f-string lo hace automáticamente!

"""

# Datos exportados por el sistema (¡Tienen trampa!)
nombre_cliente     = "María García"
costo_analisis     = "1500"          # número guardado como texto
cantidad_estudios  = "3"             # número guardado como texto

# ¡Tu turno! Escribe tu código debajo de esta línea:
# Paso 1: casting → convierte costo_analisis y cantidad_estudios a números
# Paso 2: calcula el total
# Paso 3: imprime el ticket con f-string
# Paso 4 (extra): nombre en mayúsculas